<?xml version="1.0"?>

<para-list version='10' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Terra'>
         The prefabricated walls of the spaceport prevent you from moving in that direction.
         </para>

         <para number='2' comment='No exit message - Terra'>
         The prefabricated walls of the skybridge prevent you from moving in that direction.
         </para>

         <para number='3' comment='No exit message - Terra'>
         The prefabricated walls of the hospital prevent you from moving in that direction.
         </para>

         <para number='4' comment='No exit message - Terra'>
         The Arc Royal Hilton Hotel staff respectfully requests that you do not go that way.
         </para>

         <para number='5' comment='No exit message - Terra'>
         The only exit from Kara's Bungalow is down, and no, breaking through a wall doesn't make you any more macho than you already aren't, so don't even think about it!
         </para>

      </section>

   </category>

</para-list>

