<?xml version="1.0"?>

<para-list version='10' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Terran space'>
         At this time, the Terran Space Authority forbids travel into Pandemonia by that route. If you wish to travel into Pandemonia please proceed to the South, otherwise remain in orbit or jump to another star system.
         </para>

         <para number='2' comment='No exit message - Terran space'>
         An ice crystal nearly collides with your vessel as you attempt to move out of the sector. After a second thought, you decide not to head that way.
         </para>

         <para number='3' comment='No exit message - Terran space'>
         Just before you begin to leave the sector you receive a communition from a nearby navigational beacon. The message reads, "Terran Travel Authorities advise you against traveling outside of the plane of the ecliptic or beyond explored sectors in Terran space. Please correct your heading accordingly. Thank you."
         </para>

      </section>

   </category>

</para-list>

