<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='no exit for space locations'>
         The darkness overwelms you with it's bleakness and you turnback.
         </para>

         <para number='2' comment='no exit for space station'>
         You hear a whisper behind you and a Dryad Goddess quietly advises you that you can't move in that direction.
         </para>

         <para number='3' comment='no exit planet'>
         You feel uneasy as you realize you can't move that direction.
         </para>

         <para number='4' comment='no exit treehouse'>
         If you go that way you might fall out of the tree!
         </para>

         <para number='5' comment='no exit church'>
         A quiet Dryad goddess advises you that you can not move that direction in the church.
         </para>

         <para number='6' comment='no exit Ferr s house'>
         You bump your nose on the wall.
         </para>

         <para number='7' comment='no exit forest'>
         You look around, and realize you can't move that way.
         </para>

         <para number='8' comment='no exit water'>
         You cough and sputter as the water fills your mouth, making you decide not to try that way again.
         </para>

      </section>

   </category>

</para-list>

