<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='space no exit msg'>
         Several spheres of what can only be described as energy surround your ship. Your comms unit activates "You are not authorized to depart this sector in that direction cease all attempts to do so!".
         </para>

      </section>

   </category>

</para-list>


