<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Aliment'>
         Ouch!  You can't move in that direction.  If you banged your forehead, nose, or other extremity and need medical assistance, please head back to the hospital on the landing pad.
         </para>

      </section>

   </category>

</para-list>

