<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='Space'>

      <section name='Generic'>

         <para number='1' comment='No Movement'>
         Please follow the beacons...flying outside the specified space lane could result in damage to you and your ship.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Space lanes - Pelf'>
         Please follow the beacons...flying outside the specified space lane could result in damage to you and your ship
         </para>

      </section>

   </category>

</para-list>

