<?xml version="1.0"?>

<para-list version='12' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for Irony'>
         Invalid direction.  Please try boarding your shuttle to visit Paradox!
         </para>

         <para number='2' comment='No exit message for Irony'>
         Invalid direction.  Please try boarding your shuttle to visit Confusion or go West to Paradox and the Link!
         </para>

      </section>

   </category>

</para-list>

