<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='curator'>

      <section name='noexit'>

         <para number='1' comment='Museum Curator'>
         Please do not damage the art works, or you will be forcibily evicted
         </para>

      </section>

   </category>

   <category name='joust'>

      <section name='noexit'>

         <para number='3' comment='The joust'>
         You can only finish the joust by going west
         </para>

      </section>

   </category>

   <category name='merlin'>

      <section name='noexit'>

         <para number='2' comment='In general'>
         An image of Merlin has appeared; " If you do not want to be turned into a toad, do not disrupt the rules of this planet, and keep to the chosen paths
         </para>

      </section>

   </category>

   <category name='offices'>

      <section name='noexit'>

         <para number='4' comment='Private Offices'>
         These are private offices, so please be as kind as to not keep knocking down the walls
         </para>

      </section>

   </category>

</para-list>

