<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for Rock'>
         Rock walls stop you from moving in that direction, because the terraformed area ends here.
         </para>

         <para number='2' comment='No exit message for Rock'>
         Rock walls stop you from moving in that direction.
         </para>

      </section>

   </category>

</para-list>

