<?xml version="1.0"?>

<para-list version='10' editor='standard'>

   <category name='item'>

      <section name='prod'>

         <para number='1' comment='use prod'>
         You grab the cattle prod, adjusting the settings carefully. You scan the area for any cattle to use this on but can not find any so you start zapping everyone in the area instead.
         </para>

         <para number='2' comment='use prod room'>
         You watch as %s starts looking around, then starts zapping everyone with the cattle prod including yourself.
         </para>

      </section>

      <section name='yak'>

         <para number='1' comment='smoke yak male'>
         You see %s pull out a pack of Yak 42s and remove one. You watch as he flicks the self-ignition patch to light the end and see him relax in the resulting aromatic haze, taking one drag after another enjoying it fully.
         </para>

         <para number='2' comment='smoke yak pack'>
         You pull out a pack of Yak 42s and remove one. Flicking the self-ignition patch you light the end and relax in the resulting aromatic haze, taking one drag after another enjoying it fully
         </para>

         <para number='3' comment='smoke yak pack female'>
         You see %s pull out a pack of Yak 42s and remove one. You watch as she flicks the self-ignition patch to light the end and see her relax in the resulting aromatic haze, taking one drag after another enjoying it fully
         </para>

         <para number='4' comment='smoke yak neutral'>
         You see %s pull out a pack of Yak 42s and remove one. You watch as it flicks the self-ignition patch to light the end and see it relax in the resulting aromatic haze, taking one drag after another enjoying it fully
         </para>

         <para number='5' comment='smoke yak male single'>
         You see %s place a single Yak 42 in his month. You watch as he flicks the self-ignition patch to light the end and see him relax in the resulting aromatic haze, taking one drag after another enjoying it fully.
         </para>

         <para number='6' comment='smoke yak female single'>
         You see %s place a  single Yak 42 in her month. You watch as she flicks the self-ignition patch to light the end and see her relax in the resulting aromatic haze, taking one drag after another enjoying it fully
         </para>

         <para number='7' comment='smoke yak neutral single'>
         You see %s place a single Yak 42 in its mouth. You watch as it flicks the self-ignition patch to light the end and see it relax in the resulting aromatic haze, taking one drag after another enjoying it fully
         </para>

         <para number='8' comment='smoke yak single self'>
         You place a single Yak 42 into your month. Flicking the self-ignition patch you light the end and relax in the resulting aromatic haze, taking one drag after another enjoying it fully
         </para>

      </section>

   </category>

   <category name='shuttlepad'>

      <section name='nomove'>

         <para number='1' comment='nomove'>
         An intense storm rages in that direction.
         </para>

      </section>

   </category>

</para-list>

