<?xml version="1.0"?>

<para-list version='10' editor='standard'>

   <category name='message'>

      <section name='sign'>

         <para number='1' comment='reading sign1 loc 525'>
         You look at the sign. It shows the planet services at the 4 corners of the planet and a transporter at the lp.
         </para>

         <para number='2' comment='reading sign1 525'>
         Ship Repair                            Shipyard
         </para>

         <para number='3' comment='reading sign1 525'>
         .                   Transporter
         </para>

         <para number='4' comment='reading sign1 525'>
         Infirmary                              Exchange
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         You slip and start falling when a force field throws you back onto the plateau.
         </para>

         <para number='2'>
         Sorry you can not dig without a shovel, fly without wings, go in or out without something here.
         </para>

         <para number='3'>
         You walk right into the plasteel wall and get a bloody nose.
         </para>

         <para number='4'>
         You break through the outer shell of the space station and right as vacuum of space starts to suck you out a force field pops up and seals up the hole.
         </para>

         <para number='5'>
         The automatic pilot will not let you go that way.
         </para>

         <para number='6'>
         The droid guards escort you back to the door
         </para>

         <para number='7'>
         You turn around and walk back not wanting to get lost in the desert
         </para>

         <para number='8'>
         You bang your head on the duct so hard it knocks you silly.
         </para>

         <para number='9'>
         You bang your head on the service tunnel so hard it knocks you silly.
         </para>

         <para number='10'>
         You slip in the dust while trying to go that way and fall down hurting your ego.
         </para>

         <para number='11'>
         Sorry Charlie, no power.
         </para>

         <para number='12'>
         Walking through the darkened room you get clocked on the head by the wing of a spaceship.
         </para>

         <para number='13'>
         Sorry that way is for authorized personal only.
         </para>

         <para number='14'>
         You start to walk that way and you notice something moving around in the dark so you go back.
         </para>

         <para number='15'>
         You run back after finding out the medical droid wants to do a sex change on you.
         </para>

         <para number='16'>
         A droid, thinking you are drunk, brings you back to your seat.
         </para>

         <para number='17'>
         As you try to move in the wrong direction the lights turn off forcing you back to the entrance.
         </para>

      </section>

   </category>

</para-list>


