<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         As you attempt to leave the spaceport, a security guard comes up and advises you that you that direction is closed to the public.
         </para>

         <para number='2'>
         Unfortunately, you can not go in that direction, so space warps and places you in a seat at a backgammon table.
         </para>

         <para number='3' comment='shipyard'>
         As you move, the receptionist looks at you and says sharply, "No, you can't go that way."
         </para>

         <para number='4' comment='bar'>
         Apparently you've had too much to drink as you just tried to move into a solid object.
         </para>

         <para number='5' comment='hospital'>
         A nurse tells in you in a no-nonsense tone that you can't go that direction.
         </para>

         <para number='6' comment='island'>
         It seems you are a little high on the sunshine and fresh ocean breeze.  You just tried to move in a direction that you can't.  Maybe you should sit down for a moment.
         </para>

         <para number='7' comment='house'>
         Spar's house is not built to allow you to move in that direction, so you end up back where you started.
         </para>

         <para number='8' comment='porch'>
         Trying to move in that direction will mean you have fallen off the porch.  Since Spar cares about his guests' health, a force screen keeps you from moving in that direction.
         </para>

         <para number='9' comment='beach'>
         Because the beach is a natural formation, the beach does not continue in that direction.
         </para>

         <para number='10' comment='hottub'>
         The hottub is not a sphere.  You can only get in and out of the hottub.
         </para>

      </section>

   </category>

</para-list>
