<?xml version="1.0"?>

<para-list version='11' editor='standard'>

   <category name='business'>

      <section name='moves'>

         <para number='1' comment='no exit'>
         The management reminds you that you will be charged for any damage caused to the building.
         </para>

         <para number='2' comment='no fly'>
         Despite your best attempts to move your limbs, you are unable to fly off the roof.
         </para>

         <para number='3' comment='no exit nurse'>
         The nurse pushes you back onto the exam table, "you keep walking into walls like that, you won't make it very far on this world."
         </para>

      </section>

   </category>

   <category name='hallway'>

      <section name='moves'>

         <para number='1' comment='no move'>
         The walls are made of solid plasteel.  Perhaps you should try a different way.
         </para>

      </section>

   </category>

   <category name='home'>

      <section name='moves'>

         <para number='1' comment='no move'>
         The guards remind you that this is Zarquad's personal area, and that if you can't control yourself you will be promptly removed.
         </para>

         <para number='2' comment='worship zarquad'>
         A guard waves you over and pulls aside an inconspicuous curtain, then shows you through to the private areas of the apartment.
         </para>

      </section>

   </category>

   <category name='swamp'>

      <section name='moves'>

         <para number='1' comment='no move'>
         The foliage is just too dense to move in that direction.
         </para>

      </section>

   </category>

</para-list>


