<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='all space noexit'>
         As you try to fly into restricted space, a message comes over the comms, "you are leaving accessible space, please turn around and return to normal space."  As if to make their point, a very large, heavily armed Galactic Battleship in the distance starts turning towards you.  Not wishing a confrontation you have no hope of surviving, you return to safe space.
         </para>

      </section>

   </category>

</para-list>


