<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Not knowing why, you suddenly shout out with unbrideled joy, dancing like James Brown.
         </para>

         <para number='2'>
         A large, hairy beast in a uniform five sizes too small picks you up with a snort and places you back where you started.
         </para>

         <para number='3'>
         You bluster full speed in to a stone wall...ooooo, pretty stars!
         </para>

         <para number='4'>
         You trip on an overgrown root, sending large clouds of dust in the air obscuring your view.
         </para>

         <para number='5'>
         A ghost envelops you making you forget about moving in that direction.
         </para>

         <para number='6'>
         Little rodents suddenly appear, covering you in a mass of moving fur and sharp teeth.
         </para>

      </section>

   </category>

</para-list>

