<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         A disembodied voice suddenly convinces you that it wouldn't be such a good idea to do that.
         </para>

         <para number='2'>
         The walls ooze with gallons of ecotplasm making a large puddle on the floor. You slip on the goo and fall back in a rather embarrassing heap.
         </para>

         <para number='3'>
         A skeleton appears from a hidden panel preventing you from going in that direction.
         </para>

         <para number='4'>
         A hairy beast with large eyes and fangs to match holds out a hand barring you from venturing any further.
         </para>

         <para number='5'>
         A ghost envelops you making you forget about moving in that direction.
         </para>

         <para number='6'>
         A gnarled-toothed pirate with a peg leg, eye patch and hook for a right hand stops you from heading in that direction.
         </para>

      </section>

   </category>

</para-list>

