<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No-exit Receiving'>
         You bump into a receiving clerk who immediately gives you a very nasty look in response to interrupting his work. You really should be more careful next time.
         </para>

         <para number='2' comment='No-exit shipyard/repair'>
         This area is full of very busy mechanics using tools more than capable of causing severe bodily harm. To wander off and possibly bother them would not be wise.
         </para>

         <para number='3' comment='Production Corridor'>
         You smash your head on the window, but it doesn't budge. All the workers inside see you and laugh at your humiliation. You gather what's left of your composure and look for a real way out.
         </para>

         <para number='4' comment='Turbolift'>
         The automated voice informs you that the deck you selected is not available to visitors. Please try again.
         </para>

         <para number='5' comment='Workers Only'>
         You don't have the necessary ID card to go through the door. Plus it says "Workers Only." Can't you read?
         </para>

         <para number='6' comment='SoSay s Painting'>
         You nearly knock over a seemingly priceless artifact with your bumbling around. You look up and see Starlina's picture look at you with a menacing stare. You quickly gain your composure and return to your previous position.
         </para>

      </section>

   </category>

</para-list>


