<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='no move outside'>
         The terrain is too difficult to allow you to go that way.
         </para>

         <para number='2' comment='generic no move inside'>
         You can't go that way.
         </para>

         <para number='3' comment='no move in airlock'>
         There is no airlock in that direction.
         </para>

         <para number='4' comment='no exit inside base'>
         That door is locked.
         </para>

      </section>

   </category>

</para-list>
