<?xml version="1.0"?>

<para-list version='5' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='general no move'>
         You can't move that way.
         </para>

         <para number='2' comment='shuttle pad no move'>
         Protective force fields keep you from walking off the edge of the building.
         </para>

         <para number='3' comment='no move inside'>
         You're not allowed back there.
         </para>

         <para number='4' comment='end of road message'>
         Going that way is not advised.
         </para>

         <para number='5' comment='door locked in corridor'>
         That door is locked.
         </para>

         <para number='6' comment='fence prevents movement'>
         The fence blocks your way.
         </para>

         <para number='7' comment='recovery room'>
         You can't go that way.  The nurse notices you and asks sweetly, "You sure you're feeling well enough to leave?"
         </para>

         <para number='8' comment='streets with tall bldgs'>
         There is only a wall that way.
         </para>

         <para number='9' comment='no move on farm'>
         The pig sees you start that way and stutters, "n-n-n-n-now just a d-d-d-doggone minute, th-th-that area's off-limits!"
         </para>

         <para number='10' comment='no move in bathroom'>
         You can't go that way, but if you have to go, this is the right place.
         </para>

      </section>

   </category>

</para-list>

