<?xml version="1.0"?>

<para-list version='72' editor='standard'>

   <category name='bubsy'>

      <section name='conversation'>

         <para number='1' comment='on yarn'>
         "Don't you just love it?" he asks.  "I know I sure do!  I can't say enough about it!" he lisps highly enthusiastically in his characteristic voice, and showing off his jersey.  "Besides being fun to play with in yarn ball form, wool helps keep you warm.  Even if it's been thoroughly drenched from going down a waterslide, it'll still keep you nice and warm.  And I know from extensive experience.  I even love sleeping in it!" he enthuses.
         </para>

         <para number='2' comment='on exchange/trade'>
         "Ah yes, the trading exchange," Bubsy says, "I think I've grasped the concept.  Visitors like you bring goods and services we don't make enough of here, trade them for money, then trade the money for different goods we make more than enough of here, even our textiles.  Sure a lot fairer than those aliens who simply tried to steal all my yarn."
         </para>

         <para number='3' comment='on steal, Woolies'>
         Bubsy replies, "There was one race of aliens who so lusted after wool that they tried to come and just take my entire stash of yarn.  They sucked me up along with all my yarn, ruining a wonderful nap I was having.  Then their machines picked me out as some kind of riffraff, and threw me out of their ship.  How humiliating - and from a great height.  Did... I mention I don't like heights?  I learned how to glide, somewhat, that day.
         </para>

         <para number='4' comment='on steal, Woolies, part 2'>
         I certainly wasn't going to let them get away with that. I became one purr-fectly fur-ocious feline, ready, wooling, and able to fight to smite them and get my yarn back." He stands ramrod straight, crossing his right arm diagonally across his chest and says stoicly for effect, "I regret that I have but nine lives to give to my planet."  Back in his own scratchy voice, Bubsy comments, "As you might guess, I still have several to spare."
         </para>

         <para number='5' comment='on aliens'>
         "You never know what reaction you're going to get from an alien visitor.  Some," he says, gesturing toward you with an open paw, "will be nice, friendly, and pleasant.  Others may take one look at me and flee.  Others still may be unfriendly, and one I've encountered was even greedy enough to try to steal my yarn.  I guess it never occurred to them to offer something in return."
         </para>

         <para number='6' comment='petting, part 1'>
         You reach out to pet Bubsy, who looks a bit surprised and comments, "Whoa, I haven't had many try to touch me before.  Though this is rather nice... and pleasant."  He lets you continue and starts looking a bit more relaxed with a few more strokes, and possibly even lets out a purr.  When you finish, he comments, "Well that was a pleasant experience.  And I think I know how I can repay it."
         </para>

         <para number='7' comment='petting, part 2'>
         Bubsy reaches inside an inner pocket in his jersey and produces a small ball of red yarn, which he gives to you.  "A little gift for such a nice favor," he comments.
         </para>

         <para number='8' comment='on "Furless"'>
         "When I first saw the sign, knowing my own nature as a leader, at least when no water or heights are involved, I thought they meant 'fearless'.  Then I realized that 'FURless' was no mistake. I already wear no pants.  Now they want me furless, too?  Then what?  Strip me of my shirt and have me wander around naked and exposed?  No thank you.  What perverts.  Though they should know better, best not to present the opportunity.
         </para>

         <para number='9' comment='on "Furless", part 2'>
         A leader needs to keep his dignity, you know.  And that means keeping my fur, thank you very much.  And as our furred leader, suffice it to say you won't catch me hanging around in any place that would put 'furless' and 'leader' together in the same sentence.  'Fearless', sure. I have heard that some species do get their fur, or hair, trimmed from time to time.  I'm not one of them, but, hey, whatever blows your hair back!"
         </para>

         <para number='10' comment='on (no) pants'>
         "Yes, yes, I know.  You're not the first one to comment on how I don't wear any pants.  Then again neither does Bugs Bunny, or Donald Duck, or Daffy Duck, or Wile E. Coyote, or the Roadrunner, or Top Cat or any of his gang.  In fact, I can't think of any animal cartoon star who does wear pants.  OK, wait, make that one - Roger Rabbit wears overalls, doesn't he?  Does that count?"
         </para>

         <para number='11' comment='on Earth'>
         "Ah yes, Earth, where it all started for me.  My career in show business, the alien invasion, my saving the world's supply of yarn, and finally moving out here.  I haven't been back to Earth in a while, at least not since I got this planet.  There was one place there, I remember, though, on my most recent visit, underground.  I can't remember its name, but I thought I saw Elvis back there.  It even served his favorite snack."
         </para>

         <para number='12' comment='on water'>
         Bubsy shudders slightly at the mention of water.  "I know I went for a few rides on water slides while getting back my yarn, but that didn't stop me from being terrified every time, wondering where I'd end up, worrying every time that I'd end up in over my head.  Cats HATE water.  *I* hate water.  I can't imagine a fate worse than drowning."
         </para>

         <para number='13' comment='on water, part 2'>
         "You wouldn't let a sweet, lovable feline like me drown, would you?" he asks pleadingly, clasping his hands over his chest.  "Wait... no... don't answer that," he says, his voice quavering as he shuts his eyes, one hand waving you off, the other covering his chest, then moving to cover his eyes as if to signal, "My heart couldn't take someone saying he would."
         </para>

         <para number='14' comment='on privacy'>
         "There's just no privacy for us big stars," he laments.  "Always someone seeking to get a peek at you, even through a telescope from another planet.  Not that I mind others looking at me and admiring me.  Heck, you'll probably want to take a nice, long, admiring look at me.  There are just some times where I'd like a small break from it.  It's really a matter of mood."
         </para>

         <para number='15' comment='Lucky Seven'>
         "Is that what it's called? The Lucky Seven?" he asks.  "That does sound familiar.  Thanks for reminding me," he says.
         </para>

         <para number='16' comment='on stuntcat'>
         "Nothing like finding out you have to deal with crocodiles you were never told you'd have to deal with to make you desire a stunt double.  'Next time, I get a stuntcat!' I said.  Then someone pointed out I pretty much AM a stuntcat with all the risks and chances I take.  So much for my chances at getting a stunt double.  Hard enough finding one anthropomorphic bobcat, let alone a second.  So I guess I have to be the feline Jackie Chan."
         </para>

         <para number='17' comment='on Fancy'>
         "Funny you should mention Fancy.  I met him a few times while we were both on Earth.  A real Cat-sanova he is.  As much time as he spends seducing the females, I'm surprised he found much time to become a space trader.  But he did it, and actually got his own star system, and had a few planets terraformed.  He took a liking to me, and who could blame him, as adorable as I am, and had this world terraformed.  And then put me in charge!"
         </para>

         <para number='18' comment='on Fancy, part 2'>
         "I know Fancy has loved a couple females enough to marry them.  One of them was Catspaws.  Now there's a dish for feline eyes!  I can definitely see why he fell for her!  I don't know why or how that one broke up, but he did marry another gal later.  Her name escapes me, though," Bubsy says, trying hard to remember, but in vain.  "But I could tell they really loved each other deeply.  Haven't seen her in a long time, though."
         </para>

         <para number='19' comment='on Antonia'>
         "Yes! Antonia, that was her name!" Bubsy exclaims.  "Fancy once mentioned how he and she would frequently play naughty with each other, if you know what that means, because I sure don't.  All I know is that when I was a bouncing baby bobcat and did something naughty, I quickly ended up over somebody's knee, and got a blazing hot backside that stung and stayed sore for hours," he says, reaching behind himself and rubbing around his tail.
         </para>

         <para number='20' comment='on Antonia, part 2'>
         "You don't suppose that's what he meant?  I can't imagine that from Fancy.  I know I desperately sought to avoid repeating the behavior that would bring that on, and certainly not seek it out deliberately, if that is what he meant. Either I don't have the whole story, or he MUST have meant something else."
         </para>

         <para number='21' comment='on who (are you)'>
         "Who am I?  Why just the big, adorable cartoon star of 'Claws Encounters of the Furred Kind'!" he answers in his rapid, scratchy voice.  "Please tell me you've heard of it.  Or 'Fractured Furry Tales'?  I mean, what are they teaching these days?  You'd think my cartoons were obscure ancient history.  Then again, late twentieth Earth century, I suppose much of it is by now. I suppose it's up to me to keep that bit of history alive."
         </para>

         <para number='22' comment='on job'>
         "My job?  I never really thought of it as work, but I'm the fearless leader of Yarnball, defender of the downtrodden, smiter of evil doers, general hero to this world, and cute, adorable, feline host for my visitors.  When I'm not living my dream of enjoying a great nap in all my yarn balls, that is.  When you love what you do, you don't really think of it as work, I've heard some say, and it's true," he answers enthusiastically.
         </para>

         <para number='23' comment='on Yarnball'>
         "Ah, the planet Yarnball.  Terraformed after the worlds that served as the scenery in my interactive cartoon, 'Claws Encounters of the Furred Kind', and a living memorial to it.  There have been a few touches added to it to make things compatible with being a member of the Federation.  We've aimed to capture the most enjoyable aspects of the original worlds.  We hope you enjoy them."
         </para>

         <para number='24' comment='on Claws Encounters'>
         "Claws Encounters of the Furred Kind" was my first interactive cartoon, what others commonly called a video game.  Players would guide me around in the cartoon, helping me retrieve yarn balls, bop enemies, and find the big yarn ball at the end of each chapter.  I never got tired of playing with the really good players, but when playing with those who were not so good, I tell you, my contract did not mention pain!"
         </para>

         <para number='25' comment='on frizz'>
         "Ah yes, frizzy hair," Bubsy replies.  "I've heard women from Earth talk about having "bad hair days" during humid weather.  Believe me, I can relate, but no matter how bad a bad hair day a woman has had, they can count themselves lucky.  I guarantee you that their worst day doesn't rise to the level of having one over the entire body at once, as I have experienced many times.  Just one more reason for me as a cat to HATE water."
         </para>

         <para number='26' comment='on naked, bare'>
         Bubsy responds, "Hey, when you've got a fur coat over your entire body, you never think of yourself as naked or bare anywhere.  Just because I wear only a shirt doesn't make me naked below.  And everyone around here knows better than to try to create a bare spot on me."
         </para>

         <para number='27' comment='on bye'>
         Bubsy replies enthusiastically, almost hyper, "It was great talking with you!  If there's anything else I can help you with, just let me know.  Enjoy your stay on Yarnball."
         </para>

         <para number='28' comment='on hello'>
         Bubsy perks up his pointy ears and, maintaining his big, grinning smile, says, "Yes, hello %s, what can I help you with?"
         </para>

         <para number='29' comment='on bananas'>
         Bubsy replies, "For obvious reasons," while waving his arms as if trying to keep his balance while slipping on a banana peel, "bananas are one of my least favorite fruits.  And as a carnivore, I don't really have much use for them for food, other than desperation.  Come to think of it, I think I read that Hazed dislikes bananas, but for a different reason."
         </para>

         <para number='30' comment='on flying, gliding'>
         Bubsy replies, "I pretty much learned how to glide out of necessity.  I know it looks like I'm flying when I do so, but I don't have any way to keep myself airborne indefinitely.  I'm always going to land again before too long.  But when bouncing off a cheese wheel or something else substantial, it is rather fun being airborne.  It's like, 'Wheeeee! Flying bobcat!'  As long as I don't get too high up, that is.  Then it gets scary."
         </para>

      </section>

      <section name='greeting'>

         <para number='1' comment='1st arrival'>
         From off in the distance, you are able to hear a faint, somewhat springy sound. A small figure appears to somersault high in the air quite rapidly, and as it approaches peak altitude seems to spread limbs as if wings. It glides closer until it's nearly overhead, then drops down about ten feet in front of you.  It looks like a toon bobcat about three feet tall, wearing a plain white jersey save for a red exclamation point on the front.
         </para>

         <para number='2' comment='initial meeting'>
         "Well goodness gracious sakes alive," it says excitedly in a rapid, somewhat scratchy masculine voice that might well come from a creature about three feet tall, "I've got a visitor!"  It seems unsure what to say or do next.
         </para>

         <para number='3' comment='tell him hello'>
         "Oh yes, uhh, hello," he says, reciprocating your greeting.  "Welcome to Yarnball.  Oh, and as for 'Bobcat', please, use my first name - Bubsy.  That reminds me, you probably have a name, too.  How should I address you?"  When you tell him, he responds, "Ah, %s.  I know I never would have guessed that."  He then mutters your name to himself a couple times, followed by, "I must remember that..."
         </para>

         <para number='4' comment='2nd and 3rd visits'>
         Bubsy sees you and says with excitement "Oh, hi there.  I've seen you before, haven't I?  Welcome back to Yarnball...," he says, stalling for time, trying to remember your name, "... wait, don't tell me... %s, right?"  When you confirm him correct, he says, "Good, good, I remembered!  Welcome back.  Good to see you again."
         </para>

         <para number='5' comment='if walk away 1st time'>
         Seeing you leave upon his appearance, the bobcat mutters softly to himself, "Gosh, I thought I was more cute than scary... Never know with aliens, though..."
         </para>

         <para number='6' comment='4th and later visit'>
         You hear upon your arrival a familiar springy sound from off in the distance, and soon see a familiar figure gliding in to welcome you.  In drops Bubsy wearing his signature shirt, and upon seeing you, says excitedly, "%s!  Welcome back to Yarnball!  Back again to trade or visit, I presume.  Maybe even explore?"  He's ready to follow and guide you.
         </para>

         <para number='7' comment='to room if player bolts'>
         Seeing %s dash away without a word upon his appearance, the bobcat mutters softly to himself, "Gosh, I thought I was more cute than scary... Never know with aliens, though...", the tips of his ears flapping up and down a few times.
         </para>

         <para number='8' comment='other than hello bobcat'>
         The bobcat seems to chew things over on how to respond to how you addressed him, the tips of his ears flapping up and down, as if in annoyance.
         </para>

      </section>

      <section name='nomatch'>

         <para number='1' comment='no match for Bubsy'>
         Bubsy says, "I'm afraid I don't know enough about that to comment intelligently."
         </para>

         <para number='2' comment='no match for Bubsy'>
         Bubsy shakes his head and says, "Sorry, I wouldn't know about that."
         </para>

         <para number='3' comment='no match for Bubsy'>
         Bubsy shrugs his shoulders and says, "I wish I knew."
         </para>

      </section>

   </category>

   <category name='desert'>

      <section name='chicken'>

         <para number='1' comment='egg bombing'>
         You are startled by an egg which just misses your head and splatters on the hot asphalt about a foot from you.  As the egg starts to fry, Bubsy looks equally heated up.  Spotting a lone chicken flying in the sky, Bubsy growls, "It's bad enough these chickens try to pelt ME with their eggs.  But when they attack my guests and friends, that's the last straw!"
         </para>

         <para number='2' comment='egg bomb part 2'>
         Bubsy starts running, and with a mighty leap, lands on a crate of TNT. The impact sets it off, and the resulting explosion blows the bobcat sky high!  One might think such an explosion lethal, but as he reaches the peak of his ascent, you can see Bubsy spread his arms and start gliding.  He makes his way over to the chicken, then lets himself drop down on it fast. Upon impact, you hear a faint squawk, and see the bird fall from the sky.
         </para>

         <para number='3' comment='egg bomb part 3'>
         Bubsy spreads his arms and starts gliding once again, circling to land where the chicken fell and crashed.  Picking it up, he brings it back to show you and comments, "Well, now I know what's for dinner tonight.  I know a colonel who makes these things taste really good.  Maybe I should pay him a visit..."  You're ready to go on, though.
         </para>

      </section>

      <section name='roadrunner'>

         <para number='1' comment='roadrunner sequence'>
         As you move along the road, you suddenly hear a "Meep meep!" followed by some kind of flapping sound.  Bubsy perks up his ears and excitedly says, "Oh, oh, watch this, watch this!" He puts on his best impression of a Wile E. Coyote face - mouth open in an anticipatory smile, tongue hanging out hungrily, pointed teeth showing, and a hungry look in his eyes. With that, he dashes off after the source of the sound and disappears from sight.
         </para>

         <para number='2' comment='roadrunner part 2'>
         A couple minutes later or so, Bubsy comes racing back, holding a strange, lean-looking bird.  "Meep meep!" says Bubsy to the bird, then rapidly pokes his tongue in and out, creating a sort of flapping sound similar to what you heard before.  He then lets go of it, and with another "Meep meep", the bird dashes off.  With a laugh, Bubsy says, "I just love psyching out the roadrunner.  Now that is fun!"
         </para>

         <para number='3' comment='roadrunner part 3'>
         Gesturing toward a plateau, Bubsy continues, "Old Wile E. Coyote over there may be a genius, but he overthinks things. What it takes to catch the roadrunner is really simple - speed.  Either you have it or you don't.  I guess if you don't, then you kind of have to rely on tricky schemes that may or may not work." Looking where Bubsy gestured, you see a brown-furred canine creature with what could be described as wide, puppy-dog eyes.
         </para>

         <para number='4' comment='roadrunner part 4'>
         The canine creature's expression also looks somewhat sad, as if wondering why that bobcat can catch the roadrunner, but he can't.  Bubsy smiles, looks at, and waves to him, but Wile E. only looks more depressed.  "Can't really say I blame him," Bubsy says, turning back to you.  "After all, he's been trying for how many years now to catch the roadrunner, all without success?  And yet here I do it with relative ease.  Oh well, on we go."
         </para>

      </section>

   </category>

   <category name='hospital'>

      <section name='revival'>

         <para number='1' comment='Bubsy upon revival'>
         Bubsy sees you alive again and excitedly says in his scratchy voice, "Goodness gracious, I thought you were a goner! But you had another life as well!" You explain to him the concept of life insurance, and how death need not be fatal in Fed for someone who has it. "You mean, with this life insurance, you could have as many lives as me?" he asks, then realizing the implications, adds, "Or... even more?" with noticeably less enthusiasm.
         </para>

         <para number='2' comment='Revival conv continued'>
         Bubsy seems not to relish the idea that his having nine lives is no longer so unique.  "That's right," you confirm, "as long as I remember to keep insuring myself with every new life."  Which reminds you...
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='enterloc'>

         <para number='1' comment='enter saloon'>
         The bartender notices who comes moseying on through the doors after you.  "Bubsy old pal!" he shouts.  "Good to see you again.  The usual?" he asks.  With an affirmative nod from Bubsy, the bartender sets a bottle of cold milk on the bar, which Bubsy starts to drink.
         </para>

         <para number='2' comment='train depot'>
         With a loud TOOOOOT! from the whistle, a train starts pulling out of the depot and heading northward along the tracks.  Bubsy's ears perk up, and with a quick, "Ooooh, let's catch the train! Hurry, follow me!", he takes off like a shot, with accompanying sound effect, and races out along the tracks after the train.
         </para>

         <para number='3' comment='train chase'>
         With a mighty pounce, Bubsy leaps high and lands on the roof of the caboose.  He motions to you to come aboard quickly.
         </para>

         <para number='4' comment='near home'>
         Bubsy suddenly speaks up.  "Oh, my home is right here.  This one, the one to the south."
         </para>

         <para number='5' comment='1st floor of home'>
         "Welcome to my humble abode," Bubsy tells you.  "I know this doesn't look like much, but wait till you see what I have upstairs."
         </para>

         <para number='6' comment='tailor with yarnball'>
         The tailor notices you possess one of Bubsy's yarnballs.  "Oh, Bubsy gave you one of his yarnballs, did he?  I know what I can do with that.  That looks like enough yarn for the color portion of a shirt like Bubsy's.  If you'd like one, just hand me that yarn, and I'll make you one as a gift."
         </para>

         <para number='7' comment='on road'>
         A car slowly rolls your way on the other side of the street and honks its horn for you to hear.  Bubsy instinctively leaps high in the air and spreads his arms to glide down well past the car.  Realizing that jumping over the car was not necessary, Bubsy says, "Force of habit there.  I do get a bit nervous, remembering numerous past encounters with cars that nearly ran me over."
         </para>

         <para number='8' comment='entering barber shop'>
         As you enter, Bubsy looks up at the sign and comments, "Shouldn't that be fearless?", then a couple seconds later ominously says a long, "Uh ohhhh," and quickly steps away from the entrance instead of following you inside.
         </para>

         <para number='9' comment='doctors office'>
         Bubsy follows you in and asks in what for him sounds like a plaintive voice, "Is there a veterinarian in the audience?"  With a start, the woman, recognizing the distinctive voice, looks up from her work, a smile comes to her face, and she starts giggling.
         </para>

         <para number='10' comment='doctors office part 2'>
         "Bubsy, it's really you!" she says excitedly. "You know how I can't help but laugh at that line, you old furball," she continues. "One of these days I'm going to get you to set foot inside that barber shop," she says with a playful grin.  "That'll be the same day I take a liking to water," Bubsy answers back.  "And that'll be the day you REALLY need a vet," she adds.
         </para>

         <para number='11' comment='in exam room'>
         "What's up, doc?" Bubsy says jokingly in his characteristic voice.  "Ah yes, Bubsy, my favorite bobcat," the doctor says, before adding, "And yes, there is a veterinarian in this audience.  I'm here when you need me.  But you don't look like you need my services today.  Am I right?" Bubsy agrees, and the doctor turns his attention to you with the words, "Let's have a look at your guest."
         </para>

         <para number='12' comment='Bubsy comments in tailor'>
         "I'll give you one guess where I get my shirts," Bubsy says to you.  "This guy is good.  You'd never guess how long I've had my current shirt.  The clothes here are made to last."  The clerk on duty hears Bubsy talking to you and recognizes the voice.  "Bubsy!" he calls out.  Shortly after, someone else appears from the other side of a doorway, having heard the name.
         </para>

         <para number='13' comment='Bubsy tailor comments 2'>
         "Oh, that's him!" Bubsy says excitedly when he appears.  "There's the star tailor.  If there are any clothes you need or desire, there's the guy you want making them.  He's a veritable wizard with wool.  Did I tell you about my shirts?"  "Why thank you, Bubsy.  It's great seeing you around here again," the tailor responds.  "In the market for a new shirt yet?"  "Not me, but my guest might be," Bubsy answers.
         </para>

      </section>

      <section name='exit'>

         <para number='1' comment='heading down to explore'>
         Seeing you heading down to explore, Bubsy decides to accompany you and heads down his own way - jumping over the edge, and spreading his arms to glide down.  "I'll meet you down at the bottom," he shouts for you to hear in his characteristic scratchy voice.  He quickly lands and is waiting for you as you arrive.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='Generic no exit message'>
         You can't go that way.
         </para>

         <para number='2' comment='saloon no exit'>
         You haven't had too much to drink have you?  There's only a wall that way.
         </para>

         <para number='3' comment='indoor no exit'>
         There is only a wall that way.
         </para>

         <para number='4' comment='out in desert'>
         You start wandering out into the empty desert, but then having the railroad track to keep you oriented brings you back...
         </para>

         <para number='5' comment='no exit from mesa'>
         You wander over to that edge of the mesa to descend, but soon see that the path is much too steep and the footing much too treacherous for you.  Lacking Bubsy's ability to glide, you are unable to go that way, and so turn back.
         </para>

      </section>

   </category>

   <category name='save'>

      <section name='bubsy'>

         <para number='1' comment='1st save Bubsy sequence'>
         As Bubsy jogs alongside you, he ends up stepping on a stray banana.  Suddenly he is slip-sliding out of control, waving his arms frantically trying to keep his balance.  Meanwhile his momentum carries him over the edge of the cliff.  Looking at what lies below - nothing but water - Bubsy's eyes grow large and bug way out of his head while his mouth gapes wide open in an expression of great alarm while hovering in mid-air.
         </para>

         <para number='2' comment='2nd in save Bubsy'>
         A loud, "Aaah-oooooooooo-ga!" sound effect accompanies his expression, and he fearfully chews one set of claws with his teeth, which are chattering nervously and uncontrollably, until gravity resumes its effect on him and he starts falling.  He tries to glide back toward the cliff, but can only claw at the side of the cliff, which comes loose in his hands, leaving him airborne.
         </para>

         <para number='3' comment='3rd in save Bubsy'>
         Realizing he's about to fall, Bubsy hovers in mid-air, and with a sad facial expression resembling that of Wile E. Coyote's "Yipe!", starts waving bye-bye to you with his left hand.  His feet start to fall, stretching him out, then the rest of him quickly catches up to his feet, and he plunges to the clear deep water about a hundred feet below.  A sound effect suggesting taking off like a shot accompanies the start of his fall.
         </para>

         <para number='4' comment='diving in to save'>
         With resolve, you do a cannonball jump for the water below, determined to save Bubsy from drowning. Bracing yourself as you approach the water, you break the surface and plunge about ten feet below the surface of the chilly water before arresting your momentum, and resurfacing. Once above the surface again, you can hear the splashing of frantically flaying limbs and panicked screams of your bobcat host.  "Hold on, Bubsy!" you shout.
         </para>

         <para number='5' comment='save Bubsy, part 2'>
         As you swim over, he starts to go under.  You can see his right hand above the surface, holding up one fat finger.  You're almost to him when you see him hold up a second finger on his hand, which also starts sinking noticeably.
         </para>

         <para number='6' comment='grab/rescue/save Bub/him'>
         You quickly grab Bubsy's hand and pull him up. You have hold of one surprised bobcat when he gets another breath of air, and renews his struggle to stay afloat. "Hold onto me!" you shout for him to hear. So he does - grabbing your shoulders and digging in securely with his claws. You let out a scream of pain yourself and manage to get out, "OW! CLAWS!"
         </para>

         <para number='7' comment='successful save'>
         Realizing he's hurting you, he switches to bear-hugging you tightly around the neck and holding on for dear life.  At least you're still able to breathe, and with your arms free again, start swimming to shore, which isn't easy with a panicked bobcat clutching about your head, occasionally covering up your eyes, or your nose and mouth.  Finally you do get to shore with Bubsy and drag a by-then exhausted bobcat onto terra firma.
         </para>

         <para number='8' comment='grateful saved Bubsy'>
         After a few moments to catch his breath and recover some strength, Bubsy says, with a mix of surprise and awe in his voice, "Y... you... you SAVED me.  You saved me from drowning.  You didn't have to, but you did it anyway."  He takes a moment to shake himself as dry as he can, then continues in his scratchy voice, "Believe me, I won't forget this.  I'll do everything I can to make sure nothing bad happens to you while you're here."
         </para>

         <para number='9' comment='final effect'>
         With that, his still-damp fur starts frizzing up, making him look highly puffed-up, but after a bit of rest, he is eventually ready to move again.
         </para>

         <para number='10' comment='moves away instead'>
         As you start to walk away, your curiosity impels you to at least have a look. Looking down from the cliff, you see Bubsy frantically flailing about in the water, looking terrified.  His motion gets slower, then slower still, and he starts to sink.  You can see him hold up one finger on a hand poking above the surface, then two, then three, before that hand also sinks into the water amidst a patch of air bubbles, which soon cease.
         </para>

         <para number='11' comment='moves away part 2'>
         Poor Bubsy. Hope he still has some extra lives to spare.  As you move on, the events keep replaying in your mind, and you get this nagging feeling that won't quit which makes you think that there was something you could have done.
         </para>

         <para number='12' comment='Bubsy new life after 6 mv'>
         Up in the sky, you see approaching your way a familiar shape - that of a flying bobcat with his arms spread out like wings.  He spots you and comes in to land.  "There you are!" he says in his usual scratchy voice.  "It's good to be back, albeit with one less life. It took me a while to find you again, but here I am!"
         </para>

      </section>

      <section name='player'>

         <para number='1' comment='fail, if Bubsy not saved'>
         "No no, wait! Not...," Bubsy shouts, changing to a despairing, "yet..." as a giant spider suddenly comes down on top of you. You feel a bite, and within seconds your muscles are becoming paralyzed, your blood starts running very cold, and the color drains out of your body.  Bubsy pounces on and shreds the spider to pieces, then with no further danger approaching, looks at you.  Some kind of fever starts cooking you from the inside.
         </para>

         <para number='2' comment='fail, part 2'>
         Seeing your deathly pallor, Bubsy clasps both hands over his chest and, with a worried expression on his face, hopefully asks in a plaintive voice, "Is there a veterinarian in the audience?"  Even if there is, it's too late for you, and your misery soon ends.
         </para>

         <para number='3' comment='save, part 1'>
         You hear Bubsy let out an alarmed gasp, and within the blink of an eye, he is flying like a speeding bullet just over your head, and emitting a fur-ocious growl.  He intercepts and shreds to ribbons a giant spider about to land on you.  Making sure there are no other threats nearby, he relaxes his heightened alert and tells you, "No need to thank me.  You already have by saving me from drowning, and I can't thank you enough for that.
         </para>

         <para number='4' comment='save, part 2'>
         These spiders got one of my prior lives," he says. "One of them landed on me and bit me.  Almost immediately I was paralyzed and just about literally frozen.  And then some kind of fever burned me up inside as I died.  That was a really nasty way to go.  I couldn't let that happen to you, not to a friend who saved me from drowning.  Saving you was the least I could do," he finishes in his characteristic scratchy voice.
         </para>

      </section>

   </category>

</para-list>
