<?xml version="1.0"?>

<para-list version='5' editor='standard'>

   <category name='grandstand'>

      <section name='planet'>

         <para number='1' comment='Landing area.'>
         That area is off limits.
         </para>

         <para number='2' comment='infield care center'>
         That was is blocked.
         </para>

         <para number='3' comment='exchange'>
         Traders block your path.
         </para>

         <para number='4' comment='walkway'>
         No going that way!
         </para>

         <para number='5' comment='construction'>
         The foreman blocks your path.
         </para>

         <para number='6' comment='shop'>
         The shop owner blocks your path.
         </para>

         <para number='7' comment='tavern'>
         You can't go that way.
         </para>

         <para number='8' comment='Museum'>
         A mob of tourists blocks your path
         </para>

         <para number='9' comment='Welcome to Watkins Glen'>
         No goin that way
         </para>

         <para number='10' comment='Tourist Information Bureau'>
         As you turn to leave a shelf of pamphlets is knocked over in the process.  A employee glares at you unhappily as she picks up the fallen pamphlets.
         </para>

         <para number='11' comment='City of Watkins Glen'>
         A car honks angrily at you as you almost step directly into its path.  Be careful where you walk
         </para>

         <para number='12' comment='Gallery'>
         Running into the Trophy cases will surely earn the ire of the staff, please don't do it
         </para>

         <para number='13' comment='Seneca Lodge'>
         Bumping into people blindly is not a good (or healthy) idea
         </para>

         <para number='14' comment='Bar'>
         A raucous laughter erupts from the patrons as they watch you stumble around and then fall to the ground, apparently the liquor here is more rugged than what your used to.
         </para>

         <para number='15' comment='Wine shack'>
         If you dont want to end up paying for the broken bottles of wine please don't walk that way.
         </para>

         <para number='16' comment='Entertainment room'>
         Please be careful this equipment is expensive
         </para>

         <para number='17' comment='Bathroom'>
         Caution floor slippery when wet proceed with caution
         </para>

         <para number='18' comment='Liakell s office'>
         You cant go that way!
         </para>

      </section>

   </category>

</para-list>

