<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='move'>

      <section name='noexit'>

         <para number='1' comment='in casinos'>
         They'll through your ass out if you keep messing around!
         </para>

         <para number='2' comment='on the street and else where'>
         Quit staring at the girls and watch where your going, you'll hurt somebody!
         </para>

         <para number='3' comment='desert bit'>
         There's lot's of holes out there in the desert. Hate to see you end up in one!
         </para>

      </section>

   </category>

</para-list>

