<?xml version="1.0"?>

<para-list version='7' editor='standard'>

   <category name='visitors'>

      <section name='noexit'>

         <para number='1' comment='Hangar - loc 391'>
         Walking into the polished bulkhead accomplishes little aside from leaving an oily smear of facial grime. The instant you step back from full-on face-wall contact, a scrub-bot zips over and begins ridding the ship of your bio-filth.
         </para>

         <para number='2' comment='Trading Bay - loc 392'>
         The COMEX interprets your face mashing into the screen as an order to instantly divest yourself of all worldly assets and donate the proceeds to charity - less the transit fee and tithe necessary to enroll in the Ancient Celibate Order of Whisper-Monks for an new, ascetic life farming icicles on an arctic asteroid orbiting the star HE0107-5240. Fortunately, it asks for confirmation and you're able to back out at the last moment.
         </para>

         <para number='3' comment='Automechanic - loc 327'>
         The automechanic may be a claustrophobic box, but you're not quite so insane as to try walking through solid steel... are you?
         </para>

         <para number='4' comment='Warehouse Obs - loc 393'>
         The observation platform is girdled on all sides by smoothly-curved you-proof windows. Attempting to break through them would be ill-advised.
         </para>

         <para number='5' comment='Visitor Corridor - loc 328'>
         The corridor only leads northeast, with an archway opening onto a hangar to the southwest. To go any other way would be madness. And impossible, besides.
         </para>

         <para number='6' comment='Gallery loc 265'>
         Neither pamphlets nor steel are particularly permeable by things such as yourself. The foyer cannot be left in that direction.
         </para>

         <para number='7' comment='Storage - Loc 0'>
         How did you get in here? You shouldn't be here. Ask someone to get you out.
         </para>

         <para number='8' comment='Gallery loc 266'>
         You cannot squeeze through the portholes; you're too large, and even if you weren't, they're plugged-up with thick sheets of transparent polycarbonates.
         </para>

         <para number='9' comment='Gallery loc 202'>
         Alas, quantum tunneling does not work so well on the macro-scale unassisted. The walls remain solid. You remain here.
         </para>

         <para number='10' comment='Gallery loc 201'>
         Unfortunately, there are no free cryosleep ampoules and a thick polycarbonate pane separates you from any chance at attempting to disprove that statement. There is, however, an ample selection of liquor available in the foyer, which, if imbibed in quantity, can have similar soporific qualities.
         </para>

      </section>

   </category>

</para-list>

