<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='space'>

      <section name='noexit'>

         <para number='1' comment='Linkship - loc 391'>
         You fly off towards the enfolding scarlet gases of the nebula. The signal from the linkship's navigational beacon fades into static, but your ship can sense no further guidance signals in the area. Wisely, you about-face and return to the civilized comforts of demarcated space-lanes and hot cocoa.
         </para>

         <para number='2' comment='Celandine orbit - loc 392'>
         Setting off towards the swirling nebula beyond, the linkship and planet soon fade from view, blotted out by the ruby glow of dancing gas-eddies. The planet's gravitational signature fades from your sensors with no new discoveries apparent. You come about and return to orbit before being entirely lost in the vast empty beyond.
         </para>

      </section>

   </category>

</para-list>

