<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Crash'>
         Men in grey and black uniforms quietly escort you back towards the path.  Apparently this planet isn't as free as you were lead to believe!
         </para>

      </section>

   </category>

</para-list>

