<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='movement'>

      <section name='noexit'>

         <para number='1' comment='No exit from LP'>
         A soldier approaches you and curtly asks you to remain in the areas cleared for visitors.
         </para>

         <para number='2' comment='No exit from kitchen'>
         As you attempt to move in that direction, you bump into one of the cooks. He drops the platter he was carrying, which crashes to the floor. Everyone who wasn't already glaring at you is doing so now. Maybe you should just get out.
         </para>

      </section>

   </category>

</para-list>

