<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='movement'>

      <section name='noexit'>

         <para number='1' comment='No exit from link'>
         One of the ships quickly moves to block your progress in that direction. Looks like they weren't kidding.
         </para>

         <para number='2' comment='No exit from orbit'>
         Better not try going that way - you don't see any ships like the ones at the link, but they're probably still enforcing the designated route from somewhere.
         </para>

      </section>

   </category>

</para-list>

