<?xml version="1.0"?>

<para-list version='6' editor='standard'>

   <category name='noexit'>

      <section name='cafe'>

         <para number='1' comment='cafe no exit'>
         The waitdroids quickly inform you cannot go that way and to please stay in the designated paths.
         </para>

      </section>

      <section name='champs'>

         <para number='1' comment='champs bar no exit'>
         The bartender sensing that you are about to make a wrong step stops you and points you in the right direction.  You thank him and slip a nice sized tip in the tip jar as payment for not letting you make a fool of yourself here in the bar.
         </para>

      </section>

      <section name='community'>

         <para number='1' comment='communinty co-op no exit'>
         A worker droid Yells to get your attention.  It seems you were about to release the entire contents of a whole silo onto the ground. He says to be carefull and not to move in unauthorized directions.
         </para>

      </section>

      <section name='delshannon'>

         <para number='1' comment='del shannon museum'>
         A force field prevents you from touching the displays. Security is now keeping a  watchfull eye on you. You better be carefull or they may force you to buy one of everything they sell in the gift shop as a  penalty for messing up any museum display.
         </para>

      </section>

      <section name='dentsrus'>

         <para number='1' comment='dents r us no exit'>
         A worker grabs you just before you fall in the repair bays pit. He then hands you a bill for the time that he should have been repairing the ship he is working on. You decide to sneak out while he is back working on repairing a ship.
         </para>

      </section>

      <section name='exchange'>

         <para number='1' comment='exchange no exit'>
         You clumsily bang into one of the trading machines and decide to try another direction.
         </para>

         <para number='2' comment='trading lounge'>
         The lounge staff prevent you from doing that and ask that you be more carefull. You almost made them spill the drinks ordered for the trader beside you.
         </para>

         <para number='3' comment='offices no exit'>
         You run into the office wall with a resounding thud.  The security staff check you over for any broken parts and advise you to be carefull and stay on the outlined paths.
         </para>

      </section>

      <section name='farmmuseum'>

         <para number='1' comment='farm museum no exit'>
         Security droids step into your path just in the nick of time. You were about to step into the working display of the combine tractor. You thank them for saving your life and decide to watch your step from now on.
         </para>

      </section>

      <section name='hospital'>

         <para number='1' comment='hospital waiting room'>
         You suddenly realize that you have to be more carefull while walking around. You almost tripped over the patient next to you whose leg appears to be broken.  Thank goodness you didn't do that.  They may have forced you to pay the hospital bill as payment for pain and suffering caused.
         </para>

         <para number='2' comment='hospital treatment center'>
         You are shocked awake. You were careless in your wanderings and backed into the defibulator paddles.  Lucky for you the machine was set at a low setting.  Otherwise, you may have ended up talking to the insurance agent over there about reinsuring your life insurance policy.
         </para>

      </section>

      <section name='library'>

         <para number='1' comment='library no exit'>
         By turning the wrong direction you knock over a cart of books the work droids were sorting to put back on the shelves. The head librarian tells you to take a seat and be quiet or use the appropriate directions to leave the building.
         </para>

      </section>

      <section name='neighbors'>

         <para number='1' comment='neighbors no exit'>
         You clumsily bump into a shelf as you walk through the store. On the shelf is a expensive collector plate that begins to fall to the floor.  You try to catch it but to no avail. Thank goodness the force field is in place to catch it. The clerk behind the counter looks disappointed that he didn't make a sale for you breaking the item. You put it back and continue on.
         </para>

      </section>

      <section name='postoffice'>

         <para number='1' comment='post office no exit'>
         You stop just short of falling into the automatic mail sorting device. That would have been nasty. The postmaster advises you to leave using the correct directions.
         </para>

      </section>

      <section name='railway'>

         <para number='1' comment='railway station no exit'>
         Watch Who you are stepping on!!!! Yells one of the tourists in the station. Due to your inattentiveness you accidentally stepped on one of their limbs or at least you think it is their limb.  You apologize and decide to be more observant as to where you are walking in the future.
         </para>

         <para number='2' comment='railway platform no exit'>
         A bright camera flash makes you stop in your tracks.  Its a good think to you were about to step off the platform and fall face first onto the tracks below.  That would have definately left a mark.
         </para>

      </section>

      <section name='school'>

         <para number='1' comment='school no exit'>
         The Principal asks you to stop running into the lockers or to leave the building.
         </para>

      </section>

      <section name='shipyards'>

         <para number='1' comment='shipyard no exit'>
         You run into the salesman's desk knocking off the stack of paperwork on his desk. The salesman mubles something about how he just sorted the monthly sales figures out as he quickly picks up the papers.  You think this will be a good time to leave before he gets mad and raises the price of any ship you might intend to buy.
         </para>

      </section>

      <section name='shuttlepad'>

         <para number='1' comment='launch pad no exit'>
         Pad workers yank you aside.  You just avoided getting burned in the exhaust blast of a launching shuttle.  They caution you to stay alert and stay on the paths for your safety.
         </para>

      </section>

      <section name='shuttlewash'>

         <para number='1' comment='shuttle wash no exit'>
         Alarms and red lights start sounding and flashing. You awake from your daydreamins state to discover that you were about to walk through the shuttle wash without a ship. The wash part may not have been so bad. The 500 degree hot wax that would have been applied to you would have. You quickly step out of the way as the worker droids restart the wash tunnel.
         </para>

      </section>

      <section name='spaceboys'>

         <para number='1' comment='space boys no exit'>
         Crash!!!  Oops your movements just knocked over a large display of Lub Oils. The stocker droid stares at you in disgust.  Apparently the droid had spent an hour building the display and you destroyed it in seconds.
         </para>

      </section>

      <section name='stagecoach'>

         <para number='1' comment='stagecoach lobby'>
         The Manager rings the check-in bell just in time to keep you from tripping over the luggage rack passing in front of you.
         </para>

         <para number='2' comment='hallway no exit'>
         in your rush to check out your room you run straight into the maids cart. You assist the maid in picking up the small shampoo bottles and towels tha you knocked over.
         </para>

         <para number='3' comment='dining room no exit'>
         Whap. You have just walked into the window overlooking the train platform.  The maids are not amused since they now have to clean the window again.
         </para>

      </section>

      <section name='street'>

         <para number='1' comment='street no exit'>
         The street cleaning droids stop you just in time. You were about to step into a pile of manuer that some animal left behind.  From the size of it you sure wouldn't want to see the animal that made this mess.  You check the bottoms of your shoes, thank the droid and continue on down the street. Carefully watching where you step.
         </para>

      </section>

   </category>

</para-list>