<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='noexit'>

      <section name='space'>

         <para number='1' comment='space no exit'>
         Warning lights start flashing on your control panels. You receceive a tight beam transmission from Coopersville Space Control saying you are flying into oncoming space traffic. Please follow the outlined flight paths.
         </para>

      </section>

   </category>

</para-list>