#!/usr/bin/python

# Set up a new system and planet for fed2

import os
import shutil
import sys

if len(sys.argv) < 4:
	print 'usage is new_sys system_filename planet_filename owner_name'
	sys.exit(1)

dest = '/var/opt/fed2/maps/'+ sys.argv[1];

print "creating directory for", dest
os.mkdir(dest)
os.chmod(dest,0775);

# copy files to production folder
os.system("mv " + sys.argv[2] + ".* " + dest)
os.system("mv space.* " + dest)
os.chdir(dest)

# creat .inf files
print "creating .inf files"
space_file = file("./space.inf","w+")
space_file.write('<?xml version="1.0"?>\n')
space_file.write("<infrastructure owner='" + sys.argv[3] +"' economy='None' closed='true'>\n")
space_file.write("</infrastructure>\n")
space_file.close()
planet_file = file("./" + sys.argv[2] + ".inf","w+")
planet_file.write('<?xml version="1.0"?>\n')
planet_file.write("<infrastructure owner='" + sys.argv[3] +"' economy='Agricultural' closed='false'>\n")
planet_file.write("</infrastructure>\n")
planet_file.close()

print "Setting permissions"
os.system("chmod g+w *")
os.system("chgrp fed2 *")

print "new system set up: completed"
os.system("pwd")
os.system("ls -l")

