<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='noexit'>

      <section name='cafeteria'>

         <para number='1'>
         You hear an announcement. "SECURITY TO THE CAFETERIA someone trying to escape".   Security Droids run in grab you ,then realize you are a visitor and release you.
         </para>

      </section>

      <section name='cell'>

         <para number='1'>
         You hear an announcement. "SECURITY TO THE NUT'S CELL RED ALERT".   Security Droids run in grab you ,then realize you are a visitor and release you.
         </para>

      </section>

      <section name='enterance'>

         <para number='1'>
         You realize that you cant go that way an turn around.
         </para>

      </section>

      <section name='excahange'>

         <para number='1'>
         You bounce an edge of the exchange towards the way you came,you hear chuckles an laughter behind you.
         </para>

      </section>

      <section name='fdorm'>

         <para number='1'>
         You hear an announcement. "SECURITY TO THE FEMALE DORM ROOM someone trying to escape".   Security Droids run in grab you ,then realize you are a visitor and release you.
         </para>

      </section>

      <section name='field'>

         <para number='1'>
         The grass gets longer an keeps you from going in that direction
         </para>

      </section>

      <section name='hallway'>

         <para number='1'>
         You hear an announcement. "SECURITY TO THE HALLWAY someone trying to escape".   Security Droids run in grab you ,then realize you are a visitor and release you.
         </para>

      </section>

      <section name='infirmary'>

         <para number='1'>
         You hear an announcement. "SECURITY TO THE INFIRMARY someone trying to escape".   Security Droids run in grab you ,then realize you are a visitor and release you.
         </para>

      </section>

      <section name='mdorm'>

         <para number='1'>
         You hear an announcement. "SECURITY TO THE MALE DORM ROOM someone trying to escape".   Security Droids run in grab you ,then realize you are a visitor and release you.
         </para>

      </section>

      <section name='padded'>

         <para number='1'>
         You hear an announcement. "SECURITY TO THE PADDED CELL AREA someone trying to escape".   Security Droids run in grab you ,then realize you are a visitor and release you.
         </para>

      </section>

      <section name='path'>

         <para number='1'>
         You are about to step off the edge of the path, an step back before you get your shoes dirty.
         </para>

      </section>

      <section name='room'>

         <para number='1'>
         You are contained by perimiter of the room,an realize that you cant go that way
         </para>

      </section>

      <section name='sos'>

         <para number='1'>
         The bartender tells to becareful not to damage the walls, an says if you do it again you are cut off.
         </para>

      </section>

      <section name='spad'>

         <para number='2'>
         You realize you are about to fall off the edge of the shuttle pad an turn around.
         </para>

      </section>

      <section name='station'>

         <para number='1'>
         You hear an announcement. "SECURITY TO THE NURSES STATION".   Security Droids run in grab you ,then realize you are a visitor and release you.
         </para>

      </section>

      <section name='tree'>

         <para number='1'>
         You almost slipped of the trunk of the tree but grab a branch an pull yourself back up
         </para>

      </section>

      <section name='workroom'>

         <para number='1'>
         You hear an announcement. "SECURITY TO THE WORKROOM someone trying to escape".   Security Droids run in grab you ,then realize you are a visitor and release you.
         </para>

      </section>

   </category>

</para-list>


