<?xml version="1.0"?>

<para-list version='10' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for Insane spac'>
         There's nothing else of interest in this system, so all you can do is BOARD your shuttle and explore NutHouse, or jump elsewhere.
         </para>

      </section>

   </category>

</para-list>


