<?xml version="1.0"?>

<para-list version='6' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='General dome no-exit'>
         Even in the nicest areas of the dome, you shouldn't go straying from the main road. And this is NOT the nicest area.
         </para>

         <para number='2' comment='Outside no-exit'>
         It would be most unwise to stray from the path outside the dome. The surrounding desert is unforgiving.
         </para>

         <para number='3' comment='Abbey no-exit'>
         Please, do not violate the sanctity of this place with such foolishness.
         </para>

         <para number='357' comment='Belfry no-exit'>
         DIIIIIIIIIINNNNNNGGGG!!!!!!!
         </para>

         <para number='366' comment='parapet no-exit'>
         There are REASONS Dingbat doesn't come up here, you know. You should escape to safety by going down the stairs. Now!
         </para>

         <para number='394' comment='Dome West no-exit'>
         Even in the nicest areas of the dome, you shouldn't go straying from the main road. But yes, this IS the nicest area.
         </para>

         <para number='773' comment='exchange no-exit'>
         As you step toward the dome wall, you block the exchange information it is displaying, bringing a chorus of hisses, boos and "down in in front!"s from the other traders. The exit is northeast.
         </para>

         <para number='783' comment='Cliff Dive no-exit'>
         The darker recesses of the Cliff Dive are no safe place for a cute little dish such as yourself. Stick to the defined routes. The exit is northwest
         </para>

         <para number='855' comment='Gunga s Tent no-exit'>
         Unless you're looking for a 'arf a pint o' Gunga Ding's Water-Green (and it would be truly remarkable if you were), you won't find what you're looking for in that direction. The exit is north.
         </para>

      </section>

   </category>

</para-list>

