<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Underwater All-Purpose Noexit'>
         Careful of those reef walls! The coral can be sharp, and who knows what manner of creature may take offense to your nosing around.
         </para>

         <para number='2' comment='Air All Purpose Noexit'>
         If the location description here has you climbing the walls, perhaps you should just leave and find a more exciting locale.
         </para>

         <para number='3' comment='Main Palace Noexit'>
         Your blind staggering about has gotten the attention of the courtiers and flunkies milling around. They point and laugh at the "ugly drybody" making a fool of himself.
         </para>

         <para number='4' comment='Construction Zone Noexit'>
         A busy construction worker hollars at you. "Look, if you're going to poke your nose around up here, you're liable to get it knocked off. Keep out of the construction zone."
         </para>

         <para number='5' comment='Office Tower Noexit'>
         A friendly businessman notices your lost bumbling about and takes pity on you, directing you to the exit.
         </para>

         <para number='6' comment='Leisure tower noexit'>
         Overstimulation from all the wonders of the leisure tower has clearly addled your brain. That is not an exit.
         </para>

         <para number='226' comment='Noexit from nicer whale'>
         While this taxi-whale is much cleaner and more comfortable than that OTHER whale, the comfort and cleanliness likely doesn't extend into the, shall we say, deeper areas of the whale. You probably want to swim out, at this point.
         </para>

         <para number='523' comment='Noexit at Exchange'>
         You stumble into a surly trader, distracting him from his sale. Angrily, he pushes you toward the exit to the south.
         </para>

         <para number='587' comment='Noexit at LP'>
         Look, there are only two directions that don't work from this location. That's one of them. Quit fooling around and get in the water!
         </para>

         <para number='588' comment='Noexit for Beside the platform'>
         If you'd like to return to the sea, swim down. Otherwise, climb up to the LP.
         </para>

         <para number='610' comment='Noexit from drunk whale'>
         You definitely don't want to go THAT way. Who knows where you might come out. Out! You want to go out!
         </para>

         <para number='1132' comment='Jordis  noexit'>
         A polka-dotted polecat suddenly appears from nowhere and begins to wind around your ankles, chirping and purring. Its insistence for attention prevents you from continuing in that direction
         </para>

         <para number='1294' comment='Noexit at Taxi Pickup'>
         As you swim along, exploring, a surly looking grizzled old merman swims up to you. One arm hangs mangled and useless at one side, and an eye patch covers one of his eyes. "Ye don' want to be wanderin' out into the deep blue alone, matey," he intones gruffly. "Here there be monsters." He leads you back to your previous location and tells you to keep to the path.
         </para>

         <para number='1296' comment='Sand Bar Noexit'>
         You bump into a forlorn trader recovering from a rough day at the exchange, knocking his artificial gills from his mouth. As he struggles to get them back in, you consider that perhaps this wasn't what he had in mind when he came to drown his sorrows.
         </para>

         <para number='1370' comment='Noexit at Neptune s Throne Room'>
         As you attempt to force your way into the throne room, a swordfish guard blocks your path and shakes his bill at you threateningly. Maybe you should just escape to the west.
         </para>

         <para number='1422' comment='Noexit at taxi dropoff'>
         The city is NE. If you want to go back to the LP, you'll have to find another taxi. Pray you don't find another like the one you were just in.
         </para>

         <para number='1424' comment='Hospital Noexit'>
         As you wander deeper into the hospital, a friendly nurse shark approaches you and guides you back to the waiting room. "You don't want to be wandering around, hon," she says, "it's sea-sickness season, and you don't want to catch the hogfish flu that's going around."
         </para>

      </section>

   </category>

</para-list>

