<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='202' comment='Noexit message at Fire'>
         The cosmos will not tolerate deviances from defined paths. Flames threaten to devour your ship, forcing you to return to your previous location.
         </para>

         <para number='265' comment='Noexit message at Hot'>
         The cosmos will not tolerate deviances from defined paths. Suffocating heat surrounds your ship, forcing you to return to your previous location.
         </para>

         <para number='267' comment='Noexit message at Dry'>
         The cosmos will not tolerate deviances from defined paths. Your ship is on the verge of dehydration, forcing you to return to your previous location.
         </para>

         <para number='328' comment='Noexit message at Air'>
         The cosmos will not tolerate deviances from defined paths. Wind buffets your ship, forcing you to return to your previous location.
         </para>

         <para number='330' comment='Noexit message at Aether'>
         The cosmos will not tolerate deviances from defined paths. The vacuum of Aether drags you back into equilibrium.
         </para>

         <para number='332' comment='Noexit message at Earth'>
         The cosmos will not tolerate deviances from defined paths. Walls of Earth block your path, forcing you to return to your previous location.
         </para>

         <para number='393' comment='Noexit message at Wet'>
         The cosmos will not tolerate deviances from defined paths. Intolerable moisture threatens to swamp your ship, forcing you to return to your previous location.
         </para>

         <para number='395' comment='Noexit message at Cold'>
         The cosmos will not tolerate deviances from defined paths. Unbearable Cold freezes your progress, forcing you to return to your previous location.
         </para>

         <para number='458' comment='Noexit message at Water'>
         The cosmos will not tolerate deviances from defined paths. Your ship is tossed and battered by waves, forcing you to return to your previous location.
         </para>

      </section>

   </category>

</para-list>

