<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for Rock'>
         Rock walls stop you from moving in that direction, because the terraformed area ends here.
         </para>

      </section>

      <section name='tranq'>

         <para number='1' comment='Loc 715 - disturb tranquility'>
         You carefully wade into the pool and are suddenly pulled downward by an unseen force, much like that of a gravshaft. After falling for what seems like an eternity, you finally come to rest at the bottom of the shaft and find yourself in unfamiliar surroundings...
         </para>

         <para number='2' comment='roomex'>
         Suddenly, %s wades into the pool and is sucked down into the liquid, disappearing from view.
         </para>

      </section>

   </category>

</para-list>

