<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='spindle'>

      <section name='house'>

         <para number='1' comment='Wall'>
         You run into a wall and hurt your nose.
         </para>

      </section>

      <section name='planet'>

         <para number='1' comment='out of bounds'>
         If you go that way you will fly off the ring and into the Sun.
         </para>

         <para number='2' comment='pool'>
         You hit your head on the rocks and decide not to try that again.
         </para>

      </section>

   </category>

</para-list>

