<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='no exit msg'>
         You proceed into the mist and immediately lose all sense of direction and time. As you move through the haziness, shapes and faces come into your awareness, only to be forgotten for the next. You have no idea how much time has passed as you come to the realization that you actually have not moved at all.
         </para>

      </section>

   </category>

</para-list>

