<?xml version="1.0"?>

<para-list version='24' editor='standard'>

   <category name='forest'>

      <section name='gear'>

         <para number='1' comment='fish'>
         You prepare and cast a line into the water.  While waiting and watching the small waves as they gently disturb the bobber and lap against the sides of your boat, you reflect on the serene beauty of the blue sky framing the snow-capped mountains and green forest that surround you and remember to just appreciate living.
         </para>

         <para number='2' comment='fish2'>
         Before long, you have a nice catch of fish, ready for the campfire.
         </para>

      </section>

   </category>

   <category name='general'>

      <section name='jewells'>

         <para number='1' comment='Cat msg 1'>
         Pirate walks up to you and sniffs at your knee (or equivalent).
         </para>

         <para number='2' comment='Cat msg 2'>
         Attempting to get your attention, Pirate meows and looks at you expectantly.
         </para>

         <para number='3' comment='Cat msg 3'>
         Ella walks up to you, and with a lithe motion rubs against you while arching her back.
         </para>

         <para number='4' comment='Cat msg 4'>
         Ella taps her tail absently, but knowing Pirate is watching. When he tries to snatch at it, she runs out of his sight. He gives chase, only to be ambushed by her as soon as he rounds the corner.
         </para>

         <para number='5' comment='Kick - No insurance message'>
         You should think twice about tangling with sharp animals when you are not insured. The planet's safety systems have teleported you to the hospital in an effort to strongly encourage you to INSURE.
         </para>

         <para number='6' comment='Kick - insurance good'>
         You try to kick at one of the cats as it passes by, but it's too quick for you and as it jumps out of the way, an outstretched claw manages to give you a nasty scratch.
         </para>

         <para number='7' comment='Sit msg'>
         As you sit on the comfortable couch, Ella jumps up and snuggles into your lap. When your attention is diverted, she reaches up and taps you with a paw until you start petting her again. After a while, something else attracts her, and she leaps down.
         </para>

      </section>

      <section name='keepout'>

         <para number='1' comment='Repair office - 2077'>
         You try the door, but just as you feel it begin to give, it snaps shut again quite violently, pushing you back into the corridor. Through your confusion you remember that ship repairs aren't currently required.
         </para>

      </section>

      <section name='pq_keypad'>

         <para number='1' comment='bad code'>
         There is a buzz and the small red light flashes and goes out.
         </para>

      </section>

      <section name='teleport'>

         <para number='1' comment='Use planet teleporter msg'>
         As you enter the teleporter the humming grows louder, and you feel a warmth and tingling on your skin.  The sensation penetrates you to your core as your sight fills with intense white light and your hearing reduces to silence.  You feel as if you are floating and lose all sense of time.  As your hearing comes up and your sight returns, you see that you have arrived at...
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit msg - orbital platform'>
         Walls are a rather underappreciated device. They have just prevented you from tumbling into space, condemned forever as so much interstellar flotsam. Perhaps you will look at walls differently from now on, hmm?
         </para>

         <para number='2' comment='noexit-planet'>
         There is really nothing for you in that direction.  You might get into a situation where you have to chew your own arm off.  Nobody wants that.
         </para>

         <para number='3' comment='noexit quarters security 1631'>
         There really should have been no way to get here, but to get out, you should be able to go down.
         </para>

      </section>

   </category>

</para-list>

