<?xml version="1.0"?>

<para-list version='5' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Somma'>
         Your way is barred by cold, hard ice - you have reached the limit of the planet's terraforming.
         </para>

         <para number='2' comment='Surface wall no movement'>
         A frozen wall prevents you from moving in that direction.
         </para>

         <para number='3' comment='Cave no movement'>
         The cave does not extend in that direction.
         </para>

         <para number='4' comment='Hospital be more gental'>
         There is a wall there and a lot of delicate equipment, please be more careful.
         </para>

         <para number='5' comment='Jinto s office no movement'>
         Jinto's living quarters are not that large.
         </para>

      </section>

   </category>

</para-list>

