<?xml version="1.0"?>

<para-list version='9' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for Haidec spac'>
         The cold, hard vacuum of space lies that way, and there's nothing for you there.
         </para>

         <para number='2' comment='asteroid belt movement'>
         The defense grid starts to glow an ominous red color prompting you to change your mind.
         </para>

      </section>

   </category>

</para-list>

