<?xml version="1.0"?>

<para-list version='5' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Despite the appearances of being able to float in any direction, YOU CAN'T. Just as you begin to float off into nothingness you are shoved back by an invisible force. Be careful though, that force may not always be there.
         </para>

      </section>

   </category>

</para-list>

