<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='cheeseplanet noexit'>
         I know the planet looks absolutely delicious and you want to run off and eat the planet but you cannot. You need to stay within the colony. If we let everyone run off and start eating the planet before long the planet would be gone.
         </para>

      </section>

   </category>

</para-list>

