<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='noexit message'>
         You cannot go in that direction and if you are not careful running around here you might find the consequences deadly.
         </para>

      </section>

   </category>

   <category name='rooms'>

      <section name='exchange'>

         <para number='1' comment='have glowrock'>
         The glowrock helps to illuminate the entire room and you can see you are in the exchange. You can see several very nice comfortable couches around the room. You can also see several vending machines selling various snacks to keep you energized as you do your trading. Countless screens are set up in random arrangement all around the room to facilitate any trading you wish to do.
         </para>

         <para number='2' comment='dont have glowrock'>
         The room is rather dark and the only illumination is the faint light given off by the trading monitors. You cannot see anything but countless trading monitors set up in random arrangement all around the room to use for your trading purposes. As you move around the room you keep painfully bumping into pieces of furniture that you cannot see in the faint light and your stamina drops a little..
         </para>

      </section>

      <section name='punjistick'>

         <para number='1' comment='have glowrock'>
         The glowrock helps to illuminate the punji stick pit in front of you and you are able to avoid falling in. You are quite relieved you did not fall in as there are thousands of punji sticks down below and all of them look very, very sharp. Falling into this pit would certainly result in impalement and a painful death. You can stock around and admire the sharpness of the punji sticks or you can go back NORTH to the antechamber.
         </para>

         <para number='2' comment='dont have glowrock'>
         You cannot see anything and after a few steps the ground disappears beneath you. You have only a few seconds as you fall to think about what trouble you have gotten into. Then you find yourself impaled on many sharpened punji sticks and you quickly and painfully bleed to death.
         </para>

      </section>

      <section name='shipyard'>

         <para number='1' comment='have glowrock'>
         The glowrock helps to illuminate the room and you can see a large assortment of spaceships for sale. All the newest models are here in mint condition and they shine brilliantly in the light of the glowrock. You can purchase a ship here or you can repair your current one.
         </para>

         <para number='2' comment='dont have glowrock'>
         The room is quite dark and you cannot make out much of anything. As you move around the room you painfully bump into several large hunks of metal and quickly realize this is the shipyard and you are bumping into the display models. Your stamina drops a little. You can purchase a ship here or repair your current one.
         </para>

      </section>

      <section name='snakepit'>

         <para number='1' comment='have glowrock'>
         The glow rock helps to illuminate the small snake pit in front of you and you are able to avoid falling in. You are quite relieved you did not fall in as many of the snakes below look hungry and not friendly at all. You can stick around and admire the many different species of snakes or you can go back WEST to the antechamber.
         </para>

         <para number='2' comment='dont have glowrock'>
         You cannot see anything and after a few step the ground falls out from underneath you. You land with a thud at the bottom of a pit and hear hissing noises from all around you. You begin to feel around to try to find your bearings. As you move about the hissing noise gets louder and the next thing you know you feel several sharp stabs in various places on your body.
         </para>

         <para number='3' comment='dont have glowrock continued'>
         You realize too late you have fallen into a snake pit. You continue to receive bites from every direction as you writhe in pain and the poisons take effect on your body. As the different poisons work there way through your system you become paralyzed and you slowly fade away into a painful, uncomfortable death.
         </para>

      </section>

      <section name='trashpit'>

         <para number='1' comment='have glowrock'>
         The glowrock helps to illuminate the very large trash pit in front of you and you are able to avoid falling in. You are very happy about not falling in but not to pleased with the smell of this place. You decide it is in your best interest to go back EAST to the antechamber and escape this stench.
         </para>

         <para number='2' comment='dont have glowrock'>
         You cannot see anything and after a few steps the ground disappears below you. You fall into a large pit and as you land you find yourself at the bottom or a large trash pit. The stench is horrible and you begin to gag from the fumes. Your vision starts to blacken as you gasp for air. You quickly pass out from the stench and never wake up.
         </para>

      </section>

      <section name='waterpit'>

         <para number='1' comment='have glowrock'>
         The glowrock helps to illuminate the large water pit in front of you and you are able to avoid falling in. This seems to be the storage area for the planet's water supply. When you get bored of looking at the pit of water you can go back SOUTH to the antechamber.
         </para>

         <para number='2' comment='dont have glowrock'>
         You cannot see anything and after a few steps the ground disappears underneath you. You fall head over heads and splash down into a pool of water. You swim around looking for an exit but the walls of the pit are perfectly smooth. You tread water and call out for help for quite some time but to no avail. Eventually you tire and slowly slip beneath the surface to a silent watery death.
         </para>

      </section>

   </category>

</para-list>

