<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Vivid no exit'>
         HEY, I realize this planet is so bright that its difficult to see but you cannot go that way. Adjust your sunglasses or get your eyes checked or something.
         </para>

      </section>

      <section name='sunglasses'>

         <para number='1'>
         As you put on the sunglasses a previously unseen droid appears and opens the exit door and ushers you out the door onto the surface of the planet. He hurriedly warns you to not remove your sunglasses or you will most definately go blind and then quickly shuts the door behind you.
         </para>

      </section>

   </category>

</para-list>

