<?xml version="1.0"?>

<para-list version='6'>

   <category name='extras'>

      <section name='security'>

         <para number='1' comment='door creak msg - loc 2263 - sec'>
         The door creaks as %s steps into the room.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='LP-loc2138-noexitmessage'>
         The brush and undergrowth on the side of the trail is just to thick to move that direction.
         </para>

         <para number='2' comment='lobby-multiple-noexitmessage'>
         You bump into a construction worker covered in dirt and oil. He suggests you trying heading a different way, preferably a clear pathway.
         </para>

         <para number='3' comment='bar-loc2135-noexitmessage'>
         So enthralled by your own reflection you walk towards yourself, until you are nose to nose (or equivalent). The cold glass of the mirror offers an uncomfortable chill.
         </para>

      </section>

   </category>

</para-list>

