<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='space.multi.noexitmessage'>
         Space is a mighty large adventure, except not here. A small ship cuts you off from your destination and confines you to the Interstellar Link and Orbit.
         </para>

      </section>

   </category>

</para-list>

