<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Water locations'>
         You splutter and splash nearly drowning yourself before realizing you cannot move in that direction.
         </para>

         <para number='2' comment='Path message'>
         A sweet but firm looking forest ranger comes up to you and asks you if you are lost. She leads you back to the path.
         </para>

         <para number='3' comment='road ranger message'>
         A sweet but firm looking forest ranger comes up to you and asks you if you are lost. She leads you back onto the road.
         </para>

         <para number='4' comment='populated areas message'>
         Jostling people only gets you some curious looks as it is soon evident that travel in that direction is not possible.
         </para>

      </section>

   </category>

</para-list>


