<?xml version="1.0"?>

<para-list version='7' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Ranger'>
         A sweet but firm looking forest ranger comes up to you and asks you if you are lost. She leads you back to the path.
         </para>

         <para number='2' comment='River'>
         The current is to strong for you to go in that direction!
         </para>

         <para number='3' comment='Nature trail'>
         Bob the forest ranger comes up to you can gives you a stern look and lectures you about the importance about staying on the designated path.
         </para>

         <para number='4' comment='Bonk'>
         Doah! Thats the wall!
         </para>

      </section>

   </category>

</para-list>



