<?xml version="1.0"?>

<para-list version='11' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for River space'>
         A ranger ship speeds out and blocks your path to keep you from going into uncharted areas of space and getting lost.
         </para>

         <para number='2' comment='Elevator'>
         Crash! That was the glass wall you just ran into. You are fortunate that the glass is shatter proof. The only problem is that you have a huge knot on your forehead! You begin to see birds or maybe fish floating around your head.
         </para>

         <para number='3' comment='Water'>
         You can't walk on water!!
         </para>

      </section>

   </category>

</para-list>



