<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexits'>

         <para number='1' comment='Glory no exit message'>
         While walking into walls may be funny at first, it gets old fast, so a nice security guard asks you to examine the exit directions more closely.
         </para>

         <para number='2' comment='Elevator no exit message'>
         Its dangerous to goof off in elevators, please note that the exit is North, or the elevator can go up or down to other levels.
         </para>

         <para number='3' comment='Residential no exit'>
         That door is locked.
         </para>

         <para number='4' comment='welcome hall no exit'>
         Congratulations!  You had to work hard to find a direction that is does not lead anywhere and you did it!
         </para>

      </section>

   </category>

</para-list>


