<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexits'>

         <para number='1' comment='pride basic message'>
         This is not an exit, please try again.
         </para>

         <para number='2' comment='agricultural movement'>
         That door is locked.
         </para>

         <para number='3' comment='mining'>
         That area of the mine is to dangerous for visitors.
         </para>

         <para number='4' comment='paradise'>
         Why would you ever want to leave, especially if you are here with a loved one, but if you really want to go you can leave by going OUT.
         </para>

      </section>

   </category>

</para-list>

