<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='no exit message'>
         You can't go that way, clearly you are not an Arsenal Supporter and don't know your way round., I would'nt draw attention to yourself like that again!!
         </para>

         <para number='2' comment='no exit message'>
         Hmmmm, spoilt for choice on exits am not sure why you decided to go that way!!! The lift seems to be out of bounds at the moment, but you could still explore the museum to the northwest, north and northeast or head east back to the entrance, the Directors box is south if you wanted to sneak a peek!
         </para>

      </section>

   </category>

</para-list>

