<?xml version="1.0"?>

<para-list version='9' editor='standard'>

   <category name='moves'>

      <section name='airlock'>

         <para number='1' comment='press button - 396 - player'>
         As you press the button, your skin tingles as a security scan is performed. After a few seconds, the airlock door opens and you move south...
         </para>

         <para number='2' comment='roomex'>
         %s opens the airlock door and moves south into the station.
         </para>

         <para number='3' comment='announce for 2061'>
         Security Alert: %s has just entered the Station.
         </para>

      </section>

      <section name='altar'>

         <para number='1' comment='Step onto altar - 588 - player'>
         You carefully step onto the altar and stand eye to eye with the holo of the prophet Gaelaan. Suddenly, a wave of energy washes over you and you are transported to another place...
         </para>

         <para number='2' comment='Roomex'>
         %s stands on the altar and there is a flash of white light.
         </para>

         <para number='3' comment='Announce for 2060'>
         There is a flash of white light and a figure appears inside it!
         </para>

         <para number='4' comment='Announce for 2061'>
         Security alert: %s has just activated the temple teleporter.
         </para>

      </section>

      <section name='exchange'>

         <para number='1' comment='press button - 460 - player'>
         As you press the button, your skin tingles as a security scan is performed. After a few seconds, the door slides open and you move west into the exchange...
         </para>

         <para number='2' comment='Announce for 2061'>
         Security alert: %s has just entered the exchange.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='No exit message - Habitat'>
         You cannot walk through the solid metal bulkhead.
         </para>

      </section>

      <section name='teleport'>

         <para number='1' comment='activate teleporter - 2061 - pl'>
         A wave of energy washes over you and you are transported to another place...
         </para>

         <para number='2' comment='roomex'>
         %s fiddles with the teleporter controls and there is a flash of white light.
         </para>

         <para number='3' comment='announce for 588'>
         There is a flash of white light and a figure appears inside it!
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='remote'>

         <para number='1' comment='Roomex for player using remote'>
         You watch as %s removes a small device from his pocket and fiddles with the controls. Suddenly, there is a bright flash of white light.
         </para>

         <para number='2' comment='Announce for player appearing'>
         There is a flash of white light and a figure appears inside it!
         </para>

         <para number='3' comment='exchange teleporter - player'>
         You remove the teleporter remote from your pocket and fiddle with the controls. Suddenly, a wave of energy washes over you and you are transported to the exchange...
         </para>

         <para number='4' comment='dock teleporter - player'>
         You remove the teleporter remote from your pocket and fiddle with the controls. Suddenly, a wave of energy washes over you and you are transported to the docking bay...
         </para>

         <para number='5' comment='office teleporter'>
         You remove the teleporter remote from your pocket and fiddle with the controls. Suddenly, a wave of energy washes over you and you are transported to Dunavant's office...
         </para>

         <para number='6' comment='retreat teleporter'>
         You remove the teleporter remote from your pocket and fiddle with the controls. Suddenly, a wave of energy washes over you and you are transported to another place...
         </para>

      </section>

   </category>

</para-list>


