<?xml version="1.0"?>

<para-list version='8' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Rescue space'>
         You are not allowed to land on the planet, and there's nothing else of interest in this system, so all you can do is dock your shuttle with the habitat, or jump elsewhere.
         </para>

      </section>

   </category>

</para-list>

