<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Official Locations'>
         A large fellow steps into your path and advises that you find another route to your destination.
         </para>

         <para number='2' comment='Interior Rooms (lp area)'>
         You run headlong into a wall and stagger backwards.
         </para>

         <para number='3' comment='Taverns / Bars'>
         You stagger into a wall and a waitress catches you and says "Hey there friend be careful".
         </para>

         <para number='4' comment='Restaurants'>
         A waiter takes you back to your seat.
         </para>

         <para number='5' comment='Gondola Ride'>
         You press your face to the window and realize that it's a good thing it's strong glass, it is a long long way down.
         </para>

         <para number='6' comment='Mansion Balcony'>
         The balcony wall blocks your way.
         </para>

         <para number='7' comment='Mansion Interior'>
         A house servant redirects you back the way you came.
         </para>

         <para number='8' comment='Mansion Exterior (front)'>
         A stone wall blocks your way.
         </para>

         <para number='9' comment='Mansion Exterior (rear)'>
         Please do not leave the designated paths the plants are delicate.
         </para>

         <para number='10' comment='Mansion Change Room'>
         Are you properly attired for the pool?
         </para>

         <para number='11' comment='Mansion Pool'>
         Did you remember to change out of your suit? ..... Wouldn't want to frighten folks with those blindingly white legs.
         </para>

         <para number='12' comment='Hideaway Interior'>
         That door seems securely locked.
         </para>

         <para number='13' comment='Hideaway Exterior'>
         Careful of the porch railing, it's loose and you may fall.
         </para>

         <para number='14' comment='Mountain Road'>
         You get tangled in the thick underbrush and are forced to return the way you came.
         </para>

         <para number='15' comment='Cave Corridor'>
         The walls are smooth to the touch and you cannot find a path this direction.
         </para>

         <para number='16' comment='Altaire'>
         You bump into a local on his way to somewhere. He smiles as he tips his hat to you.
         </para>

         <para number='17' comment='Falcon s Nest'>
         The innkeep directs you back the way you came.
         </para>

         <para number='18' comment='Peking Moon'>
         You step on a cat and it hisses back at you reminding you of someone but you can't quite place it.
         </para>

      </section>

   </category>

</para-list>

