<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Sapphire Space Locs'>
         Your attempt to leave Sapphire space in that direction is thwarted by a menacing blood red ship.
         </para>

         <para number='2' comment='Altaria Space Locs'>
         Your attempt to leave Altaria Orbit in that direction is thwarted by a menacing blood red ship.
         </para>

      </section>

   </category>

</para-list>

