<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='move'>

      <section name='noexit'>

         <para number='1' comment='general no exit message'>
         I don't see how you can possibly go that way.
         </para>

         <para number='2' comment='promade no exit message'>
         A force field has prevented you from moving in a direction that might result in serious injury.
         </para>

         <para number='3' comment='grand hotel noexit message'>
         The bell captain at the concierge desk clears his throat and gives you another distasteful look. You realize that if you continue in this behavior he may be forced to call the authorities.
         </para>

         <para number='4' comment='grand hotel desk clerk noexit'>
         The desk clerk sneers at you sarcastically and asks, "What part of no room without a reservation certificate isn't clear, and how do you think this behavior will help?"
         </para>

         <para number='5' comment='teleport station no exit msg'>
         The Security Guard persuades you to cease such behavior, since you clearly do not have the proper credentials to access the teleporters.
         </para>

         <para number='6' comment='ventilation duct no exit'>
         You cannot possible go that direction without bending your body in a way that would result in serious injury.
         </para>

      </section>

   </category>

</para-list>


