<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='move'>

      <section name='noexit'>

         <para number='1' comment='no entry into forbidden space'>
         You hear the loud warble of a computer alarm. Looking at the display, you realize that a nearby ship has locked a phase cannon on your engine. You realize that proceeding further in this direction is pure folly and turn back.
         </para>

         <para number='2' comment='parking orbit exit is only up'>
         The squeel from your proximity alarm indicates that you are about to slam into another ship. Where did you get your pilot's license? You should exit the parking orbit by moving UP. Geez!
         </para>

      </section>

   </category>

</para-list>


