<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='maji'>

      <section name='space'>

         <para number='1' comment='space'>
         Blinking space beacons keep you from going that direction.
         </para>

      </section>

      <section name='surface'>

         <para number='1' comment='landing area'>
         You bump into a vacant spaceship shuttle.
         </para>

         <para number='2' comment='exchange'>
         You bump into the walls of the hut.
         </para>

         <para number='3' comment='beach bar'>
         You stumble and trip on a barstool.
         </para>

         <para number='4' comment='beach'>
         A nasty little crab-like creature bars your way, his tiny pinchers going for your toes.
         </para>

         <para number='5' comment='cave'>
         You bump your nose on the rock wall.
         </para>

         <para number='6' comment='darkness'>
         You turn and turn and are unable to find your way.
         </para>

         <para number='7' comment='barracks'>
         A tall soldier in black and gold livery blocks your path.
         </para>

      </section>

      <section name='under'>

         <para number='1' comment='cavern'>
         You bump into a pale human, who turns to tell you to watch your step.
         </para>

         <para number='2' comment='crypts'>
         You crash against the stone wall.
         </para>

         <para number='3' comment='crystal'>
         The brilliant light from the crystals must be in your eyes because you find you can't go that way.
         </para>

      </section>

   </category>

</para-list>

