<?xml version="1.0"?>

<para-list version='7' editor='standard'>

   <category name='cafe'>

      <section name='chocs'>

         <para number='1' comment='buy chocolates - can t afford'>
         You can't afford to buy any chocolates.
         </para>

         <para number='2' comment='Can afford'>
         You pay 20 groats and are given a box of chocolate-covered caramels.
         </para>

         <para number='3' comment='eat caramels'>
         You pop several of the candies into your mouth and start sucking the chocolate off the outside. When you are left with the little nuggets of caramel, you chew them up and wonder whether to eat some more.
         </para>

      </section>

      <section name='food'>

         <para number='1' comment='loc 327 - order sandwich'>
         Within seconds you are handed a plate with a hot sandwich, apple slices and a drink set near by. Your waitdroid slips a small dish of Caramel sauce on the side, 'on the house' it says and then it quickly rolls away.
         </para>

         <para number='2' comment='order pizza'>
         A waitdroid brings a huge plate with a piece of peanut butter/M&amp;M pizza that is so large you think you're going to need a fork and your drink. "That's my favorite kind," it says before rolling away.
         </para>

      </section>

   </category>

   <category name='fun'>

      <section name='beach'>

         <para number='1' comment='loc 783 - go swimming'>
         Standing there looking at the water, the waves splashing up onto the shore, you cannot help yourself, you have to take a swim! With that you kick off your sandals and run for it. The water feels great on your feet and once it gets to your waist you dive under, swimming out a good ways before relaxing, laying in the water on your back and letting it wash all your worries away.
         </para>

         <para number='2' comment='play volleyball'>
         You decide to join in on a game of volleyball, and it just so happens that one side is a person short - how perfect! The guy in front of you dives for the ball and gets a mouth full of sand, everyone starts laughing as he tries spitting out the sand, even he has a smile on his face. You haven't felt this good since... Well, lets just say it's been a while....
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Landing pad - no exit - loc 328'>
         You notice a friendly Caramelien shaking his head 'Sorry friend, only Caramelien Gods can walk through walls'
         </para>

         <para number='2' comment='Cafe - loc 327 - no exit msg'>
         'Hey now, you might have had a bit to much fruit juice, maybe you should sit for awhile until you can see the exit clearly'
         </para>

         <para number='3' comment='Tour, no exit message'>
         Caramelien Stewardess reminds you that you need to stay with the tour group until the tour is done.
         </para>

         <para number='4' comment='hospital no exit'>
         Only authorized Caramelien personal allowed that way
         </para>

         <para number='5' comment='Beach'>
         Hey Dude, There's nothing but water that way
         </para>

         <para number='6' comment='Hotel/elevator'>
         The Caramelien bell hop stops humming and gives you a look, you decide it's best to go another way.
         </para>

         <para number='7' comment='Singles'>
         You waitdroid rolls up next to you, 'Excuse me, But there is no fire, in which case please refrain from exiting out the windows.'
         </para>

         <para number='8' comment='Hotel Hallway'>
         A friendly voice comes from above, 'You maybe in a hurry, but please use the proper exits'
         </para>

         <para number='9' comment='bachelorette pad'>
         A waitdroid wheels beside you, 'Hey now, maybe you have had a bit to much to drink, why don't you sit for a while, atleast until you can find the exit.
         </para>

         <para number='10' comment='bachelor pad'>
         Still dribbling the basketball a waitdroid stops you, 'Dude, you not in the right frame of mind to go running around the hotel, lets shoot some more hoops until you can see straight.'
         </para>

         <para number='11' comment='Hooneymooners suites'>
         A voice comes from above, ' You might be in a hurry, but atleast put some clothes on before running out the door!'
         </para>

         <para number='12' comment='QM s Office'>
         A camera picks up your movement and a loud booming voice comes from somewhere in the room. 'HEY YOU! WHAT ARE YOU DOING IN HERE?! YOU BEST GET "OUT" BEFORE WE GET THERE OR YOUR BUT IS MUD!' If you only knew that Queenmommy herself was watching you and laughing her buns off the entire time are you run from the room.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='bag'>

         <para number='1' comment='open goodie bag'>
         You open up the goodie bag and take out a delicious chocolate caramel, which melts in your mouth.
         </para>

      </section>

   </category>

   <category name='party'>

      <section name='hen'>

         <para number='1' comment='loc 401 - order desserts'>
         A waitdroid appears with a cart over flowing with goodies, cakes, pies, cookies, anything you can think of, and after making your selection it leaves with a wink...
         </para>

         <para number='2' comment='chip n dale'>
         You are a tad nervous about male dancers coming to your room, but what the heck, this is your last night as a unmarried female. Besides, could be fun, with all your BFFs there with ya! The door opens and the lights go out, you hear sexy music and someone stumbles in the dark, then a strobe light comes on and there are three males dancing in front of you.
         </para>

         <para number='3'>
         Once your eyes adjust you see that they are short, very short, with clown noses and bells on their feet! You are laughing so hard you couldn't see what they were doing if you wanted to!
         </para>

      </section>

      <section name='loft'>

         <para number='1' comment='loc 337 - order wine'>
         A waitdroid quickly appears at the door and hands you a bottle of wine and leaves a bucket filled with ice nearby. The waitdroid then leaves as quickly as it appeared.
         </para>

         <para number='2' comment='order strawberries'>
         A waitdroid appears with a large plate of strawberries, small cups of caramel and chocolate sauces and with a wink quickly leaves the room.
         </para>

         <para number='3' comment='loc 339 - order champagne'>
         A waitdroid opens the door slowly and after seeing that the coast is clear, proceeds into the room. It leaves a bucket of ice with the bottle sticking out on the table by the door, then leaves as quickly as possible.
         </para>

         <para number='4' comment='order peaches'>
         A waitdroid appears and with him he has a plate with peaches and pears, chocolate and caramel sauce. The waitdroid turns with a smile and wheels out of the room.
         </para>

      </section>

      <section name='stag'>

         <para number='1' comment='loc 403 - order round'>
         A waitdroid pops up behind the bar and offers you some choices. After choosing your favorite drink it pours double shots for everyone in the room and then chants 'Drink, Drink, DRINK!' until every glass is empty. Then it disappears somewhere behind the bar until needed again.
         </para>

         <para number='2' comment='dancing girls'>
         Within seconds the door opens and the most beautiful women walk into the room. Instead of grabbing a pole and dancing they slowly, sexily walk up to you, all with sly smiles on their faces.
         </para>

         <para number='3'>
         Just when you think it couldn't be better because you're not just going to get a show, but a very close up show, one by one they each give you a smack and tell you what a pig you are being, wanting to look at women when your wife-to-be is across the hall! Oh dear, it started out well...
         </para>

      </section>

   </category>

   <category name='tour'>

      <section name='present'>

         <para number='1' comment='loc 394 - give goodie bag'>
         As you near the door to the SE you are handed a goodie bag of Caramelish samples to enjoy durring the tour.
         </para>

         <para number='2'>
         As you finish the tour you are given a T-Shirt that says 'I love Caramel' on the front and 'I took the Caramel Tour' on the back, as you are pushed towards the exit door to the W.
         </para>

      </section>

   </category>

</para-list>

