<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='crunchalot story'>
         Leaving without hearing the rest of the story could leave your mind wandering for days! Please continue on the proper path..
         </para>

         <para number='2' comment='crunchy ex, cafe, hosp, empty'>
         Please stop dumping into the walls, the oil from your skin will make our paint peel!
         </para>

         <para number='3' comment='crunchy offices'>
         Just back out the way you came, seems to be the safest thing to do..
         </para>

      </section>

   </category>

</para-list>

