<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Unless you are wearing a lifejacket, it's best to stick to the marked paths.
         </para>

         <para number='2'>
         Elevators only go up and down.  Bouncing off the walls isn't very healthy (much less very sane).
         </para>

         <para number='3'>
         Please stay in the lighted corridors.  It's for you own safety.
         </para>

         <para number='4'>
         This isn't your house, so please don't rummage thru the rooms!
         </para>

         <para number='5'>
         Not staying on the marked pathways could lead to a nasty fall to the factory floor!
         </para>

         <para number='6'>
         Rummaging about in the Slayer's things is a really reallly bad idea.
         </para>

         <para number='7'>
         Rummaging about in the Tracker's things could lead to a short career here!
         </para>

      </section>

   </category>

</para-list>

