<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         A fleet of dragons decends upon your position.  Fire is bellowing forth from the nose of each corsair.  As they get closer, you can see they are really fighters.  Your com squawks, "Stay within the marked corridors of Urland space or be incinerated.  This will be your only warning."
         </para>

      </section>

   </category>

</para-list>

