<?xml version="1.0"?>

<para-list version='13' editor='standard'>

   <category name='phlax'>

      <section name='nomoves'>

         <para number='1' comment='cant move onna ground'>
         Try as you might, you simply cannot shift phase as the true Phorbans do and you bump your nose trying to walk through the wall.    Sadly, you will need to stick to the marked pathways for folk such as yourself.
         </para>

         <para number='2' comment='cant move offa mountain'>
         Peering down the mountain, you suddenly realize just how far of a drop it would be to wander off in that direction.    Resisting the urge to move, you decide to stay put, thinking you better look around again for an alternate egress.
         </para>

         <para number='3' comment='cant get out uva bldg'>
         You feel silly walking into the wall, bumping things as you go and drawing the stares of others in the area.    Maybe you need to think about how you arrived here and try reversing direction to get out again.
         </para>

         <para number='4' comment='cant get out uva hospital'>
         You stagger about, knocking things over, almost falling on your face before a comly nurse assists you back up.  She stares at you with a concerned look on her face for a moment before she is assured you are OK, whereupon she wanders off about her duties.
         </para>

         <para number='5' comment='cant get out uva pharms'>
         Your attempt to move in that direction draws the scrutiny of two burly armed guards.  They gruffly approach you and tell you to either get in line for your meds or leave the way you came in.  You think it is best not to argue with these two.
         </para>

         <para number='6' comment='cant get out uva looneybin'>
         A few of the other patients clap and cheer as you bounce off the rubber walls, others just stare vacantly drooling.  A nurse at the main station peers at you over the top of her glasses whilst four orderlies prepare some shackles and a straight jacket for you in case you get more unruly than you alrady are.  Perhaps tracing your path in reverse might help your egress.
         </para>

         <para number='7' comment='cant get out uva bar'>
         A bouncer stands up, grabs you by the shoulder and asks if you need an 'escort' out the door.  He suggests you stop trying to walk through walls and behave yourself.  He motions to the bartender to refuse to serve you any more intoxicating beverages.
         </para>

         <para number='8' comment='cant get out uva dark'>
         You stumble into some boxes, knocking them over.  You hear a gruff voice from the next room hollering orders to someone to see what is going on back there.  You better hurry out of here before you are discovered!
         </para>

         <para number='9' comment='cant get out uva bar2'>
         A bouncer stands up, grabs you by the shoulder and asks if you need an 'escort' out the door.  He suggests you stop trying to walk through walls and behave yourself.  Meanwhile, the patrons are clapping and hooting and holloring for the bouncer to make you take the mic and try your hand at versing some poetry.  Not wishing to make a further fool of yourself, you meekly back away.
         </para>

         <para number='10' comment='tall tower'>
         Looking down from your precarious perch, you dimly recall you lost your anti-gravity boots in a poker game last weekend.. or was that Arthur?  You are wishing you had jammed something into that gate before letting it slap shut.  In any event..may I suggest you don't try to get down from here in this manner?
         </para>

         <para number='11' comment='can t move inna rubble'>
         You feel silly walking into the wall, bumping things and stumbling over the rubble and repair work.  You hope there are no other beings around to make you feel any more uncomfortable than you already do.  Perhaps try reversing the direction you used to arrive here.
         </para>

         <para number='12' comment='elevator out of order'>
         Bumping about in here isn't going to make this elevator work, It is in need of repairs!  Perhaps you should egress before you cause any more damage.
         </para>

         <para number='13' comment='dusty rubble'>
         The way is blocked by dusty rubble, debris, and darkness.
         </para>

         <para number='14' comment='too many cables'>
         The cables are small, but there are so many of them that you can't move in that direction.
         </para>

         <para number='15' comment='nowhere to go'>
         The projector isn't that large, and the inside walls of the projection tower surround you.
         </para>

         <para number='16' comment='inside computer'>
         The racks and cables around the computers are blocking your way.  It is like a maze in here!
         </para>

         <para number='17' comment='cant move'>
         You can't move in that direction.  Just to prove it, you walk smack into something hard and bruise your nose. (or similar appendage)
         </para>

         <para number='18' comment='inna dumbwaiter'>
         You seem to be inside a rather cramped space of a dumbwaiter.  It is similar to an elevator, but much smaller and barely room enough for you.  Your exit directions are somewhat limited.
         </para>

         <para number='19' comment='inna tunnel'>
         Banging into the walls only makes a clunking sound and bruises your head.
         </para>

         <para number='20' comment='inna tree'>
         Considering you have climbed quite high into this tree, it's not really a wise decision to venture out on a limb like that.
         </para>

      </section>

   </category>

</para-list>

