<?xml version="1.0"?>

<para-list version='7' editor='standard'>

   <category name='space'>

      <section name='noexit'>

         <para number='1' comment='Phorbe Space - Cant go there'>
         As much as you would like to venture in that direction, Galactic Administration Order 1573829-42b prevents all unauthorized beings from occupying any sector not specifically designated for public thoroughfare.  Or more simply put... you can't go there.
         </para>

         <para number='2' comment='Phorbe Space - Cant go there 2'>
         There is just too much debris in that direction, your navigational computer refuses to map any coordinates and suggests you try an alternate destination.
         </para>

         <para number='3' comment='Phorbe Space - Cant go there 3'>
         Do I really need to remind you of the self-preservation habits of AI electronic equipment of any nature?  There is too much debris, and I'm not risking my sleek platinum hull to satisfy your flesh-bagged curiousity! Try a different direction!
         </para>

      </section>

   </category>

</para-list>

