<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='LP no Exit'>
         IN or OUT only, dude!
         </para>

         <para number='2' comment='Other No Exit'>
         The cool breeze and warm sun momentarily lull you into a state of peaceful bliss.  However, you quickly regain your bearings and realize you can't go that direction.
         </para>

      </section>

   </category>

</para-list>

