<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Exit'>
         You think about going for a swim, but decide to stay on the path.
         </para>

         <para number='2' comment='Inside'>
         Your smack dab into a wall.  Clumbsy aren't we?  No need to worry, there is medical assitance east of the landing pad.  If you dare.
         </para>

      </section>

   </category>

</para-list>

