<?xml version="1.0"?>

<para-list version='34' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Shuttle deck noexit (loc 453)'>
         Your body would need to be as massive as a shuttle to slither through the force field.
         </para>

         <para number='2' comment='Generic noexit'>
         The bioplasm coating of the walls, ceiling and floor will not allow you to pass through.
         </para>

         <para number='3' comment='Conduits noexit'>
         Your molecules are randomly reflected from the boundary walls back into the conduit and collide with other passing bioplasm matter with a strange hissing noise.
         </para>

         <para number='4' comment='Carls Bar noexit (loc 391)'>
         Your embarrassment is intense as patrons of the bar chuckle at your unsuccessful efforts to leave the bar through the transparent and flexible dome.
         </para>

         <para number='5' comment='Power Hall/Breeding Room noexit'>
         A technician steps in front of you and stops you moving that way and damaging the sensitive equipment.
         </para>

         <para number='6' comment='Staff room noexit'>
         The absence of an exit door means that you will have to climb up through the maintenance hatch in the ceiling to get out, but you will need to 'use trolley' in order to reach it.
         </para>

         <para number='7' comment='Bio-digester noexit msg'>
         If you move in that direction you will be consumed by the bio-digester monster.
         </para>

      </section>

   </category>

</para-list>

