<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Landing Pad - loc 714 - noexit'>
         As you move the wrong way, an arriving shuttle lands and almost slams down into you.
         </para>

         <para number='2' comment='Exchange - loc 715 - noexit'>
         As you head the wrong way, a stray bee comes within inches of stinging you, and you back away.
         </para>

         <para number='3' comment='Crosswalk - loc 713 - noexit'>
         As you start to fall off the edge of the crosswalk to your death, you retreat back to the path.
         </para>

         <para number='4' comment='Cafe - loc 712 - noexit'>
         A busy server politely throws you back into your seat and suggests using the regular patron doorway and to avoid interfering with the kitchen staff.
         </para>

         <para number='5' comment='Hosp. Lobby - loc 777 - noexit'>
         There is a loud yowling cry as you step onto an unfortunate animal's tail, and the glare of the alarmed receptionist urges you back to your seat.
         </para>

         <para number='6' comment='Recov. Room - loc 840 - noexit'>
         You decide not to wake a resting patient growling in its sleep, and look for the traditional exits.
         </para>

         <para number='7' comment='Op Room - loc 841 - noexit'>
         You trip over complicated instruments that you don't even recognize and almost impale yourself on a two foot long scalpel.  You see the exit to your west.
         </para>

         <para number='8' comment='Shipyard - loc 649 - noexit'>
         The tiger begins to prowl in your direction, and you back away nervously as you like to avoid being dinner.
         </para>

         <para number='9' comment='Tree Blocked Area - noexit'>
         A grove of trees blocks your way in that direction.
         </para>

         <para number='10' comment='Office - loc 778 - noexit'>
         You bang your head into a wall, and realize the only exit is through the north door.
         </para>

         <para number='11' comment='Windmill - noexit'>
         You push against the limestone walls, but can find no hidden exits.
         </para>

         <para number='12' comment='Silo - loc 456 - noexit'>
         You pound on the inside of the metal silo, and do nothing except give yourself a headache from the clanging sound.
         </para>

         <para number='13' comment='Sequioa - loc 394 - noexit'>
         Although roomy inside, you still manage to bang your head on the inside of the massive tree.
         </para>

         <para number='14' comment='Ravine Bed - loc 331 - noexit'>
         Futiley attempting to climb the muddy bank, you only manage to slide back down messier then you were before you tried.
         </para>

         <para number='15' comment='Cave Entrace - loc 264 - noexit'>
         The solid rock walls of the interior don't seem to hide any additional exits.
         </para>

         <para number='16' comment='Cub Lair'>
         The mother bear begins to move towards you as a threat, and you decide to beat a hasty retreat.
         </para>

      </section>

   </category>

</para-list>

