# Makefile for the fed2 Rigel system

DEST=/var/opt/fed2/maps/rigel

all:$(DEST)/rigel4.loc $(DEST)/rigel4.msg $(DEST)/rigel4.xev $(DEST)/rigel4.xob \
$(DEST)/space.loc $(DEST)/space.msg $(DEST)/space.xev 

include ../data.mk
