<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for roads'>
         That way would take you into a private building. It is considered the height of bad manners on Rigel to enter such without invitation.
         </para>

         <para number='2' comment='No exit message for buildings'>
         You can't leave the building that way - please use the authorized exit.
         </para>

         <para number='3' comment='No exit message for LP'>
         Only authorized personnel are allowed into any of the spaceport buildings, so you cannot go that way.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='billboard'>

         <para number='1' comment='READ BILLBOARD - LP - 786'>
         The small print on the board is a legal disclaimer saying "Rigel 4's new owner, Pugwash, makes no guarantee that prices, stockpiles, deficits or availability of labor will remain stable from day to day. In fact, there are likely to be wild fluctuations as she plays about with the controls that modify the exchange.
         </para>

         <para number='2'>
         All traders are welcome, and CEOs can build whatever they like here, but you do so at your own risk. Pugwash will accept no liability for losses accrued due to sudden changes in financial conditions on the planet.
         </para>

         <para number='3'>
         "Caveat emptor!"
         </para>

      </section>

   </category>

</para-list>

