<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for Rigel space'>
         Only the vast emptiness of space lies that way, so you turn back onto Rigel's regular space route.
         </para>

      </section>

      <section name='sun'>

         <para number='1' comment='Enter sun - 588 - move to orbit'>
         You fly perilously close to Rigel's burning globe. Luckily for you, just as your ship starts to melt, you are saved by a rescue vehicle, which grabs your ship with a powerful tractor beam and hauls you back to safety. You are deposited in orbit around Rigel 4, with only the fading smell of burnt plastic to show for your close brush with death.
         </para>

      </section>

   </category>

</para-list>

