<?xml version="1.0"?>

<para-list version='9' editor='standard'>

   <category name='death'>

      <section name='hospital'>

         <para number='1' comment='Move to hospital'>
         When you come to, you find you are being held very close by something large, warm and furry. You didn't die after all, you're in hospital, and a nurse-bunny is kissing you all better.
         </para>

      </section>

      <section name='rabbit'>

         <para number='1' comment='Enter event on 339'>
         You were warned...
         </para>

         <para number='2'>
         Faster than speeding bullet, a small fluffy white bunny leaps for your throat and rips out your jugular (or equivalent). You don't even have time to say your prayers, let alone get out your holy hand-grenade! As the blood spurts from your severed neck you curse the Cabbage authorities for not making their signs more emphatic.
         </para>

         <para number='3'>
         Your life ebbs away and you die a painful, ignominous death.
         </para>

         <para number='4' comment='Announce'>
         Faster than a speeding bullet, a small fluffy white bunny leaps for %s's throat and tips out the jugular (or equivalent). That's what happens when you don't heed the warning signs.
         </para>

      </section>

      <section name='tree'>

         <para number='1' comment='No exit event on 206'>
         As you start to descend from the tree-top, your foot slips on a lump of squirrel-excrement. You lose your grip and realise you are falling!
         </para>

         <para number='2'>
         It's no good flapping your arms up and down, it's not going to slow your descent one little bit. You plummet through the leaves towards the ground, bashing into branches as you go - but don't worry about the little scrapes and bumps you are getting, they will pale into insignificance when compared to the pain you will feel when you splat on the ground at great speed.
         </para>

         <para number='3'>
         Whimpering in terror, you black out.
         </para>

      </section>

      <section name='water'>

         <para number='1' comment='No exit event on 526'>
         Flailing your arms and legs madly, you try to swim back to the bank, but terror makes you lose all co-ordination. You suddenly realise you are drowning!
         </para>

         <para number='2'>
         We did say you shouldn't panic... as you sink below the waters, exhausted, your past life flashes before your eyes. Pity your mind insists on dwelling on the unpleasant bits! You try to fast forward to the sex scenes, but obviously your brain is stuck on play.
         </para>

         <para number='3'>
         Gasping for air, you swallow about a gallon of water, and black out.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='snail'>

         <para number='1' comment='In event on 205 - snail ride'>
         With a rumble, the snail starts moving. Hang on tight, you're in for an exciting ride!
         </para>

         <para number='2'>
         Squealing with excitement, you bounce up and down on the snail's back, waiting for it to pick up speed. It really is going very slowly. Oh well, maybe it just takes a while to get going. After all, it is a pretty large mollusc, and inertia must make it very hard to get that huge bulk started, but you are sure that once it gets moving it will just vroooooooooom along.
         </para>

         <para number='3'>
         The snail still hasn't sped up - in fact it is crawling along excrutiatingly slowly. You drum your heels against its shell and shout "Giddyup," but it seems to have no effect.
         </para>

         <para number='4'>
         Good grief! At this rate, it'll take all night just to get out of the field. The snail is moving at... well, at snail's pace. You decide to give up on this snail ride. Tutting in exasperation, you slide back down the side of the snail's shell and land on a large lettuce. You notice that the snail has moved all of two inches since you climbed on top of it. You can see just why snail racing never became popular.
         </para>

      </section>

   </category>

   <category name='noexit'>

      <section name='fields'>

         <para number='1' comment='No exit message for fields'>
         Sturdy fences around the field prevent you from going in that direction. You'll just have to go back to the road.
         </para>

      </section>

   </category>

</para-list>

