<?xml version="1.0"?>

<para-list version='9' editor='standard'>

   <category name='extras'>

      <section name='chute'>

         <para number='1' comment='Loc 583-Laundry Chute to SP-260'>
         Squirming and wiggling, you manage to crawl through the small door and begin to slide down the laundry chute.  You find yourself inside a long laundry chute which is dark, yet filled with lots of furry little bodies.  Over the comms can be heard many cries of "Whee!  Kitty in the Laundry Chute!"
         </para>

         <para number='2' comment='Loc 583-Chute to LP 260'>
         This is actually quite fun!  You start to add your own cry to the clamor, and catch yourself just in time.
         </para>

         <para number='3' comment='Loc 583-Chute to LP 260'>
         All too soon, the ride is over, and you climb OUT of the chute and onto the shuttle pad.  Straightening your clothes and regaining your dignity, you whistle and go about your business.
         </para>

      </section>

      <section name='class'>

         <para number='1' comment='Loc 714-Classroom text'>
         "I tell you, you are setting your spreads too low!" shouts one stout planet owner to another.  "What are you trying to do, put the rest of us out of business?"
         </para>

         <para number='2' comment='Loc 714-Classroom text'>
         "If you weren't such a blinking tightwad, you'd know that to sell a product you have to make the price attractive to your customer!" a second planet owner respinds, then takes a puff off his cigar.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Shuttle noexit'>
         As you try to leap off the shuttle, dozens of cat tails drag you back inside, saving you from a messy demise.
         </para>

         <para number='2' comment='Catseye Noexit'>
         You stumble into a wall and rub your head, realizing you've gone in the wrong direction.
         </para>

      </section>

   </category>

</para-list>



