# Makefile for the fed2 Chrysoberyl system

DEST=/var/opt/fed2/maps/chrysoberyl

all:$(DEST)/catseye.loc $(DEST)/catseye.msg $(DEST)/catseye.xev $(DEST)/catseye.xob \
$(DEST)/litterbox.loc $(DEST)/litterbox.msg \
$(DEST)/hairball.loc $(DEST)/hairball.msg \
$(DEST)/space.loc $(DEST)/space.msg 

include ../data.mk
