<?xml version="1.0"?>

<para-list version='11' editor='standard'>

   <category name='moves'>

      <section name='noxit'>

         <para number='1' comment='LP 1609 No Xit'>
         For your own safety, please do not go that way and become part of the landing pad.
         </para>

         <para number='2' comment='LP N rd 1545 noxit'>
         You are still to close to the landing pad to be going in that direction
         </para>

         <para number='3' comment='ZBarnGr 1480 noxit'>
         Careful now, management respectfully requests that you use the proper exits and not walk through the environmental barriers
         </para>

         <para number='4' comment='ZBarnGr BkRm 1479 noxit'>
         There may be more than one way out of here but this is not one of them
         </para>

         <para number='5' comment='sals all 1482 noxit'>
         It is a bit cramped in here and Sal does need to expand, but I think that wall is a load bearing wall and needs to stay there. Try another direction.
         </para>

         <para number='6' comment='Customs 1608 noexit'>
         Hmm, you can't go that way, the exit is south, and to tell the truth, it was not anticipated that anyone would ever actually enter in this building of their own free will.
         </para>

         <para number='7' comment='sonnys 1607 noxit'>
         I would be a bit more careful about running into the shelves, Guido might get ticked off, try another way, unless you are into that sort of thing.
         </para>

         <para number='8' comment='cryo 1670 noxit'>
         So sorry, that freezer is in use at the moment, but do keep trying, you just might get lucky and find an empty one!
         </para>

         <para number='9' comment='partRus 1606 noxit'>
         Oops, that O.R. booth is in use at the moment, there may be another one available and don't use that one over there, it is malfunctioning.
         </para>

         <para number='10' comment='NhighXrds 1671 noxit'>
         6 out of the 8 possible compass directions are acceptable directions but this in not one of the right ones.
         </para>

         <para number='11' comment='Hosp 1735 noxit'>
         You might need more repairs if you keep that up! try a diferent direction, like North.
         </para>

         <para number='12' comment='Exch 1673 noxit'>
         The exits are North and South.
         </para>

         <para number='13' comment='exch lng 1737 noxit'>
         Nope, that's not it, keep trying!
         </para>

         <para number='14' comment='M&amp;P sex 1610 noxit'>
         Some of these devices are automatic so you might want to use a bit more care when moving around in here!
         </para>

         <para number='15' comment='M&amp;Psex BkRm 1611 noxit'>
         Hmmm, that one seems to be in use right now, are you sure you got the right key?
         </para>

         <para number='16' comment='Hotel lob 1612 noxit'>
         The security droids frimly but politley ask you please stay out of that area.
         </para>

         <para number='17' comment='FersRm 1613 noxit'>
         As you bump into the wall, you hear a giggle and a soft recorded voice says "Not that way silly"
         </para>

         <para number='18' comment='Hide Out 1676'>
         There are no compass directions you can use to get out of here!  IN will take you to the LP but there are other ways out too!
         </para>

         <para number='19' comment='Mama s rm 1677 noxit'>
         That way didn't work. Maybe you should just try that way, you know, go out over there!
         </para>

         <para number='20' comment='NwHgh Road'>
         Best to stay on the road, it looks a bit rough over there.
         </para>

         <para number='21' comment='diggers 1736 noxit'>
         Bing Bong, The exit is south west.
         </para>

         <para number='22' comment='emil s 1738 noxit'>
         What's the matter, got some pepper in your eye, turn just a bit and go south east.
         </para>

         <para number='23' comment='Kims 1739 noxit'>
         You break it, you buy it, the door is south.
         </para>

         <para number='24' comment='park 1804 noxit'>
         You are near the desert here and it is not adviseable to leave the park boundarys.
         </para>

         <para number='25' comment='DD s 1082 noxit'>
         Whats behind curtain No 1.?  (you can't go this way)
         </para>

         <para number='26' comment='B&amp;B 1801 noxit'>
         Please calm down. Do not blast another hole in the wall, that is what the curtian is covering! There are two exits already and the hole is one!
         </para>

         <para number='27' comment='Gizmo s 1800 noxit'>
         There is one gadget they don't sell here and that is an instant exit maker. Please use the one already provided.
         </para>

         <para number='28' comment='Quaint 1798 noxit'>
         The terrain around here is fairly rugged so close to the highlands so you better use the exit that is to the north
         </para>

         <para number='29' comment='ElecAve 1927 noxit'>
         Oh, you were watching the antique laser show machine a bit to long. the exit is north east, here, let me help you...
         </para>

         <para number='30' comment='Zands 1931 noxit'>
         There are a few secrets around here!  Just keep looking but please keep the secret if you find it!
         </para>

         <para number='31' comment='Northern shuttle  1481'>
         The exit is South if you are trying to leave.
         </para>

         <para number='32' comment='Sshutt 1481'>
         The exit is north if you are trying to leave.
         </para>

         <para number='33' comment='Eshutt  1806'>
         The exit is west if you are trying to leave.
         </para>

         <para number='34' comment='Wshutt  1796'>
         The exit is east if you are trying to leave.
         </para>

         <para number='35' comment='Prjctn 1540'>
         I know it's dark, and if you remember, there is only one way OUT of here.... Over there!
         </para>

         <para number='36' comment='Oper booth 1541'>
         Quick and be careful!  No! not that button!  Aack you almost got another eye in your forhead! You better go OUT before you get seiously changed!
         </para>

         <para number='37' comment='Taco 1549'>
         Employees only back here please, the exit is to the SW
         </para>

         <para number='38' comment='FerrHT'>
         You can't get out that way, you would think you had never been in hot water before!  How will you get OUT?
         </para>

         <para number='39' comment='Concess 1604'>
         You need to go around the line that way, the theater is SE!
         </para>

         <para number='40' comment='Cryotube  1605'>
         Use caution or you will be a peopcycle in no time at all, Out is OUT
         </para>

         <para number='41' comment='MamaKit 1614'>
         Best to leave Mama's pots and pans alone!  SW is the way out
         </para>

         <para number='42' comment='Majes 1669'>
         Ow! that was my toe, please be careful
         </para>

         <para number='43'>
         Think outside the box, what do you do when you are in trouble, don't be down, and by all means, up the anti!
         </para>

         <para number='44' comment='patio HT  1861'>
         Out is OUT
         </para>

         <para number='45'>
         Don't jump the railings!  There are some steps over there and the door is that way!
         </para>

         <para number='46' comment='Smug Off'>
         There is no use trying to run, you have been cleared anyway so don't worry!  Try here...
         </para>

         <para number='47'>
         Well you will either end up in the back room of a bar or outside in a park, just make up your mind!
         </para>

         <para number='48' comment='works 1926'>
         Some of this stuff should not be knocked around like that, watch what you are doing!
         </para>

         <para number='49' comment='DesZAnds game 1932'>
         Back into the bar with you!  You are disturbing the Darters!
         </para>

         <para number='50' comment='Main Ent Gar 1991'>
         It doesn't cost anything so why are you trying to go around the gate?
         </para>

         <para number='51' comment='Earth gar  1990'>
         The gardens seem to go on forever, but you should turn around and go back east before you get lost.
         </para>

         <para number='52' comment='Known Gard 2054'>
         If you are lost, look for the that really tall tree-thingy over there in the NE.
         </para>

         <para number='53' comment='Zandsgard 2055'>
         Are you sure you want to leave so soon?  Ok, head North then, you are done.
         </para>

         <para number='54' comment='Zands of 2056'>
         Wow, what a wild time, need something to get that 'nano-water' out of your eye? Oh, never mind, I see it just ran out on it's on!
         </para>

         <para number='55' comment='Bows 1995'>
         Bows (as opposed to Knotts) landing is a quite little place, you can go anywhere except in this northerly direction.
         </para>

         <para number='56' comment='Lots 1,2,4  1996, 2058 2060'>
         Use caution!  Don't wander to far and certainly not in that direction!
         </para>

         <para number='57' comment='Sephorin s Home   2059'>
         Hmmmmm, there don't seem to be any secrets there
         </para>

      </section>

   </category>

</para-list>

