<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Armed guards bar the way!
         </para>

         <para number='2'>
         Armed guards keep you from wandering off too far
         </para>

         <para number='3'>
         Armed guards escort you back to the group.
         </para>

         <para number='4'>
         Heavy vegetation keeps you from going very far.
         </para>

         <para number='5'>
         Can you fly?
         </para>

         <para number='6'>
         Ghosts block the way
         </para>

         <para number='7'>
         I hope you can swim
         </para>

         <para number='8'>
         Animals found out here are used for sacrifices
         </para>

      </section>

   </category>

</para-list>


