<?xml version="1.0"?>

<para-list version='23' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Gardeners with hoses encourage you to go back.
         </para>

         <para number='2'>
         Gardeners lead you back.
         </para>

         <para number='3'>
         Muscle men with forks convince you to go back.
         </para>

         <para number='4'>
         Heavy vegitation keeps you from going very far.
         </para>

         <para number='5'>
         Can you fly like an angel?
         </para>

         <para number='6'>
         Large cats block the way
         </para>

         <para number='7'>
         I hope you can swim
         </para>

         <para number='8'>
         Gardemer's put you back on track
         </para>

      </section>

   </category>

</para-list>


