<?xml version="1.0"?>

<para-list version='18' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Angels guide you back.
         </para>

         <para number='2'>
         Angels gently guide you back.
         </para>

         <para number='3'>
         Angel guards escort you back to the group.
         </para>

         <para number='4'>
         Heavy apparitions keep you from going very far.
         </para>

         <para number='5'>
         Can you fly like an angel?
         </para>

         <para number='6'>
         Angels block the way
         </para>

         <para number='7'>
         I hope you can swim angelically
         </para>

         <para number='8'>
         Angels guide you back to the path of ritcheousness.
         </para>

      </section>

   </category>

</para-list>


