<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Siamese space'>
         There is nothing out there to meditate on, but the hard vacuum of space.
         </para>

         <para number='2' comment='Kittypallace orbit'>
         Don't stray off the path, the dragons might think of you as a tasty treat
         </para>

         <para number='3' comment='Kittypallace worm hole'>
         Keep you arms and legs in the shuttle
         </para>

         <para number='4' comment='Kittypallace wormhole entrance'>
         Keep your hands and feet in the shuttle
         </para>

         <para number='5' comment='Kittyheaven wormhole entrance'>
         Stay in the shuttle and watch out for temtations
         </para>

         <para number='6' comment='Kittyheaven wormhole'>
         stay on the path of ritcheousness
         </para>

         <para number='7' comment='Kittyheaven orbit'>
         Don't go astray
         </para>

         <para number='8' comment='Interdimensional entrance'>
         Don't leave your shuttle
         </para>

         <para number='9' comment='Interdimensional lane'>
         Don't leave your shuttle!
         </para>

         <para number='10' comment='Kittygarden orbit'>
         Don't leave your shuttle
         </para>

      </section>

   </category>

</para-list>


