<?xml version="1.0"?>

<para-list version='21' editor='standard'>

   <category name='mobile'>

      <section name='merchant'>

         <para number='1' comment='merchant hello'>
         Hello there %s! Welcome to my humble shop. Why don't you have some lemonade, relax for a while perhaps browse through the different goods for sale here? Oh, and call me Sudi, means lucky in Egyptian you know ;)
         </para>

      </section>

   </category>

   <category name='msg'>

      <section name='book'>

         <para number='1' comment='locked book - try to open'>
         As you try to pry the book open, all you suceed in doing is scratching the surface. You notice an indentation on the front cover that looks like a beetle of some kind.
         </para>

         <para number='2' comment='open book after unlock'>
         The pages of the book are made of thick sheets of some kind of metal hinged together on the side, as you open the cover, holo images seem to hover over the pages, telling the egyptian story of life, death, and rebirth in the afterlife.
         </para>

         <para number='3' comment='turn first page'>
         As you turn the first page, the translator explains the meanings of the pictures displayed there.
         </para>

         <para number='4' comment='turn second page'>
         As you turn the next page, the translator explains the meanings of the pictures displayed there.
         </para>

         <para number='5' comment='turn third page'>
         As you turn the third page, the translator explains the meanings of the pictures displayed there.
         </para>

         <para number='6' comment='turn fourth page'>
         As you turn the fourth page, the translator explains the meanings of the pictures displayed there.
         </para>

         <para number='7' comment='not in merchants stall'>
         As you turn the page on the book all you can make out is that the book is written in some ancient language made of pictures.
         </para>

         <para number='8' comment='drop unlocked book'>
         As the book hits the ground it is scooped up by a young local boy and he dashes off into the crowd. You spend a few moments searching before realizing that it is gone for good.
         </para>

         <para number='9' comment='haggle for book'>
         You pretend to browse the selection of books while haggling with the owner of the book seller stall. He finally comes down to a reasonable price of just 42ig for the book. The funds are transfered and you find yourself the proud owner of the mysterious book. Attempts to open it are fruitless and you begin to wonder if the merchant, who is studiously ignoring you now, got the better end of the deal.
         </para>

         <para number='10' comment='try to read closed book'>
         The cover of the book reads: Book of the Dead or An Egyptians Guide to Life after Life. If you want to read it, you need to open it first.
         </para>

         <para number='11' comment='turn fifth page'>
         As you turn the final page, the translator explains the meanings of the pictures displayed there. As you finish veiwing the images, you close the book.
         </para>

         <para number='12' comment='steal book from merchant'>
         As you try to discreetly lift the book from the stall and slip it into your bag, a boy perched atop the wagon starts shrieking at the top of his lungs to the merchant who sees you! He takes your hand and drags you to the magistrate's office (who happens to be his brother in law).
         </para>

         <para number='13' comment='steal continued'>
         They gather an impromptu jury with the little boy as a very credible witness. The magistrate listens to your protestations of intent to purchase the book but in the end decides that you aren't very believable. He fines you the cost of the book (which you get to keep) of 100ig plus 200ig in court costs. You are warned not to get caught stealing again or the penalty will be much stiffer.
         </para>

         <para number='14' comment='get book finishing para'>
         You frown in dismay as after leaving the trial you discover that the book you have is locked with no obvious way to open it.  There is however, an indentation in the cover shaped like a beetle of some kind.
         </para>

         <para number='15' comment='have been caught before'>
         The magistrate is not happy to see you before him again as you have obviously not learned your lesson. This time he confiscates the book and charges you a penalty of 500ig for bothering him again.
         </para>

         <para number='16' comment='try to buy book'>
         You pick the book up and try to get his attention. He seems to enjoy the challenge of getting a good price out of the customer more than the sale itself as he is too busy haggling with another customer to notice your attempts to get his attention.
         </para>

         <para number='17' comment='if tries to open, open book'>
         The book is already open!
         </para>

         <para number='18' comment='sell book unlocked'>
         You find the book seller and try to get him to buy the book back from you... After much discussion you are given 15ig for the book and sent on your way.
         </para>

      </section>

      <section name='desert'>

         <para number='1' comment='random desert message'>
         The dunes here stretch endlessly in all directions. The path you were following before has vanished leaving you lost in the desert
         </para>

         <para number='2' comment='random desert message'>
         You are standing on the edge of a sand storm. The wind is picking up and you see a large cloud of sand headed your way, you must choose which direction before you are trapped in it.
         </para>

         <para number='3' comment='random desert message'>
         Inside a sand storm. The sand blows so thick around you that all you can do for several hours is hunker down and hope that is passes soon.
         </para>

         <para number='4' comment='random desert message'>
         Sand dunes are laid out before you as far as the eye can see. You think you can see a shuttle landing off in the distance but aren't sure of the direction due to the blinding sun and the shimmering heat.
         </para>

         <para number='5' comment='random desert message'>
         He who neglects to drink of the spring of experience is likely to die of thirst in the desert of ignorance. --Ling Po
         </para>

         <para number='6' comment='random desert message'>
         Sand everywhere you look, with no discernable way out...
         </para>

         <para number='7' comment='random desert message'>
         Old Earth had a saying that: It is better to dwell in the wilderness, than with a contentious and an angry woman.... but looking around this particular desert, you have to wonder.
         </para>

         <para number='8' comment='random desert message'>
         The wind moves swiftly stirring up the sand and stinging your eyes. You are right on the edge of a massive storm
         </para>

         <para number='9' comment='random desert message'>
         The sand billows around you scouring your exposed skin. You hunker down in your robes for a while hoping that the winds will die down eventually. After several hours it is clear that the storm will last much longer than you and your only option is to try and walk out.
         </para>

      </section>

      <section name='general'>

         <para number='1' comment='on documents'>
         That wouldn't be a very good idea.
         </para>

         <para number='2' comment='no object'>
         I'm sorry I don't understand you. Can you put that a different way?
         </para>

      </section>

      <section name='lemonade'>

         <para number='1' comment='on drinking lemonade'>
         The ice cold lemonade slides down your throat (or equivalent) quenching your thirst and leaving you thoroughly refreshed.
         </para>

         <para number='2' comment='upon creation of lemonade'>
         You are handed a glazsteel mug designed to keep its contents very cold, you see it is full to the brim of ice cold pink lemonade.
         </para>

         <para number='3' comment='on drop lemonade'>
         The glazsteel mug hits the ground and while it doesn't shatter, the lemonade spills out onto the ground. A  cleaning droid appears to clean up the mess and looks none too pleased about it either.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='while planet it closed off'>
         Due to the overwhelming construction project that is currently on going, movement in that direction has been blocked.  We appologize for the inconvenience and will have the planet and pyramid functional and ready for visitors in the near future. Please stop by the merchant's tent east of the exchange for some lemonade, on the house of course.
         </para>

         <para number='2' comment='kiosk message'>
         Due to the overwhelming construction project that is currently on going, movement in that direction has been blocked.  We appologize for the inconvenience and will have the planet and pyramid functional and ready for visitors in the near future. Please feel free to have some lemonade while you are here, on the house of course.
         </para>

      </section>

      <section name='sapphire'>

         <para number='1' comment='first slow death'>
         As you finally manage to pry the stone free, the ground starts to tremble beneath your feet. A quick glance towards the exit refeals that the door to the tomb has slammed shut trapping you inside!
         </para>

         <para number='2' comment='second message'>
         The door seems firmly wedged shut and there is no obvious way for you to open it.  As the oxygen in the room starts to diminish, the torches slowly flicker then go out.
         </para>

         <para number='3' comment='third message'>
         You click on a flashlight conveniently left behind by another tourist and begin searching in earnest for an exit, but find none.  You wonder if that is voices you hear on the other side of the door. You pound on it furiously but it still doesn't budge.
         </para>

         <para number='4' comment='forth message'>
         The air begins to feel thicker as you struggle to breathe the oxygen deprived air. Darkness soon closes in around your vision as you black out and pass on to your next life.
         </para>

         <para number='5' comment='msg in the hosp w unlocked book'>
         You come into awareness and find yourself floating above your body in the embalmer's workshop. The specialists here have made quick work of preparing your body for the afterlife. The organs have been removed and placed in special jars each labeled as to their contents and your body has been carfully wrapped with a mask closely resembling your own face placed over 'your' face.
         </para>

         <para number='6' comment='message in hosp w/out book'>
         As you wake up, in your own body, you see an angry planetary official cursing the local kids that steal the warning signs. He turns to you as you wake and appologizes profusely stating that due to the fact that your death was a horrible accident, the planet has covered all the cloning costs and has made arrangements with the insurance company to ensure you are not penalized for your adventure.
         </para>

         <para number='7' comment='Not dead msg when enter tomb'>
         A guard blocks your path. "Only relatives of the dead, or the dead themselves are allowed to enter the tomb. Have some respect!"
         </para>

         <para number='8' comment='msg in hosp lockedbook'>
         As your lifeless corpse is moved to the hospital, you are compelled to follow it. You hear the embalmers arguing over whether your remains are to be mummified in accordance with custom as laid out in the book of the dead while the other points out that your copy of the book is locked so you must be a tourist. In the end, they settle on cloning you since you were covered by insurance and they get paid more for cloning.
         </para>

         <para number='9' comment='wake up in hospital alive'>
         As you wake up, this time in your own body, you see an angry planetary official berating the embalmers over their delay in cloning you. He turns to you as you wake and appologizes profusely stating that due to the fact that your death was a horrible accident, the planet has covered all the cloning costs and has made arrangements with the insurance company to ensure you are not penalized for your adventure.
         </para>

         <para number='10' comment='continuation of 5'>
         As the workers finish their grizzly work, you hear one of them remark "I guess its off to the communal burial chamber for this one." With that, they cart your body off and you are left wondering what you can do next.
         </para>

      </section>

      <section name='scarab'>

         <para number='1' comment='toss throw drop scarab'>
         As it hits the ground the scarab comes to life skittering off  before you have a chance to retrieve it.
         </para>

         <para number='2' comment='steal from merchant'>
         You wait until the merchant is helping another customer and hastily pocket one of the scarab beatles from the basket. Moments later you feel something wriggling in your nano-chameleon outfit. You look down to see the scarab crawling up your arm (or equivalent). You try to shake it off but it bites through your suit. Finally you manage to shake it loose. As it hits the ground it skitters back over to and climbs back up into the basket.
         </para>

         <para number='3' comment='BUY scarab'>
         It takes a little while but you finally catch the attention of the merchant and express interest in purchasing one of the scarab beetles. After some haggling you seal the deal for the princely sum of 13ig. You examine a couple of the beatles before selecting one and pocketing it. The merchant smiles broadly and says "You are welcome to come back any time."
         </para>

         <para number='4' comment='insert use scarab w lockbook'>
         You place the scarab in the depression of the book and it seems like a perfect fit. You twist it slowly until you hear a clicking sound. Suddenly the bands that held the book closed pop open unlocking the book. You sit down to study the pages.
         </para>

         <para number='5' comment='insert use scarab w unlockebook'>
         The book is already unlocked!
         </para>

      </section>

      <section name='tomb'>

         <para number='1' comment='Not dead msg when enter tomb'>
         A guard blocks your path. "Only relatives of the dead, or the dead themselves are allowed to enter the tomb. Have some respect!"
         </para>

         <para number='2' comment='description of heiroglyph'>
         The heiroglphy depicts several workers laboring in the reed fields harvesting the flax and papyrus plants needed to create clothing and paper.
         </para>

         <para number='3' comment='description of heiroglyph'>
         The heiroglphy depicts several workers laboring in the reed fields harvesting the flax and papyrus plants needed to create clothing and paper.
         </para>

         <para number='4' comment='another heiroglyph'>
         This heiroglyph depicts several laborers fishing on a boat. Under the water are some rather large red fish, you wonder what they might be.
         </para>

         <para number='5' comment='another heiroglyph'>
         The heiroglyph depicted here shows men busy working the fields some sowing grains, others tending the growing plants, and still others harvesting the crops.
         </para>

         <para number='6' comment='version of heiroglyph'>
         This wall depicts stone masons building what appears to be the very room you are standing in. In fact, as you look very carefully at it, you see a tiny figure of a person in the room that is drawn on the wall.
         </para>

         <para number='7' comment='version of heiroglyph'>
         Rather gruesome pictures here show the mummification process. Apparently the Egyptian people are very focused on death and the afterlife.
         </para>

      </section>

      <section name='watch'>

         <para number='1' comment='on creation of watch'>
         You distract the merchant by requesting a copy of his tax documents for auditing purposes.  As he looks away for a moment you are able to reach around the register and grab the watch. You pocket it quickly with no one being the wiser.
         </para>

         <para number='2' comment='not the PO acquire watch'>
         You try to distract the merchant so you can reach around the counter but the clerk turns back quickly and grabs your wrist as he calls a security droid to forceably remove you from his stall.
         </para>

         <para number='3' comment='on drop watch'>
         As the watch falls to the ground, it is immediately kicked away by a child before being gleefully scooped up.
         </para>

         <para number='4' comment='Use watch what user sees'>
         As you fiddle with the buttons of the watch, you see the world shimmer around you and you find yourself in a new location.
         </para>

         <para number='5' comment='on use watch what others see'>
         After fiddling with with a shiny bit of metal for a moment, %s dissappears as the air shimmers a puff of smoke appears.
         </para>

         <para number='6' comment='if not on planet'>
         You must be on the planet Karnak to use this function of the watch.
         </para>

      </section>

   </category>

</para-list>


