<?xml version="1.0"?>

<para-list version='15' editor='standard'>

   <category name='bar'>

      <section name='food'>

         <para number='1' comment='buy round of drinks player'>
         You buy a round of Pantheon's own hard apple cider for everyone in the bar.
         </para>

         <para number='2' comment='buy round room_ex'>
         %s has bought you a frosty pint of Pantheon's own, hard apple cider.
         </para>

         <para number='3' comment='buy fish and chips'>
         You order from the waitress who soon brings out a large plate of steaming fresh battered and fried cod fillets and thick chunky chips. She also deposits a bottle of malt vinegar on the table before rushing off to see to the next customer.
         </para>

         <para number='4' comment='buy baked potato'>
         You place your order with the waitress who after a breif wait returns with a baked potato loaded down with sour cream, chives, bacon pieces and cheese. Now thats the way a baked potato should be!
         </para>

         <para number='5' comment='buy mulligan stew'>
         After placing your order with a rather harried looking waitress, you soon recieve a large steaming bowl of stew. The peices of lamb are tender and fall apart easily and are completmented nicely by the large chunks of carrots, potatoes, and onions floating in the thick broth.
         </para>

         <para number='6' comment='read the menu displays'>
         .          Today's Specials          .
         </para>

         <para number='7' comment='read the menu displays'>
         ---------------------------------------------------
         </para>

         <para number='8' comment='read the menu displays'>
         Round of drinks (no limit)  ......  6ig
         </para>

         <para number='9' comment='read the menu displays'>
         Fish and Chips    ...................   5ig
         </para>

         <para number='10' comment='read the menu displays'>
         Baked Potato     ....................   5ig
         </para>

         <para number='11' comment='read the menu displays'>
         Mulligan Stew     ....................   5ig
         </para>

         <para number='12' comment='read the menu displays'>
         Shepard's Pie     ....................   5ig
         </para>

         <para number='13' comment='read the menu displays'>
         All other items at standard galactic prices.
         </para>

         <para number='14' comment='buy shepards pie'>
         After placing your order you wait... and wait... and wait. FINALLY the waitress comes out with your food. "Sorry, for the delay, the cook burnt the first one." You inspect the food and it does indeed look very good, you polish it off in no time leaving an empty dish behind.
         </para>

         <para number='15' comment='buy menu'>
         You can't decide what you want off the menu so you ask the waitress to bring out a sampler of each of the dishes available. She comes out with a huge tray of food, enough for everyone to share.
         </para>

         <para number='16' comment='buy menu room_ex'>
         %s has bought a sampler platter from the menu for everyone to share.
         </para>

         <para number='17' comment='read the menu displays'>
         Sampler Platter to share.......... 20ig
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Stair ways and Cliff top'>
         You stumble and just barely manage to catch yourself just in time to keep from breaking your neck as you discover that you cannot go in that direction.
         </para>

         <para number='2' comment='Underworld'>
         Only the dead may pass in that direction to the underworld.  Of course, if you like, that may be arranged....
         </para>

         <para number='3' comment='Indoors Homes/offices'>
         You nearly knock a picture off the wall as you walk right into it.
         </para>

         <para number='4' comment='Pantheon interior'>
         You stumble and run into a mass of solid marble as you discover that you cannot go that way.
         </para>

         <para number='5' comment='Pub Bacchus'>
         A tangle of grape vines prevents travel in that direction.
         </para>

         <para number='6' comment='Faunus Pad'>
         As you attempt to walk into the woods, you run into the wall.  It was just a hologram after all.
         </para>

         <para number='7' comment='Hospital'>
         You stumble over an occupied gurney as you, unsuccessfully, try to exit in that direction.
         </para>

         <para number='8' comment='Mars weapons'>
         Sharp implements of war block travel along that path.
         </para>

         <para number='9' comment='Uranus and Saturn'>
         Stepping through the darkness you walk right into a wall bumping your head and stubbing your toe (or equivalent) on something very large and heavy.
         </para>

         <para number='10' comment='Venus and Vestals'>
         Your path is blocked by masses of gauzy drapes that entangle those who attempt to pass through.
         </para>

         <para number='11' comment='Piazza'>
         A sudden flurry of pigeons prevents you from traveling in that direction.
         </para>

         <para number='12' comment='garden path no woods'>
         A soft chime gently reminds you to stay on the cleared pathways.
         </para>

         <para number='13' comment='Hot tub and fountain'>
         You splash about in the water nearly drowning yourself.  After all that, you realize that there is no exit that way.
         </para>

         <para number='14' comment='Wooded path'>
         A low fence prevents you from leaving the path and getting lost in the woods.
         </para>

         <para number='15' comment='Dryad tree'>
         You hear a whisper behind you and a Dryad Goddess quietly advises you that you can't move in that direction.
         </para>

         <para number='16' comment='Library'>
         As you try to move in that direction, ou accidentally knock over a pile of books resulting in a loud crash.  The librarian looks up and shushes you and asks you to please be quiet.
         </para>

         <para number='17' comment='Terrace'>
         A tall privacy fence prevents tourists from seeing in and also prevents travel in that direction.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='charon'>

         <para number='1' comment='Give coin to Ch 1959 - no coin'>
         You do not have a coin or token to pay Charon. Besides, you are not dead, so why do you want to pay the ferryman?
         </para>

         <para number='2' comment='Got coin, so hand it over'>
         You hand the 7-groat coin to Charon, who pockets it and thanks you for the tip.
         </para>

         <para number='3' comment='Got token, so hand it over'>
         You hand the 13-groat token to Charon, who pockets it and thanks you for the tip.
         </para>

      </section>

      <section name='coin'>

         <para number='1' comment='Get coin loc 2406 - already got'>
         You have already taken one coin out of the fountain; to take another would be excessive.
         </para>

         <para number='2' comment='Not got one, so create coin'>
         You reach down and pick a coin out of the water that bubbles and froths around the foot of Neptune's chariot.
         </para>

         <para number='3' comment='Flip coin - heads - player'>
         You flip the coin into the air and then catch it again. Opening your hand you see the head of the despotic Ming.
         </para>

         <para number='4' comment='roomex'>
         Flipping a coin in the air, %s catches it and displays the result - it shows the head of the despotic Ming.
         </para>

         <para number='5' comment='Tails - player'>
         You flip the coin into the air and then catch it again. Opening your hand you see the tail of the fiery shooting star.
         </para>

         <para number='6' comment='roomex'>
         Flipping a coin in the air, %s catches it and displays the result - it shows the tail of the fiery shooting star.
         </para>

         <para number='7' comment='Give coin'>
         You have not said who you want to give the coin to.
         </para>

         <para number='8' comment='Drop coin - if they are in 2406'>
         You turn your back on the fountain and toss the coin over your shoulder. You can hear the splash as it lands in the water.
         </para>

         <para number='9' comment='Anywhere else'>
         You drop the coin and it lands on one of its points and balances for a moment before being kicked away out of sight by a passer-by.
         </para>

         <para number='10' comment='Drop coin in fountain - no coin'>
         You do not have a coin to toss into the fountain.
         </para>

      </section>

      <section name='mercury'>

         <para number='1' comment='Give sandal to Mercury 2215 NO'>
         You are not carrying a sandal.
         </para>

         <para number='2' comment='Have got sandal so hand it over'>
         The God of Commerce sees that you have something for him and quickly ushers you into a private booth. He thanks you for returning his footwear to him but strangely never asks where you got it. He presses a 13-groat token into your hand for your help.
         </para>

      </section>

      <section name='oldlady'>

         <para number='1' comment='Feed birds - 2342 - no coin'>
         The old lady will only sell you the bird food if you have a coin or token to give her - which you do not. She is old-fashioned and is not interested in groats transferred direct from your bank balance. How eccentric!
         </para>

         <para number='2' comment='Got coin so feed birds - player'>
         You hand your 7-groat coin to the old lady and in return she gives you a bag of bird seed. You start to scatter it around, and the alert pigeons soon start to crowd around you and peck it up. One brave bird hops onto your arm and starts to eat the seed directly out of the bag; luckily it flies off again before making a mess of your clothes! Before long, the birds have eaten all of the food, and they fly off to bother somebody else.
         </para>

         <para number='3' comment='roomex'>
         A crowd of pigeons starts to crowd around %s, who is scattering bird seed around. The hungry birds peck it up.
         </para>

         <para number='4'>
         One brave bird hops onto %s's arm and starts to eat the seed directly out of the bag!
         </para>

         <para number='5' comment='Got token - feed birds - player'>
         You hand your 13-groat piece to the old lady and in return she gives you two bags of bird seed which you scatter around. Soon you are surrounding by greedy pigeons, who peck up the seed. Some even land on parts of your body, including your head, but once they have eaten all the food they fly off to bother somebody else.
         </para>

         <para number='6' comment='roomex'>
         A crowd of pigeons starts to crowd around %s, who is scattering bird seed around. The hungry birds peck it up.
         </para>

         <para number='7'>
         One of the birds even lands on %s's head - how very unhygienic!
         </para>

      </section>

      <section name='pendant'>

         <para number='1' comment='Twirl pendant - player'>
         You hold the pendant out in front of you and twirl it round in a circle. Light flashes from the prism, sending rainbows all around the room.
         </para>

         <para number='2' comment='roomex'>
         Flashes of colored light suddenly appear, as %s twirls a prism and sends rainbows all around the room.
         </para>

         <para number='3' comment='Wear pendant'>
         You put the pendant around your neck and admire the way the prism hangs down. Unfortunately, as you take your hands off the chain, the clasp snaps and the pendant falls to the ground. The prism shatters and the chain rolls away out of sight.
         </para>

         <para number='4' comment='Put pendant in slot 2215 - no'>
         You are not carrying a pendant.
         </para>

         <para number='5' comment='Got pendant - player'>
         You insert the pendant into the slot, but it it doesn't fit very well. Giving it a shove, you insert it as far as it will go, until it is stuck fast. A red warning light begins to flash, and an alarm buzzes loudly. Everybody in the exchange looks at you to see what you have done.
         </para>

         <para number='6'>
         A repair technician appears and glares at you. "Another fool trying to put strange items in the slot machine," he mutters to himself, as he uses some kind of tool to remove the pendant you mistakenly tried to insert. He resets the machine, which shuts off the alarm, then walks off, still grumbling, and taking your pendant with him.
         </para>

         <para number='7' comment='roomex'>
         You hear the sudden buzz of an alarm, and see a red warning light flashing on and off. Looking around for the cause, you notice that %s is looking embarrassed.
         </para>

         <para number='8'>
         A repair technician appears and you see him glaring at %s. He mutters to himself, "Another fool trying to put strange items in the slot machine," as he uses some kind of tool to remove whatever was mistakenly inserted. He resets the machine, which shuts off the alarm, then walks off, still grumbling.
         </para>

         <para number='9' comment='Drop pendant - not in loc 2410'>
         You drop the pendant and it falls to the ground. The prism shatters and the chain rolls away out of sight.
         </para>

         <para number='10' comment='In 2410'>
         You drop the pendant on the altar. The pilgrim stands up and shimmers, transforming into the Goddess of Rainbows herself. She smiles and says, "Let the planet administrator know that you ahve crossed the crystal bridge and she will arrange for your name to join the list of others who have completed the journey." She shimmers again briefly and appears once again to be a humble pilgrim.
         </para>

         <para number='11' comment='Give pendant'>
         You have not said who you want to give the pendant to.
         </para>

      </section>

      <section name='pilgrim'>

         <para number='1' comment='Give pendant to pilgrim 2410 no'>
         You are not carrying a pendant.
         </para>

         <para number='2' comment='Got pendant so hand it over'>
         You offer the pendant to the pilgrim, who then stands up and shimmers, transforming into the Goddess of Rainbows herself. She smiles and says, "Thank you for bringing this to me. It shows you have the wit and wisdom to do what is necessary." She removes the prism from its chain and folds your hand over it telling you that you will need it elsewhere.
         </para>

         <para number='3' comment='continuation of pilgrim speech'>
         "There are other missions that need solving before you are finished," she says softly. You try to speak with her to get more information about these "other missions" but she does not respond, only smiles one more time before shimmering and becoming once again, the humble pilgrim.
         </para>

      </section>

      <section name='sandal'>

         <para number='1' comment='Get sandal - 2468 - already got'>
         You are already carrying a sandal - which is trying its best to escape - and you cannot handle another one at the same time.
         </para>

         <para number='2' comment='Take a sandal'>
         You try to pick up a sandal.  One of them skitters across the floor, its wings beating frantically. With a swift lunge, you manage to catch it.
         </para>

         <para number='3' comment='Drop sandal'>
         You let go of the sandal and it flies off out of sight.
         </para>

         <para number='4' comment='Wear sandal - player'>
         You put the sandal on, and you are pulled into the air unceremoniously by one foot as the sandal tries to fly off. After dangling by your ankle (or equivalent) for a few moments, the leather strap breaks and the sandal flies out of sight.
         </para>

         <para number='5' comment='Wear sandal - roomex'>
         You hear a sudden squeal, as %s is pulled unceremoniously into the air by one foot - the cause seems to be a winged sandal. After dangling by the ankle (or equivalent) for a few moments, the leather strap breaks and the sandal flies out of sight.
         </para>

         <para number='6' comment='Throw sandal - player'>
         You chuck the sandal as hard as you can. It flaps its wings, obviously intending to fly away, but the angle at which you threw it sends it around in an arc so that it returns to your hand like a boomerang.
         </para>

         <para number='7' comment='Throw sandal - roomex'>
         You hear a whirring noise, caused by %s chucking a sandal across the room. It flaps its wings, obviously intending to fly away, but the angle at which it was thrown sends it around in an arc so that it returns like a boomerang.
         </para>

         <para number='8' comment='Give sandal'>
         You have not said who you want to give the sandal to.
         </para>

      </section>

      <section name='slot'>

         <para number='1' comment='Put coin in slot 2215 - no coin'>
         You do not have a coin to put into the slot.
         </para>

         <para number='2' comment='Got coin so in it goes - player'>
         You don't have a 13-groat coin but fumbling in your pocket you find the triangular 7-groat piece you took from the fountain. Maybe that will do. You put it into the slot, but it doesn't fit very well. Giving it a shove, you insert it as far as it will go, until it is stuck fast. A red warning light begins to flash, and an alarm buzzes loudly. Everybody in the exchange looks at you to see what you have done.
         </para>

         <para number='3'>
         A repair technician appears and glares at you. "Another fool trying to use inappropriate currency in the slot machine," he mutters to himself, as he uses some kind of tool to remove the coin you mistakenly tried to insert. He resets the machine, which shuts off the alarm, then walks off, still grumbling, and taking your coin with him.
         </para>

         <para number='4' comment='roomex'>
         You hear the sudden buzz of an alarm, and see a red warning light flashing on and off. Looking around for the cause, you notice that %s is looking embarrassed.
         </para>

         <para number='5'>
         A repair technician appears and you see him glaring at %s. He mutters to himself, "Another fool trying to use inappropriate currency in the slot machine," as he uses some kind of tool to remove the coin mistakenly inserted. He resets the machine, which shuts off the alarm, then walks off, still grumbling.
         </para>

         <para number='6' comment='Put coin in slot 2215 - no coin'>
         You do not have a token to put into the slot.
         </para>

         <para number='7' comment='Got token - player'>
         You insert your 13-groat token into the slot and it drops into the mechanism with a clunk. The machine's lights come on as it whirls to life and the screen starts displaying information.
         </para>

         <para number='8'>
         Details on the building and population of the Pantheon flash across the screen. Scanning it, you learn the amazing fact that this planet was built with only the Roman Gods and Goddesses in mind, and that mankind was merely an afterthought because they missed having worshippers.
         </para>

         <para number='9'>
         After a few shameless plugs for sponsors of tourism locations, the machine turns itself off.
         </para>

         <para number='10' comment='Roomex'>
         You hear the whirr of machinery, and looking around you see that the slot machine has sprung into life, apparently because of something %s has done. Lights flash and information scrolls across the screen, but it's too far away for you to read any of it.
         </para>

         <para number='11'>
         After a few moments, the machine turns itself off again.
         </para>

      </section>

      <section name='soul'>

         <para number='1' comment='Give coin to soul 1959- no coin'>
         You do not have a coin to give to the poor soul.
         </para>

         <para number='2' comment='Got coin so hand it over'>
         You hand your 7-groat piece to the poor soul, but it is not enough to pay the fare across the river.
         </para>

         <para number='3' comment='Give token to soul 1959- no coi'>
         You do not have a token to give to the poor soul.
         </para>

         <para number='4' comment='Got token so hand it over'>
         You hand your 13-groat piece to the poor soul, who stops wailing and thanks you profusely. In return for your generosity, she gives you a pendant that she says was a family heirloom. She then turns pays the ferryman and drifts onto the boat, to take her place amongst the other souls.
         </para>

      </section>

      <section name='token'>

         <para number='1' comment='Flip token - heads - player'>
         You flip the token into the air and then catch it again. Opening your hand you see the fierce grizzle's head.
         </para>

         <para number='2' comment='roomex'>
         Flipping a token in the air, %s catches it and displays the result - it shows the fierce grizzle's head.
         </para>

         <para number='3' comment='Tails - player'>
         You flip the token into the air and then catch it again. Opening your hand you see the menacing sting of the Zlitherworm's tail.
         </para>

         <para number='4' comment='roomex'>
         Flipping a token in the air, %s catches it and displays the result - it shows the menacing sting of the Zlitherworm's tail.
         </para>

         <para number='5' comment='Give token'>
         You have not said who you want to give the token to.
         </para>

         <para number='6' comment='Drop token - if they are in 240'>
         You turn your back on the fountain and toss the token over your shoulder. You can hear the splash as it lands in the water.
         </para>

         <para number='7' comment='Anywhere else'>
         You drop the token and it lands on an edge and balances for a moment before being kicked away out of sight by a passer-by.
         </para>

         <para number='8' comment='Drop token in fountain - no tok'>
         You do not have a token to toss into the fountain.
         </para>

      </section>

   </category>

   <category name='temple'>

      <section name='tour'>

         <para number='1' comment='No payment for tour'>
         You have to pay to take the tour, and they don't have the facility to extract the money directly from your bank account. You will need to pay with a coin or token of some kind.
         </para>

         <para number='2'>
         You hand your payment to the tour guide and join the group. As you are ushered along with the other tourists through the halls of the Temple of Vesta, you pause to look at an interesting piece of statuary. The tour group moves on, leaving you to wander around by yourself.
         </para>

      </section>

   </category>

</para-list>


