<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='space locs no movement possible'>
         A palpable blackness surrounds you that absorbs all light, including that which is in your ship.  An emergency guidance system engages and is just able to take you back to where you began.
         </para>

      </section>

   </category>

</para-list>

