<?xml version="1.0"?>

<para-list version='12' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='tarmac no move'>
         The guards won't let you go that way.
         </para>

         <para number='2' comment='generic no move'>
         You can't go that way.
         </para>

         <para number='3' comment='hospital no exit'>
         You bump into the wall, and the doctor silently wonders if someone's cloning was defective.
         </para>

         <para number='4' comment='locked door message'>
         That door is locked.
         </para>

         <para number='5' comment='Valiant &amp; Galaxy no move'>
         The windows are closed and locked, not that you'd want to jump out one.
         </para>

         <para number='6' comment='no move in bar, store'>
         Somebody is looking as if he has had too much to drink!
         </para>

         <para number='7' comment='barricaded police/constr.'>
         That way is blocked off.
         </para>

         <para number='8' comment='Studio lot no move'>
         You accidentally bump into a cartoon hippo in a ballerina costume, who was also looking away from where she was going.  "Oh, excuse me!" she says in a high voice.
         </para>

         <para number='9' comment='Acme factory no move'>
         There is no exit that way, but you do end up spilling a bag of marbles on the floor.
         </para>

      </section>

   </category>

</para-list>
