<?xml version="1.0"?>

<para-list version='6' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit LP'>
         A helpful mechanic points out to you that the maintenance shed is to the north and that Free Scotia is to the east of here.
         </para>

         <para number='2' comment='No exit maintenance shed'>
         The chief mechanic grunts at you as you try to bust your way through the walls of his shed. "The exit is to the south, you know!"
         </para>

         <para number='3' comment='No exit security check'>
         A soldier pushes you back into line. 'No admittance to unauthorised personnel'.
         </para>

         <para number='4' comment='no exit DO tent'>
         The clerk looks up at you. "Please leave our tent in one piece! It's cold enough in here without you making more holes in it." He angrily points north.
         </para>

         <para number='5' comment='no exit large field'>
         The steep hills block your progress.
         </para>

         <para number='6' comment='No exit MASH'>
         A nurse urges you to be quiet. She whispers: "You can get out over there", and points southeast.
         </para>

         <para number='7' comment='no exit visitor centre'>
         The elderly lady smiles at you and points you at the exit, which is south.
         </para>

         <para number='8' comment='no exit refter'>
         A soldier with a wooden leg hops over to you and in a slightly patronizing manner takes you by the arm and guides you to the exit in the west.
         </para>

         <para number='9' comment='no exit exchange'>
         The walls, floor and ceiling of the farmhouse are too solid for you get through, despite the damage.
         </para>

         <para number='10' comment='no exit trader lounge'>
         The bartender winks at you. "Are you sure you won't stay for another drink?", she asks slightly sarcastically. "If not, the exit is north."
         </para>

         <para number='11' comment='no exit muddy lane'>
         The woods are so dense that you cannot go that way.
         </para>

         <para number='12' comment='no exit Army Camp'>
         As you stray from the camp, a passing patrol stops you and points you back to the camp.
         </para>

         <para number='13' comment='No exit gorge road'>
         The walls of the gorge cannot be scaled without very long ladders or mountaineering equipment, and you got neither.
         </para>

         <para number='14' comment='No exit Road block'>
         A gruff soldier stops you from going in that direction. "Sorry, but no civilians allowed beyond this point! Please go back west where you'll be safe."
         </para>

         <para number='15' comment='no exit HQ'>
         An NCO with a big handle-bar moustache grabs you by the shoulder. "Hey! Where do you think YOU are going? The exit is there, in the north."
         </para>

         <para number='16' comment='no exit stairs'>
         You cannot walk through concrete, no matter how hard you try. These are stairs, and they do what stairs do best: go up and down.
         </para>

         <para number='17' comment='no exit command bunker'>
         You bounce off the concrete and decide that using the stairs to the north might be a less painful and more elegant mode of egress.
         </para>

         <para number='18' comment='no exit CO quarters'>
         You bounce your face off the concrete and decide that using the door in the north won't look nearly as stupid as what you just did.
         </para>

      </section>

   </category>

</para-list>

