<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='General Outside'>
         The thick forest growth prevents you from going that way.
         </para>

         <para number='2' comment='barn 1'>
         Believe me.  A barn is not the type of place you want to prance about all willy nilly.  You never know what you are going to step in.
         </para>

         <para number='3' comment='Field'>
         The rail fence prevents you from going further.  Keep trying and you'll find the barb wire fence.  Keep trying after that, and you meet Mr. Cattleprod.
         </para>

         <para number='4' comment='farmhouse'>
         The stone walls of the farmhouse do not agree with your nose, so perhaps walking into the wall was not a good idea.
         </para>

         <para number='5' comment='Otter'>
         Otter looks up at you and says, "Are you daft?  Can't you see the path?"
         </para>

         <para number='6' comment='exchange'>
         You bump into several merchants who glare at you because at that very moment a bikini top was removed, and they were... interested in the resulting fluctuation of the prices... yeah, that's the ticket.
         </para>

         <para number='7' comment='village square'>
         The fountain, while refreshing, is not here for you to swim in.  Please stay on the marked paths.
         </para>

         <para number='8' comment='cafe'>
         You bump into a waiter sending a bowl of steaming hot soup flying through the air.  Luckily, it hit no one.  But please be more careful.
         </para>

         <para number='9' comment='office building'>
         Mr. Face meets Mr. Wall with a resounding Thud.
         </para>

         <para number='10' comment='hay loft'>
         The sharp tines of a pitchfork convince you that this is not the way to go.
         </para>

         <para number='11' comment='platform'>
         Unless you have wings, and have learned to fly, stepping off this platform at this height, is not a good idea.
         </para>

         <para number='12' comment='Inside Tree'>
         Even though it's wood, the walls of the tree still freaking hurt when your nose makes contact with them.
         </para>

         <para number='13' comment='Jezz s house'>
         Jezz video tapes everything.  And your pathetic movements will surely be the highlight of the conversation she has with friends at her next dinner party.
         </para>

      </section>

   </category>

</para-list>


