<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         A low growl emanates from the nearby bushes, and you think that maybe you should stay on the path.
         </para>

         <para number='2'>
         You bump into the wall, and a large drop of blood falls from your nose to the floor.  At the moment it hits the floor, a groan of hunger seems to come from the walls them selves!  Perhaps you should stay on the marked paths.
         </para>

         <para number='3'>
         The bridge is quite high, and a fall would be most certainly fatal.  Are you sure that you want to move that way?
         </para>

         <para number='4'>
         The fall from this height would certainly be fatal, perhaps you should stay on the path.
         </para>

         <para number='5'>
         You splash about in the hot tub to no avail.
         </para>

         <para number='6'>
         You bump into a local villager who glares at you, and you quietly take your seat.
         </para>

         <para number='7'>
         Zardoz and Jezz ask that you please try to behave yourself in their home.
         </para>

         <para number='8'>
         Your frantic antics at moving about are being recorded and will be aired on Aekonia's Funniest Home Videos.
         </para>

         <para number='9'>
         The chaos of a Landing Pad is not the place for foolishness.  Perhaps you should stay upon the marked paths.
         </para>

         <para number='10' comment='Jezz s office'>
         Considering the implement's that Jezz has at her disposal, walking around without a care is perhaps not a very good idea.
         </para>

         <para number='11' comment='coffin'>
         Unless you desire to remain here in eternal slumber, please use the proper exit.
         </para>

      </section>

   </category>

</para-list>


