<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Tram Station'>
         The station conducter grabs your arm and says, "What's the matter young'un?  Are ye daft?  You'll wind up on the Master's dinner table if ye are not careful."
         </para>

         <para number='2' comment='Iron Door'>
         Your face makes contact with the door, and the resulting CLANG, which results from the contact of flesh and iron, reverberates throughout the hallways of the castle.
         </para>

         <para number='3' comment='Lab Entry'>
         Your face makes contact with the stone wall, and a drop of blood slowly drops from your lip.  As the blood appears to be sucked into the stones themselves, an unhuman moan of indescribable hunger seems to emanate from the very walls themselves.
         </para>

         <para number='4' comment='Exchange'>
         You trip over a trading terminal and fall flat on your face.  You overhear a nearby merchant remark, "I don't know, I prefer the wrestlers on Ainokea for a floor show."
         </para>

         <para number='5' comment='Hallway'>
         Your face slams against the hard stone walls of the hallway, and as a drop of blood leaves your nose, a voice is felt, rather than heard.  The voice says, "Come to me, my precious, and I will grant you rest."
         </para>

         <para number='6' comment='Bar'>
         The heavy hand of the bartender clamps down on your shoulder.  The bartender says, "Hey now, you'll wind up on the menu if you aren't careful."
         </para>

         <para number='7' comment='Warehouse'>
         The large 20,000 ton bays teeter after you trip and bump into them.  Perhaps in such a risky area you should be more careful.
         </para>

         <para number='8' comment='Cold Storage'>
         You bump into a covered shape, and a bit of the covering peels away revealing a foot.  My God!  It's a body!  Quick!  Run!
         </para>

         <para number='9' comment='Stairway'>
         The hard stone steps of the stairwell add a few bumps and bruises as you slip slide away, leading you to the conclusion that you should be more careful.
         </para>

         <para number='10' comment='Landing'>
         The hard stone floor is unexpectedly cold, as your head smacks against it.
         </para>

         <para number='11' comment='Wooden Door'>
         The rough hewn surface of the door adds three splinters to your butt.
         </para>

         <para number='12' comment='Laboratory'>
         You bump into a lab table and the sound of tinkling glass fills the lab.  From the next room you hear a hungry voice, "Is that my meal?"  It might be a good time to run.
         </para>

         <para number='13' comment='Cage'>
         Your attempts to move are making a great deal of noise.  Perhaps that is not a good idea considering you are INSIDE a cage.
         </para>

         <para number='14' comment='Library'>
         A shelf of books falls over and a cloud of dust rises choking off what little fresh air exists down here.  Perhaps you should be more careful.
         </para>

         <para number='15' comment='Office'>
         As you trip and fall, you seem to catch out of the corner of your eye some movement of the shadows... Are they alive?
         </para>

      </section>

   </category>

</para-list>


