<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='space'>
         Nothing that way but the cold tendrils of distant space.
         </para>

         <para number='2' comment='Landing Approach'>
         The occasional bit of wreckage and debris strewn about the face of the cliff indicate that this is not the place to deviate from ground control's instructions.
         </para>

         <para number='3' comment='Claw'>
         The Shuttle Bay clamps don't allow you to move that way.
         </para>

         <para number='4' comment='Climb'>
         Ground Control advises you to stay within the prescribed flight path.
         </para>

         <para number='5' comment='Shuttle Bay'>
         The light tap of a plasma torch on your butt reminds you that a Shuttle Bay is not the place to wander about.
         </para>

      </section>

   </category>

</para-list>


