<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Dome - all locs - no exit msg'>
         A soldier of Lair steps forward and blocks your path, forbidding you from heading into an unauthorized location.
         </para>

         <para number='2' comment='Planet surface no exit msg'>
         A Viinitarhan guard steps forward and blocks your path, forbidding you from heading into an unauthorized location.
         </para>

         <para number='3' comment='Warehouse no exit msg'>
         A Viinitarhan dock worker steps forward and blocks your path.  "You can't wander around in here without an escort," he says in heavily accented speech, "and today there are no tour guides on duty.  Stick to the path."
         </para>

         <para number='4' comment='The Club - No exit msg'>
         An invisible force field stops you from stepping over the platform's edge.  From this close proximity you can hear the crackle of energy as colorful lightning bolts flash through the field, just past your face.
         </para>

         <para number='5' comment='Farm - no exit msg'>
         A farm worker steps forward and blocks your path, stopping you from going in that direction.  "Stay on designated paths only," he warns.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='brochure'>

         <para number='1' comment='Get/read/ex brochure'>
         The brochure reads as follows:
         </para>

         <para number='2'>
         "The NENA9000 filtering device must be worn at all times when outside of the dome. It can be purchased here for 99 groats and is available in several models to ensure a proper fit for all races.  "Once you buy the device the attendant will instruct you on its proper use.
         </para>

         <para number='3'>
         Remember, remaining on the planet's surface for long periods of time is lethal due to the toxic nature of the air pollution produced by the wineries.  If you leave the dome without the NENA9000 death will occur very quickly.  The Sauterne authorities will not be responsible for injuries or fatalities suffered planet-side."
         </para>

         <para number='4'>
         Once you have finished reading the attendant takes the brochure from you and places it back in the stack.
         </para>

         <para number='5' comment='roomex'>
         %s carefully examines a brochure from the stack on the display case.  Once finished the attendant replaces it on the stack.
         </para>

      </section>

      <section name='nena'>

         <para number='1' comment='buy/get/take nena9000 - no cash'>
         It would appear that you don't have the funds to purchase the NENA9000.  You should not leave the dome until you can acquire one.
         </para>

         <para number='2' comment='successful purchase'>
         You fork over the required 99 groats and the attendant selects the device best suited to you.  After instructing you in its proper usage she gestures toward the airlock.  "As long as you have the NENA9000 with you, you can explore the planet's surface without incident."  She smiles sweetly as if the "incident" to which she refers isn't a quick but painful death.
         </para>

      </section>

   </category>

   <category name='stam'>

      <section name='boost'>

         <para number='1' comment='Loc 2077 - stam boost'>
         Along with the usual whoosh of air that accompanies the cycling of an airlock, you also feel a tingling followed by a faint odor.  Suddenly you feel completely renewed.
         </para>

      </section>

      <section name='drain'>

         <para number='1' comment='Stam drain version 1'>
         A sweet odor prickles your nostrils and you become a little lightheaded.  You feel weaker then you did a few moments ago.
         </para>

         <para number='2' comment='Stam drain version 2'>
         A sweet, tangy odor invades your nostrils and you become dizzy. You feel quite a bit weaker than you did a few moments ago.  A nearby traveler, wearing a small device on her face approaches you. "You should return to the dome right away," she says.  "You will die if you keep breathing the air out here."
         </para>

         <para number='3' comment='stam drain version 3'>
         A sweet, tangy odor completely permeates your nostrils and you become dizzy.  Your vision begins to blacken and you feel much weaker then you did a few moments ago.  A nearby beast peers in your direction and as your mind fades in and out you hear the beast say, "Who are you, who who, who who?"  Oh boy, you must really be in trouble.  You are obviously hallucinating.
         </para>

      </section>

   </category>

</para-list>

