<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexits'>

         <para number='1' comment='exchange'>
         The chairman of the Brazos Exchange informs you that you are not allowed there.
         </para>

         <para number='2' comment='Cafe'>
         You've had one too many rounds.
         </para>

         <para number='3' comment='Hospital'>
         Wait until the blood starts flowing before you try moving, pardner!
         </para>

         <para number='4' comment='Store'>
         The storeroom door is locked
         </para>

         <para number='5' comment='ne turnpike'>
         While attempting to climb the fence, you end up with a few razor wire cuts and fall to the ground.
         </para>

         <para number='6' comment='town road'>
         A barricade from the Brazos Public Works Commision restricts your movement in that direction
         </para>

         <para number='7' comment='library'>
         The librarian sternly looks down her glasses at you and politely shakes her head.
         </para>

         <para number='8' comment='Police'>
         A couple of jail guards grab you and head you in the right direction.
         </para>

         <para number='9' comment='post office'>
         Post office regulations prohibit entry.
         </para>

         <para number='10' comment='Victoria'>
         That dressing room seems to be occupied at the moment.
         </para>

         <para number='11' comment='lp'>
         Large crates with ship parts block your way
         </para>

      </section>

   </category>

</para-list>


