<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='nomove'>

      <section name='airlock'>

         <para number='1' comment='Pressure ranges'>
         Your unexpected movements within the airlock chamber is causing the automatic adjustment sensors to repeatedly change the pressure within the airlock. This rapid and sudden change in air pressure, while not fatal can be debilitating and cause nausea and headaches. You should probably either go outside or move into the facility proper.
         </para>

      </section>

      <section name='cafe'>

         <para number='1' comment='Treatment'>
         You stumble and crash into a table and accompanying chairs and end up on the floor. Doc comings running over with a medical kit and a meat cleaver. You're not sure which one he intends to use first. You stand up and quickly inform Doc nothing is hurt except your pride. Doc smiles and walks back to his grill. He looks over his shoulder and yells to you so that all can hear "I really think you should take me up on that insurance offer!"
         </para>

      </section>

      <section name='core'>

         <para number='1' comment='Confused by gray drab'>
         You seem confused by the uniformity of the gray drab interior of the central core area and appear to stumble and wander around in circles. One of the researchers, coming from the hatchway to the east, notices you and your condition and tells you that the aid station is throught the west hatchway.
         </para>

      </section>

      <section name='crater'>

         <para number='1' comment='Headache'>
         You are starting to develop a severe headache, perhaps you should walk back to your shuttle and get some oxygen therapy.
         </para>

         <para number='2' comment='Stumble'>
         You trip over a small rock on the crater floor and began to stumble and fall. Fortunately you regain your balance before face planting into the fine dusty soil of the crater floor.
         </para>

         <para number='3' comment='Walk into wall'>
         You blindly walk into the crater wall, smashing your nose and bumping your head. "OUCH" you yell. It is a good thing no one saw you otherwise they would think you were a crazy loon. As you rub your nose and head, a thought comes to you. "Perhaps I should watch where I am going."
         </para>

         <para number='4' comment='Lizard'>
         You turn to go that direction but come face to face with an three foot long indigenous animal resembling a lizard clinging to the face of the crater wall. It cocks its head to one side all the while watching you with its reptilian eyes. As you watch, it slowly flicks its forked tongue out at you and you begin to wonder if the creature is sizing you up as a meal. You quickly move away and decide to go in another direction.
         </para>

         <para number='5' comment='Dais'>
         You are starting to develop a severe headache and nausea. Perhaps you should get down off the dais, walk back to your shuttle and get some oxygen therapy.
         </para>

      </section>

      <section name='exchange'>

         <para number='1' comment='You just bought'>
         Your sudden and unexpected movements causes some confusion among the gathered traders and researchers who are bidding and trading on commodities here in the exchange. When all is said and done, you find out you've just purchased 23 bays of toxicmunchers and 15 bays of probes. The exchange manager smiles and tells you "Thank-you for your purchase. You can pick up your goods at Schrodinger's warehouse." He smiles and moves away quickly.
         </para>

      </section>

      <section name='lab'>

         <para number='1' comment='please leave'>
         You edge closer to the researchers to see what they are working on when one of them notices your shadow and turns around to confront you. "You really shouldn't be in here while we are working on this biological toxin right now, and for goodness sake, please don't tell our android co-workers we have this potentially lethal mold outside the containment lab." You quickly retreat to howls of laughter coming from the human researchers.
         </para>

      </section>

      <section name='livingquarters'>

         <para number='1' comment='android station'>
         You try to move in that direction but hit your knee on a chair leg which causes you to stumble and fall. You catch yourself by reaching out and touching one of the android regenative stations. The nasty shock you get causes you to yelp in pain and you wonder if falling down on the floor might of been more pleasant after all.
         </para>

      </section>

      <section name='pathway'>

         <para number='1' comment='Near crater'>
         While thinking about your next move, you step very close to the crater rim and it begans to crumble away. You step back just in time as small rocks and dirt go tumbling down into the crater and cascade out along the bottom. You should be more careful while idly walking around the planet's surface.
         </para>

         <para number='2' comment='Near airlock'>
         You start to explore the planet's surface when a sudden gust of wind blows some of fine dusty soil into your face causing you to cough and gasp for what little oxygen exists in the atmosphere. Perhaps you should return to your shuttle or go into the research facility for assistance.
         </para>

      </section>

   </category>

</para-list>

