<?xml version="1.0"?>

<para-list version='8' editor='standard'>

   <category name='nomove'>

      <section name='alpha'>

         <para number='1' comment='On dais'>
         The boogie man reaches out from the darkness and grabs your shoulder from behind. You start to scream and run but when you move realise that the boogie man was just a potted native plant sitting in the corner of the cave. Apparently the plant doesn't need any sunlight to thrive.
         </para>

         <para number='2' comment='Monitoring Station'>
         You start to move but stumble over some old equipment left on the floor and fall flat on your butt. You swear you hear a muffled laugh but once you get up you realise there is no one or no thing here. The hair on the back of your neck begins to tingle.
         </para>

         <para number='3' comment='Logistics Station'>
         You lose your balance and stumble into the complex equipment. As you place your hand out to steady yourself you happen to touch some buttons on the equipment. A voice suddenly eminates from a speaker overhead. "Alpha Station, this is Control, we read your emergency broadcast beacon. What is your status? Over." You decide to be more careful.
         </para>

         <para number='4' comment='On Dais (In)'>
         You walked into the cave walls which border around the raised stone dais. You think you hear some muffled laughter but when you turn to the direction from whence it came, you see nothing. You squint hard to see in the dark but only see the glow of the monitor screens.
         </para>

      </section>

      <section name='beach'>

         <para number='1' comment='Beach'>
         In a show of bravado or stupidity you attempt to scale the rocky walls. You slowly inch your way up until a rock gives loose and you fall backwards into thin air screaming all the way down to the sandy beach below. It was a good thing you were only three feet up the wall.
         </para>

      </section>

      <section name='clearing'>

         <para number='1'>
         As you start to move, you feel a hand touch your shoulder from behind. You turn but see nothing and hear nothing. The hair on the back of your neck begins to tingle.
         </para>

      </section>

      <section name='forest'>

         <para number='1'>
         As you start to move a raven swoops down in front of you and lands on the forest floor. It stares at you for a few moments, then squawks and flies back up into the canopy. You follow the raven's flight into the trees and watch it as it lands and continues to stare at you. Eventually you lose interest and go back about your business.
         </para>

         <para number='2'>
         You hear a twig snap behind you and freeze. Slowly turning around and fearful of what might be behind you tremble in fear until you see it's only a cute furry little bunny rabbit. It wiggles its nose and whiskers and then hops off in search of food.
         </para>

         <para number='3'>
         You start to move in that direction but the dense underbrush thwarts your every effort to continue. You give up and decide to try a different direction.
         </para>

         <para number='4'>
         As you start to move a violent swirling gust of wind sweeps up dust, leaves and twigs from the forest floor and blows them in your face. You cough and sputter and cover your eyes. When the gust subsides you forgot which direction you were going.
         </para>

         <para number='5'>
         As you start to move, you catch a glimpse of an animal moving in your peripheal vision. You turn to look and think you see a white wolf moving silently through the forest in the distance, but you can't be sure. The creature passes behind a large tree and vanishes.
         </para>

         <para number='6'>
         Without warning a large branch crashes down to the earth no more than ten feet in front of you. Broken limbs and leaves go careening off in many directions. You stand frozen to the ground, your heart pounding in your ears. It's a good thing you didn't go that way now isn't it?
         </para>

         <para number='7'>
         As you begin to move you hear some honking coming from the sky. Quickly moving to look through an opening in the forest canopy you see a large V of geese flying westerly. You watch as they fly off and out of sight.
         </para>

         <para number='8'>
         As you step forward you hear a menacing growl coming from the forest in front of you. Not sure of the source you decide to high step it back to where you started and decide to try a different direction. You cast a quick glance behind you before moving on, but the forest hides all traces of the animal that you disturbed.
         </para>

         <para number='9'>
         You consult your map and compass and select a landmark tree to set your direction. You look down to check your map one more time, but when you look back up all the trees suddenly look the same. You better consult your map and compass again.
         </para>

         <para number='10'>
         You start to move but catch a glimpse of movement to your side. You stop and slowly turn to see a group of hunters walking quietly though the forest. They don't see you yet, so you quietly move behind a tree. When you peek around to follow the hunters' progress you no longer can see them. It's as if the forest and undergrowth simply swallowed them up.
         </para>

         <para number='11'>
         You start to move but suddenly hear a hissing noise coming from the dense vegatation in front of you. Not sure of the source, you decide to turn around and return to your starting place. After a moment in which all is calm, you decide to try a different direction.
         </para>

      </section>

      <section name='hiddenpool'>

         <para number='1' comment='Hidden Pool'>
         You splash around in the cool water in your birthday suit. You hope there are no crawling critters or slimy creatures to bite you in an unprotected spot. Ouch!
         </para>

      </section>

      <section name='river'>

         <para number='1' comment='Tranquil Pool'>
         You chuckle to yourself as you realize you were actually thinking you could climb those sheer rock faces with just your arms and legs. You decide instead to sit on a large boulder and watch the reflections off the pond's surface.
         </para>

         <para number='2' comment='Pathway'>
         You eye that sheer rock face thinking "I bet I could climb that!" But then sanity or reality kicks in and you realize you're not a lizard. You decide to continue walking along the path.
         </para>

         <para number='3' comment='Under Water'>
         You swim out into the current and get tumbled around on the bottom of the river. Fortunately the river deposits you back in the calm patch of water. But you better surface before you run out of air.
         </para>

         <para number='4' comment='Surface'>
         You try to swim against the current but realize you are getting nowhere and quickly becoming exhausted. It might be best to go with the flow and hope for the best.
         </para>

         <para number='5' comment='Below Trunk'>
         The fast flowing water sucks you under unexpectantly filling your mouth with water. You surface quickly coughing and trying to catch your breath without swallowing any more water. As you float toward the tree trunk you need to make a quick decision.
         </para>

         <para number='6' comment='Fall off trunk'>
         You struggle to swim upstream to get back to the downed tree trunk, but the southerly current is too strong. You grow weaker fighting the current. Perhaps you show go with the flow and hope for the best.
         </para>

         <para number='7' comment='Standing in River'>
         As you start ot move, a fish suddenly jumps out of the water right in front of you. Started, you slip on a stone underwater and dunk yourself. Coming up for air you laugh at your clumsiness. You wonder what that fish thinks of you now.
         </para>

         <para number='8' comment='Lazy River'>
         The gorge walls stand like silent sentinals and block your way. One of your footwear is beginning to leak as you stand in the river. Better try to find dry land before your footwear gives way.
         </para>

      </section>

      <section name='treehouse'>

         <para number='1' comment='Treehouse'>
         You step up to a window and look at the spectacular view. Miles and miles of forested woodland. A person could get lost in there without a map. After a moment you start to feel a little dizzy from the great height of your perch. So you back away and sit down in the chair.
         </para>

      </section>

      <section name='treetrunk'>

         <para number='1' comment='Rescued'>
         You start to stand up but you hand slips on the wet bark and you collapse back down onto the tree trunk. Careful, you don't want to end back up in the river. When you are ready stand up carefully and walk off the downed tree.
         </para>

         <para number='2' comment='Walking'>
         You start to move when suddenly a ferocious gust of wind comes from the gorge to the north and knocks you slightly off balance. You quickly steady yourself before you fall off into the cold water below. Brrrrr.....
         </para>

      </section>

      <section name='village'>

         <para number='1' comment='Village'>
         You stumble and fall over some makeshift tables in the market place. The children scream and laugh at your misfortunes, while the adults don't seem to notice or at least don't let on that there is a clumsy stranger in their midst. You quicky stand up and move along.
         </para>

         <para number='2' comment='On bed'>
         You thrash around on the bed, delirious from fever. An old man brings a cup of elixer over for you to drink. The concoction is vile and bitter but soothes your convulsions and allows you to rest. As you fall asleep you hear the old man say to someone else in the room "When he is better, he will get up."
         </para>

         <para number='3' comment='In Hut'>
         You stumble around in the dark unsure of where you are going. The old man lifts his head and says "Careful, there are many things in this hut that are dangerous if disturbed. If you wish to leave you can go through the door." As he speaks you can see by the light of the fire that he is pointing to the west.
         </para>

      </section>

   </category>

</para-list>

