<?xml version="1.0"?>

<para-list version='5' editor='standard'>

   <category name='nomove'>

      <section name='space'>

         <para number='1' comment='Space'>
         You engage your engines and prepare to blast to hyperspace but your navigational computer detects no known star patterns in its database so the computer shuts the procedure before you blast off into uncharted territory. It seems modern technology is unable to deal with the uncertainty of insufficient data.
         </para>

         <para number='2' comment='Ofi Lusa'>
         You attempt to ignite your main thrusters to return up to your space ship but because of the lingering effects of oxygen depravation you instead press the button to flush your ship's sewage tanks. Opps.
         </para>

         <para number='3' comment='Wolf'>
         Your efforts to regain control of your ship seem futile. But since a fiery death on a remote planet is your only probable alternative, you should try again to get back up to your space ship.
         </para>

         <para number='4' comment='Wormhole'>
         Your attempt to leave the wormhole was unsuccessful. Give the main thrusters a moment to re-energize and try again. But hurry, a collapsing wormhole can be hazardous to your health!
         </para>

         <para number='5' comment='Above Sun'>
         It's getting hot in here and the radiation levels are starting to move into the danger zone. You should really put some distance between you and the sun as soon as possible.
         </para>

      </section>

   </category>

</para-list>

