<?xml version="1.0"?>

<para-list version='9' editor='standard'>

   <category name='nomove'>

      <section name='accesstube'>

         <para number='1' comment='Time counting down'>
         You turn to leave but find one of the station scientists blocking the door. He looks quite flumoxed by your presence in the access tube and stammers "Uhhh, you're not supposed to be here." You give him a hard stare and say "No kidding! Now will you please get out of my way so I can leave before security shows up!". The scientist still looks confused but does step away from the sliding doorway to provide room for your getaway.
         </para>

      </section>

      <section name='airlock'>

         <para number='1' comment='Airlock'>
         You turn suddenly and bang your nose on the airlock's thick walls. Hurts doesn't it. The other visitors in the airlock with you snicker at your clumsiness.
         </para>

      </section>

      <section name='corridor'>

         <para number='1' comment='Walk into wall'>
         You step back and turn in that direction but run face first into the bulkhead wall. In a game of steel versus flesh, steel wins again. You hold your head in your hands as the stars (the ones in your head) begin to fade away. Perhaps you should visit the Infirmary and get checked out.
         </para>

         <para number='2' comment='Ran over'>
         As you step in that direction a crowd of excited people come rushing from the northeast, trample you down, and keep running on toward the south. You sit in a daze not knowing what the heck just happened. A security guard comes along and says "Got in the way did ya? Next time just press up against the bulkhead wall. The traders and merchants who come to this exchange aren't known for their civility." She smiles at you and walks on.
         </para>

         <para number='3' comment='Intercom giggling'>
         You start to move but suddenly you suddenly hear a fit of giggling coming over the station's public address system. "Oh is this thing on again?" you hear someone say, then an audible click and all is quiet again. Caught up in the moment you forgot what it is that you were doing or where you were headed.
         </para>

         <para number='4' comment='Absent minded'>
         You turn and start to go in that direction, but you eye catches something lying on the corridor floor. Why it's a 100 groat coin, this must be your lucky day! You whistle a snappy tune and pocket the coin. A marsrat runs down the corridor and startles you, you jump back and bang your head on a bulkhead wall. Perhaps its not such a lucky day.
         </para>

         <para number='5' comment='Catches attention'>
         You start to turn but something at a portal window catches your eye and you stop and look out into space. Outside the station is a small space gremlin. He is furiously banging on the window with a small hammer. He sees you watching him and sticks his tongue out at you and bares his pointy teeth.You scream for help and when security arrives, the gremlin is gone. You try to explain but all they do is laugh, shake their head and walk off.
         </para>

         <para number='6' comment='Bump into someone'>
         You step and turn in that direction and run right into one of the station's scientists who was on his way for a bit to eat. Electronic notepads, data recorders, notes and other papers go flying in all directions as you both end up in a heap on the floor. You apologize profusely for your clumsiness as you help gather up all the clutter and return it to him. He takes the mess from you and continues on his way.
         </para>

         <para number='7' comment='White courtesy zone'>
         You start to move, but suddenly the station's public address systems cackles to life. "Will the owner of the gunmetal grey Class III shuttle please report to the landing bay. Your shuttle is parked in the white courtesy zone and will be scrapped if not moved. Thank-you". You hear a fit of giggles before the system is turned off.
         </para>

         <para number='8' comment='Stomach growls'>
         You start to move but suddenly your stomach lets loose with a massive growl. In the close confines of the station's corridor the noise echos loudly down the hall. Several staff members stop and cock their head to try and determine where the sound came from. You smile as they walk by and say "Did you hear that too?, someone better call security!"
         </para>

      </section>

      <section name='exchange'>

         <para number='1' comment='Pushed and jostled'>
         You turn to move when someone bumps into you from behind and picks your pocket. You turn quickly to try and find the culprit but no one in the crowd behind you betrays any indication that they were the perpertrator or that they saw anyone do the crime. In the tradings pits, it's dog eat dog and you not only have to watch your trades but also your personal well-being as well.
         </para>

      </section>

      <section name='galley'>

         <para number='1' comment='Pots and Pans'>
         You turn to leave, but bang your head on some overhanging pots, which in turn bang into somemore hanging pots and then the whole contraption comes crashing down with a thunderous roar. You look over at the chef with an "OOPS" expression but see his eyes bugging out and the veins in his neck pulsating. You should beat a hasty retreat from here while you can.
         </para>

      </section>

      <section name='infirmary'>

         <para number='1' comment='Waiting Room'>
         You turn suddenly and bang your nose on the waiting room walls. Hurts doesn't it. Good thing you are in the Infirmary already. If you want to wait perhaps the doctor can examine you in a short while.
         </para>

         <para number='2' comment='Crash'>
         You turn to leave but bump into a cart with many probes, clamps and other instruments of the medical profession that had been placed in a precise and orderly arrangement. However, your clumsiness has turned order into chaos. It will be a wonder if the doctor can find anything on that cart now.
         </para>

      </section>

      <section name='landingbay'>

         <para number='1' comment='Landing bay force shield'>
         You start to wander near the landing bay opening, getting very close to the force field when suddenly you are suddenly grabbed and pulled from behind. You turn around angrily and come face to face with the landing bay manager. He points down and says "See that yellow line and the words STAY BEHIND AT ALL TIMES, it means just that! Now please head into the station where you can wander around all you want."
         </para>

      </section>

      <section name='lounge'>

         <para number='1' comment='Fall onto couch'>
         You turn to move but stumble over a table leg and while trying to regain your balance fall onto one of the many couches in the room. All the other people in the lounge look over at the the commotion, but you plop your fist into the couch cushion and say "Ah yes, this feels good". You quickly pick up a magazine and pretend to read it, while the other people return to their own business. Once the scrutiny is over, you quickly stand up.
         </para>

         <para number='2' comment='Bang your shin'>
         You turn to move but bang your shin into a table leg. You hop around on one leg yelling "OW OW OW" much to the amusement of the other people in the lounge. The pain starts to subside and you can now stand on both feet. You look around and see all the smiles and laughter from the other people in the lounge. You quickly take a bow and say "And now for my next trick...", but everyone has already gone back to their own business.
         </para>

      </section>

      <section name='quarters'>

         <para number='1' comment='Bang head on wall'>
         You start to move in that direction but trip over the chair in the cramped quarters and fall onto the bed and bang your head on the wall. You think to yourself "I need to be more careful in the future" as you rub your sore head.
         </para>

         <para number='2' comment='Bang head on bunk'>
         You start to move in that direction but trip over the chair in the cramped quarters and fall onto the bed and bang your head on the bunk bed cross beam. You think to yourself "Owwww this is gonna leave a mark" as you rub your sore head.
         </para>

         <para number='3' comment='Bang head on bunk'>
         You start to move in that direction but trip over the chair in the cramped quarters and fall onto the bed and land on the sleeping occupant who only momentarily stirs but then falls back into a deep slumber, snoring loudly. In a flash you realize why you didn't awake the person as your get a whiff of his breath. Whew.... had a little too much to drink they did. You quietly stand up, a little intoxicated yourself from the fumes.
         </para>

         <para number='4' comment='Can not move'>
         This place is so elegant and expensive looking, you are too afraid to move around and look at things lest you accidently break something. On your wages it would take two lifetimes to pay for any damages. So you simply stand still right where you are and admire the furnishings.
         </para>

         <para number='5' comment='Soft bed'>
         You slip off your shoes and fall onto the bed. It cradles your body and the soothing action of the low grav inner mattress system slowly relaxes all your tense and tightened muscles. You begin to fall asleep, but realize there would be hell to pay (as well as one night's lodging) if you were caught sleeping here. So you put your shoes back on and stand up.
         </para>

      </section>

      <section name='reception'>

         <para number='1' comment='Intercom giggling'>
         You move suddenly and startle Stacey who was looking at puppies on her console. She jumps in fright and accidently turns on the public address system. Realizing that it was only you she begins to giggle. When she hears the giggling over the pubic address system she pouts and says "Oh is this thing on again?" She reaches over and switches it off. For a moment she looks up you with a blank expression, then  "Oh look puppies...."
         </para>

      </section>

      <section name='resturante'>

         <para number='1' comment='Spilled table'>
         You turn to move but snag an end of a table cloth and pull it and the fine meal that was being feasted upon by a couple onto the mess hall floor. You apologize to the couple seated at the table and offer to pay for their meal. While settling the bill with the maitre d' near the entrance, you bump into a waiter bringing another meal to the couple, causing him to spill it over the maitre d' who is now mad at you and yells "JUST GET OUT!"
         </para>

      </section>

      <section name='security'>

         <para number='1' comment='Force field'>
         You turn and accidently walk into the force field. A short but severe electrical shock pulsates throughout your body. The security guard outside your cell gives you a sly smile. "Hurts, doesn't it" he says. Perhaps you should just wait quietly until we furhter review your activities here on the station.
         </para>

         <para number='2' comment='Step up'>
         You stumble around the security lobby. The security guard grabs you by the shoulder and says "Citizen, please step up onto the teleportation disk to leave or I will have to put you back in the holding cell."
         </para>

      </section>

      <section name='theater'>

         <para number='1' comment='Stumble'>
         You turn to leave but slip on some spilled popcorn. You lose your balance and while attempting to regain it, plop right down into one of the viewing booths chairs. The theater manager runs excitedly over and says "That will be 100 groats please" and holds out his hand. You start to protest but decide otherwise. Heck, these ZARDOZ films might even be fun. You fish out a 100 groat coin from your pocket and hand it over.
         </para>

      </section>

   </category>

</para-list>

