<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='baseball'>

      <section name='baseline'>

         <para number='1'>
         Please stay in the baseline, thank you.
         </para>

      </section>

      <section name='default'>

         <para number='2'>
         The people of Baseball do not allow that.
         </para>

      </section>

      <section name='homeplate'>

         <para number='4'>
         Please stay in the Batters Box.
         </para>

      </section>

   </category>

</para-list>

