<?xml version="1.0"?>

<para-list version='121656078' editor='standard'>

   <category name='basics'>

      <section name='landingpad'>

         <para number='1'>
         The people of Candlepin do not allow travel in that direction.
         </para>

      </section>

   </category>

   <category name='bowling'>

      <section name='score'>

         <para number='1' comment='Bowl message - player'>
         You rub the ball in your hands and adjust your grip, then take a couple of steps and slide to the line where, with a powerful swing of your arm you release it...
         </para>

         <para number='2' comment='Roomex'>
         %s rubs a ball and adjusts the grip, then takes a couple of steps up to the line and with a powerful arm swing, releases it...
         </para>

         <para number='3' comment='Score 0 - player'>
         As you release the ball, your grip slips slightly and the ball bounces off line and goes into the gutter, rolling out of sight. You missed completely, you failed to knock any of the pins over, and you score a big fat zero. How embarrassing!
         </para>

         <para number='4' comment='Roomex'>
         The ball bounces off line and goes into the gutter, rolling out of sight. %s missed completely and failed to knock any of the pins over, scoring absolutely nothing. How embarrassing!
         </para>

         <para number='5' comment='Score is 1 - player'>
         You watch as your ball misses the pocket completely and knocks over just one pin. You score a deplorable 1 point.
         </para>

         <para number='6' comment='Roomex'>
         The ball misses the pocket completely, knocking over just one pin. %s scores a deplorable 1 point.
         </para>

         <para number='7' comment='Everyone'>
         A droid trundles up to the pins and puts the fallen one back in place.
         </para>

         <para number='8' comment='Score 2 - player'>
         You watch as your ball slips off line and knocks over just two pins. You score a pathetic 2 points.
         </para>

         <para number='9' comment='Roomex'>
         The ball slips off line, knocking over two pins. %s scores a pathetic 2 points.
         </para>

         <para number='10' comment='Everyone (and for all higher)'>
         A droid trundles up to the pins and puts the fallen ones back in place.
         </para>

         <para number='11' comment='Score 3 - player'>
         You know you have thrown the ball way too hard  and it punches out just three pins. You score a paltry 3 points.
         </para>

         <para number='12' comment='Roomex'>
         The ball is thrown way too hard and it punches out three pins. %s scores a paltry 3 points.
         </para>

         <para number='13' comment='Score 4 - player'>
         You watch as your shot hits the headpin straight on and knocks over four pins. You score an unsatisfactory 4 points.
         </para>

         <para number='14' comment='Roomex'>
         The ball rolls and hits the headpin straight on, knocking over four pins. %s scores an unsatisfactory 4 points.
         </para>

         <para number='15' comment='Score 5 - player'>
         You watch as your ball rolls wide of its mark and knocks over five pins. You score a so-so 5 points.
         </para>

         <para number='16' comment='Roomex'>
         The ball rolls wide of its mark, knocking over five pins. %s scores a so-so 5 points.
         </para>

         <para number='17' comment='Score 6 - player'>
         You watch as your shot enters the pocket and knocks over six pins. You score a mediocre 6 points.
         </para>

         <para number='18' comment='Roomex'>
         The ball rolls and enters the pocket, knocking over six pins. %s scores a mediocre 6 points.
         </para>

         <para number='19' comment='Score 7 - player'>
         You watch as the ball rolls slowly down the middle of the lane and enters the pocket, knocking over seven pins. You score a pretty good 7 points.
         </para>

         <para number='20' comment='Roomex'>
         The ball rolls slowly down the middle of the lane and enters the pocket, knocking over seven pins. %s scores a pretty good 7 points.
         </para>

         <para number='21' comment='Score 8 - player'>
         You watch as your shot enters the pocket and knocks over eight pins. You score a satisfactory 8 points.
         </para>

         <para number='22' comment='Roomex'>
         The ball rolls and enters the pocket, knocking over eight pins. %s scores a satisfactory 8 points.
         </para>

         <para number='23' comment='Score 9 - player'>
         You watch as your ball follows a perfect line and leaves one pin standing. You score a splendid 9 points.
         </para>

         <para number='24' comment='Roomex'>
         The ball rolls and enters the pocket, and leaves one pin standing. %s scores splendid 9 points.
         </para>

         <para number='25' comment='Score 10 - player'>
         You watch as your shot enters the pocket and knocks over all ten pins - it's a strike! You score a magnificent 10. Very impressive!
         </para>

         <para number='26' comment='Roomex'>
         The ball rolls and enters the pocket, knocking over all ten pins - it's a strike! %s scores a magnificent 10. Very impressive!
         </para>

         <para number='27' comment='Everyone'>
         A droid trundles up to the pins and puts them all back in place.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='alley'>

         <para number='1' comment='Take ball away - 711'>
         As you leave the alley, an official takes the bowling ball away from you - the management doesn't allow customers to walk off with the sporting equipment!
         </para>

         <para number='2' comment='Turn back if wearing shoes 713'>
         You can't leave the bowling alley without returning the bowling shoes to the registration desk - and you don't want to leave your own footwear behind.
         </para>

         <para number='3' comment='710 - turn back if not got shoe'>
         You are not allowed to proceed any further unless you are wearing bowling shoes.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='ball'>

         <para number='1' comment='get ball - 710 - already got'>
         You are already carrying a ball; you can't pick up another one until you have bowled the first.
         </para>

         <para number='2' comment='Pick up a ball'>
         You pick up one of the balls.
         </para>

         <para number='3' comment='Roomex'>
         %s has picked up one of the balls.
         </para>

         <para number='4' comment='Drop ball'>
         The ball lands with a thud - narrowly missing your foot - and rolls away. It falls into the gutter and vanishes.
         </para>

         <para number='5' comment='Roomex'>
         You hear a thud - %s has dropped a bowling ball. It rolls away out of sight.
         </para>

      </section>

      <section name='shoes'>

         <para number='1' comment='rent shoes - 648 - already got'>
         You are already wearing a pair of bowling shoes; you don't need any more.
         </para>

         <para number='2' comment='Create shoes'>
         You hold up a foot (or whatever it is your species stands on) and the man examines it. He grunts, then passes you a pair of shoes that have clearly been worn by many others before you. Ignoring the odor of past bowlers, you remove whatever footwear you are wearing and put the bowling shoes on.
         </para>

         <para number='3' comment='Return shoes - not got'>
         You don't have any bowling shoes to return.
         </para>

         <para number='4' comment='Return the shoes'>
         You take off the rather smelly bowling shoes and return them to the man behind the desk. He rummages around until he finds your own footwear, which you take and put on again.
         </para>

         <para number='5' comment='Drop bowling shoes'>
         You can't just discard the bowling shoes wherever you like - you need to get back your own footwear from the registration desk.
         </para>

      </section>

   </category>

</para-list>

