<?xml version="1.0"?>

<para-list version='15' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Alternate'>
         Your space legs seem to give out when you head that way. Perhaps it is time to look for another way to get to where you want to go.
         </para>

         <para number='2' comment='No exit - Ship Overboard'>
         You tumble off the side of the ship and fall into the water. You quickly scramble back onboard and hope no one noticed that you are not paying attention to where you walk while on board the ship.
         </para>

         <para number='3' comment='No exit message - Normal'>
         You find yourself heading off into the heavy jungle foliage, and your progress is slowed so badly that you finally turn around and head back the way you came.
         </para>

         <para number='4' comment='No exit message - Ship wall'>
         You stumble into the bulkhead on the Ship. Embarrassed, you quickly glance about to make sure no one saw you.
         </para>

         <para number='5' comment='No Exit - Force Field'>
         You catch yourself, just before you walk into the force-shield protecting this place. You make a mental note to pay better attention to where you are going next time.
         </para>

         <para number='6' comment='No Exit - Walls'>
         Walking into walls again? You really should pay better attention to where you are walking, before the local law enforcement arrests you thinking that you are intoxicated in public.
         </para>

         <para number='7' comment='no exit - Tired'>
         You must really be tired if you think you can walk through walls now. It might be time for a nap, but it is definately time to pick another direction.
         </para>

         <para number='8' comment='No exit - In the water'>
         You slip and fall into the water. Quickly making you way back to dry land you realize you want to pay more attention to the directions you are traveling, or maybe at least bring a towel with you next time.
         </para>

         <para number='9' comment='No Exit - Masts'>
         You almost fall from the mast, but at the last second catch yourself with the safety lines. Whew, that was close. Perhaps it is time to try another direction, and this time select it with more care.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='ball'>

         <para number='1' comment='Get magic 8-ball - loc 1374'>
         You take the Magic 8 Ball in your hands, thinking about  what your future might hold, wondering if you are truly ready to receive an  answer to your questions. As you pick it up you hear a low buzzing sound and notice a new ball has materialized on the desk in the exact spot the one you are holding was in.
         </para>

         <para number='2' comment='Roomex'>
         %s has picked up the Magic 8 Ball. You hear a low buzzing sound and notice a new ball has materialized on the desk in the exact spot the previous one was in.
         </para>

         <para number='3' comment='Drop'>
         The ball falls a little way and then vanishes before it hits the ground; you wonder where it might have gone.
         </para>

         <para number='4' comment='Roomex'>
         %s has dropped a Magic 8-ball. You hold your breath, expecting it to smash on the floor, but it falls a little way and then vanishes.
         </para>

         <para number='5' comment='Shake - basic message'>
         You concentrate on your question and give the ball a vigorous shake. It says:
         </para>

         <para number='6' comment='Response 1 - player'>
         Signs point to yes.
         </para>

         <para number='7' comment='Response 2 - player'>
         Reply hazy, try again.
         </para>

         <para number='8' comment='Response 3 - player'>
         Without a doubt.
         </para>

         <para number='9' comment='Response 4 - player'>
         My sources say no.
         </para>

         <para number='10' comment='Response 5 - player'>
         As I see it, yes.
         </para>

         <para number='11' comment='Response 6 - player'>
         Concentrate and ask again.
         </para>

         <para number='12' comment='Response 7 - Very doubtful.'>
         Very doubtful.
         </para>

         <para number='13' comment='Response 8 - player'>
         It is certain.
         </para>

         <para number='14' comment='Response 9 - player'>
         Outlook good.
         </para>

         <para number='15' comment='Response 10 - player'>
         Don't count on it.
         </para>

         <para number='16' comment='First response for roomex'>
         Shaking the small ball, %s seems to be pondering the future.
         </para>

         <para number='17' comment='Second response for roomex'>
         Shaking the small ball, %s looks puzzled.
         </para>

         <para number='18' comment='Third response for roomex'>
         Shaking the small ball, %s appears lost in thought.
         </para>

      </section>

      <section name='lever'>

         <para number='1' comment='Pull lever - loc 2013'>
         A strange sensation overcomes you as you are quickly teleported to the surface of Garafena.
         </para>

         <para number='2' comment='Pull lever - loc 2013'>
         A strange sensation overcomes you as you are quickly teleported to the surface of Garafena.
         </para>

      </section>

      <section name='map'>

         <para number='1' comment='Look/read map'>
         You see a dot with the notation saying you are here. From there you can also see other locations of interest:
         </para>

         <para number='2'>
         Exchange: N, W
         </para>

         <para number='3'>
         Hospital: N, NE
         </para>

         <para number='4'>
         Shipyard: E
         </para>

         <para number='5'>
         Town: N, N, Pull Lever
         </para>

      </section>

   </category>

</para-list>

