<?xml version="1.0"?>

<para-list version='11' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message Booyan space'>
         You try to slip past the marked space lanes, but are cut off by a large cruiser before you get very far. The fact that it seems to have aimed all its weapons at you helps you to decide that maybe you want to stay in the marked space lanes, and pick a new direction to head.
         </para>

      </section>

   </category>

</para-list>


