<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='standard headbonk noexit'>
         You carelessly walk into a wall and bonk your head. A dull ringing which sounds like a skull (or equivalent) meeting solid hullmetal resounds in your brainpan.
         </para>

         <para number='2' comment='military noexit'>
         You go into motion and the two armored soldiers snap to and yell, "HALT CITIZEN!"  You make a quick about face.
         </para>

         <para number='3' comment='tavern noexit'>
         Your skull (or equivalent) makes a 'tink' sound as it meets the ferroglass. Rubbing your skull, people stop dancing and stare at you. You overhear someone cooing, "Oh, I feel so sorry for synthstim addicts--it's not their fault!"
         </para>

         <para number='4' comment='infirmary noexit'>
         You bump into a corpswoman who was in the process of spinning around and dashing off to an emergency. As a result, you end up on your duff, and she stops long enough to yell, "I told you we were busy! Get out of the way!" Dumbly, you stumble back into line.
         </para>

         <para number='5' comment='exchange noexit'>
         You bump into a trading terminal, which promptly lifts up on its chassis, revealing wheels, and rolls into you after spinning its tires on the smooth metal floor. "How does it feel, fleshbag?" the terminal asks you, before settling back into its spot on the wall.
         </para>

      </section>

   </category>

</para-list>

