<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Leaving known space.'>
         As you attempt to leave the mapped portion of this system, your computer bleets at you.  Your comm unit signals a tight beam message from the Northwind Orbital Defense Platform, "You are leaving the area that our sensors can track you--go no further or at least come back to the station and upgrade your ship to withstand the rigors of exploring unknown space."     Shrugging (or equivalent), you turn about.
         </para>

         <para number='2' comment='attempt land closed pad'>
         Your comm unit signals a tight beam message, "This is your last warning. We -will- shoot you down."  You cease your efforts of landing illegally and turn about.
         </para>

         <para number='3' comment='noexit dcking profile'>
         What are you trying to do, crash your ship into the defense platform?
         </para>

      </section>

   </category>

</para-list>

