<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='no exit message for hospital'>
         Feeling a little dizzy, you stumble into the trolley sending instruments clattering to the floor. The nurse rushes over, casting you an irritated look, before beginning to tidy the mess.
         </para>

         <para number='2' comment='no exit msg for surface locs'>
         Taking a wrong turn, you teeter precariously over the edge of the jetty. Unless you want to get very wet indeed you should be more careful.
         </para>

         <para number='3' comment='no exit message for exchange'>
         You attempt to barge your way through a throng of traders, "Hey! You can't come through here!".
         </para>

         <para number='4' comment='no exit msg for diving bell'>
         You stand up very suddenly and smack your head squarely on a brass gauge. Rubbing the sore spot, you vow to be more careful in such a confined space.
         </para>

         <para number='5' comment='no exit msg for bar #786'>
         As you attempt to stride purposefully through a solid wall, a vague recollection of why that isn't such a good idea drifts towards you.
         </para>

         <para number='6' comment='no exit msg for the park'>
         You decide to test several of Newton's Laws all at the same time by walking into the railings that surround the park. You come to the conclusion that being a physicist hurts.
         </para>

         <para number='7' comment='no exit msg for main road'>
         You dangerously step from the safety of the pedestrian zone and almost make an unwanted aquaintance with a vehicle travelling rather quickly. It is probably best not to walk in that direction.
         </para>

         <para number='8' comment='no exit msg for corridor'>
         Solidish walls prevent you from moving in that direction.
         </para>

         <para number='9' comment='no exit msg for shop'>
         The shopkeeper politely informs you that there is no exit through the back of the store and that he would prefer to keep the stockroom for employees only.
         </para>

         <para number='10' comment='no exit msg for checkpoint'>
         A checkpoint guard steps menacingly in front of you. You decide that perhaps it would be better to try a different direction.
         </para>

         <para number='11' comment='exit msg for the driveway'>
         The driveway is flanked by solid steel fences. You can't move in that direction.
         </para>

         <para number='12' comment='no exit msg for market'>
         You trip over a crate that someone has left strewn on the ground and go flying comically into a wheelbarrow full of cabbages. You jump to your feet and try to maintain some semblance of dignity by pretending that you meant to do it.
         </para>

      </section>

   </category>

</para-list>

