<?xml version="1.0"?>

<para-list version='7' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Zebrina'>
         The thick banana trees block your path forwards. Turning back the way you came, you slip comically on a banana skin much to the amusement of a nearby monkey. You quickly get to your feet and dust yourself down before walking away nonchalantly as if you meant to do that all along!
         </para>

      </section>

   </category>

</para-list>


