<?xml version="1.0"?>

<para-list version='13' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Edo'>
         As you move to head that way, you run smack into an unseen wall. Using a hand scanner, you notice an unusually high level of tachyons directly in front of you. It looks like this path is blocked for now.
         </para>

         <para number='2' comment='No exit message - Edo'>
         An eerie chill crawls over your body as you suddenly begin to think twice about going this way. Who knows what could be lurking just around the corner in this house.
         </para>

      </section>

   </category>

</para-list>


