<?xml version="1.0"?>

<para-list version='12' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Japan space'>
         As you attempt to enter that sector of space, warning klaxons begin to ring out inside of your cockpit warning you of a dangerous increase in the amount of Tachyons outside of your hull. To prevent a disaster, you return to your previous heading.
         </para>

      </section>

   </category>

</para-list>


