<?xml version="1.0"?>

<para-list version='2'>

   <category name='food'>

      <section name='bar'>

         <para number='1' comment='Buy food - Cafeteria/bar 468'>
         You join the line waiting to be served. When it's your turn, you realize you don't get any choice - there is only one thing on offer, and that is a collection of soy-protein cubes in different colors. The red ones taste like meat, the green ones like vegetables, and the yellow ones like potatoes. Alternating bites of all three makes a surprisingly enjoyable meal. There are also some brown cubes which you discover taste of chocolate.
         </para>

         <para number='2' comment='No money'>
         You join the line waiting to be served, but when it's your turn you realize you are out of groats, so you give up your place to the person waiting behind you.
         </para>

      </section>

      <section name='cafe'>

         <para number='1' comment='Buy food - Cube Cafe - 400'>
         A small waitdroid trundles up and puts a plate in front of you containing your meal: absolutely regular cubes of beef swimming in a rich, creamy sauce, with a mound of fried potatoes, also cut into perfect cubes. The precision of the shapes may lead you to expect that the flavor has been skimped on, but that's not the case - it's delicious!
         </para>

         <para number='2' comment='No money'>
         Since you are out of groats, you won't get served here.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='staff'>

         <para number='1' comment='Keep non-staff out'>
         Terra Space Mining Corporation will not allow unauthorized visitors at this time.
         </para>

      </section>

   </category>

</para-list>

