<?xml version="1.0"?>

<para-list version='13' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Bellum'>
         A large fin surfaces from the inviting waters. Maybe another direction would be advisable?
         </para>

         <para number='2' comment='No exit message - Bellum Lobby'>
         A woman in revealing light body armor quickly moves you away from that direction, and points you back in the direction of the lobby.
         </para>

         <para number='3' comment='Bellum Basic'>
         You feel just rediculous bumping into the wall. You turn around embarassed and proceed in the other direction.
         </para>

         <para number='4' comment='Bellum Musem'>
         Careful! You almost knock something over that looks quite valuable.
         </para>

         <para number='5' comment='Bellum Landscape'>
         You hit your head on a rock. Ouch! That must have hurt.
         </para>

         <para number='6' comment='No exit message - Bellum Office'>
         The door seems to be locked. You don't have a key.
         </para>

         <para number='7' comment='Club Cafe Tripudio'>
         You step on the toe of a beautiful lady in rhinestone strap stilettos, she bites her lip in pain. A few of her friends quickly scowl at you.
         </para>

         <para number='8' comment='Beach'>
         You stumble over some tourists laying out on a towel, in return you receive a nasty look. Watch where you're going!
         </para>

         <para number='9' comment='Bellum outside'>
         You're looking out over miles of gorgeous Bellum landscape, you turn the other direction before tears from the beauty come to your eyes.
         </para>

      </section>

   </category>

</para-list>

