<?xml version="1.0"?>

<para-list version='29' editor='standard'>

   <category name='flump'>

      <section name='chat'>

         <para number='1' comment='Flump response to hello'>
         Hi, you look like you are in need of some illicit pleasures, and I am just the man to fulfill your needs. I am talking cigars. The finest available in the universe. And its your lucky day, I have just had a fresh batch in, so what do you say, wanna try one? If you do then just 'BUY CIGAR'.
         </para>

         <para number='2' comment='response to who'>
         I am Flump, or the family Flump. We stretch back to the dawn of civilisation. We get things, you want them we get them, its always been that way. So if you want something, you come and see Flump, it does not matter what it is or where it comed from, legal or not (though we don't tend to do too much legal stuuf you know), you come and see me, ok?
         </para>

         <para number='3' comment='response to where/bar'>
         This is the Scene of the Crime, do you like it. This is my place, bought and paid for, with blood, sweat and tears. Though none of it was mine if you know what I mean ha ha ha. Have a drink, eat a meal, the best wares in the system. Or maybe I could entice you into buying one of my cigars, I know smoking has been outlawed, but hey, what they don't find out about makes it ok. Ok?
         </para>

         <para number='4' comment='response to wisp'>
         What have you heard?, who have you been talking to, its lies whatever it is. All I will say is that Wisp used to be the principle planet in the Cloud system. It got over polluted centuries ago, uninhabitable, so it was abandoned. That fool Cloudbase thinks that by recovering the Idol of Cloudaria that he can repopulate it, the quest is a fools errand and only a fool would accept the challenge!!
         </para>

         <para number='5' comment='response to Cumulus'>
         Cumulus, nah I don't like it there, too much pomp and ceremony for my liking. Its the principle planet in the Cloud system now, since our people evacuated Wisp. But you can keep it, I prefer it right here on Cloudbase. Pah!! I hate that name, that egomaniac named a space station after himself!!!
         </para>

         <para number='6' comment='response to Cloudbase'>
         Now don't get me started there, he is such a pompous egomaniac, that he named this space station after himself. Thats the only thing I dont like about it though, this is my home, its where I conduct my business from, hey did I mention that I have a crop of fresh cigars just in? Can do you a deal if you want one, you won't find better or cheaper anywhere in the universe.
         </para>

         <para number='7' comment='response to nimbus'>
         Nimbus isn't everyones cup of tea, its the biological planet here in the Cloud system, and its a pretty earthy place filled with earthy characters. Not a place for the meek or mild. But hey, if you go there, just mention my name and you will be just fine.
         </para>

         <para number='8' comment='response to Cloudarian'>
         Us Cloudarians are probably the oldest race in the universe, the cleverest and the wisest too. But there are always exceptions to the rule, like that Cloudbase, the self styled leader of our people, there isnt a soul who has a good word to say about him and rightly so. My family should have been given the throne to rule over Cloudaria, not him, the weasel!!
         </para>

         <para number='9' comment='response to cloud'>
         You know the Cloud system didnt get its name from the dense cloud that exists in Cloud Space. It used to be clear, mind you, I quite like it, it makes my life alot easier not being seen flitting around the place, if you know what I mean? he he he. No, the Cloud is the residue of the pollution that escaped the atmosphere from Wisp, thats the reason the planet had to be abandoned you know.
         </para>

         <para number='10' comment='challenge type response'>
         All this talk about recovering the lost idol, it will never happen, I mean, it has been lost for such a long time, and besides. The task is just too hard, it is fraught with dangers and no real hope of success, only a fool would try and take it on, and you don't look like a fool to me. But if you are serious, can I have first option on that shiny new ship of yours?
         </para>

         <para number='11' comment='response to cigar'>
         Of course, you look like someone who desires and enjoys the finer things in life, and I have the best cigars that money can buy. Who cares if they have been banned, we all still need our little pleasures in life, so come on, do you want to buy one?
         </para>

         <para number='12' comment='Buy cigar response'>
         You take the cigar and quickly conceal it, in case anyone sees, as flump closes his coat and brushes himself down
         </para>

         <para number='13' comment='response to innapropraite actio'>
         Flump sidesteps your clumsy advance, he clearly thinks you are yet another predator trying to steal his wares, in a deft movement he punches you square on the jaw, you see stars for a moment before you regain your senses. Better rethink your approach, that blow on the chin just took 10 stamina points away!!!!
         </para>

         <para number='14' comment='no match to any'>
         Now I am sure that from the planet that you are from, what you just said to me made perfect sense, however, I did not understand what it was you were trying to convey, perhaps you might like to try a different approach?
         </para>

         <para number='15' comment='response to hello'>
         Ah, so its you again %s I heard you took up that silly quest to find the sacred idol, I told you that you would be wasting your time, its far too hard, and just because I mentioned death, it looks like you have chickened out of it. Well I don't blame you, I am not sure about that Cloudbase though, I don't think he will be very understanding, but he should have known it was impossible.
         </para>

         <para number='16' comment='response to flump'>
         Ah, so its you again %s I heard you took up that silly quest to find the sacred idol, I told you that you would be wasting your time, its far too hard, and just because I mentioned death, it looks like you have chickened out of it. Well I don't blame you, I am not sure about that Cloudbase though, I don't think he will be very understanding, but he should have known it was impossible.
         </para>

         <para number='17' comment='response to where'>
         look %s it seems I may just have misjudged you a little, it seems that you are far more resourceful than meets the eye. Its not my fault, yes my family have always been around, dabbling in this and dabbling in that, its what we do, but if they had any involvement in the death of that poor man, or the theft of the idol from the museum, I really cannot tell you because I really do not know, thats the honest truth!!
         </para>

         <para number='18' comment='response to wisp'>
         So tell me %s I have never been to wisp, the atmosphere is clearly safe or they would'nt have let you down there in the first place, do you think it is habitable though? Come on, let me in on the inside track, and I will cut you in a piece of any action down there!
         </para>

         <para number='19' comment='response to cumulus'>
         Well it seems that you may have changed the course of history, now that you have been down onto Wisp, the days are numbered for Cumulus as the principal planet in the Cloud system, and Wisp will take its rightful place in the system.
         </para>

         <para number='20' comment='response to cloudbase'>
         Well, even if they do re-open Wisp %s I am sure you will agree with me, nothing beats living here on Cloudbase, its so clean and fresh, this is the place for me.
         </para>

         <para number='21' comment='response to nimbus'>
         You can talk about Nimnus all you like, it won't change the place.
         </para>

         <para number='22' comment='task/challenge etc'>
         I told you that you would be wasting your time %s, its far too hard, and just because I mentioned death, it looks like you have chickened out of it. Well I don't blame you, I am not sure about that Cloudbase though, I don't think he will be very understanding, but he should have known it was impossible.
         </para>

         <para number='23' comment='response to idol'>
         Look %s its pretty clear you are more than a match for me if you really wanted to go for it, I can't hide the truth any longer, that damned Idol is of no use anyway, its too well known, can't sell it, can'y show it!! So I will tell you where it is. You can find it at ################################################################################################################################################################
         </para>

         <para number='24' comment='response to curator'>
         Look the Curator was nothing to do with me, it was hundreds of years ago, I don't know who bumped him off, you can't pin it on me!!
         </para>

         <para number='25' comment='response to musueum'>
         All I can tell you is that one of my ancestors saw an opportunity when they were moving all the exhibits from the Musuem on Wisp for storage on Cumulus. He could'nt have been very bright though, he could have taken anything and the family could have profited. But he took the Idol, the one thing that could never see the light of day or be sold on for profit.
         </para>

         <para number='26' comment='response to hello/flump'>
         Ah, its you again %s congratulations on recovering the idol, you are certainly head and shoulders above the normal populace. Well done again. Oh, could I interest you in a cigar, fresh shipment arrived this morning!
         </para>

         <para number='27' comment='multi word response'>
         Look %s you can be proud of what you have done, but don't go overboard seeking praise, its old news now. But I do have some new news!! Fresh shipment of cigars, arrived this morning, would you like to buy one?
         </para>

         <para number='28' comment='response idol/curator/museum'>
         I hear they are going to reopen the musuem now that the idol has been recovered. So they will be looking for a new Curator, cigars don't seem to be as popular as they used to be anymore, I may just apply for the position. Still, while you are here, would you like to buy a cigar?
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Cloud'>
         I would'nt do that if I were you
         </para>

         <para number='2' comment='No exit message - Cloud'>
         Do you think that is wise?
         </para>

         <para number='3' comment='No exit message - Cloud'>
         Hmmmm thats not too good an idea, better rethink that one!!!!
         </para>

         <para number='4' comment='No exit message - Cloud'>
         You peer through the mist, then wisely decide against that course of action
         </para>

         <para number='5' comment='No exit message - Cloud'>
         You feel a little intoxicated from the fumes of the local brew lingering in the air, as you realise that there is no way you could possibly head in that direction, you compose yourself momentarilly and nervously glance round the room, trying to detect if anyone actually saw you trying to leave by attempting to bludgeon your way through the wall
         </para>

         <para number='6' comment='No exit Message - Cloud'>
         You decide against gatecrashing the Parliament session as it is in full flow, whilst the concept is amusing to you, you are not so confident the locals will see it that way
         </para>

         <para number='7' comment='No exit Message - Cloud'>
         The Hospital would be the ideal place to injure yourself if that was actually your intention, you think twice and decide (sensibly) to use a proper exit
         </para>

         <para number='8' comment='No exit message - Cloud'>
         After careful consideration, you decide the planetary exhibits are all that should be viewed here, not you making a fool of yourself !!!
         </para>

         <para number='9' comment='no exit message - Cloud'>
         Interesting concept !! A prison break from a prison that you are not actually a captive in, you think it best to use an extablished exit rather than to dig your way out, risking capture and actual imprisonment, besides, you forgot your pick and shovel on board your shuttle.
         </para>

         <para number='10' comment='No exit message - Cloud'>
         You think it wise to not disturb the files and fine decoration of the offices of the rulers of Cumulus, you realise that you should not even be here in the first place as you look to see the nearest exit.
         </para>

         <para number='11' comment='No exit message - Cloud'>
         You bounce of the protective glass case that surrounds the Royal Crown and Sceptre, a red light flashes intermiitantly as you here the recorded message advising you to step away from the display. Phew !!! better be more careful, next time you may not be so lucky.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='cigar'>

         <para number='1' comment='Eat Cigar commentary'>
         You touch the self ignition tab on your cigar and place it to your lips, inhaling the smoke as you do. Clearly you have not heeded the Surgeon Generals warning about the negative health effects of smoking. You start to feel queezy, the room starts to spin, all noise around you seems amplified and the lights much brighter. You start to sweat and you feel your heart pumping hard as you slowly slip from consciousness........
         </para>

         <para number='2' comment='Eat Cigar commentary'>
         You awake to find yourself in the Infirmary, that was quite a turn you had, you pick yourself up and feel a little queasy. It seems that cigar was just no good for you at all, in fact, it managed to wipe 20 points off of your stamina!! Who said the Surgeon General was making it up when he claimed that smoking was bad for your health!!
         </para>

         <para number='4' comment='response to wisp'>
         Who told you about Wisp? What do you want to know? Well, all I will tell you is that Wisp used to be the centre of my families operations back in the time when it was the priciple planet in the Cloud system. It was abandoned many years ago, became uninhabitable you know. Anything else you hear about my family and Wisp is pure conjecture, fantasy, no substance in it at all.
         </para>

         <para number='5' comment='response to Cumulus'>
         Cumulus, huh. I don't like it there, too much pomp and ceremony. And its where that pompous Cloudbase lives. The self styled leader of the Cloudarians, I don't think so!! Us Flumps have more right to the throne, but somehow, he managed to get his hands on it. I tell you, that planet just is'nt big enough for his ego, but one day ......................
         </para>

         <para number='6' comment='response to Cloudbase'>
         That arrogant ego maniac, have no time for him ......... oh, you mean the space station we are on right now. A fine piece of engineering, did you know my family helped to finance it!!! Its our base of operations now, you will always find me here in the bar, just pop in and I can sort you with anything you might need.
         </para>

         <para number='7' comment='rsponse to Nimbus'>
         I like it on Nimbus, its not everyones cup of tea though. Its the biological planet here in the Cloud system. You need to be an earthy type to live down there. So if you are a little feeble or weak, they will take advantage of you, but hey, just mention my name and they will be as nice as apple pie!!
         </para>

         <para number='8' comment='response to cloudarian'>
         The Cloudarians go back to the dawn of civilisation you know. The premier race in the universe, not that you would think so by looking at that waste of space Cloudbase. Us Flumps are what epitomises the greatness of the race, intellectual, strong, resourceful and dammed attractive too, but you could see that the moment you layed eyes on me.
         </para>

         <para number='9' comment='response to cloud'>
         Huh, this used to be such a clear area of space, its just a coincidence that the Cloud system is shrouded in Cloud. But that suits my operation down to the ground. Its cloudy because of the over industrialisation on Wisp, it was abandoned many centuries ago because it became uninhabitable. The pollution from there has leaked out into space and thats why it is so Cloudy.
         </para>

      </section>

   </category>

</para-list>

