<?xml version="1.0"?>

<para-list version='18' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='2' comment='No exit message - Cloud'>
         Do you think that is wise?
         </para>

         <para number='3' comment='No exit message - Cloud'>
         Hmmmm thats not too good an idea, better rethink that one!!!!
         </para>

         <para number='4' comment='No exit message - Cloud'>
         You peer through the mist, then wisely decide against that course of action
         </para>

         <para number='5' comment='No exit message - Cloud'>
         You feel a little intoxicated from the fumes of the local brew lingering in the air, as you realise that there is no way you could possibly head in that direction, you compose yourself momentarilly and nervously glance round the room, trying to detect if anyone actually saw you trying to leave by attempting to bludgeon your way through the wall
         </para>

         <para number='6' comment='No exit Message - Cloud'>
         You decide against gatecrashing the Parliament session as it is in full flow, whilst the concept is amusing to you, you are not so confident the locals will see it that way
         </para>

         <para number='7' comment='No Exit Message - Cloud'>
         The Hospital would be the ideal place to injure yourself if that was actually your intention, you think twice and decide (sensibly) to use a proper exit
         </para>

         <para number='8' comment='No exit message - Cloud'>
         After careful consideration, you decide the planetary exhibits are all that should be viewed here, not you making a fool of yourself !!!
         </para>

         <para number='9' comment='no exit message - Cloud'>
         Interesting concept !! A prison break from a prison that you are not actually a captive in, you think it best to use an extablished exit rather than to dig your way out, risking capture and actual imprisonment, besides, you forgot your pick and shovel on board your shuttle.
         </para>

         <para number='10' comment='No exit message - Cloud'>
         You think it wise to not disturb the files and fine decoration of the offices of the rulers of Cumulus, you realise that you should not even be here in the first place as you look to see the nearest exit.
         </para>

         <para number='11' comment='No exit message - Cloud'>
         You bounce of the protective glass case that surrounds the Royal Crown and Sceptre, a red light flashes intermiitantly as you here the recorded message advising you to step away from the display. Phew !!! better be more careful, next time you may not be so lucky.
         </para>

         <para number='12' comment='No Exit Message'>
         You seriously ponder the thought, but checking out the cermonial Guards and the Laser beams decide against trying to enter any unauthorised area, for fear of your own wellbeing!!!
         </para>

      </section>

   </category>

</para-list>

