<?xml version="1.0"?>

<para-list version='19' editor='standard'>

   <category name='moves'>

      <section name='Welcome'>

         <para number='5' comment='Welcome player by name'>
         Welcome to Cloud Space %s, we hope you find you visit fruitful
         </para>

      </section>

      <section name='keepout'>

         <para number='4' comment='no entry to secret Cloud Space'>
         Your comms unit relays a message informing you that you are not permitted to enter this area of Cloud Space and you find yourself back where you started from.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='No Exit Message'>
         You head into that area of misty space, but somehow find yourself back in your original location.
         </para>

         <para number='2' comment='No exit message - Cloud space'>
         The cold, hard vacuum of space lies that way, and there's nothing for you there.
         </para>

         <para number='3' comment='No Exit Message'>
         Warning lights flash across your console as an alarm sounds, a message is received on your comms unit advising you that you are not eligible to enter this area of Cloud Space and that you have been escorted back to your original location
         </para>

      </section>

   </category>

   <category name='noexit'>

      <section name='No exit message'>

         <para number='1'>
         Warning buzzers sound from your console as an incoming message advises you that you are not eligible to enter this area of Cloud Space
         </para>

         <para number='2'>
         Warning buzzers sound from your console as an incoming message advises you that you are not eligible to enter this area of Cloud Space
         </para>

         <para number='3'>
         Warning buzzers sound from your console as an incoming message advises you that you are not eligible to enter this area of Cloud Space
         </para>

      </section>

   </category>

</para-list>

