<?xml version="1.0"?>

<para-list version='37' editor='standard'>

   <category name='dino'>

      <section name='chat'>

         <para number='1' comment='Hello'>
         Hey, you know that chick who used to dance alot, everynight she'd be there shaking what she'd, amn when I tell you she was cool she was red hot, I mean she was steaming. Oh, hello, its been so long since anyone has been here, how did you get here, are you ok? They told me someone would come one day, but I really did'nt expect it to be this long!!
         </para>

         <para number='2' comment='who/dino'>
         Ah, I am a bot they left here many many years ago when they abandoned Wisp, you know it used to be the principal planet in the Cloud system. The curator told me that if he did not return word to me that he may have come to an untimely end, but he hoped someone would eventually come, I guess you must be that person, I was left behind to offer any assistance that you might need, so how can I be of help to you?
         </para>

         <para number='3' comment='where/bar'>
         Ah, this is my joint, you know anybody who was anybody used to be in here when the planet was alive and kicking. You know this time over at Johhny's place, well this chick got up and she slapped Johnny's face, man we just fell about the place, but if that chick don't wanna know then forget her. Errr, sorry, I digress, it has been such a long time. This is where the people of Wisp would come to socialise, eat, drink and be merry.
         </para>

         <para number='4' comment='wisp'>
         Aaah yes Wisp, in its heyday, this was the principal planet in the Cloud system. But due to overpopulation and irresponsible industry practices, pollution built up to the extent that it was a very hazardous place to be. So they all went to the other planets, there was talk of building an orbital station around Cumulus too. They left me here to assist anyone returning to reopen the planet.
         </para>

         <para number='5' comment='cumulus'>
         Cumulus was always the second planet of the system, but they left here many years ago and it is now the epicentre of the Cloud system, they even took the palace, my, what an engineering feat that was I can tell you.
         </para>

         <para number='6' comment='cloudbase'>
         Cloudbase is a character from Cloudarian legend, one day he shall come forth and free Wisp so that it can be recolonised and take its rightful place as the principal world in the Cloud system. There was talk of building an orbital station around Cumulus, many talked of naming it after this fictional character, but I dont know if that ever really happened.
         </para>

         <para number='7' comment='nimbus'>
         Yes Nimbus was never really a very nice place, its the Biological planet in the Cloud system, not many people live there as it is pretty unhospitable, but it remains an important sphere in the system.
         </para>

         <para number='8' comment='cloud'>
         Well what can I say about the Cloud system that isnt already known, its one of the oldest systems in the universe, steeped in tradition and also one of the most technologically advanced. It used to be amongst the wealthiest too, but its been many years since I have either left this planet or had contact with anyone, so I don't really know anymore, though I am sure the Cloudarians have done all to maintain that status.
         </para>

         <para number='9' comment='cloudarian'>
         The Cloudarians are a mighty race, amonst the forefathers of the universe, peaceful, friendly and great traders too. They are also known for being the most attractive also!!
         </para>

         <para number='10' comment='museum'>
         The museum used to hold many thousands of artifacts dating back to the dawn of time, most of them were priceless. But they all got moved when Wisp was evacuated. My best friend is the curator, but I fear as I have heard no word from him, that his worst fears were realised. I hope you can find out what happened to him for me.
         </para>

         <para number='11' comment='curator'>
         The curator was a close and personal friend of mine, he told me that should anything happen to him, that he would leave some important information somewhere, but he really was'nt making very much sense at all, he seemed to be under an awful lot of pressure the last few days before the evacuation,  you should check out his office and sleeping quarters, thats where I think he might have left it
         </para>

         <para number='12' comment='reactor'>
         Well, I don't know much about reactors, but I do know the one we have here on Wisp is very old, just before the evacuation they were talking about replacing it as they could not run it at 100% due to its age.
         </para>

         <para number='13' comment='challenge/puzzle/task/mission'>
         My friend the curator was'nt making very much sense on his last few days here on Wisp. He told me something had been stolen and that he had a strong lead. He also said he was worried they might get him, so he left some important information in his diary, thats all I know, sorry I can't help you any more than that.
         </para>

         <para number='14' comment='red door pass'>
         Yes, the Red Door Pass, suprisingly enough that is used to open the Red Door!!    The colours may have faded over the passage of time, I do know that this pass opens the door to the curators office. To use it swipe the door pass in the card reader outside his office.
         </para>

         <para number='15' comment='blue door pass'>
         Oh goodness me!!  Such a long time, and there were so many different door pass colours, they were used mainly in the accommodation area, but some were used in this complex, but I am sorry, I really dont know what that one is for.
         </para>

         <para number='16' comment='green door pass'>
         I don't know what they're doing but they laugh alot behind the green door!!    Hmmm, sorry, not sure which door that one opens, you will just have to try it and see.
         </para>

         <para number='17' comment='yellow door pass'>
         The Yellow Door Pass.    Nope, you got me, not a clue!!
         </para>

         <para number='18' comment='door pass'>
         Yes, the planet used to have door passes to gain access to various areas, they were mainly used in the accommodation block, but important areas had them too.
         </para>

         <para number='19' comment='food'>
         Yes, we serve food, of course we do!!! This is my bar and grill, though our range is pretty limited these days, no supplies you see, and to be honest!! the stock is a little old!!! So you pays your money you takes your chance.
         </para>

         <para number='20' comment='drink'>
         Oh yes, we have that aplenty here, most popular joing on the planet, well it was when there were people on it. The ale matures nicely over the years so why don't you try one, I cleaned the pipes out this morning and we can supply all you need!
         </para>

         <para number='21' comment='nomatch'>
         Now, I am sure that where you come from that makes perfect sense, but you might have to run it by me again in a different way if you want me to understand and reply.
         </para>

      </section>

   </category>

   <category name='locker'>

      <section name='closed'>

         <para number='1' comment='Locker is closed'>
         One locker stands out from the rest, the door is closed but does not appear to be locked
         </para>

      </section>

      <section name='open'>

         <para number='1' comment='Locker is open'>
         One locker stands out from the rest, the door is open.
         </para>

      </section>

   </category>

   <category name='message'>

      <section name='blue'>

         <para number='1' comment='no blue door pass message'>
         You fumble through your pockets trying to find the blue door pass, but alas, it is no where to be found.
         </para>

      </section>

      <section name='green'>

         <para number='1' comment='no green door pass message'>
         You fumble through your pockets trying to find the green door pass, but alas, it is no where to be found.
         </para>

      </section>

      <section name='letter'>

         <para number='1'>
         The letter reads;    You don't know me, but I am a concerned citizen who wants to remain anonymous.    The family of Flump has stolen the sacred idol, it grieves me to know that this precious heirloom has fallen into such hands, I know you will do all that you can to recover this treasure and my conscience has been cleared knowing that I have passed this information to you.
         </para>

         <para number='2'>
         Errrrr. what letter would that be?
         </para>

      </section>

      <section name='red'>

         <para number='1' comment='no red door pass message'>
         You fumble through your pockets trying to find the red door pass, but alas, it is no where to be found.
         </para>

      </section>

      <section name='yellow'>

         <para number='1' comment='no yellow door pass message'>
         You fumble through your pockets trying to find the yellow door pass, but alas, it is no where to be found.
         </para>

      </section>

   </category>

   <category name='molly'>

      <section name='slap'>

         <para number='1' comment='Molly slaps - loc 401 -'>
         Molly quickly steps back, draws her hand back and slaps you hard across the face, you pay to touch or keep your hands to yourself she says, but I warn you I am not cheap! You dont't look the sort that can afford my services anyway, so perhaps you might want to buy some information instead, I have some very rich high ranking clients who can be a little indiscrete with their pillow talk.
         </para>

         <para number='2' comment='Mollys offers services'>
         I can offer information for 10 groats or we can have some fun if you want to part with 100 groats so whats it to be? FUN or INFO?
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit Message - Cloud'>
         You ponder the sensibility of trying to head off in that direction, but after consideration decide that you time would be better spent by heading in a direction that does not involve the use of demolition equipment.
         </para>

         <para number='2' comment='No exit Msg - Cloud - loc 583'>
         Viable exits are to the North and South, there is a locked dorr to the East beyond which is the Maintenance Shed. If you have a key then you can unlock the door to gain entry.
         </para>

         <para number='3' comment='No exit Message - Cloud'>
         Hmmmm thats not too good an idea, better rethink that one!!!!
         </para>

         <para number='4' comment='No exit Message - Cloud'>
         You peer through the mist, then wisely decide against that course of action
         </para>

         <para number='5' comment='No exit Message - Cloud'>
         You feel a little intoxicated from the fumes of the local brew lingering in the air, as you realise that there is no way you could possibly head in that direction, you compose yourself momentarilly and nervously glance round the room, trying to detect if anyone actually saw you trying to leave by attempting to bludgeon your way through the wall
         </para>

         <para number='6' comment='No exit Message - Cloud'>
         You decide against gatecrashing the Parliament session as it is in full flow, whilst the concept is amusing to you, you are not so confident the locals will see it that way
         </para>

         <para number='7' comment='No exit Message - Cloud'>
         The Hospital would be the ideal place to injure yourself if that was actually your intention, you think twice and decide (sensibly) to use a proper exit
         </para>

         <para number='8' comment='No exit Message - Cloud'>
         After careful consideration, you decide the planetary exhibits are all that should be viewed here, not you making a fool of yourself !!!
         </para>

         <para number='9' comment='No exit Message - Cloud'>
         Interesting concept !! A prison break from a prison that you are not actually a captive in, you think it best to use an extablished exit rather than to dig your way out, risking capture and actual imprisonment, besides, you forgot your pick and shovel on board your shuttle.
         </para>

         <para number='10' comment='No exit Message - Cloud'>
         You think it wise to not disturb the files and fine decoration of the offices of the rulers of Cumulus, you realise that you should not even be here in the first place as you look to see the nearest exit.
         </para>

         <para number='11' comment='No exit Message - Cloud'>
         You bounce of the protective glass case that surrounds the Royal Crown and Sceptre, a red light flashes intermiitantly as you here the recorded message advising you to step away from the display. Phew !!! better be more careful, next time you may not be so lucky.
         </para>

         <para number='12' comment='No exit Message - Cloud'>
         You seriously ponder the thought, but checking out the cermonial Guards and the Laser beams decide against trying to enter any unauthorised area, for fear of your own wellbeing!!!
         </para>

      </section>

      <section name='notake'>

         <para number='1' comment='No take Message'>
         The need for wanton violence or theft is not called for here!!
         </para>

      </section>

   </category>

   <category name='read'>

      <section name='sign'>

         <para number='1' comment='Sign - location 647'>
         Notice to all Residents of Cloud, the planetwide evacuation procedure has been posted to your personal data readers, this activity will cease on stardate 000912:247, after this date there will no further personnel transportation.
         </para>

      </section>

   </category>

   <category name='suit'>

      <section name='notininv'>

         <para number='1' comment='Dont have protection suit'>
         You dont have the Protection Suit to wear!!
         </para>

         <para number='2' comment='Not wearing protection suit'>
         You are not wearing the Protection Suit !!
         </para>

      </section>

   </category>

</para-list>

