# Makefile for the fed2 dresden system

DEST=/var/opt/fed2/maps/dresden
include ../data.mk
all:$(DEST)/slaughterhouse5.* $(DEST)/space.*  $(DEST)/tralfamadore.*  $(DEST)/pilgrim.*  $(DEST)/wildhack.* 