<?xml version="1.0"?>

<para-list version='10' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for Elemecca sp'>
         The cold, hard vacuum of space lies that way, and sensors detect that there is nothing that direction and stop you from moving your ship into uncharted territory.
         </para>

         <para number='2' comment='No exit for Inluvines'>
         Solid dirt walls prevent you from moving that dirrection.
         </para>

         <para number='3' comment='No exit for Argentia'>
         Slick ice walls prevent you from moving that dirrection.
         </para>

      </section>

   </category>

</para-list>

