<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Shuttle Pad'>
         A tanned beauty smiles and points you in a different direction.
         </para>

         <para number='2' comment='Exchange'>
         A waitress rushes over to you and prevents you from stepping through the wall.
         </para>

         <para number='3' comment='Hospital'>
         A nurse checks your forehead with her hand to make sure you havn't been in the sun too long.
         </para>

         <para number='4' comment='Supply Hut'>
         The store clerk laughs at your antics and slides a chair toward you.
         </para>

         <para number='5' comment='Capital'>
         A low growl lets you know you're about to step on something bad. Very very bad.
         </para>

         <para number='6' comment='Black Sand Beach'>
         A stone outcropping prevents you from moving that direction.
         </para>

         <para number='7' comment='Canoe Ride (to island)'>
         Be careful not to fall out of the canoe, the planet is peacefull by nature but there's no telling what might be down there.
         </para>

         <para number='8' comment='Swimming'>
         You struggle to keep your head above the water as you grow tired.
         </para>

         <para number='9' comment='Canoe Ride (from island)'>
         You sit back and enjoy the view as you watch the oarsmen make their way west to the Islet.
         </para>

         <para number='10' comment='Beaches'>
         The ocean laps at the sand, rushing in and back out again only to be met by another coming in.
         </para>

         <para number='11' comment='Breezes Cantina'>
         A low open wall prevents you from moving in that direction.
         </para>

         <para number='12' comment='Temp dead end'>
         This is as far as you can go at this time, please visit again. In time it will be complete.
         </para>

      </section>

   </category>

</para-list>

