<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Link Inbound'>
         You rebound from some unseen force as you attempt to move out of the guided path.
         </para>

         <para number='2' comment='Glide Path'>
         A fighter slips between you and your intended path as it guides you to the docking platform.
         </para>

         <para number='3' comment='Launch path'>
         A fighter slips between you and your intended path as it guides you to the Interstellar Link.
         </para>

         <para number='4' comment='Docking Platform'>
         Stepping too close to the edge you nearly fall over as a dock hand snatches you back just in time.
         </para>

      </section>

   </category>

</para-list>

