<?xml version="1.0"?>

<para-list version='7' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Augusta'>
         You are stepping into the Savannah River.  There has been a mercury spill and you can not go there.  Go back now or you will be contaminated!!!
         </para>

      </section>

   </category>

</para-list>


