<?xml version="1.0"?>

<para-list version='9' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Augusta'>
         You are stepping into the Savannah River.  There has been a mercury spill and you can not go there.  Go back now or you will be contaminated!!!
         </para>

         <para number='2'>
         you bump into the wall before you realize you can't go that way.
         </para>

      </section>

   </category>

</para-list>

