<?xml version="1.0"?>

<para-list version='7' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         The high walls of ice make going in that direction unwise.
         </para>

         <para number='2'>
         You bounce off the walls of the clinic and decide not to try moving in that direction again.
         </para>

         <para number='3'>
         Force fields prevent you from moving in that direction, but allow you to see all the activity happening in the shipyard.
         </para>

         <para number='4'>
         The waitdroids keep you from walking into the wall.
         </para>

         <para number='5'>
         You are escorted by a waitdroid back to the fireplace.
         </para>

         <para number='6'>
         A waitdroid escorts you away from the window before you break it and fall through.
         </para>

         <para number='7'>
         You slip on the ice and figure you ought to try another direction.
         </para>

         <para number='8'>
         Don't stray from the path -- there are vast crevasses in this direction!
         </para>

         <para number='9'>
         You are advised to stay to the marked path for safety!
         </para>

         <para number='10'>
         Going in that direction wouldn't be wise...
         </para>

      </section>

   </category>

</para-list>

