<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Spaceway'>
         You bonk into the substantial side of the spaceway and knock your noggin.
         </para>

         <para number='2' comment='Dome'>
         The management frowns upon visitors body slamming the side of the dome.
         </para>

         <para number='3' comment='Airlock'>
         You're in an airlock and will have to wait for the panel to open.
         </para>

         <para number='4' comment='Airlock'>
         You're in an security lock and will have to wait for the blast door to open.
         </para>

         <para number='5' comment='General'>
         There is no apparent exit in that direction.
         </para>

         <para number='6' comment='Garbage'>
         The maintenance port in that direction is locked. The management doesn't allow visitors to swim in the garbage pile - it upsets the dianoga. 
         </para>

      </section>

   </category>

</para-list>

