<?xml version="1.0"?>

<para-list version='18' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Dottle LP'>
         The shallow but steep walls of the crater prevent you from going in that direction.
         </para>

         <para number='2' comment='general'>
         You can't go that way.
         </para>

         <para number='3' comment='oblivion'>
         The Surgeon General of the Galactic Health Administration has mildly suggested that wandering through mountains of extremely hazardous nicotine waste could possibly be harmful to one's health. It is recommended that tourists remain on the path.
         </para>

      </section>

   </category>

</para-list>


