<?xml version="1.0"?>

<para-list version='13' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Dross LP'>
         The shallow but steep walls of the crater prevent you from going in that direction.
         </para>

         <para number='2' comment='Dross Ex.'>
         The server in the silly shirt snickers as you bang you head into the wall.
         </para>

         <para number='3' comment='general'>
         You can't go that way.
         </para>

         <para number='4' comment='on lorry'>
         you are only along for the ride, but you can urge the lorry to move faster towards the northwest
         </para>

         <para number='5' comment='junkyard dog'>
         that path is blocked by an extremely large and loud dog.
         </para>

         <para number='6' comment='guard'>
         the security guard suggests, rather rudely this time, to exit the building to the southeast.
         </para>

      </section>

   </category>

</para-list>

