<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Landing Pad'>
         You aimlessly wander about the vast expanse of the bailey, eventually returning back to where you started.
         </para>

         <para number='2' comment='general'>
         There doesn't appear to be an exit in that direction.
         </para>

      </section>

   </category>

</para-list>

