<?xml version="1.0"?>

<para-list version='16' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit - Rubble space 1'>
         The fast moving asteroids block that direction and you think it would be safer moving in.
         </para>

         <para number='2' comment='No exit - Rubble Space 2'>
         The fast moving asteroids block that direction and you think it would be safer moving out.
         </para>

         <para number='3' comment='No exit - Rubble Space 3'>
         The fast moving asteroids and other spectacularly soaring space junk block that direction.
         </para>

      </section>

   </category>

</para-list>

