<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='launch pad'>
         You try stepping into an undesignated area, but a man wearing the Avridonian pad worker insignia halts you.
         </para>

         <para number='2' comment='reception office 2014'>
         The woman looks up from her desk and says loudly, "Uh where are you going?"  Reaching towards the telephone, presumably to call security, you stop and return to the front of the lobby.
         </para>

         <para number='3' comment='Generic'>
         You begin moving but a large wall with no exit blocks your path.
         </para>

      </section>

   </category>

</para-list>

