<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Exit'>
         You walk smack dab into the side of a hill.  While attempting to hide your embarassment a villager strolls up to you. "Do you want to see the doctor?"   Having seen the hut on the way to exchange you politly refuse.  Good choice.
         </para>

         <para number='2' comment='Inside'>
         Your smack dab into a wall.  Clumbsy aren't we?  No need to worry, there is medical assitance east of the landing pad.  If you dare.
         </para>

      </section>

   </category>

</para-list>

