<?xml version="1.0"?>

<para-list version='5' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message'>
         The Dryland System Authority has informed you that you are not allowed to move in that direction.   In fact, you notice a fine at the bottom of a paper note for a 1000ig fine. (Cost of paper it says)
         </para>

      </section>

   </category>

</para-list>

