<?xml version="1.0"?>

<para-list version='9' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message'>
         You see a Navy Dryland Ship built on Lighthouse drift into view.   A standard broadcast informs you not to move in that direction.   On your ship screen comes a notice that you have been fined 1500ig. (Cost of maintaing the Navy)
         </para>

      </section>

   </category>

</para-list>

