<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         You slip on the ice and bump your head realizing you can't go that way.
         </para>

         <para number='2'>
         You slip on the ice knowing you can't go that way
         </para>

      </section>

   </category>

</para-list>

