<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         You slip on the ice before you realize you can't go that way
         </para>

         <para number='2'>
         You bounce off a frozen astroid realizing you can't go that way
         </para>

      </section>

   </category>

</para-list>

