# Makefile for the fed2 fringe system

DEST=/var/opt/fed2/maps/fringe

all:$(DEST)/destinystation.* $(DEST)/planetalpha.* $(DEST)/solus.* $(DEST)/space.*

include ../data.mk
 $(DEST)/hydroponicsstation1.* 