<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='nomove'>

         <para number='1'>
         Solus Station flight control orders you to abort your current trajectory and return to the established space lanes. Faced with the alternatives, you comply.
         </para>

         <para number='2'>
         Odd forces from the galactic barrier prevent your ship from moving in that direction.
         </para>

         <para number='3'>
         Floating off into the great unknown with a non-functional navigation system is not recommended.
         </para>

      </section>

   </category>

</para-list>


