<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='noexit msg generic outdoor'>
         A groundsman stands in your way and advises that unauthorised access onto the unfinished parts of the golf course could be very dangerous to life and limb.
         </para>

         <para number='2' comment='noexit msg groundsmans hut'>
         Several large machines stop you from moving in that direction.
         </para>

         <para number='3' comment='noexit msg for clubhouse'>
         A player taps you on the shoulder and tells you that you can't go that way.
         </para>

         <para number='4' comment='noexit msg from bar'>
         A waitdroid quickly steps forward and offers you yet another free drink. You take the drink and are totally distracted, so you stay where you are.
         </para>

      </section>

   </category>

</para-list>

