<?xml version="1.0"?>

<para-list version='6'>

   <category name='food'>

      <section name='burger'>

         <para number='1' comment='Sell burger in loc 456'>
         A small human girl with grease-stained robes and a cheeky grin flips one of the thick llama-burgers off the modified powerpack on which it has been cooking, and onto a slab of dark bread. She hands it to you and accepts 10 groats in exchange.
         </para>

         <para number='2'>
         The burger is almost hot enough to burn your hands... you blow on it to cool it down, then take a tentative bite. It turns out to be delicious, and you scoff the whole thing down, making the same "yum yum" noises as the rest of the patrons. You feel a lot better after the meal!
         </para>

         <para number='3' comment='No funds for burger'>
         You check your bank balance and are horrified to see how little money you have. You fumble in your pockets for some loose change, but all you turn up is a green 13-sided 283 groat coin, which is no longer legal tender. Sorry, no burger for you today!
         </para>

      </section>

      <section name='madhouse'>

         <para number='1' comment='Buy food - Jeritt - 265'>
         One of Jeritt's comedy waitdroids carries your chicken-in-a-basket over to you, pretending to trip over and narrowly avoiding dropping the whole thing in your lap. Highly amusing! The chicken is fried with a spicy crispy-crumb coating, and the meat inside is moist, juicy and incredibly tasty. The basket is edible, woven from very thin strips of potato and then fried along with the chicken.
         </para>

         <para number='2'>
         This tasty novelty dish pleases the customers and the waitdroids who are left with less clearing up to do.
         </para>

         <para number='3' comment='Not enuff groats'>
         A group of Jeritt's waitdroids cluster around you and laugh at your pathetic attempts to get some food when you don't have any money.
         </para>

      </section>

      <section name='milk'>

         <para number='1' comment='Buy milk - loc 456'>
         The elderly woman in charge of serving drinks deftly pours a tankard-full of fermented llama's milk and hands it to you. In exchange, you toss her a five groat piece, which she bites between her two remaining teeth (to check it's not a fake) before pocketing it.
         </para>

         <para number='2'>
         You take a swig of the milk, and then gasp as you attempt to swallow. Your vision dims and for a moment you think your head is about to explode. You feel a burning sensation running down your body, as the milk makes its way to your stomach... and then finally a warm feeling which spreads throughout your body and leaves you with a great sense of well-being. You proceed to finish the tankard of milk, and by the end of it you feel wonderful!
         </para>

         <para number='3' comment='No funds for milk'>
         You are about to ask the aged crone who is serving tankards of milk to sell you one, when you check your bank balance. Where did all your money go? You haven't even got enough groats to buy a drink!
         </para>

         <para number='4' comment='Buy carton of milk'>
         The elderly serving woman hands you a carton of milk to take away.
         </para>

         <para number='5' comment='No funds for carton'>
         You are about to ask the aged crone who is serving here to sell you a carton of milk to take away, when you realize that you don't have enough groats. A temporary embarassment, surely!
         </para>

         <para number='6' comment='Drink milk'>
         You take a swig of the milk, and then gasp as you attempt to swallow. Your vision dims and for a moment you think your head is about to explode. You feel a burning sensation running down your body, as the milk makes its way to your stomach... and then finally a warm feeling which spreads throughout your body and leaves you with a great sense of well-being. By the time you have swallowed a whole portion of the milk, you feel wonderful!
         </para>

         <para number='7' comment='Drink milk - last serving'>
         You take a swig of the milk, and then gasp as you attempt to swallow. Your vision dims and for a moment you think your head is about to explode. You feel a burning sensation running down your body, as the milk makes its way to your stomach... and then finally a warm feeling which spreads throughout your body and leaves you with a great sense of well-being. By the time you have swallowed a whole portion of the milk, you feel wonderful!
         </para>

         <para number='8'>
         The carton is now empty, and it self-destructs, thus leaving no litter behind.
         </para>

         <para number='9' comment='Drop milk'>
         You drop the carton of milk. It bursts as it hits the ground, and milk splashes everywhere, making a horrible mess. Anyone in the vicinity gets splattered. Fortunately, a robo-cleaner shows up to deal with it, much to its annoyance.
         </para>

         <para number='10' comment='roomex'>
         Suddenly, %s drops a carton of fermented llama milk, which bursts as it hits the floor, splashing milk everywhere - including over you. Fortunately, a robo-cleaner shows up and deals with the horrible mess, much to its annoyance, leaving you unsoiled.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='staff'>

         <para number='1' comment='Turn back non-staff - loc 325'>
         You walk towards the airlock, but it remains closed. You press the access button, but nothing happens; even pulling on the manual emergency lever has no effect. Very puzzling! Then you spot a notice tacked crookedly onto the airlock door: "Access to Brass is restricted due to emergency maintenance. No admittance without authorisation." That explains it.
         </para>

      </section>

   </category>

</para-list>

