<?xml version="1.0"?>

<para-list version='16'>

   <category name='food'>

      <section name='fedruckers'>

         <para number='1' comment='Buy food - Fedruckers - 265'>
         The waitdroid delivers an enormous juicy hamburger to your table, encased in a bun the size of a loaf, and points you towards the bar where you can help yourself to the toppings of your choice. You pile the toppings so high they almost defy the minimal gravity on Castillo, and then proceed to munch your way through it until all that remains is a few greasy stains.
         </para>

         <para number='2' comment='Not enough groats'>
         You don't have enough groats to buy food, not even in a cheap joint like this.
         </para>

      </section>

   </category>

   <category name='gifts'>

      <section name='card'>

         <para number='1' comment='loc 198 - Get trading card'>
         You reach for one of the cards, but quick as a flash, Clive picks up a wooden ruler from under the counter and whacks your hand with it. "No touching," he says in a nasal whine. "These collectibles are very valuable, so keep your grubby hands off them."
         </para>

         <para number='2' comment='Buy trading card'>
         There are a multitude of cards to choose from, so you need to specify which one you want to buy.
         </para>

         <para number='3' comment='Get current card'>
         Clive yelps in alarm as you try to pick up the special card. He grabs it off the counter before you can touch it. "No handling the merchandise," he squeaks, and points to the sign on the wall. "You pay for it, then you fondle it - until then, hands off."
         </para>

         <para number='4' comment='Buy current card - already got'>
         Clive scowls at you. "These are limited edition trading cards, get it? One per customer, that's all. You can't fool me - I know you already bought one of those. I have a good memory."
         </para>

         <para number='5' comment='Sell player a card'>
         Clive carefully - almost reverently - takes one of the Catty trading cards and places it in a special display holder. He hands it to you and you clip it to your belt.
         </para>

         <para number='6' comment='No slithy'>
         Clive scowls at you. "These are very valuable trading cards, and they cost one slithy tove. I can see you haven't got a slithy so don't you try to rip me off. You get yourself a slithy then you can come back - until then, get out of my shop."
         </para>

      </section>

      <section name='expired'>

         <para number='1' comment='Player tries to buy old card'>
         Clive looks as if he regrets the chance to take a slithy off you, as he says, "That trading card was a special limited edition offer, and it's run out now. But you could buy the current card in the collection." He points to the display on the counter.
         </para>

      </section>

   </category>

   <category name='mobiles'>

      <section name='clive'>

         <para number='1' comment='get/hug/kill clive'>
         Clive skitters out of the way with more speed than you would have expected, given his portly frame. "Cut that out," he whines in his nasal voice. Clearly he does not relish human contact.
         </para>

         <para number='2' comment='Clive chat - hello'>
         Clive looks up from the comic book he is reading. "Greetings, and welcome to my humble emporium," he says in a slightly whiny voice. He is attempting to be friendly but it does not come at all naturally. "If you have any questions about the merchandise please do not hesitate to ask."
         </para>

         <para number='3' comment='bye'>
         Clive mumbles a farewell under his breath, and then remembers he is supposed to be polite to his customers. "Have a nice day," he says, his sincerity quite underwhelming, then he returns to his comic book.
         </para>

         <para number='4' comment='collectible/merchandise'>
         Gesturing around the shop and pointing to individual items, Clive describes the goods on sale. "Over there we have the finest collection of ornate thimbles known to man. The collection of commemorative plates on this shelf are unparalleled. We've got stamps from the days before electronic messages, and coins from all over the Galaxy.
         </para>

         <para number='5'>
         "The action figures are from old holos; aficionados will recognize the characters, of course."
         </para>

         <para number='6'>
         Then he indicates the trading cards in the center of the counter. "These, though, these are the items I am most proud of. Nobody else sells these. They are trading cards depicting famous people. They're quite magnificent." He sighs contentedly as he contemplates his lovely trading cards.
         </para>

         <para number='7' comment='thimble'>
         "Decorative thimbles have long been something people like to collect - particularly women," says Clive. "They're not really my thing but I have built up an extensive collection, and people come from all over the Galaxy to buy them. I once sold the actual thimble that was used to blow up the pirate's asteroid, Snark - it was authenticated! I made a fortune on that sale."
         </para>

         <para number='8' comment='snark'>
         Clive leans towards you and whispers, "There are rumors that the asteroid still exists, but nobody knows how to get there - or at least, nobody is telling, but I bet the Galactic Administration knows about it and isn't telling."
         </para>

         <para number='9' comment='galactic admin'>
         "I try not to come to the notice of anybody from the government," says Clive. "I just want to be left alone to sell my collectibles."
         </para>

         <para number='10' comment='castillo'>
         "The planet is really just a research station but they decided recently they wanted to branch out a bit and introduce some retail outlets to encourage visitors," explains Clive. "My shop is the first one to open. If it's a success then I am sure there will be more."
         </para>

         <para number='11' comment='shop'>
         "I used to sell my collectibles out of my bedroom, you know, by mail order," Clive explains, "but my mom got a bit peeved and suggested that if I wanted to carry on then I had to get my own premises. That's when I decided to open a shop and sell things personally, to real visitors, not just remotely."
         </para>

         <para number='12' comment='plate'>
         "Some of my commemorative plates date back to before colonization of the Solar System, let alone the rest of the Galaxy," says Clive. "I've got one that celebrates a wedding between two members of the British royal family that you have probably never heard of. It's a shame, the plate has a crack running down the middle of it which reduces its value considerably."
         </para>

         <para number='13' comment='stamp'>
         Clive starts to give you a lecture about postage stamps. "Before messages were sent electronically, the only way to communicate over long distance was to send letters written on paper," he says. "These were carried by official messengers called postmen, and you paid for the delivery by purchasing little sticky tokens called stamps that you attached to the letters."
         </para>

         <para number='14'>
         He grins at you, "Yes, I know, it does sound very unlikely, doesn't it? But it's what really happened. Of course it was very unreliable and the post system died out once electronic messaging was invented. Anyway, there were people who collected these stamps, and even though stamps aren't used any more, collectors still want them. Weird, huh?"
         </para>

         <para number='15' comment='coin'>
         "I have coins from all over the Galaxy," Clive says proudly. "Some of them are old currency from before the fall of Ming. Look at this one..." He shows you a green coin with 13 sides and the head of a familiar-looking green person on one face. "These are very rare now, but they used to be common because they could be used in all kinds of automated vending machines."
         </para>

         <para number='16' comment='action/figure'>
         Clive picks up a figure of a person in a black helmet and a long black cloak. "You recognize him, of course," he says, running his fingers lovingly up and down the action figure. When you have to admit that you don't, he looks disappointed. "It's Darth," he says. "Darth Vader. Brave and noble hero of a series of films from long, long ago. No copies of them exist any more, but from what little is known about them, they were fantastic!"
         </para>

         <para number='17' comment='card'>
         "The trading cards are my speciality," says Clive in an excited voice. "Aren't they fantastic? The pictures are all from authentic holos. Some of them are of contemporary celebrities and some famous people from history. They are divided into sets. Right now I am featuring the Emperors set."
         </para>

         <para number='18' comment='emperor'>
         "The series shows six of the most famous Emperors," Clive says. "I'm selling them one at a time, a special each month. Once a card goes off sale it won't be available again. That makes them truly collectible. This month's card is of Catty, the last emperor."
         </para>

         <para number='19' comment='comic'>
         "It's the Adventures of Sam Galaxy," says Clive, showing you the comic. "He's a private eye and he solves mysteries and has adventures all over the Galaxy. It's really exciting."
         </para>

         <para number='20' comment='sam galaxy'>
         You can read all about Sam Galaxy and his adventures at http://www.ibgames.net/fed2/samgalaxy/index.html.
         </para>

         <para number='21' comment='promethius'>
         "The trading card showing Emperor Promethius was a previous special offer," says Clive. "It's no longer available - these collectors' items are for limited release only."
         </para>

         <para number='22' comment='Nomatch'>
         Clive shrugs - clearly he doesn't know how to respond to that, not being the Galaxy's best conversationalist!
         </para>

         <para number='23' comment='frizz'>
         "The trading card showing Emperor Frizz was a previous special offer," says Clive. "It's no longer available - these collectors' items are for limited release only."
         </para>

         <para number='24' comment='zetian'>
         "The trading card showing Emperor Zetian was a previous special offer," says Clive. "It's no longer available - these collectors' items are for limited release only."
         </para>

         <para number='25' comment='ming'>
         "The trading card showing Emperor Ming was last month's special offer," says Clive. "It's no longer available - these collectors' items are for limited release only."
         </para>

         <para number='26' comment='catty'>
         "The trading card showing Emperor Catty is this month's special offer," says Clive. He points to the card, which shows string of half hidden, semi-translucent figures appear to split off from behind the figure, each believed to represent one of Catty's alternative personalities...
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='elevator'>

         <para number='1' comment='Lift up from 136'>
         The doors close and with a slightly disturbing clanking noise, the elevator ascends to the surface.
         </para>

         <para number='2' comment='Lift down from 525'>
         The doors close and with a shudder the machinery makes the elevator sink down below the surface to the base.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='Surface locations'>
         The steep walls of the crater prevent you from moving in that direction.
         </para>

         <para number='2' comment='Storeroom - loc 198'>
         You can't move in that direction, but your attempt threatens to knock over a pile of boxes.
         </para>

         <para number='3' comment='For locs 327 and 392'>
         You can't go that way - in trying, you simply bump up against the walls.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='box'>

         <para number='1' comment='Get box - loc 329'>
         You can't move the box from under the bed. You could open it, though, if you were in the least bit curious about what is inside.
         </para>

         <para number='2' comment='get box - already got shoes'>
         You open the storage box and peer inside. It is full of shoes! But since you are already carrying a very similar pair, you close the box again.
         </para>

         <para number='3' comment='not got shoes - so pick them up'>
         You open the storage box and peer inside. It is full of shoes! There are so many that you are sure a couple won't be missed, so you pick up a pair and notice two significant things: one, they are constructed of some kind of stretchy material which means they really are "one size fits all", and two, they are tap shoes. Clearly the owner of this room likes dancing! You carefully close the box again.
         </para>

      </section>

      <section name='head'>

         <para number='1' comment='Get zlitherworm head - loc 329'>
         As you reach for the mounted head you feel a sharp pain in your arms, as if something was trying to chew your hands off. You scream and let go of the trophy; the pain fades away, but you are left with a feeling of overwhelming fear.
         </para>

      </section>

      <section name='paperclips'>

         <para number='1' comment='Join paperclips - loc 263'>
         You pick up a handful of paperclips and link them together into a chain, but there are so many loose paperclips on the desk it would take forever to join them all up. You soon lose interest, and dump your mini-chain back on the desk.
         </para>

      </section>

      <section name='shoes'>

         <para number='1' comment='Drop tap shoes'>
         You allow the tap shoes to fall to the ground; a cleaning droid appears and sweeps them up, giving you a dirty look for your littering.
         </para>

         <para number='2' comment='Wear tap shoes - 1 - player'>
         Slipping the tap shoes onto your feet (or equivalent), you attempt to do a shuffle off to Buffalo and slide across the floor, tripping and landing splat. Embarrassed, you take the tap shoes off again.
         </para>

         <para number='3' comment='Wear tap shoes - 1 - roomex'>
         Slipping a pair of tap shoes on, %s attempts to do a shuffle off to Buffalo and slides across the floor, tripping and landing splat. How embarrassing!
         </para>

         <para number='4' comment='Wear tap shoes - 2 - player'>
         Slipping the tap shoes onto your feet (or equivalent), you tap dance in a circle, doing an old soft shoe routine. Your moves are very impressive, until you attempt a fast spin and end up falling flat on your behind with a posterior-bruising thud. You sheepishly remove the shoes.
         </para>

         <para number='5' comment='Wear tap shoes - 2 - roomex'>
         Slipping a pair of tap shoes on, %s tap dances in a circle, doing an old soft shoe routine. The moves are very impressive, but then a fast spin goes wrong and the unfortunate dancer ends up on the floor with a posterior-bruising thud. Ouch!
         </para>

         <para number='6' comment='Wear tap shoes - 3 - player'>
         Slipping the tap shoes onto your feet (or equivalent), you do a quick step-ball-change on the spot. Feeling more confident, you build up speed, until your taps are ringing out like machine gun fire. It's all very impressive, until you try going too fast and trip over, landing on the floor in an ungainly heap. You take off the shoes, pretending you meant to do that.
         </para>

         <para number='7' comment='Wear tap shoes 3 - roomex'>
         Slipping a pair of tap shoes on, %s does a quick step-ball-change on the spot, then builds up speed until the taps are ringing out like machine gun fire. It's all very impressive, until the routine gets too fast and the poor hoofer trips and lands on the floor in an ungainly heap. Well, perhaps that was meant to happen!
         </para>

         <para number='8' comment='Wear tap shoes - 4 - player'>
         Slipping the tap shoes onto your feet (or equivalent), you dance to music that only you can hear, imagining you are Fred Astaire. Unfortunately, your imagination is far better than your skill, and you collide with a passer-by. Fortunately, no damage is done, except to your pride. You apologize profusely and remove the shoes before you are tempted to start dancing again.
         </para>

         <para number='9' comment='Wear tap shoes - 4 - roomex'>
         Slipping a pair of tap shoes on, %s dances just like Fed Astaire to music that you cannot hear. Unfortunately, the dancer's imagination, which far outstrips the skill on display, leads to a collision with a passer-by. It could have been a nasty accident, but fortunately no damage was done, except to the dancer's pride!
         </para>

         <para number='10' comment='Wear tap shoes - 5 - player'>
         Slipping the tap shoes onto your feet (or equivalent), you close your eyes and imagine that you are putting on your top hat, tying up your white tie, and brushing out your tails. Raucous laughter from a passing small child jerks you out of your fantasy, and you take off the shoes and hope nobody else noticed.
         </para>

         <para number='11' comment='Wear tap shoes - 5 - roomex'>
         Slipping a pair of tap shoes on, %s mimes putting on a top hat, tying up a white tie, and bruising out some tails. It looks really daft, and a passing child laughs raucously, which jerks the wannabe dancer out of fantasy-land.
         </para>

         <para number='12' comment='Wear tap shoes - 6 - player'>
         Slipping the tap shoes onto your feet (or equivalent), you break into a vigorous tap routine. A crowd gathers round to watch as you spin and twirl. You come to a big finish and they break into applause. As they disperse, somebody flips you a 2-groat piece. You add it to your balance and remove the shoes again.
         </para>

         <para number='13' comment='Wear tap shoes - 6 - roomex'>
         Slipping a pair of tap shoes on, %s breaks into a vigorous tap routine. A crowd gathers round to watch the spinning and twirling. The dance comes to a big finish, and the onlookers break into applause - as they disperse, one of them flips a coin to the dancer.
         </para>

      </section>

      <section name='thanks'>

         <para number='1' comment='Clues for scavenge hunt'>
         Clue 1: Where they usually serve chicken croquettes, tonight you can get the customary Thanksgiving bird.
         </para>

         <para number='2'>
         Clue 2: A famous Sioux rout was the original source of the name of the bar, where you'll find something they wore.
         </para>

         <para number='3'>
         Clue 3: Nobody sat on dinner - this is part of it, growing near the rice and corn.
         </para>

         <para number='4'>
         Clue 4: Among the food for the scientists is this bunch of cereal.
         </para>

         <para number='5'>
         Clue 5: Pick up this traditional Thanksgiving dessert from a place famous for its take-away treats.
         </para>

         <para number='6'>
         Clue 6: What has eyes, but can't see? Appropriately enough, you'll find them underground, where there is nothing to look at.
         </para>

         <para number='7'>
         Clue 7: What has ears, but can't hear?  It seems to be having trouble seeing where to go, too.
         </para>

         <para number='8'>
         Clue 8: No need to beat around the bush to gather these traditional berries. The inkigo smells intoxicatingly sweet, too.
         </para>

         <para number='9'>
         Clue 9: An example of the buckled headgear worn at the first Thanksgiving is on display in this shop that used to be posh.
         </para>

         <para number='10'>
         Clue 10: Make a wish, and maybe you can be among the lucky few to actually come out of here a winner.
         </para>

         <para number='11'>
         Clue 11: The founding fathers' vessel found in a communist bar.
         </para>

         <para number='12'>
         Clue 12: It should be inside the bird, not outside the cells.
         </para>

         <para number='13'>
         Clue 13: The rudest office in DataSpace hides the can of brown liquid.
         </para>

         <para number='14'>
         Clue 14: Exploding grain at the center of the nut.
         </para>

         <para number='15'>
         Clue 15: Popeye never said he was this, but it does grow in an alien garden.
         </para>

         <para number='16'>
         Clue 16: They're all mad here, and they eat this on a daily basis.
         </para>

         <para number='17'>
         Clue 17: With a chop chop here, and a chop chop there, you'll find it in an appropriate place for processing the feast's main course.
         </para>

         <para number='18'>
         Clue 18: A thousand years ago, man hunted with this.  The Martian colonists never needed it, so this shop doesn't sell it.
         </para>

         <para number='19'>
         Clue 19: Does another name for a horn of plenty ring a bell for you?
         </para>

         <para number='20'>
         Clue 20: Kick and pass this pigskin all day and it won't break.  Say, aren't the Tigers and Mammoths playing?
         </para>

      </section>

   </category>

</para-list>

