<?xml version="1.0"?>

<para-list version='6'>

   <category name='food'>

      <section name='reception'>

         <para number='1' comment='Buy food - reception - 530'>
         You put ten groats into one of the machines, and a foil container drops out into your hands. You wait while it heats up, then when it reaches the desired temperature, you remove the lid, revealing the meat pie contained within. It's not at all bad, for vending machine food - the pastry isn't too stale, the meat seems to have come from a real live animal, and the gravy is reasonably tasty and only a little bit glutinous.
         </para>

         <para number='2'>
         You finish the pie and drop the empty foil dish into the receptacle next to the machine, where it will be recycled.
         </para>

         <para number='3' comment='No money'>
         You look through all the pockets in your nano-chameleon suit but cannot find enough money.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Shuttle port - loc 402'>
         For security reasons you are not allowed to wander around on the surface of the asteroid.
         </para>

         <para number='2' comment='Security - loc 531'>
         Your attempt to move in a direction which is not the exit sparks a major security alert.
         </para>

      </section>

   </category>

   <category name='stats'>

      <section name='strength'>

         <para number='1' comment='buy strength - no slithy'>
         A screen lights up, telling you to deposit one slithy tove certificate into the slot provided. That's when you realize you don't have any slithies at all. Seems like you won't be able to get stronger just yet.
         </para>

         <para number='2' comment='basic message'>
         A screen lights up, telling you to deposit one slithy tove certificate into the slot provided. You do so, and after a moment, the writing on the screen changes to say "Thank you. Initiating checks." The booth's automated mechanisms close in on you and start running medical checks.
         </para>

         <para number='3' comment='already done a stat today'>
         After a moment, there is a rude buzzing sound, and the screen says, "Danger. Personal attributes already enhanced today. Further increases could result in injuries or death. Doris Biolabs is not prepared to take the responsibility. Please come back tomorrow. Have a nice day." After a moment, your slithy certificate reappears out of the slot, and you take it back.
         </para>

         <para number='4' comment='strength is already maxed'>
         After a moment, there is a rude buzzing sound, and the screen says, "Danger. Physical strength already enhanced to highest possible level. No further increase possible without risk. Doris Biolabs is not prepared to take the responsibility. Have a nice day." After a moment, your slithy certificate reappears out of the slot, and you take it back.
         </para>

         <para number='5' comment='increase strength'>
         After a moment, there is a mellow chime, and the screen says, "Medical checks completed. No problems detected. Administering injection." A large hypodermic needle is extruded from one of the automated arms, and before you can say trypanophobia, it has jabbed you and injected a special genetically engineered steroid. You feel woozy for a moment, then the sensation passes and you are aware that your muscles are solider and stronger than before.
         </para>

         <para number='6'>
         The screen says, "Strength enhancement complete. Thank you for your custom. Have a nice day."
         </para>

         <para number='7' comment='coda if now maxed'>
         Then suddenly some additional text appears: "Warning. Physical strength has now been enhanced to the highest possible level. Do not attempt further increase. Doris Biolabs is not prepared to take the responsibility."
         </para>

      </section>

   </category>

   <category name='xmas'>

      <section name='pie'>

         <para number='1' comment='buy mince pie - loc 530'>
         The machine whirrs quietly, then a robotic arm removes one of the mince pies from the warming section, puts it on a plate, and hands it to you. You take a bite, and experience a taste sensation. The pastry is crisp and light with a buttery taste. The fruit is plump and moist and juicy, and there's a hint of brandy in the flavoring. You gulp down the remaining pastry and dispose of the plate neatly.
         </para>

         <para number='2' comment='No funds for pie'>
         You can't afford a mince pie - and even if it is Christmas, you won't get any charity from Doris Biolabs!
         </para>

      </section>

      <section name='wine'>

         <para number='1' comment='buy mulled wine - loc 530'>
         The machine splutters a little as it pours you a cup of the mulled wine. As you grasp the cup, the heat of the drink warms your hands, and when you take your first sip, that heat is transferred to your mouth, your throat, and then all the way down to your stomach.
         </para>

         <para number='2'>
         It tastes of oranges, and cinnamon, and all kinds of other exotic spices that you cannot identify, but which remind you of Christmas. You drain the cup down to the last drop, and place it into the receptacle for empty containers.
         </para>

         <para number='3' comment='No funds for wine'>
         Sadly, you don't even have the 5 groats needed to buy yourself some mulled wine. What a loser!
         </para>

      </section>

   </category>

</para-list>

