<?xml version="1.0"?>

<para-list version='28' editor='standard'>

   <category name='brian'>

      <section name='chat'>

         <para number='1' comment='Hello - After briefing'>
         Brian is pleased to see you again, and wants to know what progress you have made.
         </para>

         <para number='2' comment='Hello - First meeting'>
         Brian the zombie greets you. "Hello, %s," he says. "Thank you for agreeing to help us. Shall I explain exactly what our problem is?"
         </para>

         <para number='3' comment='lab'>
         "The Count's laboratory is in the tallest tower of the castle. He needs the height for his experiments." Brian shudders at the thought. "Of course, the access to the tower is via a secret stairway; you'd never find it if you didn't know where to look."
         </para>

         <para number='4'>
         He explains that you need to go to the bedroom which Count Sinistre uses as his sleeping quarters, and search the fireplace. You'll find the way into the lab.
         </para>

         <para number='5' comment='Cellar/store room'>
         Brian explains, "You can access the store rooms in the cellar through another secret door." He rolls his eyes and mutters something about the Count being far too fond of hidden exits and entrances. "This time, it's in an old linen cupboard. Twist one of the brackets and a trapdoor will open."
         </para>

         <para number='6' comment='Control room'>
         "That's the room from which the collars are controlled," Brian explains. "You will need to walk through the room with the production line - I know, it's pretty disgusting in there, but you just need to grit your teeth and do it because it's the only place from which you can shut off those collars."
         </para>

         <para number='7' comment='Nomatch for Brian'>
         Brian frowns. "I don't have time to talk about trivial stuff like that," he says. "Things are really serious."
         </para>

         <para number='8' comment='bye'>
         "Goodbye, %s," says Brian. "Do what you can. We're all counting on you."
         </para>

         <para number='9' comment='Explain/problem'>
         "I know you're here on behalf of the Guild, to find out how Count Sinistre plans to sell commodities at silly prices. Well, I can tell you how. His methods are vile, and he must be stopped..." Brian is so filled with emotion that he cannot go on for a moment. Then he pulls himself together and continues to tell you what you need to know.
         </para>

         <para number='10'>
         "Sinistre is a brilliant scientist and inventor. He's also quite mad and has no morals whatsoever. He has discovered a way to bring the dead back to life and to turn them into his slaves. He's using them as workthings without having to pay them, or even to feed them or do any of the things planet-owners usually have to do to keep their populations happy and productive.
         </para>

         <para number='11'>
         "It's brilliant... but vile. That's how he can produce goods at such low prices." Brian turns away for a moment, then says, "It's a lot to take in, I know. You need a moment to appreciate the horror of it all. Shall I continue?"
         </para>

         <para number='12' comment='Continue'>
         Brian turns back to you and continues his briefing. "He gets his henchmen to dig up corpses from the graveyard and take them to his lab, where he does whatever it is that brings them back to... well, it's not life, so let's call it half-life, shall we?" He smiles a very bitter smile. "Then before the revived zombie comes fully back to its senses, the Count turns them into obedient slaves.
         </para>

         <para number='13'>
         "Occasionally, something goes wrong with the enslavement process, which results in a zombie that can think for itself. Like me, and Cedric who you met outside the castle, and there are a few others. We've formed a kind of zombie resistance movement, not that we are able to do very much. But most of the zombies are mindless workers, condemned to a life of being controlled by a madman.
         </para>

         <para number='14'>
         "I need your help - we need your help. Will you help us, please, %s?"
         </para>

         <para number='15' comment='Yes - no topic'>
         Brian looks at you in surprise. He wonders why you are saying yes, when he hasn't asked you anything.
         </para>

         <para number='16' comment='No - topic is help'>
         Brian looks sad. "I see. Well, there's nothing more I can say, then. I will have to hope somebody else comes along who is more willing than you are."
         </para>

         <para number='17' comment='No - topic is task'>
         Brian looks annoyed at your negative response. "Well, you aren't going to be able to help much if you don't want me to explain about the tasks you will need to complete."
         </para>

         <para number='18' comment='No - no topic'>
         Brian looks at you in surprise. He wonders why you are saying no, when he hasn't asked you anything.
         </para>

         <para number='19' comment='Help'>
         You agree to help Brian and he looks very pleased. "There are three things that need to be done," explains Brian. "The first task is to destroy whatever machine or process the Count uses to bring the dead back to life. Once that is done, you must find a way to free the enslaved zombies.
         </para>

         <para number='20'>
         And finally, the third task is to get word back to the Trading Guild about what Sinistre tried to do here, and make sure they will never, ever allow this planet to join the trading network."
         </para>

         <para number='21'>
         Brian strides around the room, leaving the odd gobbet of flesh behind him as he walks. "Do you want me to go into more detail about the tasks?"
         </para>

         <para number='22' comment='Task - machine is dead'>
         "Your second task," explains Brian, "Is to free my fellow zombies from their ghastly enslavement. They are controlled by means of slave collars that are put round their necks as soon as they become zombies. You will need to get into the control room, from where the collars broadcast their instructions."
         </para>

         <para number='23' comment='Task - machine not dead'>
         "Your first task," explains Brian, "is to put a stop to the Count's ghastly practice of bringing the dead back and turning them into zombies. I don't know exactly how he does it, but it takes place in his laboratory."
         </para>

         <para number='24' comment='Progress - unknown'>
         You don't have anything much to report to Brian, so you explain that you are still exploring the castle thoroughly because you don't want to miss anything. He looks a bit sceptical, and suggests you hurry up and find your way to the laboratory.
         </para>

         <para number='25' comment='Progress - machine1'>
         You tell Brian that you have found your way into the lab which contains what looks like the machine used to make zombies. He tells you that you need to destroy the machine, and suggests that if you haven't already, you figure should out how it works.
         </para>

         <para number='26' comment='Progress - machine2'>
         You tell Brian that you have switched on the machine and can see how it works, with lightning shooting down the rod and being passed through to the electrodes. He suggests that you find a way to short-circuit the machine, by using some wire to redirect the power from the rod into the guts of the machine itself somehow.
         </para>

         <para number='27' comment='Progress - machine3'>
         You tell Brian how you used some wire to redirect the power, but the wire burnt out. He suggests you try it again, this time with something a bit more heavy-duty - he is sure he remembers seeing some cable in the one of the storerooms.
         </para>

         <para number='28' comment='Progress - machine4'>
         You tell Brian that the cable almost did the trick, but that the join between the two cables needs to be insulated. He snorts in amusement. "Duct tape," he says. "It always comes down to duct tape, doesn't it? The universe would probably fall apart without it."
         </para>

         <para number='29' comment='Progress - control0'>
         Brian is delighted to hear that you have destroyed the zombie-making machine. "That's marvellous, %s," he says. "Now, you need to free my zombie brothers and sisters (and the neuter ones too of course) by getting into the control room."
         </para>

         <para number='30' comment='Progress - control1'>
         You tell Brian what you saw in the control room. "Well, clearly you need to find out how to use the computer," he says. "I am sure that's how the collars are controlled."
         </para>

         <para number='31' comment='Progress - control2'>
         You fill Brian in on your progress so far. "Oh, that's clever," he says. "I would never have thought to look under the keyboard for the password. Well, now you can use the computer, you should find out how to make it free the zombies. Maybe it has a manual or some kind of help function."
         </para>

         <para number='32' comment='Progress - otherwise...'>
         You tell Brian that you know how to free the zombies but that you need a collar to make the computer work properly. "Ah," he says. "I had a working collar once - I knew it might come in handy so I had it put in a safe place."
         </para>

         <para number='33' comment='Collar'>
         "I managed to get hold of a working collar a while ago," says Brian. "I thought it might be useful one day but I didn't feel happy keeping it anywhere close to me in case it affected me somehow, so I had one of the other free zombies put it in a safe place."
         </para>

         <para number='34' comment='Safe place'>
         Brian looks a little uncomfortable. "Yes, well, that's the problem - I don't know exactly where the collar is. I gave it to a zombie called Sephronia, and she assured me she would find somewhere to leave it, but then she was caught by the Count's henchmen and killed before she could tell me exactly where it was. She did sort of hint at the hiding place she had in mind, though.
         </para>

         <para number='35'>
         "What was it she said... ah yes, I remember. She said she would leave it in her own special place. I have no idea what that means; I hope you can work it out. Oh - she did emphasize the word 'leave' for some reason."
         </para>

         <para number='36' comment='Wire etc'>
         "There are some store rooms in the cellar where all kinds of old junk gets dumped. You can probably find what you need down there if you have a root around."
         </para>

         <para number='37' comment='Computer - has logged on'>
         "Well done for logging onto the computer," says Brian. "I would never have thought to look there for the password. Now you need to figure out how to use it."
         </para>

         <para number='38' comment='Computer - not logged on'>
         "I am pretty sure that computer is what controls the slave collars, so you need to find out how to use it," Brian says.
         </para>

         <para number='39' comment='Cedric'>
         "Poor Cedric isn't very bright," Brian confides. "He's not much use for anything except passing on the message to anyone who comes to the planet that they need to see me. I told him to stay outside the castle, because he is sure to be caught if he tries to come in again."
         </para>

         <para number='40' comment='Sephronia'>
         Brian looks sad. "Sephronia was a valuable member of the zombie resistance," he says. "She was the one who found out that the Guild were sending an investigator here to check out the planet's economy. She was killed by the Count's henchmen when they caught her trying to get a message to the Guild.
         </para>

         <para number='41'>
         "She was also my friend... the first of the resurrected zombies to avoid being enslaved, after me. I miss her."
         </para>

         <para number='42' comment='Count/sinistre'>
         Brian says, "Count Sinistre is the owner of this planet. He's a traditional mad scientist - doing what he wants to do with no regard for other people who might get hurt."
         </para>

         <para number='43' comment='Graveyard'>
         "The planet is well named, isn't it?" Brian comments with a wry smile. "We don't know how all the graves got onto the asteroid, but it's likely that the Count set things up like this so he would have a ready supply of corpses at hand for his experiments."
         </para>

         <para number='44' comment='Wedgewood'>
         "He's the investigating accountant the Guild sent here, but so far he hasn't been much use at all," Brian explains. "He blundered around in the graveyard a bit, died a few times, then just hung around near the landing pad waiting for someone else to show up. It's just as well you've taken over because if we had to rely on him we'd never get anything done."
         </para>

         <para number='45' comment='Resistance'>
         Brian tells you "We have to be very careful because if the Count discovers that we can think for ourselves, he has us destroyed. The castle is riddled with sensors that detect zombie movement where there isn't supposed to be any, so I am confined to this room. You won't be affected by that of course because you're still alive.
         </para>

         <para number='46'>
         "Occasionally one of us manages to sneak in and out of the castle but it's very dangerous, which is why I told Cedric to stay outside. Others have been caught, so what we can do is very limited."
         </para>

         <para number='47' comment='Hello - Met but not briefed'>
         Brian the zombie greets you. "Hello again, %s," he says. "You rushed off so quickly last time we met that I did not have a chance to tell you about our problem is. Shall I explain now?"
         </para>

         <para number='48' comment='Insulat'>
         You tell Brian you need something to insulate the cables, and he says, "Well I usually find duct tape is good for that kind of thing."
         </para>

      </section>

   </category>

   <category name='cable'>

      <section name='attach'>

         <para number='1' comment='Attach cable - no cable'>
         You don't have any cable.
         </para>

         <para number='2' comment='Cable already attached'>
         There is already a cable attached to the machine.
         </para>

         <para number='3' comment='Cable too short'>
         The cable dangling down from the lightning rod is too short. You will need to find an extension cable to make it long enough to reach the machine.
         </para>

         <para number='4' comment='Dead'>
         Since the machine is well and truly wrecked, there is no point attaching anything to it now.
         </para>

         <para number='5' comment='Otherwise...'>
         It would be easier to attach the other end of the cable to the lightning rod first.
         </para>

      </section>

      <section name='examine'>

         <para number='1' comment='Lab - Ex cable - cable1'>
         A cable dangles down from the lightning rod in the tower above you.
         </para>

         <para number='2' comment='cable2'>
         There is a cable attached to the machine, which connects it to the lightning rod in the tower above you.
         </para>

         <para number='3' comment='No cable present'>
         I can't find anything called cable in the vicinity!
         </para>

      </section>

      <section name='get'>

         <para number='1' comment='Get cable'>
         The cable is fairly firmly fixed in place - and after all that effort, why go to the trouble of removing it again?
         </para>

      </section>

      <section name='join'>

         <para number='1' comment='Join - Cables already joined'>
         There is already an extension cable attached to the cable.
         </para>

         <para number='2' comment='There is no cable dangling'>
         What cable would that be, then?
         </para>

         <para number='3' comment='Do it...'>
         You attach the extension cable to the original cable which is hanging down from the lightning rod. It is now long enough to reach across the room to the machine, so you attach the free end to one of the valve-like things on the top.
         </para>

         <para number='4' comment='Not got extension cable'>
         You don't have an extension cable.
         </para>

      </section>

   </category>

   <category name='cables'>

      <section name='examine'>

         <para number='1' comment='Attached to machine'>
         The cable and the extension cable have been joined together. One end is attached to the lightning rod on the roof and the other to the machine.
         </para>

         <para number='2' comment='Insulated'>
         The cable and the extension cable have been joined together, and the join has been well insulated with duct tape. One end is attached to the lightning rod on the roof and the other to the machine.
         </para>

         <para number='3' comment='No cables present'>
         I can't find anything called cables in the vicinity!
         </para>

      </section>

      <section name='insulate'>

         <para number='1' comment='Insulate cables - already done'>
         The join between the two cables has already been well insulated with duct tape.
         </para>

         <para number='2' comment='No cables present...'>
         I'm sorry I don't understand you. Can you put that a different way?
         </para>

         <para number='3' comment='Do it...'>
         You wrap the strips of duct tape around the join between the cable and the extension cable, until it is thoroughly insulated.
         </para>

         <para number='4' comment='No duct tape'>
         You don't have anything with which to insulate the cables. You will need to find some duct tape.
         </para>

      </section>

      <section name='join'>

         <para number='4' comment='Not got extension cable'>
         You don't have an extension cable.
         </para>

      </section>

   </category>

   <category name='castle'>

      <section name='cellar'>

         <para number='1' comment='Ex bracket - success'>
         Close examination of the brackets which used to hold the shelves indicates that one of them is loose. It is only attached to the wall at one end, so the other end can be twisted around.
         </para>

         <para number='2' comment='Ex bracket - failure'>
         The brackets were once used to hold the shelves upon which things were stored, but not any more.
         </para>

         <para number='3' comment='Twist/turn bracket - success'>
         You twist one of the brackets and it turns, just as if it was a handle. There is a clunk and a trapdoor opens up in the floor, revealing a ladder. You narrowly avoid falling down this sudden and unexpected opening! After you catch your balance, you climb down the ladder.
         </para>

         <para number='4'>
         As you reach the bottom, the trapdoor closes with another clunk.
         </para>

         <para number='5' comment='Failure'>
         You try to twist a couple of the brackets, just nothing happens.
         </para>

         <para number='6' comment='Climbing back up from cellar'>
         You climb the ladder and find a handle on the underside of the trapdoor; when you turn it, the trapdoor opens allowing you to ascend back into the cupboard.
         </para>

         <para number='7'>
         As you step off the ladder, the trapdoor closes with a clunk.
         </para>

      </section>

      <section name='control'>

         <para number='1' comment='Player gets to control room'>
         You shut your eyes and walk blindly past the horrible production line, trying not to think about the ghastly process. You are resolved to help Brian and his zombie friends, so you keep walking until you reach the end of the room and step through the door.
         </para>

         <para number='2' comment='Player can t get there'>
         You start to walk across the room, towards the door you can see at the far end, but the sight of the horrible production line is just too much for anyone to bear. You are forced to retreat, before you lose whatever meal you last ate.
         </para>

      </section>

      <section name='death'>

         <para number='1' comment='Player falls off tower'>
         You step off the platform, but unfortunately you never did learn to fly (or if you did, the winds are too strong for you to struggle through) and you plummet to the ground, hitting it with a noisy and painful splat. As the blackness closes in, all you can think about is how hard the ground was!
         </para>

      </section>

      <section name='entrance'>

         <para number='1' comment='Ex stone - talked to cedric'>
         You can see that one of the stones is a slightly different color from the others - just like Cedric said. Closer examination shows that it's really a button, cunningly disguised!
         </para>

         <para number='2' comment='Not talked to Cedric'>
         You peer at the stones, but can't see anything unusual about them.
         </para>

         <para number='3' comment='Press stone - talked to Cedric'>
         The stone depresses, just like a button, and a secret door opens up in the wall. You quickly go through it, and it shuts behind you.
         </para>

         <para number='4' comment='Don t know which stone'>
         You press a couple of the stones at random, but nothing happens.
         </para>

         <para number='5' comment='Press stones in other wall locs'>
         You press a couple of the stones at random, but nothing happens.
         </para>

         <para number='6' comment='Lift latch to open door'>
         You lift the latch and open the door. As you step through it, it slams shut behind you.
         </para>

         <para number='7' comment='Push shelves'>
         You push at the shelves, and are surprised when they move quite easily, swinging back to reveal a way into the room beyond. You step through the new opening, and the shelves swing back into place behind you.
         </para>

         <para number='8' comment='Pull shelves'>
         You pull at the shelves, but they don't want to move in that direction.
         </para>

         <para number='9' comment='Slide shelves'>
         You try to move the shelves to one side and then to the other, but they don't want to move in either of those directions.
         </para>

         <para number='10' comment='Once zombies freed, no entry'>
         A happy, dancing and slightly tipsy zombie is blocking the way. When you try to get past him, he flings his decaying arms around you and sobs his thanks very messily onto your shoulder. You manage to free yourself from his embrace and retreat.
         </para>

      </section>

      <section name='exit'>

         <para number='1' comment='Press stone in tunnel to exit'>
         The stone depresses, just like a button, and a secret door opens up in the wall. You quickly go through it, and it shuts behind you.
         </para>

         <para number='2' comment='Behind shelves - lift latch'>
         You lift the latch and open the door. As you step through it, it slams shut behind you.
         </para>

         <para number='3' comment='Wine cellar - pull shelves'>
         You pull at the shelves, and they swing back to reveal the secret tunnel. You step through the new opening, and the shelves swing back into place behind you.
         </para>

         <para number='4' comment='Push shelves'>
         You push at the shelves, but they don't budge, even when you lean all your weight against them.
         </para>

         <para number='5' comment='Slide shelves'>
         You try to move the shelves to one side and then to the other, but they don't want to move in either of those directions.
         </para>

      </section>

      <section name='fireplace'>

         <para number='1' comment='Search fireplace - success'>
         You feel around inside the fireplace, and find a lever hidden out of sight up the chimney.
         </para>

         <para number='2' comment='Searh fireplace - failure'>
         You examine the fireplace more closely, even going so far as to stick your head a little way up the chimney, but it's pitch black up there are you don't find anything unusual.
         </para>

         <para number='3' comment='Ex lever - success'>
         You can't see the lever because it's dark up the chimney, but examining it by touch tells you that it's the kind of lever meant to be pulled.
         </para>

         <para number='4' comment='Ex lever - failure'>
         I can't find anything called lever in the vicinity!
         </para>

         <para number='5' comment='Pull lever - success'>
         You give the lever a yank and suddenly the back of the fireplace, which looked like solid stone, moves to reveal an opening. You climb through it and the stones swing back into place behind you.
         </para>

         <para number='6' comment='Pull lever - failure'>
         I'm sorry I don't understand you. Can you put that a different way?
         </para>

         <para number='7' comment='Press button'>
         You push the button and the secret door opens, allowing you to climb out of the fireplace. As you emerge, the stones close up behind you.
         </para>

      </section>

      <section name='lab'>

         <para number='1' comment='Add to desc - wire1'>
         A wire dangles down from the lightning rod on the tower roof above you.
         </para>

         <para number='2' comment='wire2'>
         There is a wire attached to the machine, which connects it to the lightning rod on the tower roof above you.
         </para>

         <para number='3' comment='cable1'>
         A cable dangles down from the lightning rod on the tower roof above you.
         </para>

         <para number='4' comment='cable2 and cable3'>
         There is a cable attached to the machine, which connects it to the lightning rod on the tower roof above you.
         </para>

         <para number='5' comment='dead'>
         There is a burning smell in the room, and smoke drifts through the air. There is an occasional flash as the machine sparks.
         </para>

         <para number='6' comment='Plus there s a corpse on slab'>
         There is a decaying corpse lying on the slab.
         </para>

      </section>

      <section name='tower'>

         <para number='1' comment='Add to desc - wire1 and wire2'>
         There is a wire attached to the lightning rod, hanging down into the lab below.
         </para>

         <para number='2' comment='cable1, cable2 and cable3'>
         There is a cable attached to the lightning rod, hanging down into the lab below.
         </para>

      </section>

   </category>

   <category name='cedric'>

      <section name='catch'>

         <para number='1' comment='Catch zombie - have chatted'>
         What good would it do you to take Cedric captive now? And what has he done to deserve such treatment?
         </para>

         <para number='2' comment='Have tried before'>
         Trying to take the zombie prisoner didn't work when you tried it before; what makes you think you will succeed a second time?
         </para>

         <para number='3' comment='Try to catch with lasso'>
         You twirl the lasso around a few times and then hurl it at the zombie. It looks like a good throw, but the zombie, despite its clumsy demeanor, manages to avoid it. It glares at you, and says, "Hey, cut that out, willya?"
         </para>

         <para number='4' comment='Try to catch with bandages'>
         You try to fling a length of bandages around the zombie in order to catch it, but it just doesn't work. Maybe you need to knot them so they form some kind of lasso.
         </para>

         <para number='5' comment='Try to catch bare-handed'>
         You try to grab the zombie but it easily eludes you. You'll need to use a rope or something similar if you want to take the zombie prisoner.
         </para>

      </section>

      <section name='chat'>

         <para number='1' comment='Hello - having chatted before'>
         "Hello again," says Cedric.
         </para>

         <para number='2' comment='Hello - killed before'>
         "You killed my friend," says the zombie. "That was a rotten thing to do - he was only trying to talk to you. Still, since we all need your help, I'll try not to hold a grudge. My name's Cedric." The zombie looks sheepish. "I know, the name doesn't go with the whole undead thing, does it? But then, I didn't choose to be raised from the dead. It was Count Sinistre who did this to me."
         </para>

         <para number='3' comment='Hello - captured before'>
         "You tried to capture me. That's not very nice. Still, since we all need your help, I won't hold it against you. My name's Cedric." The zombie looks sheepish. "I know, the name doesn't go with the whole undead thing, does it? But then, I didn't choose to be raised from the dead. It was Count Sinistre who did this to me."
         </para>

         <para number='4' comment='Hello - first time'>
         "Hello," says the zombie. Now it has stopped groaning it doesn't seem to be in the least bit threatening. "My name's Cedric." The zombie looks sheepish. "I know, the name doesn't go with the whole undead thing, does it? But then, I didn't choose to be raised from the dead. It was Count Sinistre who did this to me."
         </para>

         <para number='5' comment='Resistance'>
         There's only a few of us and we're trying to find a way to free the zombies..." Cedric shakes his head. "I can't tell you anything more. Go and see Brian in the castle."
         </para>

         <para number='6' comment='sinistre/count'>
         Cedric shivers in what you assume to be terror, which makes a few scaly bits fall off his face in a most disgusting fashion. "He's the owner of this castle; this whole planet, in fact," he explains. "He's got terribly plans for us, which is why we need your help."
         </para>

         <para number='7' comment='Help/plans'>
         "I can't go into all the details of what Count Sinistre plans to do, and why we are desperate for help - I'm just the messenger," explains Cedric. "You need to talk to Brian."
         </para>

         <para number='8' comment='Brian'>
         "He's the leader of the zombie resistance," says Cedric. "He stays in the castle."
         </para>

         <para number='9' comment='Castle'>
         "I can tell you how to get into the castle - there's a secret passageway," says Cedric. "I would show you myself, but Brian told me to stay out here, but it doesn't matter because I can explain it easily."
         </para>

         <para number='10'>
         He points back the way you came. "You need to walk around the wall until you are almost as far as the broken down graveyard wall, and then look at the stones carefully. There's one about head height, on the left, that you will see is a slightly different color from the others. Press it, and a secret door opens that leads into the castle.
         </para>

         <para number='11'>
         "Once you're inside, look around until you find Brian. You don't have to worry about the Count - he's off-planet right now, so you should be safe.
         </para>

         <para number='12'>
         "Good luck."
         </para>

         <para number='13' comment='Bye'>
         "Goodbye, and say Hi to Brian from me. Good luck."
         </para>

         <para number='14' comment='Nomatch'>
         Cedric shrugs, and a vaguely worried frown crosses his brow. "I don't know anything about that," he says. "You'll have to talk to Brian, he's much cleverer than me."
         </para>

         <para number='15' comment='Zombie'>
         "It sucks, you know, being a zombie," says Cedric. "I mean, I suppose it beats being completely dead, but we don't last forever either. Our bodies are in a constant state of decay and eventually they fall apart and we die all over again. Plus we can be killed too. If Count Sinistre caught me, that's what he would do."
         </para>

      </section>

      <section name='kill'>

         <para number='1' comment='Kill Cedric - have chatted'>
         Why on earth do you want to kill Cedric? You know he's no threat to you!
         </para>

         <para number='2' comment='Already killed him'>
         You killed one zombie and it was replaced by a new one; trying to do it again would be a futile act of meaningless repetition.
         </para>

         <para number='3' comment='Kill him with spade'>
         You batter the zombie to death (or further death) with your spade until it is just a gooey pulp on the ground. The exertion makes you stagger backwards, discarding the spade as you move away from the ugly sight...
         </para>

         <para number='4' comment='Kill him with rake'>
         You stab at the zombie with your rake, gouging chunks out of its already decaying body, until it is utterly destroyed. The exertion makes you stagger backwards, letting the rake fall onto the ghastly remains...
         </para>

         <para number='5' comment='No handy weapon'>
         You don't have anything you could use as a weapon.
         </para>

      </section>

      <section name='meet'>

         <para number='1' comment='Meet Cedric for first time'>
         Suddenly a figure appears from around a corner, lurching as if unable to control its legs properly, its arms outstretched towards you, making a hideous moaning sound...
         </para>

         <para number='2' comment='Meet Cedric again'>
         The zombie moves towards you, moaning hideously.
         </para>

         <para number='3' comment='Have tried to catch Cedric'>
         The zombie recognizes you, and moves away so you can't try to lasso it again.
         </para>

         <para number='4' comment='Have killed poor Cedric'>
         You may have killed the zombie, but it clearly wasn't alone and has been replaced by another one! It is looking very angry, perhaps because it had to clear up the remains of your violent and unprovoked attack.
         </para>

         <para number='5' comment='Have spoken to Cedric'>
         Cedric the zombie raises a hand in greeting.
         </para>

      </section>

   </category>

   <category name='computer'>

      <section name='examine'>

         <para number='1' comment='Control room -1814 - basic desc'>
         It's a big old-fashioned-looking computer, made out of a dull grey plastic, with lots of flashing LEDs on the front which presumably indicate something important to those that need to know. There's a screen in the middle, and a keyboard sitting on a small shelf. A post-it note has been stuck to the edge of the screen.
         </para>

         <para number='2'>
         There is a wide slot above the screen.
         </para>

         <para number='3' comment='Player not logged on'>
         The screen is flashing up the words 'Please enter password', with a box where the operator is supposed to type in the password.
         </para>

         <para number='4' comment='Logged on'>
         The screen is showing a command line where the operator types in instructions; apart from that, it is blank.
         </para>

      </section>

      <section name='keyboard'>

         <para number='1' comment='Get keyboard'>
         You pick up the keyboard but you can't take it away because it's attached to the shelf by a short curly wire. However, you notice that there is a sticker on the bottom that says: Frankenstein.
         </para>

      </section>

      <section name='misc'>

         <para number='1' comment='Get computer'>
         The computer it far too big for you to pick up and take away with you - leaving aside the moral considerations of stealing office equipment!
         </para>

      </section>

      <section name='note'>

         <para number='1' comment='get post-it note'>
         The post-it note is attached to the side of the screen a lot more firmly than it looks, and you find it impossible to remove. It must be made with super-strength glue.
         </para>

      </section>

      <section name='screen'>

         <para number='1' comment='Control room -1814 - basic desc'>
         The screen is one of those old-fashioned 2-D screens with a flat surface. Very outdated technology! There's a post-it note stuck to the edge.
         </para>

      </section>

      <section name='slot'>

         <para number='1' comment='Full slot description'>
         The slot is about six inches long and an inch wide. It has a collar inserted firmly into it.
         </para>

         <para number='2' comment='Empty slot description'>
         The slot is about six inches long and an inch wide - it's much too big for a standard data crystal or disk, so whatever is meant to be inserted into it has to be quite large.
         </para>

         <para number='3' comment='Put collar into slot - already'>
         There is already a collar in the slot, which fits snugly in the available space, so you could not jam a second one in there no matter how hard you tried.
         </para>

         <para number='4' comment='Insert collar'>
         You insert the collar into the slot. After a bit of jiggling, and trying it the other way around, it slides in and snaps firmly into place.
         </para>

         <para number='5' comment='Not carrying collar'>
         You do not have a collar.
         </para>

         <para number='6' comment='Ex collar - it is in slot'>
         The collar is firmly seated in the slot on the side of the computer.
         </para>

         <para number='7' comment='Not in slot'>
         I can't see any collar in the vicinity!
         </para>

         <para number='8' comment='Get collar - it is in slot'>
         The collar is firmly inserted into the computer's slot; the force required to remove it might cause some damage, which wouldn't be a good idea.
         </para>

         <para number='9' comment='Can t insert collar - not logon'>
         You try to insert the collar into the slot, but it won't go in. You look at the screen and find out why: it is flashing up an urgent warning that only authorized users are allowed to do that. After a few moments, the box asking for the password reappears.
         </para>

      </section>

      <section name='type'>

         <para number='1' comment='type - version A - frankenstein'>
         The computer chimes with a mellow tone and the words 'password accepted' appear on the screen. After a few moments, they vanish and the screen goes blank except for a command line with a flashing cursor where the operator types in instructions.
         </para>

         <para number='2' comment='Nomatch'>
         The computer makes a rude noise and the words 'password not accepted' appear on the screen in large red letters. After a few moments, they vanish, and the 'please enter password' box returns.
         </para>

         <para number='3' comment='type - version B - help'>
         A list of the commands scrolls up on the screen. Most of it is pretty incomprehensible, and it scrolls off the top fast, but you manage to spot the one command you need. To disable the collars the command is: UNLOCK COLLARS. Well, that sounds simple enough!
         </para>

         <para number='4' comment='Unlock collars - no collar'>
         A warning message flashes on the screen in big red letters: 'Synchronization frequency required. Please insert sample collar into slot.'
         </para>

         <para number='5' comment='Success'>
         The computer makes a soft chime, and a message appears on the screen: 'Collars unlocked and deactivated.' You have done it! You can hear the sound of yelling and cheering coming from the processing room, and then Brian bursts in. "Thank you, oh thank you %s," he says. "You did it. You freed us all!"
         </para>

         <para number='6'>
         A horde of joyful zombies follow him in and hoist you onto their crumbling shoulders. They carry you out through a passageway you didn't know about and back outside the castle walls, where they deposit you gently. With excited cries about going off to have a party, they all vanish back inside again, leaving Brian to congratulate you once again on your success.
         </para>

         <para number='7'>
         "There is one last thing you must do for us," he says. "The Galaxy must know about the evil Count Sinistre and his nefarious plots. Tell Wedgewood, and he will tell the Guild, who in turn will ensure that Sinistre will never, ever be allowed to join the federation of trading planets.
         </para>

         <para number='8'>
         You have done a great thing here today. Now I am off to join the party, and then I'm taking all the zombies off to The Lattice where we will get work as extras in horror films." He grins a grin so enormous you are worried his face will fall off, and then shambles back inside the castle.
         </para>

         <para number='9' comment='Nomatch'>
         The computer bleeps angrily at you - it doesn't recognize that command.
         </para>

      </section>

   </category>

   <category name='graveyard'>

      <section name='death'>

         <para number='1' comment='Player falls into open grave'>
         Suddenly you tumble into an open grave, landing badly and bashing your head on a partially-buried rock. The fatal wound makes the earth walls of the grave seem to close in around you...
         </para>

      </section>

      <section name='effects'>

         <para number='1' comment='Spooky sound 1'>
         Lightning forks across the sky above you, accompanied by a cacophonous clap of thunder which echoes back and forth before dying away.
         </para>

         <para number='2' comment='Spooky sound 2'>
         Thunder rumbles in the distance, rolling around the landscape, seeming to circle your position until it gets back to its point of origin and stops.
         </para>

         <para number='3' comment='Spooky sound 3'>
         The misty air is riven with a piercingly high howl, that of some demented creature or dangerous animal.
         </para>

         <para number='4' comment='Spooky sound 4'>
         You hear a strange creaking noise, but you can't tell where it is coming from. It continues for a few moments and then stops just as suddenly.
         </para>

         <para number='5' comment='Spooky sound 5'>
         A low moaning sound echoes around, the sound of some poor creature in terrible despair.
         </para>

         <para number='6' comment='Spooky sound 6'>
         A high-pitched scream, that of somebody suffering the most terrible torment, hangs in the air for a moment before dying away.
         </para>

      </section>

      <section name='exit'>

         <para number='1' comment='Player climbs out of graveyard'>
         As you leave the graveyard, the mist thins and disperses, allowing you to see your surroundings properly at last.
         </para>

      </section>

   </category>

   <category name='machine'>

      <section name='examine'>

         <para number='1' comment='Ex machine - basic desc'>
         The machine is huge, taking up a whole wall of the laboratory. It has some large valves attached to the top, some capacitors on the side, and the face is covered with dials and gauges which presumably mean something. There is a big red handle on the side, which must be how you operate the machine.
         </para>

         <para number='2' comment='additional desc - wire2'>
         The machine has a wire attached to it which goes up to the lightning rod on the roof above.
         </para>

         <para number='3' comment='cable2 and cable3'>
         The machine has a cable attached to it which goes up to the lightning rod on the roof above.
         </para>

         <para number='4' comment='dead'>
         The machine looks completely wrecked - the valves or capacitors or whatever they are have shattered, the front has been blown off, and acrid smoke drifts out of the inner workings - along with the occasional spark.
         </para>

      </section>

      <section name='use'>

         <para number='1' comment='Use machine - dead'>
         You pull the handle down several times, but nothing happens because the machine is kaput - remember?
         </para>

         <para number='2' comment='Corpse is on slab'>
         You pull the handle down, and the machine starts to hum. Some of the dials light up, and the needles in the gauges move. A crack of lightning hits the lightning rod and surges down to the electrodes, shocking the corpse back into some semblance of life.
         </para>

         <para number='3'>
         Congratulations, you have just made a zombie. Welcome to the mad genius club! Unfortunately, as you attempt to pat yourself on the back, the resurrected corpse roars in pain and rage and breaks free of the leather straps. It leaps off the slab and seizes you, then snaps your neck with a sudden burst of violence.
         </para>

         <para number='4' comment='wire2'>
         You pull the handle down, and the machine starts to hum. Some of the dials light up, and the needles in the gauges move. A crack of lightning hits the lightning rod and surges down the wire into the machine itself.
         </para>

         <para number='5'>
         Unfortunately, before the power surge has a chance to do any damage, the wire burns out and disintegrates. You are going to need to find something more robust like some industrial cable.
         </para>

         <para number='6' comment='cable2'>
         You pull the handle down, and the machine starts to hum. Some of the dials light up, and the needles in the gauges move. A crack of lightning hits the lightning rod and surges down the cable into the machine itself.
         </para>

         <para number='7'>
         Unfortunately, the power surge doesn't seem to be strong enough to do any damage. You look closely at the join between the two cables and realize that the power is arcing between some of the bare wires, reducing the efficiency of the circuit. You are going to have to find a way to insulate the cables.
         </para>

         <para number='8' comment='cable3 - success'>
         You pull the handle down, and the machine starts to hum. Some of the dials light up, and the needles in the gauges move. A crack of lightning hits the lightning rod and surges down the cable into the machine itself.
         </para>

         <para number='9'>
         There is a loud bang, and the front of the machine blows off. The room fills with acrid smoke, and sparks fly out from the exposed inner workings of the machine. The cable fries completely and disintegrates.
         </para>

         <para number='10'>
         Congratulations, you have destroyed the zombie-making machine. Brian will be very pleased.
         </para>

         <para number='11' comment='Normal operation'>
         You pull the handle down, and the machine starts to hum. Some of the dials light up, and the needles in the gauges move. A crack of lightning hits the lightning rod and surges down to the electrodes, causing sparks to fly across the slab. Now you can see how the machine is supposed to work - you need to come up with a way to sabotage it. Maybe Brian will have some ideas.
         </para>

      </section>

   </category>

   <category name='mobiles'>

      <section name='wedgewood'>

         <para number='1' comment='Hello - first greeting'>
         "Hello, I'm Wedgewood," says the rumpled-looking man. He consults his clipboard for a moment. "You must be %s - Puckleberry told me to expect you. I know he briefed you on the background and explained why I am here on this ghastly planet." He gives a little shudder as he considers his situation.
         </para>

         <para number='2'>
         After a moment of forlorn contemplation, he continues. "Well, I've tried to find the information I was sent here to get, but I haven't got very far." Wedgewood sighs.
         </para>

         <para number='3'>
         "The planet seems to be one big graveyard - hence the planet name I suppose - and every time I tried to get through it, I blundered into an open grave and died. I did manage to figure out how to avoid the damn things, but frankly, I am not cut out for this kind of work so I called for help. I'm an accountant, not a famous adventurer like that fellow, what's his name - Michigan Smith.
         </para>

         <para number='4'>
         "No, I am not the right one for this mission, and I hope you are, and that you are going to help."
         </para>

         <para number='5' comment='Hello if greeted not briefed'>
         Wedgewood frowns at you, a look of disapproval on his lined face. "Well, hello again. You rushed off before I had a chance to brief you on the mission," he says.
         </para>

         <para number='6' comment='Hello - has been brief'>
         Wedgewood seems pleased to see you, and somewhat relieved that you are still in one piece. "Oh good, %s, why don't you tell me how you are getting on?" You need to tell Wedgewood about your progress.
         </para>

         <para number='7' comment='Mission/help/brief'>
         "It's a relief to have someone here who is more suited to dangerous exploration," says Wedgewood. He holds up one finger. "Firstly, you need to explore and find out as much as you can about this place. That means getting through the graveyard - fortunately, I can tell you how to do that safely.
         </para>

         <para number='8'>
         "There seems to be some kind of building on the other side of the graveyard but I couldn't make out what it is. So secondly," he gestures with a second finger, "Find out what the building is and whether you will be able to get into it, then come back to tell me how you get on. We'll make some more plans once we have more of an idea of the situation."
         </para>

         <para number='9'>
         "It's very misty in the graveyard," explains the accountant, "Making it hard to see where you are walking, which is why I kept blundering into those blasted graves. However, the last time I died I managed to figure out how to avoid them in future. They all seem to be freshly dug, so there is always a pile of earth or some disturbed soil nearby.
         </para>

         <para number='10'>
         "Avoid walking anywhere that looks like there has been digging or where the ground has been disturbed, or where there are heaps of soil, and you shouldn't die."
         </para>

         <para number='11' comment='Progress - zombies freed'>
         You tell Wedgewood that you have succeeded in destroying Count Sinistre's machine to turn the dead into the undead, and freed the zombies. Wedgewood grabs your hand and shakes it vigorously. "Splendid work, %s, absolutely splendid," he says, and for the first time a smile breaks out on his face.
         </para>

         <para number='12'>
         "You have succeeded where I was not able. Puckleberry will be delighted. I will message him immediately with the good news. Go and see him to collect your reward."
         </para>

         <para number='13' comment='Progress - brian - met'>
         You tell Wedgewood that you have spoken to another zombie, Brian. He is not so shocked as when you told about Cedric - he must be getting used to the idea of intelligent zombies now! Wedgewood asks you whether you have any useful information from Brian, but you have to admit that you do not. He looks a little exasperated and suggests you go back and talk to Brian some more.
         </para>

         <para number='14' comment='Progress - brian - brief'>
         You tell Wedgewood all the things Brian told you, about Count Sinistre and his enslavement of the zombies. Wedgewood's jaw drops as he listens, then he shouts, "Of course, that's how he intends to sell his goods for such low prices. Good grief, what a despicable plan. He'll be about to undercut all his competitors - it could wreak havoc in the Guild."
         </para>

         <para number='15'>
         You mention that it's not too good for the zombies, either, and he looks startled. "Oh, yes, of course, the poor zombies, we must think about them too. Well, from now on, obviously you need to liaise closely with this Brian and do what he suggests to put a stop to the evil Count and his nefarious plans. I don't see that I can be of much help until you have done what Brian asks."
         </para>

         <para number='16' comment='Progress - cedric - unknown'>
         Wedgewood looks a little disappointed that you haven't discovered anything significant yet. "Oh well, I suppose you'd better go back and look around some more."
         </para>

         <para number='17' comment='Progress - cedric - met'>
         You tell Wedgewood that you saw a zombie, and he looks astonished. At first he doesn't seem to believe you - "A zombie? But that's absurd. There's no such thing. Have you been drinking, %s?" - but eventually you manage to convince him that you are not off your head at which point he starts to ponder what to do about it.
         </para>

         <para number='18'>
         "I suppose it must be dangerous, in which case you should kill it. Isn't that what one traditionally does, at least in the holos I have seen? Or maybe take it prisoner so we can extract information from it. But will it be able to talk?" Wedgewood really does seem to be out of his depth with this situation and is clearly not going to be much help.
         </para>

         <para number='19'>
         "Oh, I really don't know... I think you are going to have to decide for yourself how to proceed; this is not my area of expertise."
         </para>

         <para number='20' comment='Progress - cedric - captured'>
         You explain to Wedgewood that you tried to capture the zombie using a lasso made out of bandages. He is very impressed by your resourcefulness, but when you confess that it didn't work, he looks glum. "Well, if you haven't already tried to kill it, maybe that's the next step," he says doubtfully. "It's a shame you weren't able to catch it and make it talk."
         </para>

         <para number='21' comment='Progress - cedric - killed'>
         You tell Wedgewood about killing the zombie with a garden implement. "Good," he says, "That was very brave of you. I could never have done that. Of course, now we'll never know what it wanted - it's a pity we couldn't make it talk somehow..." This doesn't seem very helpful but clearly Wedgewood is now out of ideas.
         </para>

         <para number='22' comment='Progress - has talked to cedric'>
         You tell Wedgewood that you had a chat with Cedric, and he looks astonished. "It spoke to you? You actually had a conversation with the zombie? My word, that is quite amazing. Well done, %s, well done, it would never have occurred to me that the creature was intelligent. I hope he was able to tell you something useful."
         </para>

         <para number='23' comment='Castle - Knows about stone'>
         You tell Wedgewood that you know how to get into the castle, and he is pleased with your progress, but suggests you go back and explore some more until you find the information he needs about how the owner of the planet plans to sell his goods so cheaply.
         </para>

         <para number='24' comment='Doesn t know about stone'>
         You tell Wedgewood that there is a huge castle on the other side of the graveyard. "Ah, that must be the building I caught a glimpse of just before I plummeted into yet another of those graves," Wedgewood says, then mutters to himself, "Very dangerous, leaving them open like that, against health and safety regulations I am sure."
         </para>

         <para number='25'>
         He turns his attention back to you. "The information I need, about the economics of this blasted planet, are probably inside the castle, so the next part of your mission must be to find your way inside." He lifts a fourth finger, then thinks for a moment and goes back to finger number three.
         </para>

         <para number='26' comment='Bye'>
         Wedgewood says, "Goodbye, %s," and goes back to what he was doing before you arrived - pacing around in a circle looking worried.
         </para>

         <para number='27' comment='Nomatch'>
         Wedgewood wrings his hands and looks worried. "What? What was that? Can we keep focussed here please?"
         </para>

         <para number='28' comment='Brian'>
         "Brian does seem like a resourceful person... erm... zombie... whatever," says Wedgewood. "I think you need to do what he tells you and put a stop to Count Sinistre's plans."
         </para>

         <para number='29' comment='Resistance'>
         "It sounds like somebody needs to stand up to this Count," Wedgewood declares. "I am glad the zombie resistance now has you to assist it to reach its goals. I don't see that there's anything I can do to help, but you have my moral support of course."
         </para>

         <para number='30' comment='Cedric'>
         "A zombie with a name... what an extraordinary thing..." muses Wedgewood. "Although he doesn't sound all that bright so probably won't be much help. Maybe there are more of them about."
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Noexit message for graveyard'>
         You cannot move in that direction; the mist swirls around you as you try, and seems to be pushing you back.
         </para>

         <para number='2' comment='Noexit message for castle'>
         There is no obvious exit that way, although in this strange castle who knows what may be hidden?
         </para>

         <para number='3' comment='Noexit message for crypts etc'>
         The stone walls of the building prevent you from exiting in that direction, no matter how desperate you are to get out.
         </para>

         <para number='4' comment='Noexit - castle wall'>
         The castle wall on one side, and the graveyard wall on the other, stop you from going that way.
         </para>

         <para number='5' comment='Noexit - castle wall'>
         The castle wall and the earth bank that enclose the dry moat stop you from going that way.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='armor'>

         <para number='1' comment='Hall - 1498 - Get armor'>
         You try to pick up one of the suits of armor, but it turns out to be extremely heavy. You manage to shift it a bit, but the metal pieces of the armor make some very loud clanking noises and eventually you decide the chance of attracting attention is a bit too much.
         </para>

         <para number='2' comment='Wear armor'>
         You stare at the armor for a moment, but can't see any way to climb inside the thing without completely dismantling it first.
         </para>

         <para number='3' comment='Dismantle armor'>
         You attempt to remove the helmet from one of the suits of armor, but it seems to be firmly fixed on. Turning your attention to the breast plate, you manage to lever one side off, but it's such hard work that you don't see any point continuing, so you push it back into place. Besides, it was making a terrible racket, which doesn't seem like a good idea in this spooky castle!
         </para>

      </section>

      <section name='bandage'>

         <para number='1' comment='Get bandage - already got one'>
         You've already got several lengths of the frayed bandages - what do you want to do, make your very own mummy?
         </para>

         <para number='2' comment='Pick up bandage'>
         You pick up a handful of the grubby bandages. They really don't look fit to be used on a wound!
         </para>

         <para number='3' comment='Drop bandages'>
         You allow the bandages to fall to the ground, where they are blown away by a chill draft.
         </para>

         <para number='4' comment='Use bandages'>
         You wrap some of the bandages around one of your limbs, which is pretty pointless since you're not actually injured and they sure ain't a fashion accessory. Realizing how stupid you look, you unwrap them again.
         </para>

         <para number='5' comment='Roomex'>
         For some unknown reason, %s wraps some bandages around an appendage, then after a moment takes them off again. Must be the strain of this horrible planet.
         </para>

         <para number='6' comment='Knot/tie bandages'>
         You quickly tie together several lengths of the fabric to form a lasso.
         </para>

      </section>

      <section name='board'>

         <para number='1' comment='Control 1814 - get noticeboard'>
         The noticeboard has been firmly fixed to the wall, so you can't pick it up. If you want to see what is on the board, read it.
         </para>

         <para number='2' comment='Read noticeboard - option 1'>
         A scrap of paper contains the one word: Eureka!
         </para>

         <para number='3' comment='Option 2'>
         On one of the pieces of paper, someone has used a thick black magic marker to draw a spiral.
         </para>

         <para number='4' comment='Option 3'>
         A piece of paper torn out of a magazine or newspaper has a picture of the Galactic Trading Guild headquarters building on Earth. Somebody has scribbled all over it in red pen.
         </para>

         <para number='5' comment='Option 4'>
         The words 'klaatu barada nikto' have been jotted onto what looks like a paper napkin.
         </para>

         <para number='6' comment='Option 5'>
         The take-away menu from the Sizzling Wok on Mercury has been pinned to the board.
         </para>

         <para number='7' comment='Option 6'>
         A page has been torn out of a scholarly book of some kind. The only words on it you can understand are 'The' and 'A' - the rest might as well be written in Martian!
         </para>

         <para number='8' comment='Option 7'>
         There is a postcard with a picture of a ruined castle on one side, labelled 'Frank's Place'. You peek at the reverse, but it is blank.
         </para>

         <para number='9' comment='Option 8'>
         On a picture of well-known sim star Brix Chanterel, someone has drawn a collar around his well-muscled neck.
         </para>

         <para number='10' comment='Option 9'>
         There is a picture taken with an old-fashioned 2D camera showing a red fish swimming in a tank. The label shows it is a herring.
         </para>

         <para number='11' comment='Option 10'>
         A business card from a Captain Jack Harkness of the Torchwood Institute has been pinned to the board.
         </para>

      </section>

      <section name='bone'>

         <para number='1' comment='Get bone'>
         You try to pick up one of the bones, but in so doing you knock a pile of them all over the floor, so decide to leave well alone.
         </para>

         <para number='2' comment='Get skeleton'>
         You start to pick up one of the skeletons, but it falls apart in your hands and becomes just one more jumbled heap of bones.
         </para>

      </section>

      <section name='cable'>

         <para number='1' comment='Get cable - already got'>
         Unsnarling the length of cable you already have was arduous enough, so you don't want to go through that again!
         </para>

         <para number='2' comment='Pick up some cable'>
         You start to uncoil a length of cable. It's snarled up with some of the discarded equipment, so you have to painstakingly unsnarl it before you can pull a length free.
         </para>

         <para number='3' comment='Use cable'>
         You need to be more specific about what you want to do with the cable.
         </para>

         <para number='4' comment='Attach cable'>
         You need to attach the cable to something specific,  unless you want to make a useless loop. Best to take it to the place where you need it first.
         </para>

         <para number='5' comment='Drop cable'>
         You drop the cable and it rolls away out of sight.
         </para>

      </section>

      <section name='chart'>

         <para number='1' comment='Control - 1814 - get flipchart'>
         You try to remove the flipchart from its stand, but it is well fastened down. Then you try to pick up the stand, but one of the tripod legs collapses and a hinge in the middle pinches a bit of your skin, giving a nasty nip, so you give up.
         </para>

         <para number='2' comment='Read flipchart'>
         The top page of the flipchart contains a very complex flowchart diagram made up of circles, squares and diamonds connected by arrows. You attempt to trace the flow of the arrows, but the multiple branches and convergences just make your head hurt.
         </para>

         <para number='3' comment='Flip flipchart'>
         You riffle through the other pages, but they are all just as incomprehensible as the first. Whatever the diagrams are supposed to represent, it's clearly not as simple as A-B-C.
         </para>

      </section>

      <section name='coffin'>

         <para number='1' comment='Get coffin'>
         The coffins are all too large and heavy for you to pick up. Besides, walking around with a coffin would be kind of weird.
         </para>

      </section>

      <section name='collar'>

         <para number='1' comment='Graveyard - 851 - find collar'>
         Digging the rake deeply into the pile of leaves, you rake some of the leaves off the pile and move them to the other side of the monument. You see something glinting in the remaining leaves, so bend down to take a closer look. You find a metallic collar which has been buried here, and you pick it up.
         </para>

         <para number='2' comment='Already got a collar'>
         Having found a collar under the leaves, you cannot muster up the enthusiasm to look for anything else.
         </para>

         <para number='3' comment='Wear collar'>
         You place the collar around your neck (or equivalent) and you immediately feel very strange. You can hear a voice in your head, saying, 'Keep working... keep working... keep working' and your mind starts to drift. You somehow summon up the mental fortitude to resist and manage to remove the collar before the locking mechanism fully engages, and fling it away in horror. You are left feeling very shaken and quite weak from your lucky escape.
         </para>

         <para number='4' comment='Get collar in food proc room'>
         You move closer to one of the zombies, choking back your revulsion at the appalling smell coming off its decaying body, and try to remove its collar. However, the collar is locked into place and won't budge. You are going to have to find out how to unlock the collars.
         </para>

         <para number='5' comment='drop collar'>
         You drop the collar. It breaks into several pieces, which scatter in all directions.
         </para>

      </section>

      <section name='corpse'>

         <para number='1' comment='Get corpse - already got one'>
         There is no way you can carry more than one dead body at a time.
         </para>

         <para number='2' comment='Pick up corpse'>
         You pick up one of the corpses. There is a vile stench as your action releases some long-trapped gas; it makes you feel quite faint.
         </para>

         <para number='3' comment='Drop corpse'>
         You allow the body to fall to the ground. Unfortunately, the impact accelerates the process of decay and the corpse makes a nasty squelching noise and disintegrates.
         </para>

         <para number='4' comment='Use corpse'>
         You want to USE a CORPSE? What kind of a sicko are you?
         </para>

         <para number='5' comment='Drop corpse in lab - already'>
         You have already dumped a corpse on the slab, and when you try to drop another one on top of it, it rolls onto the floor and disintegrates.
         </para>

         <para number='6' comment='Not already there so drop it'>
         You dump the corpse on the slab, then fasten the leather straps across its chest and attach the electrodes to its forehead.
         </para>

         <para number='7' comment='Ex corpse - corpse on slab'>
         The corpse has been laid out on the slab neatly - or as neat as something that is decaying and has bits falling off it can ever be - and the leather straps fastened across its chest. There are electrodes attached to its pallid forehead.
         </para>

         <para number='8' comment='No corpse on slab'>
         I can't find anything called corpse in the vicinity!
         </para>

         <para number='9' comment='Get corpse'>
         After all the trouble you went to, lugging the corpse up here and firmly strapping it to the slab - not to mention attaching the electrodes to it - it would be such a waste to just remove it again. Go on... try the machine... why don't you?
         </para>

      </section>

      <section name='crow'>

         <para number='1' comment='Get crow'>
         You lunge towards the crow, attempting to grab hold of it, but it's much too fast for you. It flaps its wings and rises into the air, then lands back on the monument again, squawking rudely as if it is laughing at you.
         </para>

         <para number='2' comment='Kill crow'>
         You advance towards the crow with murder on your mind, but before you can get close it flaps its wings and flies upwards. It circles around a few times, cawing loudly in derision, before landing again.
         </para>

      </section>

      <section name='extcable'>

         <para number='1' comment='Get extension cable - already g'>
         Unknotting the extension cable was really hard work, so you should use the one you have.
         </para>

         <para number='2' comment='Pick up some ext cable'>
         You tug at one of the extension cables, but it is knotted up with some other bits of cable. You carefully unknot it and finally are able to pull it free.
         </para>

         <para number='3' comment='Use ext cable'>
         You need to be more specific about what you want to do with the extension cable.
         </para>

         <para number='4' comment='Attach ext cable'>
         You need to attach the extension cable to another piece of cable - that's what it's intended for. Best to take it to the place where you need it first.
         </para>

         <para number='5' comment='Drop ext cable'>
         You drop the extension cable and it rolls away out of sight.
         </para>

      </section>

      <section name='fungus'>

         <para number='1' comment='Get fungus'>
         That wouldn't be a good idea; if the fungus were poisonous, you might get some on your fingers and then accidentally transfer it to your mouth or something.
         </para>

         <para number='2' comment='Eat fungus'>
         That really would be a terribly bad idea! If you want to kill yourself, just go ahead and suicide.
         </para>

      </section>

      <section name='horse'>

         <para number='1' comment='Nursery 1433 - get rockinghorse'>
         The rocking horse is heavy and also a very awkward shape - there's no practical way to grasp it in order to exert proper lifting pressure. You try several different ways, but without any success.
         </para>

         <para number='2' comment='Rock rocking horse'>
         You gently rock the rocking horse backwards and forwards a few times, taking care to keep all body parts well out of reach of the rockers. It rocks smoothly but makes some rather loud creaks.
         </para>

         <para number='3' comment='Ride rocking horse'>
         You clamber onto the back of the rocking horse, and rock yourself backwards and forwards. The motion is very soothing, despite the loud creaking noises the rockers make, and for a moment you forget your unpleasant surroundings. Then, realizing you cannot relax for long, you get off the horse again and return to adulthood.
         </para>

      </section>

      <section name='implements'>

         <para number='1' comment='Kitchen - 1678 - get implements'>
         You move the implements around, trying to identify something that would be useful, but they are so rusty, and encrusted with so much muck and filth, that it's impossible to figure out what any of them are.
         </para>

      </section>

      <section name='insect'>

         <para number='1' comment='Get insect'>
         There is no good reason to pick up one of the insects, unless you plan to drop it down somebody's neck, which would be a really horrible thing to do!
         </para>

      </section>

      <section name='lasso'>

         <para number='1' comment='Drop lasso'>
         You allow the lasso to fall to the ground, where the bandages are blown away by a chill draft.
         </para>

         <para number='2' comment='Use/swing/throw lasso - normal'>
         You swing the lasso around a few times then let it fly. It fails to catch anything and just falls to the ground, from whence you retrieve it.
         </para>

         <para number='3' comment='Roomex'>
         Swinging a lasso made out of bandages in the air, %s lets it fly. It fails to catch anything and just falls to the ground, from whence the wannabe-cowboy retrieves it.
         </para>

      </section>

      <section name='leaves'>

         <para number='1' comment='Get/move/search leaves: no rake'>
         You pick up a handful of leaves and deposit them on the other side of the monument, but shifting them by hand is going to take forever!
         </para>

      </section>

      <section name='rake'>

         <para number='1' comment='Get rake - already got one'>
         You can't possibly handle more than one of these unwieldy rakes at a time.
         </para>

         <para number='2' comment='Pick up rake'>
         You pick up a rake and tuck it under your arm, carefully avoiding the spiky prongy bits on the end.
         </para>

         <para number='3' comment='Drop rake'>
         You let go of the rake and it falls to the ground, almost hitting your legs with its spiky metal prongs. The springy metal makes it bounce off at an angle to vanish away somewhere.
         </para>

         <para number='4' comment='Use rake - normal response'>
         There's nothing here to rake, so all your clumsy actions succeed in doing is making a few pointless scratches in the ground.
         </para>

         <para number='5' comment='Roomex'>
         Wielding a rake very clumsily, %s makes a few pointless scratches in the ground.
         </para>

      </section>

      <section name='rations'>

         <para number='1' comment='Bedroom - 1435 - get rations'>
         You pick up one of the concentrated ration packs - commonly known as rat packs by those unfortunate enough to have to live off them - and unwrap it. Inside the glossy wrapper is something that looks like tightly-packed shreds of cardboard. Still, it's supposed to be highly nutritious, so you choke down the tasteless thing and feel considerably fuller than you did before.
         </para>

      </section>

      <section name='rose'>

         <para number='1' comment='Get vase'>
         You reach for the vase, but a realization that it must once have been placed here by a loved one makes you decide to leave it where it is.
         </para>

         <para number='2' comment='Get rose - already got'>
         One dead flower should be enough for anyone!
         </para>

         <para number='3' comment='Pick up rose'>
         You grasp the stem of one of the dead flowers, which digs its thorns into you, drawing blood. Nevertheless, you pick it up.
         </para>

         <para number='4' comment='Drop rose'>
         You let the rose fall to the ground. It lands on your foot, and one of its thorns leaves a nasty puncture wound.
         </para>

         <para number='5' comment='Smell rose'>
         You lower your nose (or equivalent olfactory organ) to the dead rose but it doesn't smell of anything apart from decay. The thorns scratch your proboscis, though, leaving an annoyingly painful wound.
         </para>

      </section>

      <section name='shears'>

         <para number='1' comment='Get shears - already got a pair'>
         It's not possible to use two pairs of shears at once, so there would be no point to picking up another pair.
         </para>

         <para number='2' comment='Pick up shears'>
         You pick up a pair of shears by the handles, avoiding the blades which - while not all that sharp - could still give you a nasty cut.
         </para>

         <para number='3' comment='Drop shears'>
         Just as you should never run with scissors, it's not a good idea to drop shears. You almost slice your foot off. As you jump out of the way of the falling blades, you knock the shears away and can't see where they end up.
         </para>

         <para number='4' comment='Use shears - grassy locations'>
         You make some random snipping motions in the air with your shears, but there's nothing here that needs to be pruned.
         </para>

         <para number='5' comment='Roomex'>
         You hear a snip-snip noise as %s makes some aimless cutting motions in the air with a pair of shears.
         </para>

      </section>

      <section name='skull'>

         <para number='1' comment='Get skull - already got one'>
         You have no need for more than one skull - unless you want to start a juggling act!
         </para>

         <para number='2' comment='Pick up skull'>
         You take one of the skulls, which continues to grin at you despite your rude treatment.
         </para>

         <para number='3' comment='Drop skull'>
         You let the skull fall to the ground, where it shatters into a gazillion tiny pieces of bone. Alas poor Yoric.
         </para>

         <para number='4' comment='Roomex'>
         There is a thud, followed by a smashing noise. %s has dropped a skull which has shattered into a gazillion tiny pieces of bone. Alas poor Yoric.
         </para>

         <para number='5' comment='Use skull'>
         You stare at the skull for a while but cannot think of anything useful you could do with it.
         </para>

         <para number='6' comment='Juggle skull'>
         You throw the skull up into the air and catch it, then do it again. On your third throw, you miss the catch and just touch the skull with your fingertips, sending it zooming off at an angle out of sight.
         </para>

         <para number='7' comment='Roomex'>
         Showing very little skill, %s tosses a skull into the air and catches it a few times, but then a botched catch sends the skull zooming off at an angle out of sight.
         </para>

         <para number='8' comment='Kick skull'>
         You let go of the skull and as it falls towards the ground you execute a perfect drop kick, sending it quite a distance away. A smashing sound shows that it has landed, and not survived the experience. Alas poor Yoric.
         </para>

         <para number='9' comment='Roomex'>
         There is a thud, followed by a smashing noise. %s has dropped kicked a skull which has landed badly. Alas poor Yoric.
         </para>

      </section>

      <section name='slab'>

         <para number='1' comment='Basic desc for slab'>
         The slab is a long rectangular table, about the right size for laying a body on. There are thick leather straps in several places along the sides. At one end is a large set of electrodes.
         </para>

         <para number='2' comment='There is a corpse on slab'>
         There is a decaying corpse lying on the slab.
         </para>

      </section>

      <section name='spade'>

         <para number='1' comment='get spade - already got one'>
         You are already carrying one spade - you can't dig with two even if you are ambidextrous or have more than two manipulating limbs.
         </para>

         <para number='2' comment='Pick up spade'>
         You pick up a spade and swing it up onto your shoulder in a "hi ho, hi ho, it's off to work we go" kind of motion.
         </para>

         <para number='3' comment='Drop spade'>
         The spade hits the ground and the handle breaks into two jagged pieces. It's now useless; in frustration, you kick the pieces away out of sight.
         </para>

         <para number='4' comment='Use spade - normal response'>
         You aimlessly dig the spade into the ground, without much effect - it's too hard for you to dig a hole, or the spade is not a good enough tool, or you are not skilled enough.
         </para>

         <para number='5' comment='Roomex'>
         Using a spade, %s attempts to dig a hole in the ground, with absolutely no success whatsoever.
         </para>

      </section>

      <section name='stuff'>

         <para number='1' comment='Get/search stuff/junk'>
         There is so much stuff in this room that it's impossible to search it as random. If you know what you are looking for, just look for that.
         </para>

      </section>

      <section name='tape'>

         <para number='1' comment='Get duct tape - already got'>
         You had a hard enough time unsticking the duct tape you are already carrying; surely what you have is enough.
         </para>

         <para number='2' comment='Pick up some duct tape'>
         You carefully unstick several lengths of duct tape, trying not to let them stick to you.
         </para>

         <para number='3' comment='Use duct tape'>
         You need to be more specific about what you want to do with the duct tape.
         </para>

         <para number='4' comment='Attach/stick duct tape'>
         You need to specify what you want to stick the duct tape to. Best to take it to the place where you need it first.
         </para>

         <para number='5' comment='drop duct tape'>
         You drop the duct tape and it rolls away out of sight.
         </para>

      </section>

      <section name='urn'>

         <para number='1' comment='Get urn - already got one'>
         You have already taken one urn - leaving aside the moral considerations of robbing the dead, surely that's enough to handle?
         </para>

         <para number='2' comment='Pick up urn'>
         You pick up one of the urns, and are surprised by how heavy it is.
         </para>

         <para number='3' comment='Drop urn'>
         The urn smashes on the ground, and the contents spill out. That is no way to treat somebody's remains - have you no respect for the dead?
         </para>

         <para number='4' comment='Roomex'>
         There is a smashing noise as %s drops an urn on the ground, spilling the contents all over the place.
         </para>

         <para number='5' comment='Open urn'>
         You take the lid off the urn and look inside. It's filled with ashes, with the occasional white shard of bone. You hastily put the lid back on, before you are forced to consider your own mortality.
         </para>

         <para number='6' comment='Empty urn'>
         You remove the urn's lid, and upend the container, tipping the contents out onto the ground. For a moment, you admire the swirling patterns the falling ashes make, then the horror of what they represent hits you, and you let the urn slip through your fingers to smash into many tiny pieces.
         </para>

         <para number='7' comment='Roomex'>
         There is the whisper of falling ash, as %s empties out an urn. This is followed by a smashing noise as the container hits the ground and disintegrates.
         </para>

      </section>

      <section name='wheelbarrow'>

         <para number='1' comment='Get wheelbarrow'>
         You cannot pick up the wheelbarrow, it is much too heavy; the best you could do would be to wheel it, although you'd never get it up those steps.
         </para>

         <para number='2' comment='Wheel wheelbarrow'>
         The wheel squeaks rustily as you wheel the wheelbarrow backwards and forwards a few times. Wasn't that fun?
         </para>

         <para number='3' comment='Roomex'>
         A squeaking noise fills the mausoleum as %s trundles a wheelbarrow backwards and forwards a few times. You ponder asking for a ride, but the barrow looks incredibly dirty and not very stable, so you decide it wouldn't be a good idea.
         </para>

      </section>

      <section name='wine'>

         <para number='1' comment='Wine cellar - 1677 - get wine'>
         You select a bottle at random from the shelves, raising a cloud of dust which swirls around in the air before settling again.
         </para>

         <para number='2' comment='Open/drink wine'>
         You hunt around for something with which to remove the cork, but you don't seem to be carrying a corkscrew, so you have to settle for pushing the cork into the body of the bottle with a convenient digit. Once the bottle is open, you take a few swigs, but it tastes like the worst vinegar in the world. In your disgust, you drop the bottle, which smashes.
         </para>

         <para number='3' comment='drop wine'>
         You drop the bottle and it smashes on the ground. The wine that is released by the breaking bottle seeps away, leaving behind a pungent vinegary smell.
         </para>

      </section>

      <section name='wire'>

         <para number='1' comment='Get wire - already got'>
         It took you long enough to untangle the first piece of wire - why don't you try to do something with that before you get some more?
         </para>

         <para number='2' comment='Pick up some wire'>
         You untangle a piece of wire from the mess, which takes a bit of time and a lot of patience!
         </para>

         <para number='3' comment='Use wire'>
         You need to be more specific about what you want to do with the wire.
         </para>

         <para number='4' comment='Attach wire'>
         You need to attach the wire to something specific, unless you want to make a loop for some strange reason. Best to take it to the place where you need it first.
         </para>

         <para number='5' comment='Drop wire'>
         You drop the wire and it rolls away out of sight.
         </para>

      </section>

      <section name='wood'>

         <para number='1' comment='Get wood/coffin'>
         You pick up one of the splintered planks, but it's too unwieldy so you drop it again.
         </para>

      </section>

      <section name='worm'>

         <para number='1' comment='Get worm'>
         What a revolting idea!
         </para>

         <para number='2' comment='Eat worm'>
         Oh, you have got to be kidding! Ewwww!
         </para>

      </section>

      <section name='zombies'>

         <para number='1' comment='Food proc - 1813 - zombies'>
         The zombies ignore you and carry on with their work. They do not react at all to your presence - it is as if they are not aware of you at all.
         </para>

      </section>

   </category>

   <category name='puzzle'>

      <section name='insurance'>

         <para number='1' comment='Player is not insured'>
         A voice calls after you faintly, saying something that you can't make out - although it sounds urgent. The only word you recognize is "insurance". With a start, you realize that you have neglected to purchase life insurance. Should you proceed onto the planet, any accident that befalls you could be fatal. Shaken at the thought, you return to the landing pad and vow to fly straight to Earth to rectify this oversight.
         </para>

      </section>

      <section name='leaving'>

         <para number='1' comment='Player not sent by Guild'>
         As you approach your shuttle, you decide that anything you found on this horrible planet should be left there - you don't want to contaminate your ship. So you look through your inventory and discard anything from Graveyard.
         </para>

      </section>

      <section name='start'>

         <para number='1' comment='Player not sent by Guild'>
         As you leave the landing pad, a figure appears from the trees. He stares at you, and then says, "Oh no. No no no. You're not who I was expecting. The Trading Guild didn't send you, did they? You must leave - right now - or you will be in terrible danger." He ducks back behind a tree.
         </para>

         <para number='2' comment='Player sent by Guild'>
         As you leave the landing pad, a figure appears from the trees. He stares at you, and then nods in recognition and beckons you to join him behind a tree to the west.
         </para>

         <para number='3' comment='Behind tree - puzzle not start'>
         As you walk into the trees, the man who warned you to leave hisses at you,  "Go away. I can't help anyone who wasn't sent by the Trading Guild. It's really not safe for you here." He reinforces his warning by agitatedly pushing you back onto the path.
         </para>

      </section>

   </category>

   <category name='rod'>

      <section name='cable'>

         <para number='1' comment='Attach cable to rod - no cable'>
         You don't have any cable.
         </para>

         <para number='2' comment='Cable already attached'>
         There is already some cable attached to the lightning rod.
         </para>

         <para number='3' comment='Do it...'>
         You wrap one end of the cable around the lightning rod, making sure the bare ends are touching the metal of the rod. The other end of the cable hangs down into the lab below.
         </para>

      </section>

      <section name='examine'>

         <para number='1' comment='Ex lightning rod - Basic desc'>
         The lightning rod is a tall spike of metal pointing into the sky, where it attracts the lightning sent by the omnipresent storm.
         </para>

         <para number='2' comment='Wire hanging down'>
         A wire attached to the lightning rod dangles down into the lab below.
         </para>

         <para number='3' comment='Cable hanging down'>
         A cable attached to the lightning rod dangles down into the lab below.
         </para>

      </section>

      <section name='wire'>

         <para number='1' comment='attach wire to rod - no wire'>
         You don't have any wire.
         </para>

         <para number='2' comment='Wire already attached'>
         There is already some wire attached to the lightning rod.
         </para>

         <para number='3' comment='Do it...'>
         You wrap one end of the wire around the lightning rod, making sure the bare ends are touching the metal of the rod. The other end of the wire hangs down into the lab below.
         </para>

      </section>

   </category>

   <category name='wire'>

      <section name='attach'>

         <para number='1' comment='Attach wire - No wire'>
         You don't have any wire.
         </para>

         <para number='2' comment='Already attached'>
         There is already a wire attached to the machine.
         </para>

         <para number='3' comment='Do it...'>
         You grasp the dangling wire and attach it to one of the valve-like things on top of the machine.
         </para>

         <para number='4' comment='Dead'>
         Since the machine is well and truly wrecked, there is no point attaching anything to it now.
         </para>

         <para number='5' comment='Otherwise...'>
         It would be easier to attach the other end of the wire to the lightning rod first.
         </para>

      </section>

      <section name='examine'>

         <para number='1' comment='Ex wire in lab - wire1'>
         A wire dangles down from the lightning rod in the tower above you.
         </para>

         <para number='2' comment='wire2'>
         There is a wire attached to the machine, which connects it to the lightning rod in the tower above you.
         </para>

         <para number='3' comment='No wire'>
         I can't find anything called wire in the vicinity!
         </para>

         <para number='4' comment='Ex wire - in tower'>
         A wire attached to the lightning rod dangles down into the lab below.
         </para>

      </section>

      <section name='get'>

         <para number='1' comment='Get wire'>
         The wire is fairly firmly fixed in place - and after all that effort, why go to the trouble of removing it again?
         </para>

      </section>

   </category>

</para-list>

