<?xml version="1.0"?>

<para-list version='2'>

   <category name='mobiles'>

      <section name='guard'>

         <para number='1' comment='Guard - password'>
         The guard looks at you and gives a faint smile. "Yes, you have to give me the password or I won't let you enter the arena. And no, the password is not anything as simple as "password". You won't be able to guess it, so don't waste your time trying."
         </para>

         <para number='2' comment='arena'>
         "The arena is the main part of the hunt asteroid," the guard says. "It's where the games are held. You can't enter the arena unless you know the password."
         </para>

         <para number='3' comment='Portal'>
         The guard explains, "The portal leads to the arena, and it is the only way to get there. But I won't let you through without the correct password. There are no exceptions."
         </para>

         <para number='4' comment='nomatch'>
         "Nope," says the guard, shaking his head with a sly grin. "That's not the password."
         </para>

         <para number='5' comment='Player gives correct password'>
         The guard nods his head and steps aside, allow you to step into the portal. You are transported into the arena...
         </para>

         <para number='6' comment='hello'>
         The guard nods a polite greeting back to you, but otherwise doesn't seem willing to chat. He's only here to let people through to the arena if they give the correct password.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='keepout'>

         <para number='1' comment='457 - can t walk through portal'>
         The guard will not allow you to step through the portal unless you give him the correct password for today.
         </para>

      </section>

   </category>

   <category name='party'>

      <section name='food'>

         <para number='1' comment='buy food'>
         A droid hands you the special easter food: it's an egg custard pie. The crumbly pastry is rich and buttery, and the wobbly egg filling slithers down your throat, leaving a slight aftertaste of nutmeg. Delicious!
         </para>

         <para number='2' comment='Throw pie - player'>
         You take one of the egg custard pies but instead of eating it, you throw it into the crowd at random, wondering who it will hit. But before it can land on any of the party guests, a heroic waitdroid jumps up and positions itself so it takes the pie right in the face. Squelch! Skilful use of a napkin on the part of the droid prevents any of the custard from flying off and hitting anyone. What a clever droid!
         </para>

         <para number='3' comment='Throw pie - roomex'>
         A pie suddenly sails across the room, thrown by %s. You wonder who it will hit, and get ready to duck if necessary. But before it can land on any of the party guests, a heroic waitdroid jumps up and positions itself so it takes the pie right in the face. Squelch! Skilful use of a napkin on the part of the droid prevents any of the custard from flying off and hitting anyone. What a clever droid!
         </para>

         <para number='4' comment='Buy drink'>
         A waitdroid hands you a mug of what looks like hot chocolate, with whipped cream on top. It doesn't seem very party-ish, but then you take a swig and realize it's laced with brandy. It tastes wonderful, and the feeling as the warm chocolate and alcohol slide down is marvellous.
         </para>

         <para number='5' comment='Buy round - player'>
         You instruct a waitdroid to serve a round, and it hands out mugs of what looks like hot chocolate, with whipped cream on top. It doesn't seem very party-ish, but then you take a swig and realize it's laced with brandy. It tastes wonderful, and the feeling as the warm chocolate and alcohol slide down is marvellous.
         </para>

         <para number='6' comment='Buy round - roomex'>
         Prompted by %s, a waitdroid hands you a mug of what looks like hot chocolate, with whipped cream on top. It doesn't seem very party-ish, but then you take a swig and realize it's laced with brandy. It tastes wonderful, and the feeling as the warm chocolate and alcohol slide down is marvellous.
         </para>

      </section>

   </category>

</para-list>

