<?xml version="1.0"?>

<para-list version='40' editor='standard'>

   <category name='extras'>

      <section name='fountain'>

         <para number='1' comment='fountain color change msg'>
         The fountain abruptly changes color to an electric neon pink.
         </para>

         <para number='2' comment='fountain color change msg'>
         The color of the fountain slowly changes until it is a soothing, restful, green.
         </para>

         <para number='3' comment='fountain color change msg'>
         Movement catches your eye and you turn and watch the fountain slowly change to a rather nice cool blue color.
         </para>

         <para number='4' comment='fountain color change msg'>
         The fountain changes color to a violent, alarming crimson.
         </para>

         <para number='5' comment='fountain color change msg'>
         The fountain changes color to a rather startling bright canary yellow.
         </para>

         <para number='6' comment='fountain color change msg'>
         The fountain becomes a rather tasteless muddy brown color.
         </para>

         <para number='7' comment='fountain color change msg'>
         The liquid in the fountain transforms itself into a translucent, milky white, color.
         </para>

         <para number='8' comment='fountain color change msg'>
         The fountain suddenly swiches to dynamic bands of color swirling around the liquid. It's quite an impressive display at the moment.
         </para>

      </section>

      <section name='locations'>

         <para number='1' comment='loc 1443'>
         There follows a series of harrowing 2D color pictures of executions and torture, taken from the period while humans were still confined to Earth. The move to holographs coincides with the exploration and colonizing of the planets and reaching the stars.
         </para>

         <para number='2' comment='loc 1443 cont'>
         This section has holos of the xenocide on Sirius V, and the use of mass-drivers against civilian populations. These pictures led directly to the formulation of the Rigel Accords declaring such acts war crimes.
         </para>

         <para number='3' comment='loc 1443 cont'>
         Finally there is a series of famous holos of atrocities committed by the Praetorian Guard, publication of which triggered the fall of the House of Ming. The net result of the exhibition is a sobering reminder of the sort of behavior both humans and non-humans are capable of.
         </para>

         <para number='4' comment='loc 1443 cont'>
         As a coda, in the south east corner, by the exit is a polished six foot high slab of Venusian fire opal with some writing carved into it.
         </para>

         <para number='5' comment='location 1571'>
         One of today's holos seems to be a bunch of men, wearing some sort of strange armor, running round in an endless plain of waist high grass looking for some women (who aren't wearing armor). Very odd.
         </para>

         <para number='6' comment='location 1571'>
         A second holo seems to have been made completely in black and white. It shows an endless series of street demonstrations, clashes with police, rioting and burning factories. Since it has no spoken soundtrack, or subtitles, it's very difficult to figure out what's going on.
         </para>

         <para number='7' comment='location 1571'>
         The final holo is about some sort of existentialist party. All the guests seem to be standing against the walls, occasionally uttering cryptic remarks while holding a drink of their choice in a plastic cup. To say that the holo was opaque would be something of an understatement!
         </para>

         <para number='8' comment='location 1571'>
         The overall effect of the three different holos all playing in the same space is indescribable. After watching for a while you start to develop a headache! Some people, though, are watching it all with rapt attention. Each to their own. In the mean time the exit is north east.
         </para>

         <para number='9' comment='loc 2393 extra text'>
         The salesman is calling out a series of numbers, and for each number the tech produces a different background. Judging from the --Oooh's-- and the --Aaah's-- from the watchers, it's making quite an impression.
         </para>

         <para number='10' comment='loc 2393 extra text'>
         As you watch the droid calls out "42" and the tech produces a background set in the Norwegian fjords. There is an appreciative round of applause, and you take the opportunity to glance around, but there is nothing else to see except the door in the south wall.
         </para>

      </section>

   </category>

   <category name='food'>

      <section name='fur'>

         <para number='1' comment='Buy food Breakfast in Fur 1509'>
         A waitdroid, which is also covered in fur to match the decor, places a large tray on the table in front of you. On the tray are fourteen small dishes, each containing a few forkfuls of food. This is the ultimate in taster menus! You tuck in with relish, enjoying the contrasts of flavors and textures between all the different foodstuffs. Faster than you expected, it has all gone, and you are left with the memory of the melange of tastes.
         </para>

         <para number='2' comment='Not enuff groats'>
         A waitdroid, which is also covered in fur to match the decor, points out that you don't have any money.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='moves'>

         <para number='1' comment='keep non-staff from reception'>
         As you start to go through the door an alarm sounds. A battered and scarred looking security droid steps swiftly in front of you. "I'm sorry", it says, "but Lattice is temporary off-limits for the duration of the emergency." Its voice sounds like it could do with a dose of lub-oil. Ignoring your questions, it escorts you back into the shuttle launch bay.
         </para>

      </section>

   </category>

   <category name='newbod'>

      <section name='message'>

         <para number='1' comment='newbod puzzle message'>
         You enter the room and contemplate the tranquility of the scene. After a few moments a Buddhist clad in a saffron-colored robe approaches you and hands you a hexagonal object. He informs you that it is for the 'riddle master' and is gone before you can ask any questions.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='buzzer'>

         <para number='1' comment='press buzzer - msg to room'>
         A loud buzzing sound tells you someone has pressed their buzzer. A quick look at the contestants shows you that the light has come on in front of %s.
         </para>

         <para number='2' comment='Press buzzer - player message'>
         You press your buzzer. The button lights up with a bright red light, and a loud buzzing noise fills the studio.
         </para>

         <para number='3' comment='Examine portable buzzer'>
         This special portable buzzer can be moved out of the studio - even to different planets - so that the game can be played on location. It's actually a whole set of buzzers mounted on a board, running off a big battery pack.
         </para>

         <para number='4'>
         Each buzzer is a large red button - one for each contestant (and somehow there are always just the right number of buzzers!) Press it, and it will light up and make a noise.
         </para>

         <para number='5' comment='Get buzzer - staff'>
         You pick up the board containing the buzzers and tuck it under one of your arms (or equivalent appendages).
         </para>

         <para number='6' comment='Non-staff'>
         You start to pick up the buzzer board, but before you can lift it, a studio engineer bustles up and asks to see your authorization to move it. Since you don't have any, you step away from the buzzer and try to look innocent.
         </para>

         <para number='7' comment='Drop buzzer'>
         You put the buzzer board down with a thud, setting it up so it is all ready to be used in an event. Each buzzer gives a little buzz to prove that they are all working.
         </para>

         <para number='8' comment='Get buzzer - staff - roomex'>
         With a heave, %s picks up the board containing the buzzers and tucks it under one arm (or equivalent appendage).
         </para>

         <para number='9' comment='Drop buzzer - roomex'>
         You hear a thud followed by a series of buzzes, and see that %s has set up a board with a set of buzzers mounted on it, ready to play an event.
         </para>

      </section>

      <section name='dylan'>

         <para number='1' comment='Examine Dylan (1)'>
         A creature a little like a large version of an Earth rabbit is sitting on the floor with his back to the wall. He is slumped over a guitar and appears to be fast asleep.
         </para>

         <para number='2' comment='Examine Dylan (2)'>
         He's wearing a badge with a curious picture on it, and on the floor by his feet is an old workman's cap.
         </para>

         <para number='3' comment='toss coin to dylan (1)'>
         You toss a 20 groat coin into the cap, and Dylan wakes up with a start.
         </para>

         <para number='4' comment='toss coin to dylan (2)'>
         "Groovy man!" he says and strums a few chords on the guitar. He begins to sing, "Well, I woke up this morning..."
         </para>

         <para number='5' comment='toss coin to dylan (2)'>
         At this stage he falls asleep again and slumps back over his guitar.
         </para>

         <para number='6' comment='shake/talk to dylan'>
         Dylan surfaces briefly, mutters, "Wassamatterman..." and goes back to sleep.
         </para>

      </section>

      <section name='emily'>

         <para number='1' comment='Emily chat - hello'>
         "Hello dearie", she says cheerfully. "Welcome to my emporium. Feel free to look around with no obligation, but be careful, some of the items are hot, so to speak."
         </para>

         <para number='2' comment='arm I'>
         "This arm?" She grins a wicked grin and flexes the mechanical arm with a hiss of steam. "There's quite a story behind it." She then proceeds to tell you a colorful, and highly improbable, tale of an escapade.
         </para>

         <para number='3' comment='arm II'>
         The story weaves in Ming's illegitimate daughter, time travel, the 1st Marchioness of Salisbury (who died when her hair caught fire after being entangled in a chandelier), and a three-legged albino Rigellian snarcot.
         </para>

         <para number='4' comment='arm III'>
         Struggling to keep a straight face, you smile politely and nod.
         </para>

         <para number='5' comment='lattice'>
         "Nice place, unless you are color blind, in which case all the disks look the same color. Just as well Galactic Admin equal opportunities don't apply here!"
         </para>

         <para number='6' comment='vocab - bye'>
         "Bye." She waves to you and blends back into the steamy atmosphere.
         </para>

         <para number='7' comment='job'>
         She gives you a strange look. "I'm the proprieteuse of this magnificent establishment, of course!"
         </para>

         <para number='8' comment='emporium'>
         Emily smiles modestly. "It's just a few bits and pieces that I picked up along the way. Mainly stuff those pompous stuffed shirts at the Galactic Administration would like to see banned as too dangerous."
         </para>

         <para number='9' comment='ming'>
         "Ming? I know people didn't like him, but he had his good points you know..." Her face takes on a dreamy look, and she refuses to talk further about the subject.
         </para>

         <para number='10' comment='gaelaan'>
         "What a twit - Martians bearing gifts, indeed. What probably happened to him was that his friends the Martians caught him and drained all the blood out of him. Good riddance I say."
         </para>

         <para number='11' comment='teleporter I'>
         "Our teleporters? One hundred percent genuine navy Mk1 teleporters. You can only get them on The Lattice, because it's outside the Galactic Administration's control. They cost a slithy a month to rent, and work everywhere except that they can't cross cartel boundaries. Well... there are a couple of other restrictions, but they're not worth mentioning."
         </para>

         <para number='12' comment='teleporter II'>
         She waves her mechanical arm which emits a dismissive puff of steam.
         </para>

         <para number='13' comment='orrery'>
         "The one next door? Brilliant isn't it! It was too big to fit in here. The techs love it. They threatened to go on strike if the Protector didn't give me a room large enough to install it in."
         </para>

         <para number='14' comment='Nomatch'>
         Emily shrugs, and her arm makes a clanking noise.
         </para>

      </section>

      <section name='lottery'>

         <para number='1' comment='Activate lottery machine'>
         %s switches on the lottery machine. It starts to hum, and the lights start flashing. Slowly, the drum rotates, then picks up speed, until it is spinning fast. The lights flicker in patterns around the edge of the drum, and the balls inside are whirled every which way, until it is impossible to predict the order in which they will come out.
         </para>

         <para number='2' comment='Release ball - option 1'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is red, marked with a number 0.
         </para>

         <para number='3' comment='option 2'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is yellow, marked with a number 1.
         </para>

         <para number='4' comment='option 3'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is blue, marked with a number 2.
         </para>

         <para number='5' comment='option 4'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is green, marked with a number 3.
         </para>

         <para number='6' comment='option 5'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is orange, marked with a number 4.
         </para>

         <para number='7' comment='option 6'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is purple, marked with a number 5.
         </para>

         <para number='8' comment='option 7'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is pink, marked with a number 6.
         </para>

         <para number='9' comment='option 8'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is brown, marked with a number 7.
         </para>

         <para number='10' comment='option 9'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is grey, marked with a number 8.
         </para>

         <para number='11' comment='option 10'>
         There is a drum roll, and the lottery machine releases a ball. It pops out the top of the machine, rolls down a chute, and lands in the appropriate slot... the ball is black, marked with a number 9.
         </para>

         <para number='12' comment='Stop lottery machine'>
         Now that the required number of balls have been released, %s switches off the lottery machine. The spinning slows, the lights flicker for a last time, and it stops.
         </para>

      </section>

      <section name='notice'>

         <para number='1' comment='xtra text for reception notice'>
         Visitors are permitted to make use of the public portions of the Lattice teleportation system. To use the system, 'STEP ONTO color' where 'color' is the color of the disk you wish to use. The public portions of the system are as follows:
         </para>

         <para number='2'>
         yellow - to the Lattice production complex
         </para>

         <para number='3'>
         black  - to the local offices of Armstrong Cuthbert Inc
         </para>

         <para number='4'>
         blue   - to the commodities exchange
         </para>

         <para number='5'>
         green  - to the leisure and visitor complex
         </para>

         <para number='6'>
         white  - return to the reception area
         </para>

         <para number='7'>
         You may also use grey disks which are for local sub-complexes.
         </para>

         <para number='8'>
         Visitors are prohibited from using gold disks and are warned that red disks are extremely dangerous and often lead to areas likely to be fatal to both organic and non-organic beings.
         </para>

      </section>

      <section name='pass'>

         <para number='1' comment='Eat pass'>
         You screw the pass up into a little ball and stuff it in your mouth, chewing vigorously until it is a soggy mass. Then with a massive effort, you swallow it. Very commendable, but don't you think you are taking security just a little too far?
         </para>

         <para number='2' comment='Drop pass'>
         You drop the pass. A security droid immediately appears and scoops it up, then vanishes again. Well, it wouldn't do to leave it lying about where just anybody could find it.
         </para>

         <para number='3' comment='issue pass please - loc 2706'>
         You issue a pass...
         </para>

         <para number='4'>
         %s chucks a security pass for the private studio to you. You fail to catch it, and it lands on the floor in front of you.
         </para>

         <para number='5' comment='No pass - no entry to 2770'>
         As you open the door to the private studio, a large, aggressive-looking security droid stops you and asks to see your pass. Since you don't have a pass, it refuses to let you in.
         </para>

         <para number='6' comment='have pass - enter studio'>
         A large security droid looms up and checks your pass, before standing aside to let you enter.
         </para>

      </section>

      <section name='plaque'>

         <para number='1' comment='read the plaque'>
         This room has been constructed from the plans for a giant steam driven orrery prepared for Victorian industrialist Raymond Skeffington Quick-Manning.
         </para>

         <para number='2'>
         Quick-Manning, whose fortune came from the invention of an efficient mines water pump started building the orrery in the grounds of his mansion near Black Dyke Mills.
         </para>

         <para number='3'>
         Unfortunately, the escalating cost of the construction drove Quick-Manning deep into debt, and he died of a heart attack while attending a creditors meeting.
         </para>

         <para number='4'>
         The orrery was abandoned only partially constructed, and the ruins, particularly the machine room with its tall chimney, became known to the locals as "Manning's Folly".
         </para>

         <para number='5'>
         The room is as faithful a replica of the orrery as is possible within a closed environment.
         </para>

         <para number='6'>
         The main changes are the substitution of modern lighting for gas lights and the heating of the steam boiler is by electricity rather than coal. In addition, the materials used in the construction of the orrery have been brought up to modern safety standards, and some of the heavenly bodies discovered after Quick-Manning's death have been added.
         </para>

      </section>

      <section name='wheel'>

         <para number='1' comment='Get wheel'>
         You cannot pick up the wheel! Even if you were strong enough, you would ruin all the electronics and so on.
         </para>

         <para number='2' comment='Spin wheel - personal msg'>
         You give the wheel a hefty spin... The lights flash frantically as it spins around and around and around. The audience whoops and hollers, cheering the wheel on, willing it to stop in an advantageous slot. It slows... gets slower... even slower... it almost stops, then jerks one more space...
         </para>

         <para number='3' comment='Spin wheel - roomex'>
         %s spins the wheel. The lights flash frantically as it spins around and around and around. The audience whoops and hollers, cheering the wheel on, willing it to stop in an advantageous slot. It slows... gets slower... even slower... it almost stops, then jerks one more space...
         </para>

         <para number='4' comment='Wheel - option 1'>
         The wheel finally comes to a stop on the space marked Free Spin.
         </para>

         <para number='5' comment='Wheel - option 2'>
         The wheel finally comes to a stop on the space marked Lose a Turn.
         </para>

         <para number='6' comment='Wheel - option 3'>
         The wheel finally comes to a stop on the space marked Bankrupt.
         </para>

         <para number='7' comment='Wheel - option 4'>
         The wheel finally comes to a stop on the space marked 700.
         </para>

         <para number='8' comment='Wheel - option 5'>
         The wheel finally comes to a stop on the space marked 450.
         </para>

         <para number='9' comment='Wheel option 6'>
         The wheel finally comes to a stop on the space marked 1000.
         </para>

         <para number='10' comment='Wheel option 7'>
         The wheel finally comes to a stop on the space marked 1000.
         </para>

         <para number='11' comment='Wheel option 8'>
         The wheel finally comes to a stop on the space marked 750.
         </para>

         <para number='12' comment='Wheel option 9'>
         The wheel finally comes to a stop on the space marked 750.
         </para>

         <para number='13' comment='Wheel option 10'>
         The wheel finally comes to a stop on the space marked 600.
         </para>

         <para number='14' comment='Wheel option 11'>
         The wheel finally comes to a stop on the space marked 600.
         </para>

         <para number='15' comment='Wheel option 12'>
         The wheel finally comes to a stop on the space marked 500.
         </para>

         <para number='16' comment='Wheel option 13'>
         The wheel finally comes to a stop on the space marked 500.
         </para>

         <para number='17' comment='Wheel option 14'>
         The wheel finally comes to a stop on the space marked 400.
         </para>

         <para number='18' comment='Wheel option 15'>
         The wheel finally comes to a stop on the space marked 400.
         </para>

         <para number='19' comment='Wheel option 16'>
         The wheel finally comes to a stop on the space marked 350.
         </para>

         <para number='20' comment='Wheel option 17'>
         The wheel finally comes to a stop on the space marked 350.
         </para>

         <para number='21' comment='Wheel option 18'>
         The wheel finally comes to a stop on the space marked 300.
         </para>

         <para number='22' comment='Wheel option 19'>
         The wheel finally comes to a stop on the space marked 300.
         </para>

         <para number='23' comment='Wheel option 20'>
         The wheel finally comes to a stop on the space marked 200.
         </para>

         <para number='24' comment='Wheel option 21'>
         The wheel finally comes to a stop on the space marked 200.
         </para>

         <para number='25' comment='Wheel option 22'>
         The wheel finally comes to a stop on the space marked 150.
         </para>

         <para number='26' comment='Wheel option 23'>
         The wheel finally comes to a stop on the space marked 150.
         </para>

         <para number='27' comment='Wheel option 24'>
         The wheel finally comes to a stop on the space marked 100.
         </para>

         <para number='28' comment='Examine portable wheel'>
         This special portable wheel can be moved out of the studio - even to different planets - so that the game can be played on location. It's just like the regular wheel, except it is mounted on a trolley so it can be pushed along, and it runs off a big battery pack.
         </para>

         <para number='29'>
         It's decorated with lights, which flash wildly when the wheel is spinning. There are 25 spaces on which the wheel can stop. To set the portable wheel in motion, spin it.
         </para>

         <para number='30' comment='Get wheel - staff'>
         You start to push the trolley upon which the wheel sits. It slowly trundles into motion; you will continue to push it until you drop it.
         </para>

         <para number='31' comment='Non-staff'>
         You give the trolley upon which the wheel sits a little push, but before you can exert enough pressure to make it move, a studio engineer bustles up and asks to see your authorization to move the wheel. Since you don't have any, you step away from the wheel and try to look innocent.
         </para>

         <para number='32' comment='Drop wheel'>
         You stop pushing the portable wheel on its trolley and allow it to settle into place where it is.
         </para>

         <para number='33' comment='Get wheel - staff - roomex'>
         With a heave, %s starts to push the trolley upon which the wheel sits and it slowly trundles into motion.
         </para>

         <para number='34' comment='Drop wheel - roomex'>
         You hear a creak, and see that %s has stopped pushing a portable wheel of fortune.
         </para>

      </section>

   </category>

   <category name='teleport'>

      <section name='general'>

         <para number='1' comment='teleport move text'>
         There is a brief flash of light and you are in a different place.
         </para>

         <para number='2' comment='attempt to teleport on gold'>
         Nothing happens, except that a sign saying "Access not authorized" lights up. A passing droid warns you that gold disks are reserved for the sole use of the Protector and her retinue.
         </para>

      </section>

   </category>

</para-list>

