<?xml version="1.0"?>

<para-list version='24' editor='standard'>

   <category name='food'>

      <section name='absinthe'>

         <para number='1' comment='Buy absinthe - Cafe Blanc 1355'>
         A waitdroid pours you a very small glass of the highly potent drink. You knock it back in one - tears spring to your eyes and your brain feels like it's going to dribble out of your ears. All you can manage to say for the next few minutes is a strangled, croaked out, "Wow!"
         </para>

         <para number='2' comment='No money'>
         A waitdroid gives a gallic shrug and sneers at you as you try to get a drink without paying.
         </para>

      </section>

      <section name='blanc'>

         <para number='1' comment='Buy food - Cafe Blanc - 1355'>
         You signal to one of the gallic waitdroids, and after not too long a delay, it brings you a croque monsieur - the French version of a toasted ham and cheese sandwich. The melted cheese oozes out the sides as you bite into it, making a dreadful mess, but the taste is so good it's worth it.
         </para>

         <para number='2' comment='No money'>
         The waitdroids have that kind of sixth sense which tells them when a potential customer hasn't got any money, so they ignore you.
         </para>

      </section>

      <section name='camile'>

         <para number='1' comment='Buy food - Brasserie - 1417'>
         The waitdroid puts a plate in front of you containing the house speciality: steak frite. The steak is a thin cut called "onglet" which has been grilled to perfection, so the inside is still almost raw and the outside seared to seal in the flavor. The French fries are long and thin, crisp and golden on the outside and fluffy inside. The pepper sauce is both creamy and piquant.
         </para>

         <para number='2'>
         The green salad is fresh and crunchy, and coated with a delicious French dressing. You cannot remember when you last had a meal so wonderful.
         </para>

         <para number='3' comment='No money'>
         Without groats, all you can do is sniff the aromas coming from the kitchen. What a sad state to find yourself in!
         </para>

      </section>

      <section name='caviar'>

         <para number='1' comment='Buy food - M/M Champers Bar 777'>
         Your 10 groats gets you the tiniest morsel of caviar, barely enough to fill the petite mother-of-pearl spoon upon which it is presented. It tastes marvelous but is gone in an instant, at which point the waitdroid takes the valuable spoon away from you, lest you were tempted to slip it into your pocket.
         </para>

         <para number='2' comment='No money'>
         If you don't have any money, you are certainly in the wrong place! Neither Minnie nor Maxie will serve paupers.
         </para>

      </section>

      <section name='champers'>

         <para number='1' comment='Sell champers - loc 777'>
         Maxie himself comes over and serves you, carefully removing the cork from a bottle of champagne without causing it to shoot across the room. He pours you a glass and goes back to the bar. You drink down the bubbly, pour yourself another glass, drink that... and pretty soon the bottle is empty. It is only then that you notice the bill: you've been charged 100 groats for the champers!
         </para>

         <para number='2' comment='No funds for champers'>
         Minnie himself appears by your side and discreetly whispers to you that a credit check has shown you don't have enough money to buy a bottle of champagne. You ask just how much it costs, and are aghast to hear that they charge 100 groats a bottle!
         </para>

      </section>

      <section name='chaud'>

         <para number='1' comment='Buy food - Club Chaud - 1419'>
         A waitdroid fights through the crowds and shoves a long baguette into your hands. It has been split, spread with a very runny camembert cheese, then sandwiched back together again. The bread is still warm from the oven - it couldn't get much fresher - and the cheese is extremely ripe, and very smelly. A perfect French snack, in fact!
         </para>

         <para number='2' comment='No money'>
         A waitdroid fights through the crowds to see what you want, but when you discover that you don't have enough groats to buy any food, it vanishes again.
         </para>

      </section>

      <section name='hotel'>

         <para number='1' comment='Buy food - Hotel Francois 1545'>
         You are served with a French continental breakfast - called "cafe complete" - an enormous cup of coffee, more like a soup bowl than a cup, with a freshly-baked croissant and a pot of peach jam to spread on it. Eating the croissant, you spray buttery crumbs everywhere, but a tiny cleaning droid zooms around sucking them up almost before they can hit the ground.
         </para>

         <para number='2' comment='No money'>
         If you are not a guest in the hotel, you have to pay for breakfast.
         </para>

      </section>

      <section name='observe'>

         <para number='1' comment='Buy food - Observation - 1994'>
         A towering club sandwich is placed before you: multiple layers of toasted white bread, containing turkey, bacon, lettuce, tomato and smooth white mayonnaise. The whole thing is held together with a long cocktail stick. You can hardly get your mouth round the sandwich to bite through it...
         </para>

         <para number='2'>
         Finally you succeed in eating the whole thing without actually demolishing the layers in the process, and are left with the cocktail stick, which you slip into your pocket.
         </para>

         <para number='3' comment='No money'>
         You can't afford to eat here, so just relax and enjoy the view.
         </para>

      </section>

      <section name='society'>

         <para number='1' comment='Buy food - Magsoc Members 521'>
         A standard ration pack is placed before you. This is the food explorers take with them when heading off to parts unknown, but since the link closed and exploration stopped, a big stockpile has built up, which society members are slowly eating their way through. The ratpack contains all the nutrients you need, but unfortunately has the taste and texture of cardboard. Still, you munch through it heroically, doing your duty to the society.
         </para>

         <para number='2' comment='No money'>
         The Society has never fed its members for free!
         </para>

      </section>

      <section name='spin'>

         <para number='1' comment='Buy food -Spinning wheel - 1035'>
         The barman hands you a plate containing an assortment of nibbles, including a small cheese and onion tartlet, a mini sausage roll, a hunk of cheese and a lump of pineapple on a stick, a chicken drumstick (well you assume it's chicken...) and some raw vegetables with a cheesy dip. It is all designed to be eaten with the minimum of fuss, and you munch your way through it without really noticing.
         </para>

         <para number='2' comment='No money'>
         Your attempt to get food without paying for it attracts a scowl from the owner, and he does not look like a person you want to offend.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='keepout'>

         <para number='1' comment='MagSoc - 521 - non-members'>
         The door to the Magellan Society members room refuses to open to admit you. Perhaps it is because you are not a society member.
         </para>

      </section>

   </category>

   <category name='newbod'>

      <section name='president'>

         <para number='1' comment='newbod puzzle complete [1]'>
         The president comes out from behind his desk to greet you. "Congratulations on successfully completing the test," he tells you. "I was monitoring it from up here and it was an excellent result. I have already registered your membership in the Society."
         </para>

         <para number='2' comment='newbod puzzle complete [2]'>
         "I would also like to take the opportunity to thank you for your help in getting Victor out of the problems he was having with Starport Security. I took the liberty of transferring sufficient funds into your account to cover those expenses.
         </para>

         <para number='3' comment='newbod puzzle complete [3]'>
         "It is the custom of the Society to welcome new members with a few small gifts. First is the sum of 2,500ig to help defray the fuel costs involved in completing the test and the second is a voucher for ten days' worth of free exemption from customs.
         </para>

         <para number='4' comment='newbod puzzle complete [4]'>
         "If you show it to the customs manager in the starport, he will either give you a ten day certificate, or if you already have one, extend your current certificate by ten days. Use it as soon as possible, since it only has a limited life.
         </para>

         <para number='5' comment='newbod puzzle complete [5]'>
         "Finally, there is a special bonus for commanders and captains - by arrangement with Armstrong Cuthbert, an award of 50 hauler points, since the exploration you did for the test will help with Akaturi jobs when the time comes."
         </para>

         <para number='6' comment='newbod puzzle complete [6]'>
         He smiles and shakes your hand. "So welcome to the Magellan Society. I hope our association will be fruitful, and I look forward to hearing more about your exploration in the future." With that he turns to talk to another explorer who has been waiting, more or less patiently, for the President to finish talking to you.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='blythe'>

         <para number='1' comment='kiss blythe'>
         For a moment, your lips press against Blythe's perfectly proportioned, pleasingly pink, plump lips, but then it squirms away from you with a faint expression of distaste on its face. "I am sorry, but that's not one of the services I am prepared to offer," it says. "I have neither the interest, the skill, nor indeed the plumbing. Find someone else to indulge your baser urges."
         </para>

         <para number='2' comment='Blythe chat - hello boys'>
         Blythe inclines his head politely. "Greetings, Mr %s," it says. "Welcome to Rotary Offices, supplier of services for the businessman. If you would tell me of your requirements, I will do my best to fulfil your needs."
         </para>

         <para number='3' comment='hello girls'>
         Blythe inclines his head politely. "Greetings, Ms %s," it says. "Welcome to Rotary Offices, supplier of services for the businessman. If you would tell me of your requirements, I will do my best to fulfil your needs."
         </para>

         <para number='4' comment='hello things'>
         Blythe inclines his head politely. "Greetings, M %s," it says. "Welcome to Rotary Offices, supplier of services for the businessman. If you would tell me of your requirements, I will do my best to fulfil your needs."
         </para>

         <para number='5' comment='blythe/who'>
         It gives a small smile. "Blythe is all the name I have, and all I need. Who I am is not as important as my function, which is to act as the facilitator for all Rotary Offices customers. If you need to rent office space, or obtain secretarial or clerical services, or if your needs are more... shall we say... esoteric, I am certain that we can be of assistance."
         </para>

         <para number='6' comment='rotary/where'>
         "Rotary Offices has been catering to the business community that visits Magellan since the space station's inauguration," Blythe explains. "Many companies do business here without having a permanent presence, and we rent them office space and hire them the staff they need, as well as providing just about anything else they require, no matter how specialist or odd."
         </para>

         <para number='7' comment='office space/offices'>
         "We have a range of rooms from small cubbies up to grand suites, which can be used for meetings or as offices. They can be hired for a period as short as an hour or as long as you like..." Blythe starts to list the charges but since you have no need for office space, you don't pay much attention.
         </para>

         <para number='8' comment='secretarial/clerical/services'>
         "Our staff are available to contract on an hourly rate or, if your needs are more long-term, we can negotiate monthly or even yearly rates," Blythe tells you. "We have available people with all manner of skills, from secretarial and clerical to more... um... executive functions."
         </para>

         <para number='9' comment='esoteric/specialist/odd/executi'>
         Blythe lowers its voice a little. "Since we are off Earth, the Galactic Administration's rules and regulations are not so strictly enforced as they are downstairs. This allows us to provide services which may not be freely available elsewhere. If you give me some idea of the kind of thing you are looking for, perhaps I can give you more information."
         </para>

         <para number='10' comment='espionage/spying'>
         "I am afraid that's a little out of our line of work. Besides, the SpyNet organization pretty much has the private espionage business in Sol sewn up, so you should see about contacting them. They have an office in Earth's commercial area, I believe."
         </para>

         <para number='11' comment='spynet'>
         "Nobody knows much about SpyNet; they are extraordinarily secretive. I suppose as spies that makes sense. Rotary Offices does not try to compete with SpyNet - we have our own areas of expertise." Blythe looks pensive for a moment. "As a young being I did cherish dreams of becoming some kind of intelligence agent, but it became clear my aptitudes did not incline in that direction."
         </para>

         <para number='12' comment='sex'>
         Blythe laughs. "Oh dear, if that's what you are interested in, there are scores of kindly persons just waiting to relieve you of your groats in return for a moment of comfort - you don't need Rotary Offices for that. I, myself, do not indulge in the pleasures of the flesh. I cannot imagine what anyone sees in them."
         </para>

         <para number='13' comment='magellan'>
         "I very much enjoy living and working on the space station," Blythe says. "There's a free and easy attitude here; you can do what you want and be who you want to be, and so long as you don't do anything that's bad for business, nobody cares. Anything goes, really, particularly anything that serves to part visitors from their money. That suits me."
         </para>

         <para number='14' comment='earth'>
         Blythe frowns. "I was born downstairs, and had a miserable childhood. I vowed to escape the planet as soon as I was old enough, by any means necessary. Oh, it's not that I have anything against Earth, not really, it's just that I detest the way the GA's rules and regulations bind so very tight. Things are much looser here."
         </para>

         <para number='15' comment='ga/galactic administration'>
         Blythe's face takes on a somewhat pained expression. "I do detest the way bureaucracies end up perpetuating their own power. I've studied history, and although I admit the GA is not as bad as some, its sheer size and scale means its nature is always going to be oppressive to anyone who doesn't fit one of the clearly defined roles.
         </para>

         <para number='16'>
         "I turned out to be a very square peg that definitely did not fit into the round hole, and spent most of my childhood resisting being hammered into place. I did not want to fit, you see, and the institution which was charged with my care and comfort knew no way to deal with nonconformists like myself other than to use brute force - for my own good, of course."
         </para>

         <para number='17' comment='stat'>
         Blythe turns his head from side to side quickly, as if checking that nobody can overhear him. "Yes, recent developments have made it possible for various organizations to enhance the physical or mental capabilities of just about any type of being. Here, we have a service specializing in boosting endurance, or stamina as it is sometimes called.
         </para>

         <para number='18'>
         "It's all highly illegal, you understand. For all my talk about the GA's rules not applying here, they would come down on us hard if they had proof of just what service we are providing here. For the other stats, you will have to look elsewhere."
         </para>

         <para number='19' comment='stamina'>
         "We can increase your stamina but it's not a pleasant process for you, nor is it cheap. It's completely reliable, though - it works every time, I assure you.
         </para>

         <para number='20'>
         "So, to the details: 1 slithy will gain you 1 stamina point. But you can only do it once each day; your body won't take any more than that. In fact, that limit applies to all of the stat-boosting services you might avail yourself of - the most you can safely increase your attributes is one enhancement, of any of the stats, a day.
         </para>

         <para number='21'>
         "If you wish to improve your endurance, then BUY STAMINA."
         </para>

         <para number='22' comment='nomatch'>
         "I am so very sorry, that is not a service that we can offer at this time," says Blythe with an apologetic air.
         </para>

      </section>

      <section name='stick'>

         <para number='1' comment='Use cocktail stick - individual'>
         You thrust the cocktail stick out in front of you and wave it around as if you were fencing with a sword. Then you realize what a twit you look, and stop - hoping nobody saw your idiotic behavior.
         </para>

         <para number='2' comment='Use cocktail stick - room-ex'>
         Thrusting a cocktail stick out, %s waves it around, as if fencing with a sword. What a twit!
         </para>

      </section>

   </category>

   <category name='snark'>

      <section name='bellman'>

         <para number='1' comment='talk -assignment I'>
         Von Bellman puts down his knife and fork and looks directly at you for a long moment before replying. "The Directorate of Naval Intelligence, also known as the DNI, has asked the Magellan Society to find someone to act as their agent in an extremely sensitive assignment.
         </para>

         <para number='2' comment='talk - assignment II'>
         "It seems that the Snark asteroid has vanished. It was left in a remote section of the asteroid belt after its Hilbert Space generator was destroyed by DNI agents shortly after Ming vanished. It's no longer there and no one knows what has happened to it.
         </para>

         <para number='3' comment='talk - assignment III'>
         "The DNI want it back. Or at least they want it back in its orbit in the asteroid belt. And to do so they can't use a regular agent because of the extremely sensitive nature of the task. Indeed, I cannot emphasise enough how sensitive this is."
         </para>

         <para number='4' comment='talk - assignment IV'>
         He picks up his fork, pauses, and then repeats the word, "Sensitive!", stabbing the fork in your direction for emphasis, after which he resumes eating his meal.
         </para>

         <para number='6' comment='talk - sensitive I'>
         He looks at you in surprise. "Of course it's sensitive. The whole of known space understands that the paradigm shift which caused the Interregnum was initmately bound up with the shenanigans around Snark.
         </para>

         <para number='7' comment='talk - sensitive II'>
         "That cut us off from the out-system planets for hundreds of years. If this gets out there will be mass panic that it might happen again. Hundreds of looneys will start 'investigating', muddying the trail and destroying valuable evidence.
         </para>

         <para number='8' comment='talk - sensative III'>
         "The DNI must get this matter dealt with before word leaks out, which is why they have asked the Society to recommend a suitable entity willing to act as their agent. If you are prepared to be that agent, just tell me that you accept."
         </para>

         <para number='10' comment='talk - accept I'>
         He smiles for the first time. "Excellent! Now... I know you are the one for the job, because we investigated you intensively before we picked you. However, the DNI insisted that you pass a test first. Basically you need to find their Sol System Border Field Office.
         </para>

         <para number='11' comment='talk - accept II'>
         "I have no idea where it is, so I can't give you any clues, although I suspect that the name of the office is indicative of its location. The DNI's assumption is that if you can't find their office, you are unlikely to be able to solve their problem!
         </para>

         <para number='12' comment='talk - accept III'>
         "And that reminds me, you will need this to prove your bona fides when you do find the entrance. Show it to whoever is in the room, and they will give you access to the field office. Be careful who you give it to. Giving it to the wrong person might be dangerous, or expensive..."
         </para>

         <para number='13' comment='talk - accept IV'>
         With that von Bellman hands you what appears to be a schedule for the production of some sort of heavy bulk processing machinery.
         </para>

         <para number='15' comment='talk dni/naval intel'>
         "I know only what is common public knowledge about the Directorate.", says von Bellman blandly. He clearly knows more than that. Probably a great deal more. Equally clearly, he isn't going to tell you anything else. "You really need to find them yourself if you want to gather any more information."
         </para>

         <para number='20' comment='talk - bye I'>
         Conversation drifts on to other topics unrelated to Snark, and the two of you finish a very pleasant meal washed down with an excellent bottle of green Mouton Rigelchild '53.
         </para>

         <para number='21' comment='talk - bye II'>
         Shaking hands you take your leave of von Bellman, and you hear him mutter, "I know you can do it." He repeats it a little louder, looks you straight in the eye and repeats his statement a third time. Finally, he warns you that as a security precaution he will, in the future, act as though he doesn't know you.
         </para>

         <para number='35' comment='talk - nomatch'>
         He shrugs and continues eating.
         </para>

      </section>

   </category>

   <category name='stats'>

      <section name='stamina'>

         <para number='1' comment='buy stamina - no slithy'>
         Blythe ushers you through a door into a room that looks like a cross between a laboratory and a gymnasium. Before it hands you over to the technicians who will perform the procedure, it explains that it needs to know that you have the wherewithal to pay for it, and to that end you should display the certificate of slithy ownership. It is at this point you realize that you don't, in fact, have any slithies.
         </para>

         <para number='2'>
         With an embarrassed apology for wasting Blythe's time, you leave the room.
         </para>

         <para number='3' comment='basic message'>
         Blythe ushers you through a door into a room that looks like a cross between a laboratory and a gymnasium, and hands you over to the tender mercies of the technicians. They efficiently strip your clothing and proceed to give you a thorough check-up.
         </para>

         <para number='4' comment='already done a stat today'>
         After a moment, one of them frowns at you. "Didn't anyone explain how dangerous all this is? You've already had one of your personal attributes enhanced today, and your body just can't take the strain of any more treatment. Come back tomorrow." He ushers you back out of the lab/gym.
         </para>

         <para number='5' comment='stam is already maxed'>
         After a moment, one of the technicians looks at you in consternation. "Sorry, pal, you have already boosted your stamina as high as it will go; any further enhancement would risk catastrophic organ failure, and we're not prepared to risk it. It's more than my job's worth. Too big a liability, you know." He ushers you back out of the lab/gym.
         </para>

         <para number='6' comment='Increase stam'>
         Evidently, you pass, because they attach wires to various parts of your body and push you into a giant treadmill that looks like a hamster's wheel. It starts to rotate and you have no choice but to move with it, unless you want to be dumped onto the floor. It picks up speed and you are forced to run, fast, faster and then even faster, reaching what you assume is the height of your endurance.
         </para>

         <para number='7'>
         Just as you think you cannot keep going any longer, you feel sharp pains all over your body as a surge of power is sent over the wires to provide an extra stimulus.
         </para>

         <para number='8'>
         Finally, your ordeal comes to an end, but you actually feel fitter than you did before. The technicians give you another check, and pronounce themselves satisfied. One of them takes a certificate of slithy tove ownership from you, and ushers you back out of the lab/gym.
         </para>

         <para number='9' comment='Coda if player is now maxed'>
         Just before he says goodbye, he cautions you that you have increased your endurance to as great a level as is possible, so you should not risk trying to make your stamina any higher.
         </para>

      </section>

   </category>

   <category name='view'>

      <section name='enter'>

         <para number='1' comment='1st entry message for window'>
         The observation window is currently showing a view of the planet Earth, which moves slowly - oh so slowly - from one side to the other. The sight of the blue-green-white globe that is the cradle of mankind never fails to affect even those who haven't set foot on the planet.
         </para>

         <para number='2' comment='2nd entry message'>
         Through the window you can see an expanse of stars filling the blackness with points of light, together making up the milky way - the Galaxy in which the Solar System resides.
         </para>

         <para number='3' comment='3rd entry message'>
         Through the window you can see a cluster of ships hanging in space a short distance from Magellan. You think you can make out which ship is yours! Shuttles moving between the ships and the station are just visible as tiny moving specks.
         </para>

         <para number='4' comment='4th entry message'>
         Through the observation window you can see a huge cargo scow which has just lifted off from the cargo docking bays on wheel two. It drifts away in the direction of Mars, getting smaller and smaller until it finally vanishes from sight.
         </para>

         <para number='5' comment='5th entry message'>
         Through the window you can see a maintenance bot. You realise that as it moves, it is wiping the glass with its soft, cloth-like appendages - cleaning the accumulation of space dust off it to preserve the view.
         </para>

      </section>

      <section name='loop'>

         <para number='1' comment='First view from window'>
         The edge of the planet Earth appears on one side of the huge window, then slowly - oh so slowly - moves into full view. The sight of the blue-green-white globe that is the cradle of mankind never fails to affect even those who haven't set foot on the planet.
         </para>

         <para number='2' comment='2nd view from window'>
         Earth slides gently out of view and through the window you can see an expanse of stars filling the blackness with points of light, together making up the milky way - the Galaxy in which the Solar System resides.
         </para>

         <para number='3' comment='3rd view from window'>
         The station turns, bringing into view a cluster of ships hanging in space a short distance from Magellan. You think you can make out which ship is yours! Shuttles moving between the ships and the station are just visible as tiny moving specks.
         </para>

         <para number='4' comment='4th view from window'>
         A huge cargo scow moves ponderously past the window, having just lifted off from the cargo docking bays on wheel two. It drifts away in the direction of Mars, getting smaller and smaller until it finally vanishes from sight.
         </para>

         <para number='5' comment='5th view from window'>
         The view of the stars is interrupted by a maintenance bot which buzzes across from one side of the window to the other. It vanishes from sight, then reappears, traversing a different part of the glass. You realise that as it moves, it is wiping the glass with its soft, cloth-like appendages - cleaning the accumulation of space dust off it to preserve the view.
         </para>

      </section>

   </category>

</para-list>

