<?xml version="1.0"?>

<para-list version='6'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Workshop'>
         It is far too dangerous to move in that direction.
         </para>

         <para number='2' comment='Storage - loc 782'>
         You cannot move in that direction, and in your attempt to do so you trip over a small shrubbery.
         </para>

         <para number='3' comment='Storage - loc 846'>
         You cannot move in that direction, and in your attempt to do so you make a drum of noxious chemicals rock back and forth in a very worrying manner.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='button'>

         <para number='1' comment='Press button - loc 589'>
         A small sign lights up, saying, "Please do not press this button."
         </para>

      </section>

      <section name='marsrat'>

         <para number='1' comment='Marsrat event - reception'>
         The receptionist eyes your marsrat quizically. "Have you been stealing animals from the workshops?" she asks. You reassure her that the rat is not one of Slarti's creations, but she doesn't believe you, and eventually just takes it off you.
         </para>

      </section>

      <section name='spider'>

         <para number='1' comment='In room - 717 - spider delay'>
         A spider suddenly drops out of a tree and lands on you. You can feel all twelve of its little legs tickling your skin as it crawls down your arm and then jumps into a convenient pocket, where it starts to munch on some stale biscuit crumbs.
         </para>

         <para number='2' comment='On leaving workshop'>
         As you leave this part of the workshop, the spider jumps out of your pocket and runs back up your arm. It hurls a strand of web upwards into a tree, then rapidly climbs up it until it is once again sitting on a branch, looking at you.
         </para>

         <para number='3' comment='Get spider'>
         You reach out to the spider, but it scurries away out of your reach, and just sits on a tree branch watching you. Maybe it's laughing!
         </para>

         <para number='4' comment='Get spider - already got it'>
         You try to get the spider out of your pocket, but it eludes your searching fingers. It obviously likes it in there!
         </para>

         <para number='5' comment='Drop spider - carrying'>
         You attempt to grab the spider and remove it from your pocket, but no matter how you fumble you can't get hold of it. Clearly it doesn't want to leave!
         </para>

         <para number='6' comment='Drop spider - not carrying'>
         You are not carrying the spider!
         </para>

         <para number='7' comment='Squash spider'>
         You try to squish the spider but it evades your murderous grasp. Just as well, really - Slarti would not be happy if you killed off one of the creatures he had created.
         </para>

      </section>

   </category>

</para-list>

