# Makefile for the fed2 Sol system

DEST=/var/opt/fed2/maps/sol

all:$(DEST)/brass.loc $(DEST)/brass.msg $(DEST)/brass.xev $(DEST)/brass.xob \
$(DEST)/castillo.loc $(DEST)/castillo.msg $(DEST)/castillo.xev $(DEST)/castillo.xob \
$(DEST)/doris.loc $(DEST)/doris.msg $(DEST)/doris.xev $(DEST)/doris.xob \
$(DEST)/earth.loc $(DEST)/earth.msg $(DEST)/earth.xev $(DEST)/earth.xob \
$(DEST)/graveyard.loc $(DEST)/graveyard.msg $(DEST)/graveyard.xev $(DEST)/graveyard.xob \
$(DEST)/help.loc $(DEST)/help.msg \
$(DEST)/hilbert.loc $(DEST)/hilbert.loc \
$(DEST)/horsell.loc $(DEST)/horsell.loc \
$(DEST)/hunt.loc $(DEST)/hunt.msg $(DEST)/hunt.xev $(DEST)/hunt.xob \
$(DEST)/lattice.loc $(DEST)/lattice.msg $(DEST)/lattice.xev $(DEST)/lattice.xob \
$(DEST)/magellan.loc $(DEST)/magellan.msg $(DEST)/magellan.xev $(DEST)/magellan.xob \
$(DEST)/magrathea.loc $(DEST)/magrathea.msg $(DEST)/magrathea.xev $(DEST)/magrathea.xob \
$(DEST)/mars.loc $(DEST)/mars.msg $(DEST)/mars.xev $(DEST)/mars.xob \
$(DEST)/mercury.loc $(DEST)/mercury.msg $(DEST)/mercury.xev $(DEST)/mercury.xob \
$(DEST)/moon.loc $(DEST)/moon.msg $(DEST)/moon.xev $(DEST)/moon.xob \
$(DEST)/paradise.loc $(DEST)/paradise.msg $(DEST)/paradise.xev $(DEST)/paradise.xob \
$(DEST)/pearl.loc $(DEST)/pearl.msg $(DEST)/pearl.xev $(DEST)/pearl.xob \
$(DEST)/phobos.loc $(DEST)/phobos.msg $(DEST)/phobos.xev $(DEST)/phobos.xob \
$(DEST)/rhea.loc $(DEST)/rhea.msg $(DEST)/rhea.xev $(DEST)/rhea.xob \
$(DEST)/silk.loc $(DEST)/silk.msg $(DEST)/silk.xev $(DEST)/silk.xob \
$(DEST)/snark.loc \
$(DEST)/space.loc $(DEST)/space.msg $(DEST)/space.xev $(DEST)/space.xob \
$(DEST)/starbase1.loc $(DEST)/starbase1.msg $(DEST)/starbase1.xev $(DEST)/starbase1.xob \
$(DEST)/sumatra.loc $(DEST)/sumatra.msg $(DEST)/sumatra.xev $(DEST)/sumatra.xob \
$(DEST)/system.loc $(DEST)/system.msg  \
$(DEST)/titan.loc $(DEST)/titan.msg $(DEST)/titan.xev $(DEST)/titan.xob \
$(DEST)/venus.loc $(DEST)/venus.msg $(DEST)/venus.xev $(DEST)/venus.xob 

include ../data.mk

