<?xml version="1.0"?>

<para-list version='19'>

   <category name='food'>

      <section name='taproom'>

         <para number='1' comment='Buy food - Taproom - 328'>
         The waitdroid brings you a huge platter with a selection of traditional food from the pre-space days of Earth. There's some haggis, a heap of grits, pickled cabbage, raw sea urchin, some tripe, and in case you fancy anything sweet, a plate of semolina, tapioca and sago. It's an odd combination but you eat it all up.
         </para>

         <para number='2' comment='Not enough groats'>
         The taproom does not charge old Earth prices, and you don't seem to have enough groats to eat.
         </para>

      </section>

      <section name='wok'>

         <para number='1' comment='Buy food - Sizzling Wok - 648'>
         A softly shuffling waitdroid bows low then ceremoniously presents you with a sizzling dish containing squid in black bean sauce. It smells delicious, and tastes even better.
         </para>

         <para number='2' comment='Not enough groats'>
         You can't afford to buy any food, and if you try to take some without paying, the chef is likely to use his cleaver on something other than his ingredients.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Corridors'>
         The rock walls of the underground corridor prevent you from going in that direction.
         </para>

         <para number='2' comment='Tunnels'>
         The rock walls of the tunnel stop you from going that way.
         </para>

         <para number='3' comment='Tunnels'>
         The rock walls stop you from going in that direction.
         </para>

         <para number='4' comment='Tunnels'>
         You just manage to stop yourself from walking over the drop off. You kick a pebble over the edge - there is a very long pause before you hear it hit the bottom.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='box'>

         <para number='1' comment='Ex box - it s open'>
         The box is made out of wood that has a blue tinge to it and a grain that forms swirling patterns that look like weird alien faces. The box is open, and is filled with candles.
         </para>

         <para number='2' comment='Ex box - it s closed'>
         The box is made out of wood that has a blue tinge to it and a grain that forms swirling patterns that look like weird alien faces. The box is closed.
         </para>

         <para number='3' comment='Get/take box'>
         You pick up the box, but before you can make off with it one of the Solarium's attendants gives you a piercing stare and clears her throat in a meaningful way, so you put it back down again.
         </para>

         <para number='4' comment='Open box - it s already open'>
         The box is already open!
         </para>

         <para number='5' comment='Open the box'>
         You release the magnetic clasp and open the box, which turns out to be full of candles.
         </para>

         <para number='6' comment='roomex'>
         %s has opened the box, which turns out to be full of candles.
         </para>

         <para number='7' comment='Close box'>
         You close the box and the lid fastens with a snap of the magnetic clasp.
         </para>

         <para number='8' comment='roomex'>
         You hear a snapping noise - %s has closed the box.
         </para>

         <para number='9' comment='Already closed'>
         The box is already closed!
         </para>

         <para number='10' comment='Get candle - box is closed'>
         I can't find anything called candle in the vicinity!
         </para>

         <para number='11' comment='Box is open but already got one'>
         You already have a candle - why don't you use that one before you grab another one?
         </para>

         <para number='12' comment='Give the girl a candle'>
         You take a candle out of the box.
         </para>

         <para number='13' comment='roomex'>
         %s has taken one of the candles out of the box.
         </para>

         <para number='14' comment='Desc of candles if box is open.'>
         The box is full of spherical, rainbow-colored candles.
         </para>

         <para number='15' comment='Desc of candles if box closed'>
         I can't find anything called candle in the vicinity!
         </para>

      </section>

      <section name='candle'>

         <para number='1' comment='Drop candle'>
         You drop the candle, and the wax shatters into a fine rainbow-colored dust. It shimmers in the air for a moment then vanishes.
         </para>

         <para number='2' comment='roomex'>
         The air is suddenly filled with rainbow-colored dust, all that is left of a candle that %s has dropped. The dust shimmers in the air for a moment then vanishes.
         </para>

         <para number='3' comment='Desc of candle in inventory'>
         The candle is in the shape of a sphere, and is made up of layers of different colored wax forming a rainbow pattern. The self-igniting wick protrudes from the center.
         </para>

         <para number='4' comment='Light candle in a bar'>
         You give the candle a little shake and the wick ignites. The candle burns brightly, the flame starting out a bright violet color. But before it can change to a different color as the rainbow wax melts, a waitdroid squawks in horror and up-ends an ice bucket over the candle, extinguishing it before it can set fire to the furnishings.
         </para>

         <para number='5' comment='roomex'>
         A flame ignites! %s has lit a candle which burns a bright indigo color. Then a waitdroid squawks in horror and up-ends an ice bucket over the candle, extinguishing it before it can set fire to the furnishings.
         </para>

         <para number='6' comment='Light candle outside bar - 1'>
         You give the candle a little shake and the wick ignites. The candle burns brightly, the flame changing color as the rainbow wax melts. It starts off violet, sending a shimmer of the blue/red hue over everything in sight.
         </para>

         <para number='7' comment='roomex'>
         A flame ignites! %s has lit a candle which burns brightly, the flame changing color as the rainbow wax melts. It starts off violet, sending a shimmer of the blue/red hue over everything in sight.
         </para>

         <para number='8' comment='Candle burn 2'>
         The candle starts to burn indigo, with a purple flicker that makes shadows dance.
         </para>

         <para number='9' comment='roomex'>
         A candle which %s is holding starts to burn indigo, with a purple flicker that makes shadows dance.
         </para>

         <para number='10' comment='Candle burn 3'>
         The candle burns blue, a flame that has a hint of coldness in it.
         </para>

         <para number='11' comment='roomex'>
         A candle held by %s burns blue, a flame that has a hint of coldness in it.
         </para>

         <para number='12' comment='Candle burn 4'>
         The candle's flame turns green, a color that makes everything around you look slightly sickly.
         </para>

         <para number='13' comment='roomex'>
         The flame of a candle which %s holds turns green, a color that makes everything around you look slightly sickly.
         </para>

         <para number='14' comment='Candle burn 5'>
         The flame of your candle turns yellow, its flickers sending a wash of gold which touches everything you can see.
         </para>

         <para number='15' comment='roomex'>
         The flame of a candle carried by %s turns yellow, its flickers sending a wash of gold which touches everything you can see.
         </para>

         <para number='16' comment='Candle burn 6'>
         Your candle starts to burn orange, the flame glowing brightly in a color that is full of life.
         </para>

         <para number='17' comment='roomex'>
         A candle which %s is holding starts to burn orange, the flame glowing brightly in a color that is full of life.
         </para>

         <para number='18' comment='Candle burn 7 - final'>
         The candle's flame turns a fiery red, as it reaches the last color of the rainbow and burns up the final layer of wax until nothing is left but a faint shimmer of color in the air that fades away.
         </para>

         <para number='19' comment='roomex'>
         The flame of %s's candle turns a fiery red, as it reaches the last color of the rainbow and burns up the final layer of wax until nothing is left but a faint shimmer of color in the air that fades away.
         </para>

         <para number='20' comment='Candle continues to burn in bar'>
         The candle changes color as it burns. A waitdroid notices it and squawks in horror; it up-ends an ice bucket over the candle, extinguishing it before it can set fire to the furnishings.
         </para>

         <para number='21' comment='roomex'>
         A candle held by %s changes color as it burns. A waitdroid squawks in horror and up-ends an ice bucket over the candle, extinguishing it before it can set fire to the furnishings.
         </para>

      </section>

      <section name='dice'>

         <para number='1' comment='Get dice'>
         You pick up the dice and slip them into your pocket. A waitdroid notices you stealing the dice and stares disapprovingly; still, it must happen frequenly because it just rolls its sensors long-sufferingly and gets a replacement set and places them on the bar.
         </para>

         <para number='2' comment='Roll dice - player'>
         You give the dice a vigorous shake, blowing on them for luck...
         </para>

         <para number='3' comment='Roll dice - roomex'>
         There is a rattling sound, and you notice that %s has rolled a pair of dice. They bounce a few times and then fall still.
         </para>

         <para number='4' comment='Dice 1 - option 1'>
         The first die shows one.
         </para>

         <para number='5' comment='Dice 1 - option 2'>
         The first die shows two.
         </para>

         <para number='6' comment='Dice 1 - option 3'>
         The first die shows three.
         </para>

         <para number='7' comment='Dice 1 - option 4'>
         The first die shows four.
         </para>

         <para number='8' comment='Dice 1 - option 5'>
         The first die shows five.
         </para>

         <para number='9' comment='Dice 1 - option 6'>
         The first die shows six.
         </para>

         <para number='10' comment='Dice 2 - option 1'>
         The second die shows one.
         </para>

         <para number='11' comment='Dice 2 - option 2'>
         The second die shows two.
         </para>

         <para number='12' comment='Dice 2 - option 3'>
         The second die shows three.
         </para>

         <para number='13' comment='Dice 2 - option 4'>
         The second die shows four.
         </para>

         <para number='14' comment='Dice 2 - option 5'>
         The second die shows five.
         </para>

         <para number='15' comment='Dice 2 - option 6'>
         The second die shows six.
         </para>

         <para number='16' comment='Drop dice'>
         You drop the dice clumsily and they roll away out of sight.
         </para>

      </section>

      <section name='jukebox'>

         <para number='1' comment='Play jukebox - loc 328 - 1'>
         The jukebox plays a selection of tracks from Pink Floyd's "Dark Side of the Moon" album.
         </para>

         <para number='2' comment='Jukebox - 2'>
         The jukebox plays "Astronomy Domine" by Pink Floyd.
         </para>

         <para number='3' comment='Jukebox - 3'>
         The jukebox plays "Fly Me to the Moon" by Frank Sinatra.
         </para>

         <para number='4' comment='Jukebox - 4'>
         The jukebox plays "Send in the Clones" by Stephen Sondheim.
         </para>

         <para number='5' comment='Jukebox - 5'>
         The jukebox plays "Silver Machine" by Hawkwind.
         </para>

         <para number='6' comment='Jukebox - 6'>
         The jukebox plays "Electric Dreams" by Human League.
         </para>

         <para number='7' comment='Jukebox - 7'>
         The jukebox plays the jazz classic "Moon Maiden" by Duke Ellington.
         </para>

         <para number='8' comment='Jukebox - 8'>
         The jukebox plays "Rocket Man" by Elton John.
         </para>

         <para number='9' comment='Jukebox - 9'>
         The jukebox plays "Walking on the Moon" by the Police.
         </para>

         <para number='10' comment='Jukebox - 10'>
         The jukebox plays "Sleeping Satellite" by Tasmin Archer.
         </para>

         <para number='11' comment='Jukebox - 11'>
         The jukebox plays "Starman" by David Bowie.
         </para>

         <para number='12' comment='Jukebox - 12'>
         The jukebox plays "Cosmic Girl" by Jamiroquai.
         </para>

         <para number='13' comment='Jukebox - 13'>
         The jukebox plays "Calling Occupants of Interplanetary Craft" by The Carpenters.
         </para>

         <para number='14' comment='Jukebox - 14'>
         The jukebox plays "Black Hole Sun" by Soundgarden.
         </para>

         <para number='15' comment='Jukebox - 15'>
         The jukebox plays "Venus as a Boy" by Bjork.
         </para>

         <para number='16' comment='Jukebox - 16'>
         The jukebox plays "2,000 Light Years From Home" by the Rolling Stones.
         </para>

         <para number='17' comment='Jukebox - 17'>
         The jukebox plays "Across the Universe" by the Beatles.
         </para>

         <para number='18' comment='Jukebox - 18'>
         The jukebox plays "Life on Mars" by David Bowie.
         </para>

         <para number='19' comment='Jukebox - 19'>
         The jukebox plays "Planet Claire" by the B-52s.
         </para>

         <para number='20' comment='Jukebox - 20'>
         The jukebox plays "Urban Spaceman" by the Bonzo Dog Doo-dah Band.
         </para>

      </section>

   </category>

   <category name='stats'>

      <section name='int'>

         <para number='1' comment='buy intelligence - no slithy'>
         The droid demands you pay your slithy up front, but you don't have one. There's no chance you can fool it into giving you the treatment without payment; it's too canny for that. It ignores you and continues to potter around the machinery.
         </para>

         <para number='2' comment='basic message'>
         The droid demands you pay your slithy up front, so you hand over the certificate. It points to the chair, and you take a seat. To your consternation, the droid attaches restraints to your arms and legs which prevent you from standing up again. It cackles in derision, "Oh don't worry, it's just a precaution - the pain may make you thrash about a bit, and I don't want you damaging the equipment in your throes of agony."
         </para>

         <para number='3'>
         It presses a few buttons, and the machinery starts to hum.
         </para>

         <para number='4' comment='Already done a stat today'>
         After a few seconds, the hum dies away, and the droid frowns. "Oh dear," it says. "It appears you are rather keen on enhancing your stats - some kind of obsessive fanatic, perhaps? - and you've had a treatment of some kind already today. It's not physically possible to endure the strains of more than one each day. Sad, I wanted to see you suffer for your ideals, but it's not to be. Not today, anyway."
         </para>

         <para number='5'>
         It unstraps you and, somewhat reluctantly, hands back the slithy certificate.
         </para>

         <para number='6' comment='Int already maxed'>
         After a few seconds, the hum dies away. "Oh, now that's a downright shame," the droid says. "It seems I can't take your slithy and watch you writhe in pain after all. Your intelligence is already as high as this machine can manage." It gives the equipment a kick, then regretfully unstraps you and hands back the slithy certificate.
         </para>

         <para number='7' comment='Increase int'>
         The hum increases, and you experience a feeling of pressure inside your head. The pressure turns to discomfort, which turns to pain, which turns to agony, which turns to... thankfully, you black out before your head explodes completely. While you are unconscious, the machine works on your brain, increasing your neural connections, boosting production of chemicals, and generally making it much more efficient.
         </para>

         <para number='8'>
         Suddenly, you wake up and open your eyes. The pain is a distant memory, and your mind seems sharper now. The droid smirks at you - it really did enjoy seeing you in extreme pain. Still, you got what you paid for. It unstraps you, and goes back to whatever it was doing to the machinery before you got there.
         </para>

         <para number='9' comment='Coda if now maxed'>
         As an afterthought, it says, "I won't be seeing you again, I suppose. Your intelligence is just about as high as this old machine can take it. Oh well..."
         </para>

      </section>

   </category>

</para-list>

