<?xml version="1.0"?>

<para-list version='29' editor='standard'>

   <category name='family-jewels'>

      <section name='assistant'>

         <para number='1' comment='talk to the assistant - hello'>
         The assistant bows and asks how he can be of assistance.
         </para>

         <para number='2' comment='job/work'>
         The assistant explains that it is his job to assist the shops patrons in making suitable choices for their purchases. "Having a human in the shop makes Family Jewels more than just an automated purchasing booth," he proudly explains.
         </para>

         <para number='3' comment='moon/selena'>
         "Working on the Moon is an interesting experience," he comments drily, "What with demands for protection money on one hand, and the Galactic Administration's regulations about 'illegal jewelry' on the other."
         </para>

         <para number='4' comment='galactic admin/GA'>
         He explains that the Galactic Administration has defined certain types of jewelry as 'illegal jewelry' which you can't buy without permission.
         </para>

         <para number='5' comment='illegal jewelry (1)'>
         He looks around furtively. "We used to sell so-called illegal jewelry - stuff that had been banned by the authorities. Mostly it was medallions, apparently people kept getting them caught in airlock doors. The Galactic Administration felt decisive action was needed so banned them.
         </para>

         <para number='6' comment='illegal jewelry (2)'>
         He rolls his eyes.
         </para>

         <para number='7' comment='illegal jewelry (3)'>
         "For a while we flouted the ban and sold them under-the-counter, but lately, the authorities have got more... well... authoritarian about the whole health and safety issue, so the owner decided to stop selling them."
         </para>

         <para number='8' comment='family jewels'>
         "Family Jewels was established soon after the colony was opened. With the exception of the so called 'illegal jewelry' most of what we sell is very sophisticated." He waves a hand in the general direction of the displays.
         </para>

         <para number='9' comment='protection'>
         The assistant sighs, "Yes protection. I believe about thirty years ago the current owner's father declined to pay up. A few days later the shop suffered the only robbery it's ever had - and very nearly went bankrupt. Now we just look on the local mafia's payments as part of the cost of doing business."
         </para>

         <para number='10' comment='mafia (1)'>
         The shop assistant looks round nervously, "Although notionally run by part of the Galactic Administration, this colony is controlled by a local mafia. As long as you pay up they don't bother you, and they also make sure no other criminals bother you either."
         </para>

         <para number='11' comment='mafia (2)'>
         He shrugs. "It's not ideal, but at least it makes the Galactic Administration careful about what demands they make on the colonists, though they have got even more zealous about enforcing their 'illegal jewelry' regulations."
         </para>

         <para number='12' comment='nomatch'>
         The assistant tells you that he can't help you, though he does, obviously, know about his work and the Moon colony.
         </para>

         <para number='13' comment='bye'>
         The assistant wishes you a pleasant and fruitful stay on the Moon.
         </para>

         <para number='14' comment='jewels/jewelry'>
         The assistant waves his hand round the shop. "What you see is the bulk of what we carry."
         </para>

         <para number='15' comment='regulations'>
         "The Galactic Administration has regulations on everything it can get its sticky fingers near. The main ones that affect us are the ones relating to the so-called 'illegal jewels'."
         </para>

         <para number='16' comment='buy'>
         The assistant looks at you in disbelief. "I really don't think you could afford any of the items we have on sale."
         </para>

         <para number='17' comment='medallion'>
         "We used to sell medallions, although they were classed as 'illegal jewelry'. Sadly, we don't offer them for sale any more."
         </para>

         <para number='18' comment='egg/easter egg'>
         "The Fedberge egg was a truly fabulous item," the assistant says reverentially. "Fedberge's designers came up with it as an exclusive keyring charm just for us, for a limited period only. It was the first time we offered an item designed to fit on the TenBrane keyring. It's been withdrawn now, but it was a huge success so we may look for more opportunities to sell accessories of this type."
         </para>

         <para number='19' comment='fedberge'>
         "You must have heard of Fedberge, surely?" gushes the assistant. "They are Galaxy-famous. But then perhaps you don't usually move in the circles that can afford that sort... of..." he trails off, not wanting to embarrass you by implying you are not the kind of clientele they generally serve.
         </para>

         <para number='20'>
         "Fedberge have been in operation for centuries - I believe they even date back to before space flight. There's an entry on them in the Encyclopedia Galactica if you want to know more."
         </para>

         <para number='21' comment='keyring/tenbrane'>
         "That was a new departure for Family Jewels. We had never dabbled in keyring charms before; we usually leave those kind of cheap gewgaws to Gallagher's. Of course, our Fedberge egg was in an altogether different class from their offerings." The assistant gives a little sneer, as he shows you his egg.
         </para>

         <para number='22' comment='gallagher'>
         "They like to think they are the top notch, with their strange gadgets and flashy jewelry, but really..." the assistant looks down his nose as he contemplates Gallagher's shop. "They weren't very happy when they found out we planned to sell something to attach to the TenBrane keyring, they seemed to think they had exclusive rights to that kind of accessory, but they were wrong and we had the lawyers to back us up."
         </para>

         <para number='23'>
         He gives a small smile of triumph. "Their complaints came to absolutely nothing in the long run. We sold the egg for the limited period we had intended, and it was a huge success. I am sure we'll sell more keyring charms in the future."
         </para>

      </section>

   </category>

   <category name='food'>

      <section name='alhambra'>

         <para number='1' comment='Buy food - Alhambra - 908'>
         You stuff some money into the popcorn-selling droid's slot and in exchange receive a bag of popcorn so big you can hardly see over it. Any family that could get through this lot in one sitting must have more members than an army regiment! Still, you start munching and find the popcorn is so very more-ish that to your surprise you actually manage to finish the whole bag on your own.
         </para>

         <para number='2' comment='Not enuff groats'>
         You can't afford to buy any popcorn. What desperate times must have befallen you!
         </para>

      </section>

      <section name='cafe'>

         <para number='1' comment='Buy food - cafe - 390'>
         The waitdroid brings you a large plate of cannoli - Italian pastries stuffed with a sweet ricotta-cheese filling. Very delicious! It also pours you a cup of espresso coffee, which is very small but so strong you wouldn't want more than a few mouthfuls. The coffee taste cuts through the sweetness of the cannoli beautifully.
         </para>

         <para number='2' comment='Not enuff groats'>
         You cannot afford to eat here - and this is not a good place to try and get away without paying!
         </para>

      </section>

      <section name='canteen'>

         <para number='1' comment='Buy food - Canteen - 854'>
         You seat yourself at one of the long tables and a dinner-droid appears. You pay it, and it carelessly places a tray full of food in front of you. The service is very slapdash, but the food smells just wonderful! You have been given an enormous plate of meaty lasagna and a big slab of pungent garlic bread. You stuff yourself until it's all gone, and feel so full you don't think you'll need to eat again for a week!
         </para>

         <para number='2' comment='Not enuff groats'>
         You haven't got the groats to eat here, and if you try to get food without paying, the workers will toss you out - and they won't be gentle about it!
         </para>

      </section>

      <section name='casino'>

         <para number='1' comment='Buy food - Casino - 973'>
         A very glamorous humanoid waitress brings you a silver dish containing pretzels, which can be eaten easily one-handed without interfering with the gambling. You crunch your way through them and, surprisingly, feel as full and satisfied as if you had eaten a full meal. These pretzels have been specially formulated to give the energy to allow patrons to continue playing the tables for days at a time.
         </para>

         <para number='2' comment='Not enuff groats'>
         The gambling here is far too rich for you, and so, it would appear, is the food - you can't even afford to buy yourself a bowl of pretzels.
         </para>

      </section>

      <section name='mario'>

         <para number='1' comment='Buy food - marios - 847'>
         Mario's wife, Maria, appears from the kitchen, carrying a steaming plate of spaghetti and meatballs. Mario pauses in his conversation to watch out of the corner of his eye as you tuck in - once he sees you making the appropriate noises of enjoyment, he resumes his chat and everyone else in the bar relaxes. The food is, indeed, wonderful and you eat every last bit, leaving only a few smears of tomato sauce on the tablecloth (and your clothes).
         </para>

         <para number='2' comment='Not enuff groats'>
         A waitdroid points to the sign on the wall which says, "Please do not ask for credit, as a laser burn through the kneecaps often offends." You can't afford to buy a meal in Mario's, and only a fool would try to swindle the staff in here.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='elevator'>

         <para number='1' comment='Elevator from loc 530 down'>
         With a clanking noise, the doors close and the elevator jerks into motion. The descent is not very smooth, and when it reaches the lower level it stops with a severe jerk. Clearly the Selena authorities don't believe in spending money maintaining facilities that are only used by staff.
         </para>

         <para number='2'>
         The doors rattle open and you step out.
         </para>

         <para number='3' comment='Elevator up from 600'>
         There is a screech of tormented metal and the doors slam shut. The elevator machinery gives a groan, the gearing graunches, and it slowly heaves itself upwards to the next level.
         </para>

         <para number='4'>
         The doors open and you walk out.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='Surface'>
         Wandering around on the surface without an escort is strongly discouraged, so you should stick to the marked paths.
         </para>

         <para number='2' comment='Family Jewels - loc 722'>
         There is no way out in that direction, and your attempt to find one knocks a display of sunstones, making it wobble precariously.
         </para>

         <para number='3' comment='Mario s - loc 847'>
         An unpleasant-looking character carrying a violin case blocks your passage.
         </para>

         <para number='4' comment='Rock face - loc 852'>
         Rock walls bar your passage in that direction.
         </para>

      </section>

      <section name='temple'>

         <para number='1' comment='Search loc 412'>
         You move some of the heavy boxes, which tires you a little, but is worth it because you find a hidden doorway. You check that nobody is watching and then slip through it.
         </para>

         <para number='2' comment='Search loc 412'>
         You slip back out of the temple, close the door behind you, and shove the boxes back into their former position to make sure it remains well hidden.
         </para>

      </section>

   </category>

   <category name='navcomp'>

      <section name='about'>

         <para number='1' comment='Info on navigation computer'>
         Arnie himself appears from behind a pile of junk and explains that these are 'surplus' ex-navy Mk 1 navigational computer software upgrades. The software will pilot your ship from the orbit of any planet with an exchange to the orbit of any other planet with an exchange.
         </para>

         <para number='2' comment='nav comp cont'>
         For you, as a special once in a lifetime deal, he will only charge 1,000ig. "A snip," he enthuses. There is only one problem...
         </para>

         <para number='3' comment='nav comp cont'>
         In order to activate the program a special one-off code is needed, and to get that he will need a bribe from you to give a friendly navy programmer. Arnie thinks that a slithy tove would suffice to overcome the programmer's scruples.
         </para>

         <para number='4' comment='nav comp ends'>
         When you enquire why, if it is surplus, a bribe is needed, Arnie just shrugs. "Take it or leave it," he tells you, "it's not like you can get it anywhere else."
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='barbells'>

         <para number='1' comment='Get barbells - loc 719'>
         You bend down and grab hold of the barbells, then try to straighten up. The heavy weight won't move. You try harder, your muscles straining, sweat pouring off you, but they just will not budge. One final, titanic effort, and you manage to lift the barbells about a millimetre off the floor before your back gives out and with a spasm of agony, you let go and attempt to straighten your aching back.
         </para>

         <para number='2' comment='barbells - 2'>
         A trainer, who was watching your feeble attempt, pats you on the shoulder in a patronising fashion and says, "Remember to bend from the knees, not the waist!" This doesn't make you feel any better about your pathetic performance.
         </para>

         <para number='3' comment='roomex'>
         You hear the sounds of straining. It is coming from %s, who is trying - and failing - to lift the barbells. It looks like the effort is very painful!
         </para>

      </section>

      <section name='cards'>

         <para number='1' comment='Get cards - from loc 972'>
         You pick up one of the new packs of cards, but then decide that it might be missed, so change your mind and swap it for an open, used pack.
         </para>

         <para number='2' comment='Drop cards - player'>
         Clumsily, you drop the cards which scatter all over the place. Before you have a chance to collect them up again, a cleaning droid with lightning reactions appears and hoovers up all of the discarded cards, puts them in its trash receptacle, and then trundles off again.
         </para>

         <para number='3' comment='Drop cards - roomex'>
         Clumsily, %s drops a pack of cards which scatter all over the place. A cleaning droid with lightning reactions appears and hoovers up all of the discarded cards, puts them in its trash receptacle, and then trundles off again.
         </para>

         <para number='4' comment='Deal cards - 1 - player'>
         Removing the cards from their box, you start to deal them out, attempting that easy flick of the wrist that professional dealers use. Unfortunately it goes wrong, and you just end up with the cards being thrown every which way. Sheepishly, you gather them up again and put them back in the box.
         </para>

         <para number='5' comment='Deal cards - 1 - roomex'>
         Removing a pack of cards from a box, %s starts to deal them out, attempting that easy flick of the wrist that professional dealers use. Unfortunately it goes wrong, and the cards just end up being thrown every which way. Sheepishly, the wannabe-dealer gathers them up and puts them back in the box.
         </para>

         <para number='6' comment='Deal cards - 2 - player'>
         Removing the cards from their box, you start to deal them out. Unfortunately you failed to notice that you have the pack the wrong way up, so that all the cards are being dealt face up. When you realize that everyone can see the values of all the hands, you gather them up again and put them back in the box.
         </para>

         <para number='7' comment='Deal cards - 2 - roomex'>
         Removing a pack of cards from a box, %s starts to deal them out. Unfortunately, the pack is the wrong way up, so that all the cards are being dealt face up. Noticing that everyone can see the values of all the hands, the wannabe-dealer gathers them up again and puts them back in the box.
         </para>

         <para number='8' comment='Deal cards - 3 - player'>
         Removing the cards from their box, you start to deal them out. Unfortunately your clumsy attempt to look as if you know what you are doing results in you fumbling and dropping a whole bunch of cards on the ground. Whoops! You gather them up again and put them back in the box.
         </para>

         <para number='9' comment='Deal cards - 3 - roomex'>
         Removing a pack of cards from a box, %s starts to deal them out. Unfortunately, the wannabe-dealer fumbles and drops a whole bunch of the cards on the ground. Whoops! Blushing, the incompetent cardsmith gathers them up again and puts them back in the box.
         </para>

         <para number='10' comment='Shuffle cards - 1 - player'>
         To give the cards a thorough shuffle, you split the pack in two and riffle the two halves together so that the cards interleave. By repeating the move several times, you ensure that the cards are thoroughly mixed up.
         </para>

         <para number='11' comment='Shuffle cards - 1 - roomex'>
         In order to give the cards a thorough shuffle, %s takes a pack and splits it in two, riffling the two halves together so that the cards interleave. By repeating the move several times, the cardsmith ensures that the cards are thoroughly mixed up.
         </para>

         <para number='12' comment='Shuffle cards - 2 - player'>
         To give the cards a thorough shuffle, you spread them all out on a handy surface and move them around at random. A few moments of this ensures that the cards are thoroughly mixed up.
         </para>

         <para number='13' comment='Shuffle cards - 2 - roomex'>
         In order to give the cards a thorough shuffle, %s spreads a pack out on a handy surface and moves them around at random. A few moments of this ensures that the cards are thoroughly mixed up.
         </para>

         <para number='14' comment='Shuffle cards - 3 - player'>
         To give the cards a thorough shuffle, you remove some cards from the bottom of the pack and put them on the top, then do this again and again. After a few moments, the cards become thoroughly mixed up.
         </para>

         <para number='15' comment='Shuffle cards - 3 - roomex'>
         In order to give the cards a thorough shuffle, %s takes some cards from the bottom of the pack and puts them on top, then does this again and again. After a few moments, the cards become thoroughly mixed up.
         </para>

         <para number='16' comment='Cut cards - player'>
         Taking the cards out of their box, you cut them to reveal...
         </para>

         <para number='17' comment='Cut cards - roomex'>
         Taking a pack of cards from out of their box, %s cuts them to reveal...
         </para>

         <para number='18' comment='Cut cards - 1'>
         the Ace of Spades.
         </para>

         <para number='19'>
         the Queen of Hearts.
         </para>

         <para number='20'>
         the King of Diamonds.
         </para>

         <para number='21'>
         the Jack of Clubs.
         </para>

         <para number='22'>
         the Ten of Hearts.
         </para>

         <para number='23'>
         the Nine of Clubs.
         </para>

         <para number='24'>
         the Eight of Diamonds.
         </para>

         <para number='25'>
         the Six of Spades.
         </para>

         <para number='26'>
         the Two of Spades.
         </para>

         <para number='27'>
         the Two of Clubs.
         </para>

         <para number='28'>
         the Two of Hearts.
         </para>

         <para number='29'>
         the Two of Diamonds.
         </para>

      </section>

      <section name='holocard'>

         <para number='1' comment='Get holo-card - already got one'>
         Possession of more than one holo-card is considered a sin by the members of the temple, since it is against the principles which proclaim that the Martians' gifts should be shared equally.
         </para>

         <para number='2' comment='Give her a card'>
         You pick up one of the holo-cards. Treat it carefully, because it is a holy item for cult members.
         </para>

         <para number='3' comment='roomex'>
         %s has picked up one of the holo-cards.
         </para>

         <para number='4' comment='Squeeze holo-card'>
         You squeeze the holo-card. It lights up and a 3D image appears to float in the air above it. It shows a scene from the life of Gaelaan, the famous moment when he receives his revelation. He is gazing upwards, and his face reflects awe, shot through with surprise and even a tinge of regret. After a few moments, the image fades away.
         </para>

         <para number='5' comment='roomex'>
         A 3D image appears, produced by a holo-card that %s is holding. It shows a scene from the life of Gaelaan, the famous moment when he receives his revelation. He is gazing upwards, and his face reflects awe, shot through with surprise and even a tinge of regret. After a few moments, the image fades away.
         </para>

         <para number='6' comment='Out of juice'>
         Nothing happens when you squeeze the holo-card; it has run out of power. You will have to get it recharged at the temple from which you got it.
         </para>

         <para number='7' comment='Recharge holocard'>
         You hold the holo-card against the panel on the recharger. A light on the unit glows red for a moment, then turns green, indicating that the card is now fully powered up.
         </para>

         <para number='8' comment='Roomex'>
         The light on the recharger changes to red as %s holds a holo-card against it, then it turns green again to show that the card is now fully powered up.
         </para>

         <para number='9' comment='Wrong place to recharge'>
         There is nothing here that will recharge the holo-card. You will need to take it back to the temple from whence it came.
         </para>

         <para number='10' comment='Drop holocard'>
         You let the card fall to the ground, and it breaks into pieces with a crunching sound. Oh dear. Better hope no members of the cult saw you; they would be furious at the destruction of a holy icon.
         </para>

         <para number='11' comment='roomex'>
         There is a crunching sound. %s has dropped a holo-card to the ground, and it has broken into pieces.
         </para>

      </section>

      <section name='krystal'>

         <para number='1' comment='Examine Krystal'>
         Krystal is the Galaxy's supreme gossip columnist, working for magazine Galactopoliton. She has had one eye replaced with a camera so everything she sees is recorded to be used in her ascerbic columns. A holo-pencil is stuck behind one ear. She will talk to anybody in the hope of getting some good gossip, so say hello to her.
         </para>

         <para number='2' comment='kiss/hug/grope krystal'>
         Krystal draws back from you. "Woah there, sweet thing," she says. "I'm not into any of that physical stuff. I'll watch somebody else doing it, specially when they didn't ought to have been, but won't get involved myself. So keep your hands, and your lips, and any other body part, to yourself if you please."
         </para>

         <para number='3' comment='hello boys'>
         Krystal looks up from the tape she is editing and smiles at you. "Well, hello honeybun, aren't you the cutest little guy?" She looks delighted to see you. "What kind of gossip do you have for me, I wonder... I hope it's really juicy."
         </para>

         <para number='4' comment='hello girls'>
         Krystal looks up from tape she is editing and smiles at you. "Well, hello honeybun, aren't you a gorgeous babe?" She looks delighted to see you. "What kind of gossip do you have for me, I wonder... I hope it's really juicy."
         </para>

         <para number='5' comment='hello things'>
         Krystal looks up from tape she is editing and smiles at you. "Well, hello honeybun, aren't you the sweetest being?" She looks delighted to see you. "What kind of gossip do you have for me, I wonder... I hope it's really juicy."
         </para>

         <para number='6' comment='krystal/who'>
         "Krystal the Muse I used to be called when I started out," she explains. "I was so good at finding out people's secrets, they thought I had some kind of psychic power." She giggles at the idea.
         </para>

         <para number='7'>
         "It was rubbish, of course, I was just very good at my job. Still am, sweet thing - after all, I have been collecting gossip for centuries."
         </para>

         <para number='8' comment='gossip'>
         "Gossip is the lifeblood of the Galaxy, sweetie," Krystal says. "A good rumor moves faster than light, spreading from planet to planet by means unknown to science. I merely assist in that process, refining the gossip down so that I report on the truly juicy nuggets of scandal."
         </para>

         <para number='9' comment='scandal'>
         "Scandal is what people want; they crave information about those in high places getting up to things they oughtn't," explains Krystal. "If a celebrity has a dirty little secret, it's not just my job, but my duty, to ferret it out and expose it to the full glare of publicity. It's my calling. And I love it, I really do, it makes me tingle."
         </para>

         <para number='10' comment='celebrit'>
         "The public is obsessed with celebrities, sugar; always have been and always will be. The sole purpose of Galactopoliton magazine is to tell you all about celebrities. And that doesn't mean people who have achieved something important - far from it. The more useless a person in the public eye is, the more the public wants to know about them. Those who are famous for being famous get more attention than those who have a skill of some kind."
         </para>

         <para number='11' comment='galactopoliton'>
         "The whole purpose of Galactopoliton is to report on the doings of celebrities. Any trivial fact will do - their favorite color, the type of tentacle sheaths they wear, where they hibernated last season. But it's my job to find out the stuff they don't want us to report. It's the flip side of being famous; if you want to use the media to further your career, you've also got to accept that they're going to dig up the dirt on you."
         </para>

         <para number='12' comment='dirt'>
         "Nobody is squeaky clean. They've all done something they're ashamed of. Of course, what kind of thing that is will depend on what they are famous for. Who cares if a rockstar gets involved in something scandalous involving sex with aliens or abusing substances? Not me, not you, not anyone. Ah, but if a Galactic Administration official does that then the public gets very moralistic, and I can make a lot of money dishing the dirt.
         </para>

         <para number='13'>
         "Some holostars can raise a ruckus all they want; they are expected to be wild and crazy, that's the image they have built, they can get away with all kinds of appalling behavior. But then there's the ones with the cleancut images, who are seen as role-models for young people. Woe betide them if they get caught with their metaphorical trousers down! With any luck, I'll be there to snap that image at the most embarassing trouser-less moment."
         </para>

         <para number='14' comment='rockstar'>
         "Take the Rolling Stones," says Krystal. "Nearly 500 years they have been touring, and they may have faces as wrinkled as a Martian's hide, but they can still party hard with the best of them.
         </para>

         <para number='15'>
         "Keith has ingested more pharmaceuticals than the entire output of Phobos, Mick gets seen having relations with beings from all over the Galaxy, and not only does the public not get outraged, they expect the Stones to behave like that because it's what aging rockers do.
         </para>

         <para number='16'>
         "On the other hand, if the members of New Droids on the Block, or Z Club 9, or any of those bands designed to appeal to youngsters, started taking drugs or cavorting with alien hotties, that would be a major scandal. That's just the kind of thing I love to find out about!"
         </para>

         <para number='17' comment='politician'>
         "The people, gotta love them; they have such a high expectation of those who take public office, and GA bureaucrats take great pains to keep their peccadilloes out of the press," she explains. "Mind you, it's not as if a predilection for sex and drugs and so on actually means an official can't do his, her or its job, but the people don't like it.
         </para>

         <para number='18'>
         "It's odd, but they don't get nearly so upset when financial scandals come to light, or bribery and corruption, or even massive incompetence. But I don't concern myself with those; I'm not a newsdroid."
         </para>

         <para number='19' comment='holostar'>
         "Image is everything in the holowood," Krystal tells you. "Right at the start of a career, an aspiring holostar gets channelled in a particular direction, and whatever image they choose, or have imposed on them, that's what they are stuck with. It's almost impossible to change the image later, although a few have managed it."
         </para>

         <para number='20'>
         She flips through the recordings she is editing and then shows you a hologram of simstar Brix Chanterel, with his shirt off, his well-developed muscles rippling as he breathes in and out. "Look at this guy," she says. "Gorgeous but dumb, right? A great action hero, sexually attractive, expected to be a bit wild but not to have an opinion on anything important.
         </para>

         <para number='21'>
         "He's actually very bright - went to university and got a degree before he became a holostar. But the public doesn't want him to be; his image is of the big, strong, stupid guy. Nobody would care if he was caught sleeping with an Argolian triplet nest, but they'd be pretty disgusted if they saw a picture of him reading a book."
         </para>

         <para number='22'>
         She flips a bit more and comes up with virginal beauty Twinkle, star of moralistic holos promoting honesty and fidelity. "On the other hand, little miss perfect here - she's a cutey, isn't she? - is seen as the perfect role-model for our youth, so any hint of scandal attached to her would end her career in a heartbeat.
         </para>

         <para number='23'>
         "Sad to say, I've been searching for years, but have never found anything to report on. I cannot believe she is as innocent as her image paints her, so I guess she must have great security. I'll keep looking. One day I'll catch her out."
         </para>

         <para number='24' comment='newsdroid'>
         "Well, cupcake, newsdroids don't shy away from gossip, of course, but they do a lot better at the real important stuff, like politicians on the take or businessthings on the make. I could have gone down that route; I worked for the original Fed newspaper, Line Noise, for a while, but soon realized I preferred the celebrity scandal circuit.
         </para>

         <para number='25'>
         "Besides, at Galactopoliton, I can do what I want; I don't think Hazed lets the Fed2 Star newsdroids off the leash much."
         </para>

         <para number='26' comment='hazed'>
         "I have the greatest respect for her as the editor of the Star, but I wouldn't want to work for her," Krystal says with some fervour. "She's a stickler and if things don't go just the way she likes them, she turns vicious."
         </para>

         <para number='27'>
         She leans forward to confide in you. "There's a reason she employs droids in her office rather than flesh and blood reporters; she can get away with treating them like slaves. I hear she beats them regularly, and if one of them messes up, it gets killed and converted into some piece of office furniture.
         </para>

         <para number='28'>
         "You will note that when a newsdroid gets a byline in the Star, it doesn't last very long... whatever happed to Robby, who started writing its own stories a few years ago? And then we haven't heard anything from Dot Matrix in a good while; I wouldn't be surprised if it had come a cropper and was now a heap of scrap metal in the corner of Hazed's office.
         </para>

         <para number='29'>
         "It's only the rare organic reporters like Hally Godarkly that seem to have any shelf life at the Star, and even they have to walk carefully. So no, I won't be going to work for Hazed."
         </para>

         <para number='30' comment='star'>
         "Oh honey, the Fed2 Star's a very different publication from the one I work for - it's more general, covering all areas of news and reportage, and it comes out weekly so everything is a bit slapdash. Galactopoliton is quarterly so all the articles have been a long time in the making, and we can polish them to perfection. Not that I am looking down on the Star, of course, there is a place for trashy journalism, I am sure."
         </para>

         <para number='31' comment='moon/where'>
         "I'm on the moon because I heard a rumor that Gariux Gigorax, the Trantorian opera star, was coming here for vacation. My sources tell me that he's on the verge of divorcing his wife and taking up with a trio from Algol. Well, he does have three heads so I guess it would make sense for him to get a babe for each of them...
         </para>

         <para number='32'>
         "But so far, I've not had much luck in getting close to him. They take security very seriously on Earth's moon, and don't welcome snoops of any kind. I've already been threatened by the charming gentleman who owns this bar."
         </para>

         <para number='33' comment='mario/bar'>
         Krystal lowers her voice. "Mario is a piece of work alright. He was nothing but a two-bit hoodlum when I was a young recorder, but he made himself invaluable as an enforcer to the moon's powers that be, until he took control of the security of the whole place. Running this bar is just a convenient front for him. Right now, he's mildly ticked off with me; I don't want to do anything to get him really angry!"
         </para>

         <para number='34' comment='nomatch'>
         "I don't know anything about that, honey," Krystal says, "but if you tell me more maybe there's a story in it."
         </para>

      </section>

      <section name='menella'>

         <para number='1' comment='Vocab - hello'>
         Menella smiles brightly at you. "Hello", she says, "I'm Menella." She points to her name tag, which reads 'Menella Bute Smedley IV', in a rather violent purple writing.
         </para>

         <para number='2' comment='Vocab - job &amp; who'>
         "I'm the project manager for the Selena City Works and the resident expert on projects, schedules, charts and the like." She smiles deprecatingly.
         </para>

         <para number='3' comment='vocab - charts'>
         "Obviously, as a project manager I use a lot of them," she explains. "Did you know, that in pre-Ming times they used to use two dimensional gant charts? I just found that out the other day. Only two dimensions! Poor things."
         </para>

         <para number='4' comment='vocab - schedule I'>
         "Schedules, my dear, are the meat and drink of a project manager! I am the queen of schedules." She gestures theatrically. "I am -the- inner system specialist on schedules, everyone consults me." She lowers her voice conspiratorially, "Even Freya herself once asked for my help when she was trying to do a schedule for Bella."
         </para>

         <para number='5' comment='vocab - schedule - II'>
         She mutters something that is difficult to hear, but it sounds suspiciously like, "A losing proposition if there ever was one."
         </para>

         <para number='6' comment='vocab - project I'>
         "Project management." Her eyes light up, and your heart sinks. Oh no! You've triggered off a project bore. "Well..." she says and proceeds to lecture you at length about the ins and outs of project management.
         </para>

         <para number='7' comment='vocab - project II'>
         After a few minutes your attention starts to wander, and you begin watching a moonbug making its way across the wall behind Menella. It may be your imagination, but just before it slips into a crack in the wall and vanishes, it seems to give Menella a two fingered salute!
         </para>

         <para number='8' comment='vocab - project III'>
         ...
         </para>

         <para number='9' comment='vocab - project IV'>
         "So there you have the long and the short of it..." Menella finishes her lecture. You check your chrono and realise that she's been going on for two and a half hours. No wonder you feel hungry.
         </para>

         <para number='10' comment='vocab selena I'>
         "Selena City? It was a marvel of engineering when it was built - the very first habitat not on Earth. It was actually built on time and in budget!" She pauses for your comment and you mumble something about that being most impressive. "All in a day's work for a project manager." She waggles her index finger at you.
         </para>

         <para number='11' comment='vocab selena II'>
         "I have the original project schedules - they're on some sort of plant fibre material. The plans have been handed down the generations by each project manager to his or her successor," she informs you striking what she obviously believes is a dramatic pose.
         </para>

         <para number='12' comment='vocab - sol I'>
         "I don't very often leave the inner system," she tells you, "I prefer it here because the aliens seem to mostly keep to the outer system. Not that I have anything against aliens, of course," she hastens to add.
         </para>

         <para number='13' comment='vocab - sol II'>
         "Sometimes, though, I need to consult in person with my opposite number in the outer system - she's on Titan, and I have to travel out to the system borders. I do find it a bit fraught." She shudders ostentatiously.
         </para>

         <para number='14' comment='vocab - aliens I'>
         "Well", she says, with a quick look round to make sure no one else can hear what she is saying, "I don't want to sound biased, but they're not like us you know." Her manner becomes more confidential after this astounding revelation. "I mean to say, arachnids. And what about the slimy ones leaving their trails all over the floor.
         </para>

         <para number='15' comment='vocab - aliens II'>
         "I suppose we should really feel sorry for the poor benighted creatures. I'm told that we have a responsibility to help them reach the heights of our own cultural sophistication." She strikes a noble pose. "It's the Earthman's burden, as they say."
         </para>

         <para number='16' comment='vocab - bella I'>
         "Bella actually came in here to visit me once, you know." She preens. Looking round she lowers her voice in a furtive manner. "Bella is a project manager's nightmare, she only knows three measurements of time - 'two weeks', 'before Xmas', and 'in due course'."
         </para>

         <para number='17' comment='vocab - bella II'>
         Menella leans closer and her voice drops to a whisper. "It's common knowledge amongst the project manager community..." you have visions of serried ranks of project managers, stretching into the distance, "...that Bella was late with the creation of the Federation universe!
         </para>

         <para number='18' comment='vocab - bella III'>
         "The rumour is that she only got away with it because time didn't exist before the start of the universe. Mind you, there is a school of thought that says she cheated and ran time backwards to make it appear on schedule!" She taps the side of her nose. "Enough said."
         </para>

         <para number='19' comment='vocab - hazed I'>
         "Hazed? She drops in regularly to chat. Why, only the other day she offered me a chocolate from that box she carries all the time. She said I could have any of the ones with teeth marks on them, because she doesn't like hard centres. I'm sure she has a miniature teleporter in the box. When I took the chocolate, another immediately materialised in it's place!
         </para>

         <para number='20' comment='vocab - hazed II'>
         Hazed and I are like that." She entwines her fingers to show just how 'close' she and Hazed are purported to be. This was probably not a good idea on Menella's part, since she then needs your assistance to untwine them.
         </para>

         <para number='21' comment='vocab - freya'>
         "Of course I know Freya", she pouts indignantly. "She's the patron demi-goddess of project managers. Freya and I go back years, we went to the Horsell High School prom together."
         </para>

         <para number='22' comment='vocab - bye I'>
         "Goodbye", she trills, "Doooo come and see me again, it's been soooo nice chatting to you."
         </para>

         <para number='23' comment='vocab - bye II'>
         As you turn to go, her communicator chimes and she answers it. "Yes sir. At once, sir. I'm sorry about the cost overrun, sir, but you know how it is with arachnids, it's impossible to get them to use all their legs. What! You hold me responsible, but how could I know? What do you mean it's my job to know..."
         </para>

         <para number='24' comment='vocab - nomatch'>
         Menella looks at you blankly; obviously the concept is outside her experience!
         </para>

      </section>

      <section name='wrench'>

         <para number='1' comment='Get sonic wrench'>
         It is much heavier than it looks!
         </para>

         <para number='2' comment='Drop sonic wrench'>
         The wrench lands on your foot, and the sonic gripping operation starts to squeeze your toes (or equivalent) in a painful fashion. With a shout, you kick the wrench away across the room, where it lands with a noisy clatter.
         </para>

         <para number='3' comment='Roomex'>
         With a shout, %s kicks the wrench across the room - it must have landed on a foot or equivalent body part - where it lands with a loud clatter.
         </para>

         <para number='4' comment='Wrench is returned - room msg'>
         A moment later, a small droid skitters across the room and retrieves the wrench, presumably to return it to the place it belongs.
         </para>

         <para number='5' comment='Take wrench away when leaving'>
         As you step out of the workshop, a small droid skitters up and tells you that it is forbidden to remove tools from the room unless you have authorization. It demands that you return the sonic wrench, and won't let you leave until you do. You shrug and hand it over - you didn't really want it, anyway!
         </para>

         <para number='6' comment='Use wrench'>
         That is not possible, for a number of reasons: 1) there is nothing here that needs to be tightened or loosened; 2) you do not know how to operate the wrench; and 3) you are not a trained and licensed operator, so using this equipment would be against the health and safety regulations.
         </para>

      </section>

   </category>

</para-list>

