<?xml version="1.0"?>

<para-list version='1'>

   <category name='food'>

      <section name='knobs'>

         <para number='1' comment='Buy food - Knobs/Knockers 453'>
         You are served a sandwich of succulent, spicy hot pastrami, sliced thin and piled high onto sour rye bread, with a smear of mustard. This sandwich is a complete meal in itself, and after eating it you feel wholly satisfied.
         </para>

         <para number='2' comment='No money'>
         You start to order some food, then realize with embarrassment that you are completely out of cash. Guess you'll have to go hungry!
         </para>

      </section>

   </category>

</para-list>

