<?xml version="1.0"?>

<para-list version='1'>

   <category name='food'>

      <section name='teahouse'>

         <para number='1' comment='Buy food - Pearl Teahouse 264'>
         You signal to one of the droids. It bows to you and fetches you a cup of tea and a plate of delicacies: smoked trout mousse wrapped in gravlax on cucumber rounds. You alternate bites of the small snacks with sips of tea; a most satisfying mingling of flavors.
         </para>

         <para number='2' comment='No money'>
         You signal to one of the droids. It bows to you but informs you regretfully that you do not have the necessary funds to eat here.
         </para>

      </section>

   </category>

</para-list>

