<?xml version="1.0"?>

<para-list version='11' editor='standard'>

   <category name='buggy'>

      <section name='alpha'>

         <para number='1' comment='Press button'>
         You haven't said which button you want to press!
         </para>

         <para number='2' comment='Button 2 - buggy already there!'>
         Nothing happens when you press button 2 - because you are already at the Alpha Dome!
         </para>

         <para number='3' comment='press button 1 - move to LP'>
         With a whirring sound, the buggy lifts off the surface and slowly drifts towards the start of the magnetic track that leads to the shuttle pad. Once it finds the track and is facing the right way, it picks up speed and soon you can no longer see the Alpha Dome - just empty rock all around you.
         </para>

         <para number='4' comment='button 1 - arrive at alpha'>
         Before long, the visitors dome comes into view. The buggy slows then stops on the edge of the shuttle pad. The doors spring open and the computerized voice says, "Shuttle Pad", so you get out.
         </para>

         <para number='5' comment='Press button 3'>
         The computerized voice says, "We are very sorry, but the laboratories in Beta Dome are currently closed to visitors." You'd better pick another destination.
         </para>

         <para number='6' comment='Press button 4'>
         The computerized voice says, "Warning. Gamma Dome is a high-security facility. Access prohibited for non-Phobos personnel." It sounds quite firm about it, too! You'd better pick another destination.
         </para>

      </section>

      <section name='auth'>

         <para number='1' comment='If player already has keycard'>
         Tracey shows a tiny spark of intelligence, in that she notices you already have authorization to use the buggies, so she doesn't need to issue you with a new keycard.
         </para>

         <para number='2' comment='Give player keycard'>
         Tracey laboriously types your details into her computer, misspelling your name twice before finally getting it right. She presses a button and a keycard pops out of a slot in the desk with such force that it flies into the air like a piece of toast. You catch it before it falls under the desk.
         </para>

      </section>

      <section name='enter'>

         <para number='1' comment='Get into buggy - no auth'>
         The door to the buggy will not open. A red light flashes and a computerized voice says, "You are not authorized to use a buggy. Please enter the Visitors Center to obtain the necessary authorization."
         </para>

         <para number='2' comment='Got auth - enter buggy'>
         As you open the buggy door, a green light illuminates, and a synthesized voice says, "Authorization checked. Buggy doors opening." You climb in and seat yourself.
         </para>

      </section>

      <section name='pad'>

         <para number='1' comment='Press button'>
         You haven't said which button you want to press!
         </para>

         <para number='2' comment='Button 1 - buggy already there!'>
         Nothing happens when you press button 1 - because you are already at the landing pad!
         </para>

         <para number='3' comment='press button 2 - move to alpha'>
         With a whirring sound, the buggy lifts off the surface and slowly drifts towards the start of the magnetic track that leads to the Alpha Dome. Once it finds the track and is facing the right way, it picks up speed and soon you can no longer see the visitors dome or the landing pad - just empty rock all around you.
         </para>

         <para number='4' comment='button 1 - arrive at alpha'>
         Before long, a dome comes into view. The buggy slows then stops outside the dome airlock. The doors spring open and the computerized voice says, "Alpha Dome", so you get out.
         </para>

         <para number='5' comment='Press button 3'>
         The computerized voice says, "We are very sorry, but the laboratories in Beta Dome are currently closed to visitors." You'd better pick another destination.
         </para>

         <para number='6' comment='Press button 4'>
         The computerized voice says, "Warning. Gamma Dome is a high-security facility. Access prohibited for non-Phobos personnel." It sounds quite firm about it, too! You'd better pick another destination.
         </para>

      </section>

   </category>

   <category name='food'>

      <section name='morph'>

         <para number='1' comment='Buy food - Morph Bar - 340'>
         A waitdroid deposits a plate of morphood in front of you - a foodstuff invented on Phobos, needless to say. As you watch, it changes from solid to liquid and back again, the color changes, and - as you find out when you pluck up the courage to actually eat some - so does the taste.
         </para>

         <para number='2'>
         You place some in your mouth and feel it change disconcertingly from steak, to chocolate, to soup, to ice cream, to bread... each mouthful does the same, leaving you reeling from the very strange gustatory experience.
         </para>

         <para number='3' comment='Not enuff groats'>
         You are so hard up you cannot even afford to buy yourself a meal - and Phobos is not run as a charity!
         </para>

      </section>

      <section name='noshery'>

         <para number='1' comment='Buy food - Noshery - 586'>
         Seating yourself at one of the communal tables, you ask for whatever is on offer today as the main meal. With a buzzing noise and a flash of light, a plate materializes in front of you containing a large slice of steak and kidney pudding: thick, meaty chunks of steak, tender slices of lamb kidneys, all in a rich gravy, surrounded by a fluffy case of suet pastry. It is served with a heap of mashed potato and some minted peas.
         </para>

         <para number='2'>
         You eat it all and contemplate licking the remains of the delicious gravy off the plate, before reluctantly deciding it wouldn't be polite.
         </para>

         <para number='3' comment='Not enuff groats'>
         Only Phobos staff can eat in the Noshery without paying - if you don't have any money, you will just have to go hungry.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='keepout'>

         <para number='1' comment='Turn back non-staff'>
         As you walk away from your shuttle, a figure in a white environmental suit hurries up to you. "No, stop right there," he says. "Sorry, we've got a bit of a contamination problem at the moment, you have to leave." He pushes you back towards your shuttle and won't allow you to go anywhere else.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='keycard'>

         <para number='1' comment='Examine keycard'>
         The keycard authorizes you to use a buggy to travel between the domes on Phobos. The card has biometric properties and has acclimated itself to your uniqueness: it is made out in the name of %s.
         </para>

         <para number='2' comment='Drop keycard'>
         As part of the Galactic Administration's campaign against litter, the keycard is super-bio-degradable - it is designed to disintegrate completely on contact with the ground. You can now confirm that this anti-litter initiative works perfectly.
         </para>

      </section>

      <section name='tracey'>

         <para number='1' comment='Kiss/hug/grope/get Tracey'>
         She may be stupid, but she is adept at avoiding unwanted amorous attentions. As you lean over the desk towards her, she backs away and picks up her comm unit. "Uh-huh," she says, wagging a finger at you. "No touching, or I will call security."
         </para>

         <para number='2' comment='hello'>
         Tracey repeats her mantra: "Welcome-to-Phobos-my-name-is-Tracey-how-may-I-help-you." She looks at you briefly with a vacant stare, waiting for you to tell her what you want.
         </para>

         <para number='3' comment='tracey/who'>
         "Tracey Alamanadina," she introduces herself, "And I am pleased to meet you, %s. I am the receptionist for The Phobos Pharmaceuticals Cooperative Visitors Center...." She stumbles a little over the long words... "and I am here to help you."
         </para>

         <para number='4'>
         That seems to be the end of her official welcome; she relaxes slightly now she is not having to recite what she has obviously memorized with great difficulty, and starts talking more naturally, using what passes for teen slang these days. "I've been working here for decs and it's never a dull moment, you know?" She gives a little giggle and snaps her chewing gum. "The scientist guys, they come up with new stuff all the time, you know?"
         </para>

         <para number='5' comment='reception/job'>
         "All my buds thought it was real pash, me getting such an exotic post, you know?" Tracey tells you with a high-pitched giggle. "They're stuck in these, like, drear places with totally boring accountants and such. Real terror, you know?" You nod to indicate that you do, indeed, know.
         </para>

         <para number='6'>
         "My Unc got me this post, he's something crucial in the government, you know? He said it would be good for me to, what was it, broaden my hor... hori... something, anyway. I didn't want to say gbye to my buds, but now I've made some new buds here, and they really are pash, quite the biz, you know?"
         </para>

         <para number='7' comment='scientists'>
         "They are some wild guys, always doing weird stuff, but they come up with these things that make loads of groats for the co-op, you know? The astro-turf, living computers, living fur, clothes made out of real flowers..." She shrugs, drawing your attention to her amazing dress.
         </para>

         <para number='8'>
         "People think scientists are nerdy and all that, but some of them here are real ruggedy, you know? And they have great parties." She smiles and giggles.
         </para>

         <para number='9' comment='Phobos/where'>
         "It is odd living on such a small planet. If they didn't have the fake gravity thingy it would be real square. I was brought up on Earth and I miss not going outside, you know? But the scientists have come up with all kinds of growing stuff that stops the rock being too sad."
         </para>

         <para number='10' comment='Earth'>
         "Earth is my real home," she confides. "I'll go back there one day and get married and settle down. This is just temp. I mean, Earth's the only real planet in the system, you know? The rest are just colonies. Earth's where the important stuff happens."
         </para>

         <para number='11' comment='buggy'>
         "If you want to use a buggy you need a keycard. I can't just give you one, you need to formally ask me for authorization. Sorry. It's the rules. Sorry. I can't break the rules. It's more than my job's worth. Sorry."
         </para>

         <para number='12' comment='dress/clothes'>
         "Oh yeah, it's really wack, you know? Just one of the amazing things cooked up by those scientists. The dress is really made of real flowers, and the blossoms move around as they follow the light. It lasts about a week then the petals start dropping off, which is a bit of a mizz, but I guess they'll get that bug ironed out soon, you know?"
         </para>

         <para number='13' comment='ming'>
         "Who?" Tracey has obviously never heard of the ex-Emperor; the look on her face is one of complete and utter incomprehension.
         </para>

         <para number='14' comment='emperor'>
         She giggles, "Now you're being silly. We don't have an Emperor any more, we have the Galactic Administration. Unc Silus does something in their headquarters. He works on a real high floor, the view is really wack, you know?"
         </para>

         <para number='15' comment='galactic admin/GA'>
         "When I want to go back to Earth my Unc Silus will get me a job in the GA HQ, he says. That'll be pash, you know?"
         </para>

         <para number='16' comment='flowers'>
         She smiles at you broadly. "You noticed my dress! Yes, it really is made of real live flowers. Amazing, you know?"
         </para>

         <para number='17' comment='computers'>
         "The living computers are creepy, you know?" Tracey tells you. "They have feelings and moods and stuff, just like real people do. I don't know if I like that. I mean, what if they just don't feel like doing stuff one day, you know? I mean, what if a computer got in a bad mood, you know? I mean, when I'm in a bad mood I sometimes throw things, but a computer might mess up something serious, you know?" She shudders at the thought.
         </para>

         <para number='18' comment='furs'>
         "Living furs are totally wack," Tracey says. "I love them, they're like a cross between a blanket and a pet. I've got three in my room, and I just wrap myself up in them and it's like being in the middle of a heap of furry animals, all warm and soft and snug..."
         </para>

         <para number='19' comment='living'>
         "They specialize in living stuff here," Tracey explains. "Living furs, living computers, and just look at my dress!"
         </para>

         <para number='20' comment='nomatch for Tracey'>
         Tracey stares at you with a look of complete and utter incomprehension on her face. She doesn't understand what you just asked her about.
         </para>

         <para number='21' comment='buds'>
         "They're a real wack crew," Tracey tells you. "There's Jem and Kojo and Fazackerly and Minto and Mandy and Jackie and the four Marys - they're clones you know - and my best bud of all, Bunty." She beams at you, as if she expects you to have heard of these people.
         </para>

         <para number='22' comment='gravity'>
         "Oh, all that science stuff is beyond me," Tracey says with a giggle. "I don't know how the gravity thingy works. You'll have to ask one of the scientists I guess."
         </para>

         <para number='23' comment='unc/silus'>
         "I don't know what it is he does for the Galactic Administration, but it must be real important because he works all the time - I mean, he never takes any time off, you know? And he's always being called in to deal with stuff in the middle of the night, you know? But I don't know what stuff."
         </para>

         <para number='24' comment='help'>
         "That's my job, to help you," Tracey assures you, although the complete lack of any vestige of intelligence in her gaze doesn't fill you with confidence that she will be able to!
         </para>

         <para number='25' comment='clue/magellan/victor'>
         "If you are doing the Magellan Society treasure hunt, I am not supposed to give you any clues. Victor's told me not to try to help you, and what Victor says, I have to do, you know?" She giggles.
         </para>

         <para number='26' comment='dna/sculture/spiral'>
         "Oh, you saw that, did you?" asks Tracey. "Well I guess it's hard to miss, hanging there right inside the entrance, you know? One of my buds explained to me what it was supposed to be, but I didn't really understand. Something to do with biology, I think..." she looks at you blankly.
         </para>

         <para number='27' comment='dome'>
         "There's four domes on Phobos," Tracey explains. "This dome is the Visitors Center, then there's Alpha, Beta and Gamma domes. There's buggies that let you drive to the other domes, they are too far to walk."
         </para>

         <para number='28' comment='alpha'>
         "Alpha Dome is where we all live, all the permanent people on Phobos, that's the scientists and the other ones like me."
         </para>

         <para number='29' comment='beta'>
         "Beta Dome is the main laboratory dome. Normally you could visit there, but it's off-limits just now because of some security problem or something."
         </para>

         <para number='30' comment='gamma'>
         "Oh, you can never go to Gamma Dome," Tracey exclaims. "Even I can't go there, it's totally out of bounds, you know? That's where they do the dangerous stuff and the top secret stuff, you know?"
         </para>

         <para number='31' comment='morph'>
         "Oh, it's over there," Tracey says, waving in a vaguely westerly direction. "I don't drink there, it's for visitors, you know? Well, not usually, although when my Unc Silus comes to call we grab a bite there to save time, because he's always so busy, you know? But I never get drunk in the Morph Bar, the decor is just too strange to mix with alcohol, you know?"
         </para>

         <para number='32' comment='dorm/accommodation'>
         "The dorms are that way," Tracey tells you and points south. "There's nobody staying there at the moment so if you want to crash for a while just go on in."
         </para>

         <para number='33' comment='date'>
         "Are you asking me for a date?" Tracey giggles. "Oh, that's so sweet of you, but I don't go out with strangers."
         </para>

         <para number='34' comment='bye'>
         "Have a nice day," Tracey says with a big, bright smile, then she spits out her chewing gum and pops a fresh stick into her mouth, and turns her attention back to her magazine.
         </para>

         <para number='35' comment='Ex Tracey'>
         Tracey is very pretty, and dressed in an outrageously fashionable outfit that seems to have been made out of flowers. It even gives off a floral perfume, too. There is not the slightest sign of intelligence in her eyes.
         </para>

      </section>

   </category>

</para-list>

