<?xml version="1.0"?>

<para-list version='11'>

   <category name='food'>

      <section name='bistro'>

         <para number='1' comment='Buy food - Arts Bistro - 716'>
         The waitdroid brings a large platter of buffalo wings (from the real flying buffalo developed in Rhea Labs). A fireproof bowl of extra spicy dipping sauce is offered with them. Funny, they don't taste at all like chicken.
         </para>

         <para number='2' comment='No money'>
         The waitdroid offers you a glass of water as you lack the groats to buy wings.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='keepout'>

         <para number='1' comment='Non-staff - airlock - loc 720'>
         As you enter the airlock, a man in a lab coat prevents you from closing the door. "Sorry, sorry," he says, "We're closed to visitors just now. No cause for alarm, there's no emergency... it's just routine maintenance. Yes, that's it." He looks nervously over his shoulder into the main dome. What he sees alarms him, because he squeaks, then pushes you roughly back out of the airlock and slams the door shut in your face.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='Crater exit no moves'>
         The walls of the crater are much too steep to climb.
         </para>

         <para number='2' comment='Airlock'>
         Breaking a hole in the side of the airlock is strongly discouraged.
         </para>

         <para number='3' comment='Dome edges'>
         Please refrain from knocking holes in the side of the dome as the inhabitants will not appreciate the exposure to the outside.
         </para>

         <para number='4' comment='corridors'>
         It is strongly recommended that visitors stay inside the corridors which link the domes as vacuum is difficult to breathe.
         </para>

         <para number='5' comment='Path to cave'>
         The ground to either side of the trail is much too rough to allow passage. Please stay on the path.
         </para>

         <para number='6' comment='Cave entrance'>
         There are too many rocks to allow movement in that direction at this time.
         </para>

         <para number='7' comment='In the cave'>
         The cave walls prevent movement in that direction.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='rope'>

         <para number='1' comment='Use rope to climb down pit'>
         You quickly tie the rope onto the ring, remembering to use a good sturdy reef knot. What a piece of luck - the rope is just long enough to reach the floor of the pit. You slither down the rope and find yourself in...
         </para>

         <para number='2' comment='Use rope anywhere else - 1'>
         You can't see anything to attach the rope to, so you tie it into a neat bow. Very pretty!
         </para>

         <para number='3' comment='Use rope - anywhere else - 2'>
         You can't see anything to attach the rope to, so you practice tying a round turn and two half-hitches.
         </para>

         <para number='4' comment='Use rope anywhere else - 3'>
         You can't see anything to attach the rope to, so with a skillful series of knots you create a lovely macrame wall hanging.
         </para>

         <para number='5' comment='Climbing back up rope'>
         You climb back up the rope - not so easy as it was to go down! After a bit of effort, you reach the top. Deciding to retrieve your rope for later use, you untie it from the ring. But whoops - butterfingers! You fumble and drop the rope, which falls out of sight, gone forever.
         </para>

      </section>

   </category>

   <category name='shop'>

      <section name='rope'>

         <para number='1' comment='Get rope...'>
         You cannot just take what you want - that would be stealing, and Joe Bob doesn't take kindly to people trying to steal his goods. If you want some rope, you need to buy some rope.
         </para>

         <para number='2' comment='Buy rope - not enuff groats'>
         Joe Bob's fine rope costs money, and you don't even have the two groats necessary to buy a length of it. Come back when you can afford it.
         </para>

         <para number='3' comment='Sell the player some rope'>
         You hand over two groats. Joe Bob bites into them, to ensure they are not counterfeit (at least, you assume that's the reason, and not because he likes the taste of money!) and hands you a coil of rope.
         </para>

      </section>

   </category>

   <category name='tannoy'>

      <section name='bistro'>

         <para number='1' comment='bistro announcements 716'>
         The tannoy goes bing-bong and an artificial voice says, "Security to Rhea Laboratories. A vegetable has escaped."
         </para>

         <para number='2' comment='bistro announcements 716'>
         The tannoy goes bing-bong and an artificial voice says, "Professor Dimsdale, please return to the classroom. Your students are waiting."
         </para>

         <para number='3' comment='bistro announcements 716'>
         The tannoy goes bing-bong and an artificial voice says, "Commander Penguin, please report to the Armstrong Cuthbert office."
         </para>

         <para number='4' comment='bistro announcements 716'>
         The tannoy goes bing-bong and a crazed voice says, "Brains! I want brains! Give me your br-" before it is abruptly cut off.
         </para>

         <para number='5' comment='bistro announcements 716'>
         The tannoy goes bing-bong and an artificial voice says, "Please disregard the previous announcement."
         </para>

         <para number='6' comment='bistro announcements 716'>
         The tannoy goes bing-bong and an artificial voice says, "This is a test of the tannoy announcement system. If this had been an actual announcement you would have heard an announcement. This is only a test."
         </para>

         <para number='7' comment='bistro announcements 716'>
         The tannoy goes bing-bong and an artificial voice says, "Tickets for the Cabbages Farewell Concert go on sale tomorrow! Seating is limited so get in line for your tickets early!"
         </para>

      </section>

   </category>

</para-list>

