<?xml version="1.0"?>

<para-list version='2'>

   <category name='food'>

      <section name='exchange'>

         <para number='1' comment='Buy food - exchange lounge 262'>
         You order a crottled greep sandwich on Venusian pumpernickel. It is expressly forbidden by the Geneva Convention of 1896 to transmit the true recipe for crottled greeps verbally, in writing, or through telepathy.
         </para>

         <para number='2' comment='No money'>
         You don't have the groats to buy yourself any food. They don't give their crottled greeps away for nothing, you know!
         </para>

      </section>

      <section name='sier'>

         <para number='1' comment='Buy food - Sierpinsky - 393'>
         You are presented with a wafer of baked pastry on which are arranged three large steamed centipedes with a garnish of a chopped blue vegetable and a dish of glossy-black paste, which gives off an acrid aromatic odor.
         </para>

         <para number='2' comment='No money'>
         You cannot afford to buy any of the food on sale in the lounge.
         </para>

      </section>

   </category>

</para-list>

