<?xml version="1.0"?>

<para-list version='3'>

   <category name='death'>

      <section name='sun'>

         <para number='1' comment='Death by sunshine - loc 1108'>
         Your incautious instructions send the ship plunging toward the surface of the sun. Desperately you wrestle with the controls in an effort to break away... Too late!
         </para>

         <para number='2'>
         Before you even have time to think a last thought the refrigeration equipment gives up the uneven struggle, and you are fried to a crisp!
         </para>

         <para number='3' comment='Announce - solar orbit'>
         In space, no-one can hear you scream - which is a pity, because otherwise you would have heard %s, who has just flown into the sun and experienced an agonizing fiery death. Oh dear.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for asteroids'>
         You are veering off the safe paths through the rocky debris of the asteroid belt. Your navigation computer alerts you to the danger, so you turn back.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='atm'>

         <para number='1' comment='use atm/get money - loc 1172'>
         You cannot take money out of the ATM without typing in the correct PIN.
         </para>

         <para number='2' comment='enter pin/type pin/enter number'>
         That is not the correct PIN.
         </para>

         <para number='3' comment='get atm'>
         You cannot remove the ATM machine, and attempting to do so will bring the full wrath of the Galactic Banking Corporation's enforcers down upon you.
         </para>

         <para number='4' comment='get pin'>
         There's nobody here to give you a PIN - if you don't already know it, you cannot use the machine.
         </para>

      </section>

   </category>

</para-list>

