<?xml version="1.0"?>

<para-list version='3'>

   <category name='exchange'>

      <section name='display'>

         <para number='1' comment='Loc 335 - random display'>
         The prices display is showing a vivid, uniform, blue.
         </para>

         <para number='2'>
         The ticker screen is displaying the message, 'Keyboard not found. Press any key to continue'.
         </para>

         <para number='3'>
         The screen shows a message, 'General failure reading Drive A'. You are left wondering who General Failure is, and why he is reading Drive A.
         </para>

         <para number='4'>
         The ticker stutters into life with the message, 'Press Ctrl-Alt-Del to reboot'. Someone, somewhere, is obviously having problems!
         </para>

         <para number='5'>
         The screen conveys the message, 'New hardware detected. Please insert operating system data crystal number 8,541'.
         </para>

         <para number='6'>
         Instead of prices the screen shows a large, animated, dancing paperclip.
         </para>

         <para number='7'>
         The ticker displays the message, 'Non-system data crystal in drive A. Please remove and reboot'.
         </para>

         <para number='8'>
         The screen displays a message, 'Cannot find display device. Unable to output this message'.
         </para>

         <para number='9'>
         The ticker board carries a message saying, 'These prices violate the filtering rules and have been deleted'.
         </para>

         <para number='10'>
         The board is offering to sell a million tons of a commodity called 'qwertyuiop' at a price of minus 10,000ig/ton. Somehow that doesn't look quite right!
         </para>

         <para number='11'>
         A message on the screen says, "You seem to be attempting to buy something. Would you like some help with that?"
         </para>

      </section>

   </category>

   <category name='food'>

      <section name='rama'>

         <para number='1' comment='Buy food - Rama bar - 462'>
         The bartender takes your money with one hand and hands you a plate and a dish with the other two hands. On the plate are three triangular-shaped pieces of camembert, covered with breadcrumbs and deep fried - a delicacy called Gordon's cheese triangles - and three triangular pieces of toast.
         </para>

         <para number='2'>
         The dish contains a red sauce made from some kind of berries, which are also triangle-shaped. Each piece of cheese lasts for three mouthfuls, as does the toast.
         </para>

         <para number='3' comment='Not enuff groats'>
         The bartender makes a rude gesture at you with all three of his hands, indicating that you don't have the money to eat here.
         </para>

      </section>

   </category>

</para-list>

