<?xml version="1.0"?>

<para-list version='14'>

   <category name='food'>

      <section name='brasserie'>

         <para number='1' comment='Buy food - Sumatra Brass - 197'>
         You are presented with a platter containing a vast selection of dishes: sizzling tandoori chicken, saffron yellow pilau rice studded with almonds and buttery sauteed onion bits, grizzle vindaloo, king prawn korma, peshwari nan, onion bhaji, lamb tikka masala, and Venusian slug jalfrezi. You try some of everything - even the slugs are gorgeous - and suddenly realize you've scoffed the whole lot.
         </para>

         <para number='2' comment='No money'>
         You cannot afford to eat here, so will just have to satisfy yourself by looking at, and smelling, what other people are eating.
         </para>

      </section>

      <section name='cafeteria'>

         <para number='1' comment='Buy food - Cafeteria - 1352'>
         The waitdroid brings you three dishes: green eggs and ham, animal crackers in soup, and three little pigs roti. It's all good.
         </para>

         <para number='2' comment='No money'>
         You don't have enough groats to eat here, sorry.
         </para>

      </section>

      <section name='coffee'>

         <para number='1' comment='Buy coffee - all bars'>
         A droid hands you one of the yellow bulbs you have seen all over the place here. Squirting the contents into your mouth, you almost choke on the strong, thick coffee. No wonder there's a hazard warning on the label! You drain the bulb and hand the empty back to the droid.
         </para>

         <para number='2' comment='No money'>
         You will have to pay for the coffee, and you don't have enough groats. What a pathetic situation you find yourself in!
         </para>

      </section>

      <section name='corsica'>

         <para number='1' comment='Buy food -King of Corsica 196'>
         A young and attractive serving person in a very skimpy uniform serves you with a plate of fish and chips, with a sprinkling of bitter herbs. Oh well, nobody comes here for the food anyway. You eat it without much enjoyment, but feel a little better for it.
         </para>

         <para number='2' comment='No money'>
         A young and attractive serving person in a very skimpy uniform asks you for money, which you don't have. She laughs. You hang your head in shame.
         </para>

      </section>

      <section name='custer'>

         <para number='1' comment='Buy food - Custer - 1161'>
         The bartender gives you a large plate containing several durian-fed Venusian landcrabs, with some monster slobby yellow cheese. An odd combination, but it fills you up.
         </para>

         <para number='2' comment='No money'>
         Your request for food is ignored - everyone can see you are broke!
         </para>

      </section>

      <section name='guevarra'>

         <para number='1' comment='Buy food - Chez G - 450'>
         A servingdroid brings you a huge platter containing Choo Choo's trophy-winning pulled pork and BBQ sauce, with a side order of coleslaw and some sliced white bread. It is exactly as originally made at Choo Choo's BBQ in the region of Earth once known as Georgia, Good Ole USA, and as you eat it you agree it was worth exporting.
         </para>

         <para number='2' comment='No money'>
         The servingdroid jerks its head towards a sign on the wall that says, "No money? No food!"
         </para>

      </section>

      <section name='muddy'>

         <para number='1' comment='Buy food - Muddy Waters - 195'>
         A waitdroid appears with a tray hoist over its head to avoid colliding with anything, and serves you your food: a huge slab of dry-rub smoked baby back ribs with a side order of coleslaw and maple baked beans. You quickly reduce the food to nothing but bones, and the waitdroid clears the rubble away again with speed and efficiency.
         </para>

         <para number='2' comment='No money'>
         You attempt to order some food, but somehow the waitdroids can tell that you don't have enough money, so they pretend they haven't seen you.
         </para>

      </section>

      <section name='working'>

         <para number='1' comment='Buy food - Workingmen - 1287'>
         A server brings you a large bowl of meaty borscht, with a side order of potato pirogen fried in butter with brown onions. It's delicious and filling.
         </para>

         <para number='2'>
         You ask a server for some food, but when he holds out his hand for money, you realize you are right out of groats. You tell him you've changed your mind...
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='keepout'>

         <para number='1' comment='Turn back non-staff - loc 901'>
         A union representative hurries up to you and tells you this is an active contruction site. "Sorry, sorry," he chants, "No visitors today. Come back tomorrow. Or better still, next week."
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='shuttle area'>
         A burly droid glides over and places a heavy hand on your shoulder. "Nah then, nah then, citizen; you can't be wandering off the pathways without authorization."
         </para>

         <para number='2' comment='control shed'>
         You stumble against an unyielding glazsteel panel.
         </para>

         <para number='3' comment='ops shed'>
         Your effort only succeeds in rearranging the rock dust on the floor into an increasingly unsightly mess.
         </para>

         <para number='4' comment='custers pub'>
         You clumsily stumble into the stacked crates bruising yourself.
         </para>

         <para number='5' comment='custers pub main'>
         You stumble into a cluster of workers who laugh, spin you around, and push you away.
         </para>

         <para number='6' comment='rock corridors'>
         You stumble into a rock wall and loudly muttering, you turn away. A miner glares at you.
         </para>

         <para number='7' comment='sneeze'>
         Your foot slips on the rock dust. Stumbling and stirring up a cloud of rock dust, you sneeze mightily and turn back.
         </para>

         <para number='8' comment='fountain'>
         You attempt to climb up the slippery side of the fountain but your wet hands can find no purchase on the smooth marble. You look for a way to get out.
         </para>

      </section>

   </category>

   <category name='newbod'>

      <section name='message'>

         <para number='1' comment='newbod puzzle [1]'>
         As you enter the bar you are accosted by a dubious-looking character wearing a black leather trench coat. His accent is excruciatingly false - he's obviously been watching too many Lattice spy sit-coms. "We haff vot you are looking for." He beckons you over into a dark corner and opens his trench coat.
         </para>

         <para number='2' comment='newbod puzzle [2]'>
         You gasp in amazement. Hung in the coat from strategically placed straps are dozens of unmarked illegal bulbs of coffee!
         </para>

         <para number='3' comment='newbod puzzle [3]'>
         The man smiles a sinister smile and hands you one of the bulbs. "Make zure you teeell all of your friendzz about it. Else..." He draws a finger across his throat. "Zzzzzztt!"
         </para>

      </section>

   </category>

</para-list>

