<?xml version="1.0"?>

<para-list version='183' editor='standard'>

   <category name='admin'>

      <section name='displayflags'>

         <para number='1'>
         You haven't said whose flags you want to display!
         </para>

         <para number='2'>
         Can't find a player with that name!
         </para>

      </section>

      <section name='saveplayer'>

         <para number='1'>
         You haven't said who you want to save!
         </para>

         <para number='2'>
         Can't find a player with that name!
         </para>

      </section>

      <section name='setalpha'>

         <para number='1'>
         Alpha crew flag set.
         </para>

         <para number='2'>
         Alpha crew flag cleared.
         </para>

      </section>

      <section name='sethost'>

         <para number='1'>
         Host flag set.
         </para>

         <para number='2'>
         Host flag cleared.
         </para>

      </section>

      <section name='settechie'>

         <para number='1'>
         Techie flag set.
         </para>

         <para number='2'>
         Techie flag cleared.
         </para>

      </section>

   </category>

   <category name='billing'>

      <section name='adminchange'>

         <para number='1'>
         Valid status options are 'trial', 'active', 'comp', 'suspended', 'cancelled', or 'blocked'.
         </para>

         <para number='2'>
         Please wait while the account is updated.
         </para>

      </section>

      <section name='displayaccount'>

         <para number='1'>
         Unable to find that player's account!
         </para>

      </section>

      <section name='displayemail'>

         <para number='1'>
         I'm sorry, I'm unable to find your email address at the moment.
         </para>

      </section>

      <section name='processreply'>

         <para number='1'>
         Your email address has been changed.
         </para>

         <para number='2'>
         I'm sorry, I'm unable to change your email address at the moment.
         </para>

         <para number='3'>
         Your password has been changed.
         </para>

         <para number='4'>
         I'm sorry, I'm unable to change your password at the moment.
         </para>

         <para number='5'>
         I'm sorry, I'm unable to find that account.
         </para>

         <para number='6'>
         ADMIN: account updated.
         </para>

         <para number='7'>
         ADMIN: unable to update requested account.
         </para>

      </section>

      <section name='updateemail'>

         <para number='1'>
         I'm sorry, I'm not able to check your password at this time. Please log off and log back on before trying again. Thank you.
         </para>

         <para number='2'>
         Wrong password - email address not updated.
         </para>

         <para number='3'>
         Please wait while your email address is updated.
         </para>

      </section>

      <section name='updatepassword'>

         <para number='1'>
         I'm sorry, I'm not able to change your password at this time. Please log off and log back on before trying again. Thank you.
         </para>

         <para number='2'>
         Wrong password - password not updated.
         </para>

         <para number='3'>
         Please wait while your password is updated.
         </para>

      </section>

   </category>

   <category name='channel'>

      <section name='send'>

         <para number='1'>
         There is a brief, almost inaudible, hum from your comm unit.
         </para>

      </section>

   </category>

   <category name='channelmanager'>

      <section name='leave'>

         <para number='1'>
         I'm sorry, I'm unable to find the channel you are tuned to!
         </para>

         <para number='2'>
         Your comm unit is unable to find the channel requested!
         </para>

      </section>

      <section name='list'>

         <para number='1'>
         Your comm unit is unable to find the channel requested!
         </para>

      </section>

      <section name='send'>

         <para number='1'>
         I'm sorry, I'm unable to find the channel you are tuned to!
         </para>

      </section>

   </category>

   <category name='cmdparser'>

      <section name='accept'>

         <para number='1'>
         You already have an uncompleted contract!
         </para>

         <para number='2'>
         You haven't specified which job you want to accept.
         </para>

         <para number='3'>
         You need a ship to haul cargo!
         </para>

         <para number='4'>
         Armstrong Cuthbert Inc has no haulage work for you at the moment.
         </para>

      </section>

      <section name='act'>

         <para number='1'>
         You haven't said what you want to act!
         </para>

      </section>

      <section name='admin'>

         <para number='1'>
         I don't know which admin service you want!
         </para>

         <para number='2'>
         You haven't given me enough information to change an account!
         </para>

      </section>

      <section name='adminchange'>

         <para number='1'>
         I don't know what you want to change!
         </para>

         <para number='2'>
         You haven't given me enough information to change an account!
         </para>

      </section>

      <section name='adminset'>

         <para number='1'>
         Navigator flag cleared.
         </para>

         <para number='2'>
         Navigator flag set.
         </para>

         <para number='3'>
         Can't find a player with that name!
         </para>

         <para number='4'>
         Don't know which flag you want to set!
         </para>

      </section>

      <section name='adminunlock'>

         <para number='1'>
         You didn't say who you want to unlock!
         </para>

         <para number='2'>
         Can't find a player with that name!
         </para>

      </section>

      <section name='board'>

         <para number='1'>
         You haven't said what you want to board.
         </para>

      </section>

      <section name='brief'>

         <para number='1'>
         Brief descriptions from now on.
         </para>

      </section>

      <section name='buy'>

         <para number='1'>
         You haven't said what you want to buy.
         </para>

         <para number='2'>
         You can only buy food or a round of drinks in a bar or cafe.
         </para>

         <para number='3'>
         You can only buy a spaceship at a shipyard.
         </para>

         <para number='4'>
         I'm afraid I can't see any way you can purchase that at this point.
         </para>

         <para number='5'>
         I think the command you want is change clothes.
         </para>

      </section>

      <section name='call'>

         <para number='1' comment='general error'>
         Because of a technical glitch at Comms Central you are unable to place the call.
         </para>

         <para number='2' comment='unknown player specified'>
         The Nightwatch despatcher tells you that she can't locate the person you are trying to report.
         </para>

      </section>

      <section name='change'>

         <para number='1'>
         The command is 'change clothes description', where 'description' is the description of your natty new threads.
         </para>

      </section>

      <section name='check'>

         <para number='1'>
         You haven't said what you want to check!
         </para>

         <para number='2'>
         You can only check prices in exchanges at the moment.
         </para>

      </section>

      <section name='checkprice'>

         <para number='1'>
         You haven't said what commodity you want to check the price of.
         </para>

         <para number='2'>
         Can't find a commodity with that name!
         </para>

      </section>

      <section name='com'>

         <para number='1'>
         You haven't provided a message to send!
         </para>

      </section>

      <section name='display'>

         <para number='1'>
         You haven't said what you want to display!
         </para>

         <para number='2'>
         I don't understand what you want to display!
         </para>

      </section>

      <section name='drop'>

         <para number='1'>
         You haven't said what you want to drop!
         </para>

      </section>

      <section name='examine'>

         <para number='1'>
         You haven't said who, or what, you want to examine!
         </para>

      </section>

      <section name='execute'>

         <para number='1'>
         I think the command you are looking for is board shuttle.
         </para>

         <para number='2'>
         You probably need to use the collect command.
         </para>

         <para number='3'>
         You probably need to use the deliver command.
         </para>

         <para number='4'>
         I think, perhaps, the command you are looking for is buy ship.
         </para>

         <para number='5'>
         The command you are probably looking for is either 'join channel xxx', where xxx is the name of the channel you wish to join, or 'leave channel' to stop using your current channel. You can display a list of all the channels being used at the moment with the command 'display channels'.
         </para>

      </section>

      <section name='fed2'>

         <para number='1'>
         Federation II is dedicated to Toby Hamilton, sys-admin extraordinaire and friend.  Federation II is written by Alan Lenton and published by Interactive Broadcasting Ltd. The Hamsters (http://www.thehamsters.co.uk/) are Federation II's official rock band.
         </para>

      </section>

      <section name='follow'>

         <para number='1'>
         You haven't said who you want to follow!
         </para>

      </section>

      <section name='full'>

         <para number='1'>
         Full descriptions from now on.
         </para>

      </section>

      <section name='get'>

         <para number='1'>
         Can't see anything with that name!
         </para>

         <para number='2'>
         You haven't said what you want to get!
         </para>

      </section>

      <section name='grouptalk'>

         <para number='1'>
         You haven't provided a message to send to your group!
         </para>

      </section>

      <section name='help'>

         <para number='1'>
         For help in getting started with Fed II, type HELP START.
         </para>

         <para number='2'>
         Help is available on a number of topics. New players will find the following useful: HELP TALK, HELP GROAT, HELP MOVE, HELP PERMIT, HELP SPACESHIP.
         </para>

         <para number='3'>
         There is also help available on some of the commands: type HELP followed by the command name, for example: HELP BOARD.
         </para>

         <para number='4'>
         Full help can be found on the ibgames web site at: http://www.ibgames.net/fed2/info/index.html.
         </para>

      </section>

      <section name='jobs'>

         <para number='1'>
         Armstrong Cuthbert will notify you when new jobs become available.
         </para>

         <para number='2'>
         Armstrong Cuthbert will no longer notify you when new jobs become available.
         </para>

         <para number='3'>
         I don't know whether you want to turn job notifications 'on' or 'off'!
         </para>

         <para number='4'>
         Armstrong Cuthbert doesn't provide workboard jobs for those over the rank of Captain!
         </para>

      </section>

      <section name='join'>

         <para number='1'>
         You haven't said what you want to join!
         </para>

         <para number='2'>
         I don't understand what you want to join!
         </para>

      </section>

      <section name='joinchannel'>

         <para number='1'>
         You haven't said which channel you want to join!
         </para>

      </section>

      <section name='leave'>

         <para number='1'>
         You haven't said what you want to leave!
         </para>

         <para number='2'>
         I don't understand what you want to leave!
         </para>

      </section>

      <section name='lock'>

         <para number='1'>
         That command is only available to game staff.
         </para>

         <para number='2'>
         Can't find that person in the player database.
         </para>

      </section>

      <section name='parse'>

         <para number='1'>
         I'm sorry I don't understand you. Can you put that a different way?
         </para>

      </section>

      <section name='post'>

         <para number='1'>
         You haven't said what message you want to post!
         </para>

      </section>

      <section name='repay'>

         <para number='1'>
         You haven't said how much you want to repay.
         </para>

      </section>

      <section name='say'>

         <para number='1'>
         You haven't said anything!
         </para>

      </section>

      <section name='sell'>

         <para number='1'>
         I'm afraid you can't sell that at the moment.
         </para>

      </section>

      <section name='spynet'>

         <para number='1'>
         There are four Spynet Services currently available - Spynet Financial, Spynet Notice, Spynet Report, and Spynet Review.
         </para>

      </section>

      <section name='spynetreport'>

         <para number='1'>
         You haven't said who it is that you want a report on.
         </para>

         <para number='2'>
         Spynet regrets that it is unable to locate the requested person...
         </para>

      </section>

      <section name='tell'>

         <para number='1'>
         You haven't provided a message to send!
         </para>

      </section>

      <section name='termwidth'>

         <para number='1'>
         You haven't told us the width of your terminal.
         </para>

         <para number='2'>
         Formatting turned off.
         </para>

      </section>

      <section name='tradingallowed'>

         <para number='1'>
         You must be in a commodity exchange to trade commodities!
         </para>

         <para number='2'>
         I'm sorry, but trading on the commodities market is not allowed at your rank.
         </para>

      </section>

      <section name='unignore'>

         <para number='1'>
         You haven't said who you want to take off the ignore list!
         </para>

      </section>

      <section name='update'>

         <para number='1'>
         You haven't said what you want to update - your email or your password.
         </para>

         <para number='2'>
         Update options are 'email' or 'password'.
         </para>

      </section>

      <section name='updateemail'>

         <para number='1'>
         The format of the command is 'update email password new_address'
         </para>

         <para number='2'>
         The new email address you have given is not a valid address.
         </para>

      </section>

      <section name='updatepassword'>

         <para number='1'>
         The format of the command is 'update password old_password new_password'.
         </para>

      </section>

      <section name='wantansi'>

         <para number='1'>
         ANSI codes will be passed through to you.
         </para>

         <para number='2'>
         ANSI codes will be stripped out of text.
         </para>

      </section>

      <section name='whois'>

         <para number='1'>
         You haven't said who you want to look up!
         </para>

      </section>

      <section name='xxt'>

         <para number='1'>
         You haven't provided a message to transmit!
         </para>

      </section>

      <section name='zap'>

         <para number='1'>
         You haven't said who you want to zap!
         </para>

      </section>

   </category>

   <category name='company'>

      <section name='buydepot'>

         <para number='1'>
         Your company doesn't have the funds available.
         </para>

      </section>

      <section name='buyfactory'>

         <para number='1'>
         Factories cost 2 Mig, and your company doesn't have the cash available.
         </para>

         <para number='2'>
         You already have the maximum number of factories allowed.
         </para>

         <para number='3'>
         Your company has built a factory:
         </para>

         <para number='4'>
         Ordinance 485, Section 18, Para 101 forbids the building of biological production facilities, except on designated bio-production planets.
         </para>

      </section>

      <section name='displaydepot'>

         <para number='1'>
         Your company doesn't have a depot on that planet!
         </para>

      </section>

      <section name='displayfactory'>

         <para number='1'>
         You don't have a factory with that number.
         </para>

      </section>

      <section name='fetch'>

         <para number='1'>
         Your company doesn't have a depot on this planet.
         </para>

         <para number='2'>
         The depot doesn't have anything in that bay.
         </para>

         <para number='3'>
         Your comm unit beeps and displays a message informing you that the cargo has been transferred from the depot to your ship.
         </para>

      </section>

      <section name='flushfactory'>

         <para number='1'>
         You don't have a factory with that number.
         </para>

      </section>

      <section name='sellbay'>

         <para number='1'>
         You need to be in a commodity exchange to trade.
         </para>

         <para number='2'>
         You don't have a depot on this planet.
         </para>

         <para number='3'>
         You don't have anything stored in that bay.
         </para>

      </section>

      <section name='selldepot'>

         <para number='1'>
         You don't have a depot on that planet!
         </para>

      </section>

      <section name='sellfactory'>

         <para number='1'>
         You don't have a factory with that number.
         </para>

      </section>

      <section name='setfactcapital'>

         <para number='1'>
         You don't have a factory with that number.
         </para>

      </section>

      <section name='setfactoutput'>

         <para number='1'>
         You don't have a factory with that number.
         </para>

      </section>

      <section name='setfactstatus'>

         <para number='1'>
         You don't have a factory with that number.
         </para>

      </section>

      <section name='setfactwages'>

         <para number='1'>
         You don't have a factory with that number.
         </para>

      </section>

      <section name='store'>

         <para number='1'>
         You don't have a depot on that planet!
         </para>

         <para number='2'>
         The depot doesn't have any unused bays left.
         </para>

         <para number='3'>
         When you ask where your cargo is the gang boss tells you, "It may be in Schrodinger's warehouse - but then again it may not be." And she walks off with a knowing smirk.
         </para>

      </section>

      <section name='upgradedepot'>

         <para number='1'>
         Your company doesn't have the funds available.
         </para>

      </section>

      <section name='upgradefactory'>

         <para number='1'>
         You don't have a factory with that number!
         </para>

         <para number='2'>
         You don't have the cash to upgrade a factory!
         </para>

         <para number='3'>
         That factory has already been fully upgraded!
         </para>

      </section>

      <section name='upgradestorage'>

         <para number='1'>
         You don't have a factory with that number!
         </para>

         <para number='2'>
         You don't have the cash to upgrade a factory's storage!
         </para>

         <para number='3'>
         That factory storage has already been fully upgraded!
         </para>

      </section>

   </category>

   <category name='comunit'>

      <section name='comms'>

         <para number='1'>
         Your comm unit is accepting comm messages.
         </para>

         <para number='2'>
         Your comm unit is not accepting comm messages.
         </para>

      </section>

      <section name='ignore'>

         <para number='1'>
         You do not have anyone on your ignore list.
         </para>

         <para number='2'>
         You have the following on your ignore list:
         </para>

      </section>

      <section name='spynetnotice'>

         <para number='1'>
         OK - SpyNet Notice is now ON.
         </para>

         <para number='2'>
         OK - SpyNet Notice is now OFF.
         </para>

      </section>

   </category>

   <category name='fedmap'>

      <section name='boardshuttle'>

         <para number='1'>
         You don't have a space ship - until you do you can't leave the planet except by using commercial liners.
         </para>

      </section>

      <section name='landshuttle'>

         <para number='1'>
         There isn't anywhere your shuttle can land.
         </para>

         <para number='2'>
         Can't find landing location - please mail feedback@ibgames.com with details.
         </para>

         <para number='3'>
         You maneuver your ship into a parking orbit, carefully avoiding the holographs of double yellow lines. Boarding the shuttle you settle into the pilot's seat. "Let's go," you tell the computer.
         </para>

         <para number='4'>
         You hear a dull 'clunk' as the shuttle disengages. The ride down is, as usual, smooth. You disembark and look over your surroundings.
         </para>

      </section>

      <section name='launchshuttle'>

         <para number='1'>
         Your shuttle isn't here to be boarded!
         </para>

         <para number='2'>
         Can't find orbit location - please mail feedback@ibgames.com with details.
         </para>

         <para number='3'>
         Boarding the shuttle you settle into the pilot's seat. "Let's go," you tell the computer.
         </para>

         <para number='4'>
         There is a short pause while the computer awaits clearance, and then you are pushed back into your seat by the acceleration. The computer announces, "Docking complete," and you board your ship.
         </para>

      </section>

   </category>

   <category name='gifts'>

      <section name='keyring'>

         <para number='1' comment='keyring'>
         is carrying a multi-dimensional keyring made by the prestigious TenBrane Corp. If you look carefully you can see the glow of the macro-superstring logo. It has on it:
         </para>

         <para number='2' comment='Washroom key'>
         The ornate key is a much sought after key to the Galactic Administration executive washroom, and is genetically coded to its owner.
         </para>

         <para number='3' comment='2005 valentine'>
         You can see a small red valentine heart with the number 2005 etched into it.
         </para>

         <para number='4' comment='staff key fob 2005'>
         The key fob carries the writing 'Fed2 Staff 2005'.
         </para>

         <para number='5' comment='croquet mallet'>
         You can see a miniature croquet mallet cunningly carved so that it also appears to be a tiny pink flamingo.
         </para>

         <para number='6' comment='silver shamrock'>
         The shamrock is an exquisitely wrought silver keyring accessory.
         </para>

         <para number='7' comment='Jester for 2005'>
         You can see a square cut Venusian diamond. At its heart a tiny holo of a jester juggles balls, turns cartwheels and performs fire eating tricks for your entertainment. In tiny letters on the edge of the plinth on which he is performing is the number '2005'.
         </para>

         <para number='8' comment='Maypole for 2005'>
         The maypole is a marvel of miniature engineering. Tiny figures holding the ribbons dance round it as you watch. Power is supplied by the keyring, and etched into the pole, just visible, is the number 2005.
         </para>

         <para number='9' comment='Class of 2005 scroll'>
         The scroll, engraved with the words 'Class of 2005', is an exquisitely wrought white gold keyring accessory.
         </para>

         <para number='10' comment='2005 tarot card'>
         The tiny tarot card is made of burnished gunmetal depicting a highly stylized sun on the obverse. The reverse side is an art deco geometric design with the number 2005 in the center.
         </para>

         <para number='11' comment='liberty bell 2005'>
         The tiny replica of the Liberty Bell is made of bronze. If you look carefully you can see that it even has a crack down one side - just like the original. Stamped on the rim is the number 2005.
         </para>

         <para number='12' comment='laser lighter 2005'>
         This keyring accessory is a tiny laser BBQ lighter. The lighter is embossed with the number 2005 on one side, and Gallagher's logo on the other.
         </para>

         <para number='13' comment='magellan ship 2005'>
         This keyring accessory is a silver replica of Magellan's ship, the Victoria. Engraved on the sails are the numbers 1522 and 2005.
         </para>

         <para number='14' comment='Jack O Lantern'>
         The jack o lantern grins evilly at you. The light inside is powered by the keyring, and has been set to pulse in an odd, and rather unsettling, arrhythmic fashion. The number 2005 is imprinted on the back.
         </para>

         <para number='15' comment='Firework -2005'>
         As you touch it the firework emits a shower of multi-colored sparks which crackle and flash as they float away. The legend Diwali 2005 has been embossed into the side of the firework.
         </para>

         <para number='16' comment='Thanksgiving 2005'>
         You inadvertently squeeze the tiny rubber turkey, a 2005 special, and it immediately makes a farting noise the volume of which completely belies the size of the charm!
         </para>

         <para number='17' comment='Christmas Cracker 2005'>
         You examine the TenBrane Corp reverse-entropy Christmas cracker. There is a *BANG!* as it comes apart, and then, before your very eyes, the exploded parts drift back together to form a whole. On the side is an ornate number, 2005.
         </para>

         <para number='18' comment='staff star 2005'>
         The tiny star glitters with an intense blue-white light. It reminds you of Rigel seen from its fourth planet. Squinting slightly, and donning a pair of Raybans, you can make out lettering deep in the heart of the star - 'Fed2 staff 2005'.
         </para>

         <para number='19' comment='ming 2006 music box'>
         It starts to play Auld Lang Syne and a hologram appears with the numbers 2006. Suddenly they vanish and are replaced by a shadowy figure - it is the ex-Emperor Ming! He laughs maniacally, shouts "I'll be back" and then fades away.
         </para>

         <para number='20' comment='Jan 2006 charm'>
         This is one of the new 53 tera-quantel 'Box Brownie 2006' holo cameras. At the touch of a button the tiny camera expands to operating size, making it easy to use both camera and projector modes.
         </para>

         <para number='21' comment='Feb 2006 charm'>
         This Valentine rose is perfectly formed, with deep red petals that will never fade, droop or fall off. In the centre of the bloom, a small holo flashes the number '2006'.
         </para>

         <para number='22' comment='Mar 2006 charm'>
         This four-dimensional glass prism gathers in light and disperses it, sending rainbows spreading out in all directions. Every so often, the number '2006' flashes in amongst the seven bright colors.
         </para>

         <para number='23' comment='St Pat 2006 charm'>
         A tiny silver leprechaun clutching a pot of gold dances inside a silver cage, his little hat bouncing up and down as he sways from side to side doing a jig. The words 'St Patrick's Day 2006' are embroidered on his jacket.
         </para>

         <para number='24' comment='April 2006 charm'>
         Deep within the center of the faceted emerald, green lights flicker and flash in imitation of the Martian lights. From time to time, the brilliant flashes of lightning coalesce and form into the numbers '2006'.
         </para>

         <para number='25' comment='Easter 2006 charm'>
         The exquisite miniature egg is made from an iridescent nacre-like material that shines and flashes in different colors depending on how the light hits it. A delicate tracery of gold filigree frames the egg; the thin gold wires come together on the top of the egg to form the number '2006'.
         </para>

         <para number='26' comment='May 2006 charm'>
         The beautiful apple blossom is fashioned from white gold, its petals gleaming as the light hits them. It has been impregnated with scent, giving off a fresh flowery smell that is redolent of spring.
         </para>

         <para number='27' comment='June 2006 charm'>
         This tiny tin foil hat is made from the highest-quality crumpled silver foil, shaped to fit a teeny little head. A twisted wire coathanger pokes out of the top, acting as an antenna to both receive and deflect signals.
         </para>

         <para number='28' comment='July 2006 charm'>
         This miniature Mark IV laser bbq was originally designed to cook baby squarm tentacles, a delicacy across the Galaxy, but you could just about use it on a cocktail sausage, too - if it weren't for the fact that the power pack had been removed for health and safety reasons.
         </para>

         <para number='29' comment='August 2006 charm'>
         It is a stylized representation of the sun, complete with curving rays, carved out of a small piece of amber. Looking into the center, you can see an alien insect trapped forever in the tree sap from which the material was formed.
         </para>

         <para number='30' comment='Sep 2006 charm'>
         About 12 inches long, this feather comes from the tail of the extremely rare Altarian phoenix. The barbs are the deepest red, and they shimmer as the feather moves so that flames appear to be flickering along the edges.
         </para>

      </section>

      <section name='medallions'>

         <para number='1' comment='promethius card'>
         The card has a holo of Emperor Promethius on it. He is sitting on a jet black throne with flames around the base, but the detail is not very good. Promethius was one of the earliest emperors, and the holo is clearly very ancient.
         </para>

         <para number='2' comment='frizz'>
         The card holds a holo of the Emperor Hector Frizz, last of the Martian rulers. He is standing on the bridge of an ancient battlecruiser, with a huge screen display of Mars in the background.
         </para>

         <para number='3' comment='staff holo 2006'>
         The card shows a holo of all the Fed2 staff sitting in a group, smiling merrily - but if you look closely, you can see that one joker (who we won't name) appears twice, once on each side of the group. He, she or it obviously dashed from one end to the other while the holo camera was slowly panning across the group.
         </para>

         <para number='4' comment='star of david'>
         Silver filigree has been shaped into a Star of David and hung from an undecorated silver chain.
         </para>

         <para number='5' comment='zetian'>
         The trading card has an extremely good hologram of the Empress Wu Zetian addressing a parade of space navy cadets, probably at their passing out parade. The quality of the holo makes you suspect it has been enhanced at some stage.
         </para>

         <para number='6' comment='cross of lorraine'>
         The double-barred cross is made of Xmetal and hangs on a leather thong.
         </para>

         <para number='7' comment='goldstein'>
         The impassive face of Benedict Arnold Goldstein, sometimes called 'The Pretender', but not to his face, stares at you from the holo. Goldstein is the true power behind the Galactic Administration and a man not to be triffled with, since his power rivals that of the ancient emperors.
         </para>

         <para number='8' comment='horseshoe'>
         The pewter medallion features a horseshoe, an ancient symbol of luck. The medallion is attached to a silver chain.
         </para>

         <para number='9' comment='ming'>
         The holo of Ming 'The Merciless' shows the famous banquet to which all his rivals were invited - and poisoned! The victims were stuffed and mounted in cases along the walls of the entrance hall of his main palace.
         </para>

         <para number='10' comment='st christopher medallion'>
         This green enamelled silver Saint Christopher medallion depicts the patron saint of travellers. It hangs on a necklace of small jade beads.
         </para>

         <para number='11' comment='yin-yang'>
         The ancient Chinese symbol has been enameled onto the medallion, which is hung on a hammered gunmetal chain.
         </para>

         <para number='12' comment='peace symbol'>
         The universal peace symbol has been hand carved out of a small piece of red amber and hangs on an intricately wrought polished steel chain.
         </para>

         <para number='13' comment='hammer and sickle'>
         The old Communist symbol of the unity of workers and peasants has been carved onto a piece of malachite. The carving is suspended on a gold chain.
         </para>

         <para number='14' comment='martini glass'>
         The gold medallion bears the image of a martini glass with an olive in it. The significance of the image is lost in history, but the medallions, which have a gold chain, are very popular.
         </para>

         <para number='15' comment='sufi symbol'>
         This gold winged heart is a symbol of the Sufi movement, a mystic branch of Islam. The chain it is attached to has alternate links of silver and gold.
         </para>

         <para number='16' comment='catty'>
         The shadowy figure of the last emperor - Catty - looks out from the holo. A string of half hidden, semi-translucent figures appear to split off from behind the figure. Each is believed to represent one of Catty's alternative personalities...
         </para>

         <para number='17' comment='lotus'>
         The carved ivory lotus flower symbolises cosmic harmony to Buddhists. It hangs from a white silk cord.
         </para>

         <para number='18' comment='dove of peace'>
         The medallion shows a dove carrying an olive branch in its beak. It is made from an alloy of Xmetal and electrum which has a curious oily, blue-white cast to its surface. The chain is made from the same material.
         </para>

         <para number='19' comment='rose'>
         An image of a single red rose has been enamelled onto the medallion, which comes with a silver chain.
         </para>

         <para number='20' comment='angel'>
         The silver medallion has been inset with tiny seed pearls to create the image of an angel. The medallion has a silver chain.
         </para>

         <para number='21' comment='Wedjat'>
         The rock crystal medallion has a depiction of the Eye of Horus carved onto it. It is suspended from a leather thong.
         </para>

         <para number='22' comment='maltese cross'>
         The medallion is a bronze replica of a Maltese coin from 1567AD (Earth, pre-atomic era). It is attached to a pewter chain.
         </para>

      </section>

   </category>

   <category name='location'>

      <section name='move'>

         <para number='1'>
         You can't move in that direction.
         </para>

         <para number='2'>
         You realize that you are about to enter an uncharted sector. Lacking the equipment to do so safely, you turn back.
         </para>

      </section>

   </category>

   <category name='notices'>

      <section name='post'>

         <para number='1'>
         Message posted to public noticeboard...
         </para>

      </section>

      <section name='read'>

         <para number='1'>
         You instruct your comm unit to show you the noticeboard, and the messages scroll across its screen.
         </para>

      </section>

   </category>

   <category name='player'>

      <section name='akaturi'>

         <para number='1'>
         The clerk tells you that the company's Akaturi division only employs adventurers.
         </para>

         <para number='2'>
         You already have work for the company's Akaturi division.
         </para>

         <para number='3'>
         No one here has the faintest idea what you're burbling about!
         </para>

      </section>

      <section name='breakupgroup'>

         <para number='1'>
         People have stopped following you.
         </para>

      </section>

      <section name='buyfuel'>

         <para number='1'>
         You don't have a ship to buy fuel for!
         </para>

      </section>

      <section name='buyship'>

         <para number='1'>
         You need to complete your current job contract before you buy a new spaceship.
         </para>

         <para number='2'>
         The sales droid asks to see your permit. Seeing your blank look he explains that before you can fly a spaceship around the crowded traffic lanes in the system you must have a permit to show that you are competent to do so. The permits, it seems, are issued by the Galactic Administration.
         </para>

      </section>

      <section name='buywarehouse'>

         <para number='1'>
         You don't have a permit to build warehouses!
         </para>

         <para number='2'>
         You don't have the 650,000ig it costs to build a warehouse!
         </para>

         <para number='3'>
         To buy a warehouse you have to go in person to the exchange on the planet where you want the building.
         </para>

         <para number='4'>
         You have paid to have a warehouse built on this planet.
         </para>

      </section>

      <section name='calendar'>

         <para number='1' comment='Displays info about events'>
         The following events are held in Fed2: Tues 10.00pm - Fedpardy and Fed Phrase Game; Wed 10.00pm - Meet and Greet; Thurs10.00pm - Federgories; Sat 4.00pm - Cryptograms; Sat 10.00pm - Wacky Words and Fed Word Scramble; Sun 4.00pm - Wacky Words and Role-playing Class; Sun 10.00pm - Training Classes. For more details see the schedule at http://www.ibgames.net/fed2/events/calendar.html.
         </para>

      </section>

      <section name='capcash'>

         <para number='1'>
         The Interstellar Revenue Service has audited your accounts and assessed you for
         </para>

      </section>

      <section name='capt2adv'>

         <para number='1' comment='male/neuter version'>
         Something flashes up on the clerk's screen, and you are handed a message. It tells you that your promotion to adventurer has come through and notes that you have proved to be reliable and efficient in the work you have undertaken for Armstrong Cuthbert Inc. The company's Akaturi division is therefore, you are informed, able to offer you some rather more interesting work than just hauling bulk cargo.
         </para>

         <para number='2'>
         To obtain details of the work available, please drop into any Armstrong Cuthbert Inc office and ask for Akaturi work.
         </para>

         <para number='3' comment='female version'>
         Something flashes up on the clerk's screen, and you are handed a message. It tells you that your promotion to adventuress has come through and notes that you have proved to be reliable and efficient in the work you have undertaken for Armstrong Cuthbert Inc. The company's Akaturi division is therefore, you are informed, able to offer you some rather more interesting work than just hauling bulk cargo.
         </para>

      </section>

      <section name='changeclothes'>

         <para number='1'>
         You reprogram your nano-chameleon clothes to produce a dazzling new outfit. The Digital Clothes Management software deducts 10 groats from your bank balance.
         </para>

      </section>

      <section name='cheat'>

         <para number='1'>
         Flipping though your copy of the 'Galactic Limits' listings magazine, a discrete small ad catches your eye. 'Galactic bureaucracy seeks candidates for new Emperor. Apply Box 6969.'
         </para>

         <para number='2'>
         Intrigued, you punch the box number into your communicator, and a faceless bureaucrat appears on the screen. (Faceless bureaucrats were originally created by adding Cheshire Cat genes to human stock.)
         </para>

         <para number='3'>
         There is a shimmer of teleporter effect and you are moved into a sumptuous room in the late Emperor's palace. The bureaucrat explains that the galactic bureaucracy feels the need for a figurehead, and offers you a one day trial at the job, which you accept with some alacrity.
         </para>

         <para number='4'>
         The trial is not very auspicious. There are no less than five assassination attempts (one successful, but the bureaucracy pays for the cloning), several hour long harangues from planetary ambassadors, and a full scale riot which burns down the west wing of the palace...
         </para>

         <para number='5'>
         The bureaucracy are very pleased with your performance. They have been looking for someone to, as the humans so aptly say, 'take the heat'.
         </para>

         <para number='6'>
         You, however, have had enough, and decline the Imperial purple with as much grace as you can muster, asking to be returned to your starting place!
         </para>

      </section>

      <section name='collect'>

         <para number='1'>
         You don't have a job to collect!
         </para>

         <para number='2'>
         You have already collected your cargo!
         </para>

         <para number='3'>
         No one here has any cargo for you to collect.
         </para>

         <para number='4'>
         The clerk plugs your com unit into a terminal and there is a beep as the encrypted job authorisation is extracted. You monitor the loading on your ship's internal cameras, via your com unit. Satisfied, you sign for the cargo and the clerk gives you a perfunctory smile before turning back to the screen.
         </para>

      </section>

      <section name='com2capt'>

         <para number='1'>
         Congratulations on your promotion to Captain!
         </para>

      </section>

      <section name='deliver'>

         <para number='1'>
         You don't have a cargo to deliver!
         </para>

         <para number='2'>
         You haven't collected your cargo yet - so you can't deliver it...
         </para>

         <para number='3'>
         Late delivery penalties wipe out half of the haulage fee.
         </para>

         <para number='4'>
         A 20 percent bonus for fast delivery is added to your haulage fee.
         </para>

         <para number='5'>
         Your request is ignored. You will have to wait for the stevedores.
         </para>

         <para number='6'>
         You hand the clerk the papers for your cargo. He checks the details while you monitor the unloading on the ship's cameras. The stevedores finish and the foreman runs a scanner over the bonding.
         </para>

      </section>

      <section name='displayallware'>

         <para number='1'>
         You don't have any warehouses.
         </para>

         <para number='2'>
         You have warehouses on the following planets:
         </para>

      </section>

      <section name='displayjob'>

         <para number='1'>
         You don't currently have a shipping contract.
         </para>

      </section>

      <section name='drop'>

         <para number='1'>
         You're not carrying that!
         </para>

         <para number='2'>
         That's not a good idea. These ships don't have cleaning droids.
         </para>

      </section>

      <section name='dropoff'>

         <para number='1'>
         There's no one here expecting anything from you.
         </para>

         <para number='2'>
         You hand over the package and receive a receipt for it.
         </para>

      </section>

      <section name='fetch'>

         <para number='1'>
         You don't have a ship!
         </para>

         <para number='2'>
         You don't have a warehouse on this planet!
         </para>

         <para number='3'>
         You don't have any cargo stored in that bay!
         </para>

         <para number='4'>
         Your comm unit beeps and displays a message informing you that the transfer of your cargo from the warehouse to your ship is complete.
         </para>

      </section>

      <section name='follow'>

         <para number='1'>
         You can't follow someone while you are in space!
         </para>

         <para number='2'>
         You follow yourself, turning round and round till you become dizzy and fall over, banging your head, which finally brings you to your senses.
         </para>

         <para number='3'>
         Group leaders cannot follow other players!
         </para>

         <para number='4'>
         If you want to follow someone, they have to be in your location!
         </para>

         <para number='5'>
         You can't follow someone if any of the group are ignoring you!
         </para>

      </section>

      <section name='get'>

         <para number='1'>
         I don't think that would be a very good idea!
         </para>

      </section>

      <section name='insure'>

         <para number='1'>
         You are already insured!
         </para>

         <para number='2'>
         There isn't an insurance broker around to sell you insurance.
         </para>

      </section>

      <section name='leavechannel'>

         <para number='1'>
         You're not tuned to a channel!
         </para>

      </section>

      <section name='lose'>

         <para number='1'>
         You're not following anyone!
         </para>

      </section>

      <section name='marry'>

         <para number='1' comment='spouse not in game'>
         I can't find anyone of that name on the planet!
         </para>

         <para number='2' comment='spouse not in location'>
         Your would be partner has to be here for the ceremony!
         </para>

         <para number='3' comment='no registrar'>
         You need a registrar to perform the ceremony!
         </para>

         <para number='4' comment='can t pay'>
         It is traditional to give the registrar the gift of a slithy tove for conducting the ceremony. Unfortunately you don't have a slithy tove so the ceremony can't take place.
         </para>

         <para number='5' comment='trying to marry self'>
         That sort of narcissistic activity isn't allowed!
         </para>

         <para number='6' comment='Wedding registrar player(1)'>
         The registrar accepts your gift graciously and agrees to conduct the wedding for you.
         </para>

         <para number='7' comment='Wedding registrar couple (2)'>
         Your guests file in and all sit at the back, as though they were in school. When everyone is seated the ceremony begins. It is very simple and very moving.
         </para>

         <para number='8' comment='Wedding registrar couple (3)'>
         The registrar calls you up to the platform and asks each of you in turn to recite your marriage vows. He then inscribes your names into a large leather bound volume - a real book - with a quill pen. He carefully blots the entry and declares the two of you married to one another.
         </para>

         <para number='9' comment='Wedding registrar (4) everyone'>
         With that the registrar bows and invites the whole party to adjourn to wherever the reception is to be held and complete whatever other ceremonies the couple's culture might call for.
         </para>

         <para number='10' comment='Wedding registrar guests (1)'>
         Along with the other guests, you all sit at the back, as though you were still at school. Once everyone is seated and the coughing and shuffling has ended the ceremony begins. It is very simple and very moving.
         </para>

         <para number='11' comment='Wedding registrar guests (2)'>
         The registrar calls the couple up to the platform and asks each of them in turn to recite their marriage vows. Using a quill pen, he inscribes their names into a large leather bound book - a real book with real paper. After he has carefully blotted the writing he declares the couple to be married.
         </para>

         <para number='12' comment='Wedding registrar guests (3)'>
         With his part in the ceremony complete the registrar bows and invites everyone to adjourn to wherever the reception is to be held, there to complete whatever other ceremonies the couple's culture calls for.
         </para>

      </section>

      <section name='mood'>

         <para number='1'>
         Setting new mood...
         </para>

      </section>

      <section name='overdraft'>

         <para number='1'>
         A text message from the bank appears on your comm unit screen. It says, 'U r ovrdrwn. U hve bn chgd 200ig fr ths msg.'
         </para>

      </section>

      <section name='pickup'>

         <para number='1'>
         There's nothing here for you to pick up.
         </para>

         <para number='2'>
         You pickup the valuable package and sign for it.
         </para>

         <para number='3'>
         You've already picked up the valuable package!
         </para>

      </section>

      <section name='ranks'>

         <para number='1'>
         You need to purchase a spaceship to promote to Commander.
         </para>

         <para number='2'>
         You need to pay off your loan to become a Captain.
         </para>

         <para number='3'>
         You need to earn 850 hauling credits to become an Adventurer.
         </para>

         <para number='4'>
         You need to complete 75 Akaturi jobs, have 75,000ig in the bank, and become a member of the Galactic Trading Guild, Inc. to become a Merchant.
         </para>

         <para number='5'>
         To promote to Trader you need 800 merchant points and then to deposit a 400,000ig bond with the brokers on Earth.
         </para>

         <para number='6'>
         To promote to Industrialist you need to be a trader with at least 500 trading points. At that stage you can use the REGISTER command to set up your own business.
         </para>

         <para number='7'>
         There are no promotion requirements to promote to Manufacturer - you can promote whenever you like!
         </para>

         <para number='8'>
         You need to survive for four full accounting cycles without declaring bankruptcy.
         </para>

         <para number='9'>
         To promote to Founder you need to link a planet into the game.
         </para>

         <para number='10'>
         To promote to Engineer you need to have a total of 30 builds.
         </para>

         <para number='11'>
         To promote to Mogul you need to have a total of 70 builds.
         </para>

         <para number='12'>
         To promote to Technocrat you need to have a total of 125 builds on one of your planets.
         </para>

         <para number='13'>
         To promote to Gengineer you need to have a total of 200 builds on one of your planets.
         </para>

         <para number='14'>
         To promote to Magnate you need to have a total of 265 builds on your technological planet.
         </para>

         <para number='15'>
         To promote to Plutocrat you need to have a total of 335 builds on your leisure planet. Your star system must have at least two planets in it.
         </para>

         <para number='16'>
         You cannot promote any further - Plutocrat is the highest rank in the game.
         </para>

      </section>

      <section name='repay'>

         <para number='1'>
         You don't owe the bank any money.
         </para>

      </section>

      <section name='sellwarehouse'>

         <para number='1'>
         Your comm unit beeps and a message appears notifying you that the sale of your warehouse is complete, and that the sum of 250,000ig has been credited to your account.
         </para>

         <para number='2'>
         You don't have a warehouse on this planet!
         </para>

      </section>

      <section name='sendgroupdetail'>

         <para number='1'>
         You're not part of a group!
         </para>

      </section>

      <section name='setnavflag'>

         <para number='1'>
         You can't make a player a navigator until they have a spaceship!
         </para>

      </section>

      <section name='shipstatus'>

         <para number='1'>
         You don't have a ship to report on.
         </para>

      </section>

      <section name='showinventory'>

         <para number='1'>
         a sweet wrapper which you discard.
         </para>

         <para number='2'>
         a sticky toffee with fluff stuck to it, which you promptly drop.
         </para>

         <para number='3'>
         a straightened paperclip, which slips through your fingers and vanishes.
         </para>

         <para number='4'>
         a splintered lollypop stick. Useless. You toss it away.
         </para>

         <para number='5'>
         a handful of biscuit crumbs. You let them trickle through your fingers.
         </para>

         <para number='6'>
         a piece of string, not quite long enough to do anything with. Sighing, you drop it.
         </para>

         <para number='7'>
         a sticky blob of used chewing gum. Yuk! You get rid of it by sticking it on something else.
         </para>

         <para number='8'>
         a ticket stub from the cinema on the Moon, which you bin.
         </para>

         <para number='9'>
         a used subway ticket from the Venus shuttle, which you discard as useless.
         </para>

         <para number='10'>
         a receipt from a shop called 'Madam Boverie'. You can't remember what it was for, so you bin it.
         </para>

         <para number='11'>
         a card from the Hounslow Brasserie, which you accidently drop and are unable to retrieve.
         </para>

         <para number='12'>
         a ticket to last year's Hamsters concert. You discard it and wonder about the next concert.
         </para>

         <para number='13'>
         a leaky pen which no longer works. You look at the ink on your digits and rapidly drop the pen.
         </para>

         <para number='14'>
         a key. What it's for you have no idea, so you ditch it.
         </para>

         <para number='15'>
         a small message capsule that hisses "What has it got in its pocketses?" You hastily drop it.
         </para>

      </section>

      <section name='smile'>

         <para number='1'>
         You look around smiling broadly.
         </para>

      </section>

      <section name='starve'>

         <para number='1'>
         Amazing. You've managed to starve yourself to death!
         </para>

         <para number='2'>
         You're starting to feel hungry...
         </para>

         <para number='3'>
         You're feeling starving hungry!
         </para>

      </section>

      <section name='store'>

         <para number='1'>
         You don't have a ship!
         </para>

         <para number='2'>
         You don't have any of that to store!
         </para>

         <para number='3'>
         You don't have a warehouse on this planet!
         </para>

         <para number='4'>
         You don't have room in your warehouse - the cargo goes mysteriously missing in transit...
         </para>

      </section>

      <section name='suicide'>

         <para number='1'>
         Pulling out an unmarked tube of capsules, you wash five of them down with a large swig of Diesel's Old Peculiar. Within a few moments you start to feel the effects.
         </para>

         <para number='2'>
         Having made the decision, you carefully rig the fusion reactor containment system to fail at the push of a button. You check that no one else in the sector is close and, taking a deep breath, press the button. Your world disolves in a flash of actinic light. Farewell!
         </para>

         <para number='3'>
         Slowly consciousness returns. With difficulty you look around, seeing only unfamiliar medical machines and antiseptic walls. Looks like they managed to successfully clone you after your 'accident', but you are going to need to renew your insurance.
         </para>

         <para number='4'>
         The color drains out of your vision. Everything around you looks like it is being displayed on a low resolution black and white screen. Darkness closes in. Farewell!
         </para>

      </section>

      <section name='void'>

         <para number='1'>
         You don't have a contract to renege on!
         </para>

         <para number='2'>
         An Armstrong Cuthbert freighter pulls alongside and your cargo is transferred across.
         </para>

         <para number='3'>
         Your request is ignored. You will have to wait for the stevedores.
         </para>

         <para number='4'>
         Your betrayal of trust has very serious consequences, costs you 10,000ig in compensation, and a loss of face, honor and credit.
         </para>

      </section>

   </category>

   <category name='playerindex'>

      <section name='broadcast'>

         <para number='1'>
         Just for a second, it almost seems like you can hear an echo bouncing back from the edge of the universe!
         </para>

      </section>

      <section name='callnightwatch'>

         <para number='1' comment='player being hauled off (1)'>
         has called Nightwatch and reported you as a vagrant. Several officers appear to investigate, and one of them gives some orders into his comm unit and a robot trolley arrives.
         </para>

         <para number='2' comment='player being hauled off (2)'>
         You are loaded onto it, transported to the nearest dormitory, and unceremoniously dumped onto the first empty bunk they can find.
         </para>

         <para number='3' comment='tell staff member'>
         The Nightwatch despatcher thanks you for your report. The vagrant will be taken care of.
         </para>

      </section>

      <section name='com'>

         <para number='1'>
         There is a brief hum from your comm unit.
         </para>

      </section>

      <section name='destructor'>

         <para number='1'>
         Federation II is closing down for a few minutes...
         </para>

      </section>

      <section name='logoff'>

         <para number='1'>
         As you step into the stasis field, total blackness enfolds you, and all concept of time flees from your consciousness... Au revoir until we meet again!
         </para>

         <para number='2'>
         A message appears on your com screen, "You are reminded that the Orbital Administration takes no responsibility for unattended cargos lost or stolen."
         </para>

      </section>

      <section name='zap'>

         <para number='1'>
         You can't zap a game manager!
         </para>

      </section>

   </category>

   <category name='review'>

      <section name='read'>

         <para number='1'>
         The Spynet Review - Being an account of births, deaths, promotions and other interesting happenings during the current session.
         </para>

         <para number='2'>
         Nothing of interest has occurred this session - yet.
         </para>

      </section>

   </category>

   <category name='ship'>

      <section name='addcargo'>

         <para number='1'>
         You arrange to have the goods transferred to your ship. By the time you realize that there isn't space for the container it has mysteriously disappeared. No one seems to know which stevedores moved the cargo, or, more likely, no one is admitting to knowing! Be more careful next time...
         </para>

      </section>

      <section name='buy'>

         <para number='1'>
         "That's great," enthuses the droid. "Tell you what - I'll throw in a free shuttle and a half tank of fuel!" He plugs himself into a nearby terminal. "You're in luck, we have that model in your color in orbit at this moment. Please press a digit onto this pad to authorize the agreement and act as a key to the ship."
         </para>

         <para number='2'>
         You follow the droid's instructions and are the proud owner of a spaceship. (Well strictly speaking, the bank is the proud owner of your spaceship!) The shuttle awaits you on the landing pad.
         </para>

         <para number='3'>
         The droid's lips curl in a nasty sneer - they must be made of memory metal - and it looks at you down its olfactory sensor. "Forget it punk," it tells you. "You don't have enough groats to buy a used empty hull, let alone a functioning ship." With that it turns its back on you and opens a conversation with another prospect.
         </para>

         <para number='4'>
         An oily looking sales droid oozes up to you and tells you, "Have I got a deal for you! For just 200,000ig I can let you have one of our special reconditioned Harrier class starter ships. And that includes a loan to cover 100 percent of the cost! It's a steal at that price. So. Waddayasay? Yes or no?"
         </para>

      </section>

      <section name='buyfuel'>

         <para number='1'>
         You already have a full tank of fuel!
         </para>

         <para number='2'>
         You don't have the funds to buy that amount of fuel!
         </para>

         <para number='3'>
         A tanker wallows alongside. A scruffy figure in a battered space suit connects a hose to your fuel intake and refuels your ship. He casually wipes an oily rag over your ship's sensors, accepts the inflated charge with a cheery "Many thanks, guv," and shambles off at a lazy pace.
         </para>

         <para number='4'>
         Unfortunately, you have bought more fuel than your tank has room for. The excess vents through the relief valve and dissipates rapidly. Some people obviously have groats to burn!
         </para>

      </section>

      <section name='reducefuel'>

         <para number='1'>
         You have run out of fuel, and are unable to move.
         </para>

         <para number='2'>
         A warning buzzer sounds...
         </para>

      </section>

   </category>

   <category name='shipbuilder'>

      <section name='addcomputer'>

         <para number='1'>
         You cannot order a computer lower than level 1. Installing a level 1 computer.
         </para>

         <para number='2'>
         Nice try. Installing a level 7 computer.
         </para>

      </section>

      <section name='addfueltanks'>

         <para number='1'>
         You must leave at least 20 tons of cargo space.
         </para>

      </section>

      <section name='addhull'>

         <para number='1'>
         There is a long pause during which the screen remains blank. Finally a message appears telling you that the computer cannot find the design you asked for. It asks you to make a choice from the on-screen menu.
         </para>

         <para number='2'>
         Your permit does not allow anyone below the rank of merchant to fly spaceships larger than the Dragon class. Please try again.
         </para>

         <para number='3'>
         Your permit does not allow pilots of your rank to fly spaceships larger than the Guardian class. Please try again.
         </para>

      </section>

      <section name='addjammers'>

         <para number='1'>
         No jammer packages installed.
         </para>

         <para number='2'>
         One jammer package installed.
         </para>

      </section>

      <section name='addmagazine'>

         <para number='1'>
         No magazine? OK - it's your funeral!
         </para>

      </section>

      <section name='addpower'>

         <para number='1'>
         Your power supply is insufficient to drive the spaceship.
         </para>

      </section>

      <section name='addsensors'>

         <para number='1'>
         No sensor packages installed.
         </para>

         <para number='2'>
         One sensor package installed.
         </para>

      </section>

      <section name='addshields'>

         <para number='1'>
         Installing shields into hull.
         </para>

         <para number='2'>
         No shields installed.
         </para>

      </section>

      <section name='addweapons'>

         <para number='1'>
         No weapons added to the configuration.
         </para>

         <para number='2'>
         No further weapons added to the configuration.
         </para>

         <para number='3'>
         Installing requested weapon system.
         </para>

         <para number='4'>
         Your ship is capable of mounting further weapon systems.
         </para>

         <para number='5'>
         Unable to identify the weapon you want. Please choose from the list supplied.
         </para>

      </section>

      <section name='constructor'>

         <para number='1'>
         The droid ushers you over to a booth where you can configure and order your new ship. As the door hisses shut after it, the screen lights up with a welcoming message telling you that you can configure and purchase a ship from the comfort of the booth.
         </para>

      </section>

      <section name='displayhulls'>

         <para number='1'>
         The screen presents you with a choice of hulls:
         </para>

         <para number='2'>
         Which one do you want? Please type in the name.
         </para>

      </section>

      <section name='displaymag'>

         <para number='1'>
         You have ordered a missile launcher. To use it you need to allocate space to a magazine to hold the missiles. How many missile do you want the magazine to be able to hold?
         </para>

      </section>

      <section name='displayshields'>

         <para number='1'>
         We can fit a ten strength shield unit for just 25,000ig. Do you want one?
         </para>

      </section>

      <section name='displayship'>

         <para number='1'>
         The details of the spaceship you have configured are as follows:
         </para>

         <para number='2'>
         Thank you for browsing our catalog. We hope you will soon be able to afford to buy one of our spaceships.
         </para>

         <para number='3'>
         Do you want to purchase a ship with this configuration?
         </para>

         <para number='4'>
         You need to pay off your loan before you can buy a new spaceship.
         </para>

      </section>

      <section name='displayweapons'>

         <para number='1'>
         Your chosen hull has no facilities for mounting weapons.
         </para>

         <para number='2'>
         Your chosen hull has facilities for mounting one weapon system.
         </para>

      </section>

      <section name='purchase'>

         <para number='1'>
         Thank you for your interest. We hope you will return when you are ready to make a purchase.
         </para>

         <para number='2'>
         Thank you for making your purchase with us. Your account has been debited with the agreed price, and your new spaceship is waiting for you in orbit.
         </para>

         <para number='3'>
         The screen blinks off and the door of the booth slides open allowing you back into the main office.
         </para>

      </section>

   </category>

   <category name='unload'>

      <section name='addplayer'>

         <para number='1'>
         The clerk tells you that there are no stevedores available to unload your ship, and that you will have to wait until a crew finishes their current job.
         </para>

      </section>

      <section name='processlist'>

         <para number='1'>
         The clerk listens to a comm unit message and tells you that the stevedores have finished their tea break.
         </para>

         <para number='2'>
         Flinging down the copy of Interplanetary Geographic, you start pacing the room again.
         </para>

         <para number='3'>
         The clerk tells you to stop pacing and sit down. Plunking yourself down on an uncomfortable, overstuffed seat you pick up a massively out of date copy of Interplanetary Geographic.
         </para>

      </section>

   </category>

   <category name='work'>

      <section name='accept'>

         <para number='1'>
         Unfortunately, someone seems to have already taken that job.
         </para>

      </section>

      <section name='displaywork'>

         <para number='1'>
         Work available from Armstrong Cuthbert:
         </para>

         <para number='2'>
         Armstrong Cuthbert Inc has no work suitable for one of your rank.
         </para>

      </section>

      <section name='notifyplayers'>

         <para number='1'>
         Your comm unit bleeps. Armstrong Cuthbert has freight available for hauling.
         </para>

      </section>

   </category>

</para-list>

