<?xml version="1.0"?>

<para-list version='20'>

   <category name='death'>

      <section name='nuke'>

         <para number='1' comment='Death loc 969 - announce to 905'>
         Ignoring the warning sign on the door, %s boldly walks into the transuranics storeroom, and receives a blast of radiation so intense that death results pretty quickly - but not without some unpleasant screaming first!
         </para>

         <para number='2' comment='Death loc 970 - announce in 905'>
         %s pays no attention to the sign which warns what lies behind the door, and as a result suffers through all the unpleasant consequences of walking into a room full of uranium. Not a nice way to go!
         </para>

         <para number='3' comment='Death loc 906 - announce in 905'>
         Is it stupidity or ignorance that leads %s to ignore the large sign warning of the thorium stored in the room? Whatever the reason, the result is a fatal dose of radiation, followed by an unpleasant, lingering death that it's best not to dwell upon.
         </para>

         <para number='4' comment='Death loc 969 - victim'>
         Wow! What stupidity! You have walked into the main storeroom for the highly radioactive transuranic elements. As you walk in you are blasted by such a massive dose of radiation that you are dead within the hour!
         </para>

         <para number='5' comment='Death loc 970 - victim'>
         Well, the notices did warn you. You have just walked into the base's main uranium store, and received a fatal dose of radiation. We will draw a veil over your lingering death, and assume that it happens at once.
         </para>

         <para number='6' comment='Death loc 906 - victim'>
         Why didn't you read the sign on the door? You have just received a fatal dose of radiation as you poked around in the Thorium storeroom. It will take a few days for you to die a lingering death, but we will assume that you peg out immediately!
         </para>

      </section>

   </category>

   <category name='food'>

      <section name='canteen'>

         <para number='1' comment='Buy food - Canteen - 837'>
         Although you are not a member of staff, you can eat here if you pay. On handing over your groats, a dinner lady gives you a plate and tells you to help yourself. You load the plate with some croquettes that supposedly contain chicken, with a side order of some kind of unidentifiable green vegetable. None of it tastes very nice, but at least it fills you up.
         </para>

         <para number='2' comment='Not enough groats'>
         If you are not a member of staff you have to pay to eat here, and you don't seem to have enough groats.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='bar'>

         <para number='1' comment='1124 - Stop player from methane'>
         A waitdroid stops you from walking into the other side of the dome. "The apres ski bar is for those who have just come off the slopes, not for any visitors," it tells you, ushering you back into the seedy side of the Methane Cafe.
         </para>

         <para number='2' comment='1124 - Take skis'>
         As you walk into the bar, a waitdroid bends down to unstrap the skis from your feet (or equivalent) and gives them to a delivery droid, who puts them away safely, ready to be returned to the top of the mountain.
         </para>

      </section>

      <section name='chairlift'>

         <para number='1' comment='Examine chairlift - 1352'>
         The chairlift is very basic - just pairs of seats mounted either side of a pole, with the pole suspended from an overhead wire. The seats are continually moving, so the trick to using it is to position yourself where a seat will scoop you up.
         </para>

         <para number='2'>
         To get to the top of the mountain, you will need to 'use chairlift'.
         </para>

         <para number='3' comment='Use chairlift - player'>
         You step in front of one of the seats, and it hits your behind and forces you to sit in it. Your feet leave the ground and the seat swings upwards into the air, as it heads up the side of the mountain.
         </para>

         <para number='4'>
         A gust of wind makes the chair rock from side to side in an alarming fashion, but you manage to hang on as it slowly travels upwards, past the ski slopes, to the peak of the mountain. Your feet hit the ground again and you jump out of the seat.
         </para>

         <para number='5' comment='Roomex'>
         You hear a thud as %s steps in front of one of the moving seats and is scooped up and carried up the mountain.
         </para>

         <para number='6' comment='Announce - 1364'>
         The chairlift deposits another skier on the top of the mountain.
         </para>

      </section>

      <section name='hopper'>

         <para number='1' comment='Journey to mountain - player'>
         The hopper's engines start and the craft hurls itself into the air, travelling away from Titan's main domes. Before long, an enormous ice mountain appears ahead of you, and the hopper lands in its shadow. You remove your seat belt and get out.
         </para>

         <para number='2' comment='Announce - 653'>
         One of the hoppers suddenly hurls itself into the air - you can just glimpse %s through the window, being carried off to the ski slope.
         </para>

         <para number='3' comment='Announce - 1159'>
         Another hopper lands and a passenger disembarks...
         </para>

         <para number='4' comment='Return journey - player'>
         The hopper takes off and transports you back to the main inhabited area of the moon. Mist swirls around the craft, making it hard to see anything of the terrain it passes over, and before you know it you're back near your parked shuttle. You unstrap yourself and get out of the hopper.
         </para>

         <para number='5' comment='Announce - 1159'>
         One of the hoppers suddenly takes off. You can see that it is transporting %s back to Titan's main inhabited area.
         </para>

         <para number='6' comment='Announce - 653'>
         Another hopper lands and a passenger disembarks...
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='Surface'>
         That way lies a sheer drop over a cliff... not recommended!
         </para>

         <para number='2' comment='Exchange - loc 713'>
         There is no exit that way, just clusters of traders who resent your attempts to push past them.
         </para>

         <para number='3' comment='Canteen - 837'>
         A very large, fierce-looking dinner lady prevents you from moving in that direction.
         </para>

         <para number='4' comment='Living quarters - 772'>
         Walking into walls is certainly going to leave a scuff mark - and somebody might hear the noise!
         </para>

         <para number='5' comment='Control room - 454'>
         As you turn, you knock a switch. Alarms blare out. Better leave before someone comes to investigate!
         </para>

         <para number='6' comment='Halls - 326, 327, 328'>
         You cannot go that way unless you intend to hurl yourself into the crushing machines.
         </para>

      </section>

      <section name='secure'>

         <para number='1' comment='522 - touch scanner'>
         You touch the scanner and it takes a minute sample of your DNA to check against its database. Since you don't work for the company, clearly you won't be authorized to enter the secure dome... but obviously something is wrong, because the door opens with a whooshy noise!
         </para>

         <para number='2' comment='roomex'>
         The door to the secure dome opens with a whooshy noise!
         </para>

         <para number='3' comment='announce 458'>
         The exit door opens with a whooshy noise!
         </para>

         <para number='4' comment='The door closes again'>
         The door to the secure dome closes with a whooshy noise!
         </para>

         <para number='5' comment='announce 458'>
         The exit door closes with a whooshy noise!
         </para>

         <para number='6' comment='458 - Press button'>
         You press the button and the door opens with a whooshy noise!
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='fountain'>

         <para number='1' comment='Examine fountain - loc 778'>
         Although it is small, the fountain is a potent symbol of humankind's ability to exist on the most inhospitable of worlds - even on a barren ball of rock, the resourcefulness of those who set up the colony can provide freely-flowing water.
         </para>

         <para number='2' comment='Fountain - 2'>
         The stone carving that makes up the fountain takes the form of a beautiful young girl, clad in a flowing robe. In her arms she holds an urn, from which gushes... well, trickles... water, which lands in a small pool surrounded her stone feet.
         </para>

         <para number='3' comment='Fountain - 3'>
         The residents of Titan love this fountain, and spend hours sitting on the edge, trailing their hands or dipping their toes in the water.
         </para>

         <para number='4' comment='Get in fountain'>
         You plunge into the water of the fountain. It's only a few feet deep, but it's enough that you can lie completely submerged by the water, your nano-chameleon suit using its vacuum capabilities to ensure you can still breathe. The water is clear and you can see the top of the dome through the ripples. After a few moments, you emerge feeling cooled and refreshed.
         </para>

         <para number='5' comment='Paddle in fountain'>
         You sit on the edge of the fountain and tentatively dangle your feet into the water. It's cool, but not too cold to bear. The water laps against your legs and seems to wash away all your tensions. The dome's artificial light is warming and the contrast of the cold water and warm air is delicious. But life must go on, you cannot spend all day dreaming by the fountain, so you eventually jump to your feet again.
         </para>

         <para number='6' comment='Get in fountain - roomex'>
         With a splash, %s plunges into the water of the fountain and lies submerged by the water for a few moments - luckily, nano-chameleon suits can use their vacuum capabilities to let the wearer breathe under water.
         </para>

         <para number='7' comment='Paddle in fountain - roomex'>
         Ripples run across the surface of the water in the fountain, as %s sits on the edge and paddles in the cool water.
         </para>

      </section>

      <section name='lever'>

         <para number='1' comment='Pull lever - loc 327'>
         You yank on the lever, and a loud klaxon sounds. The machinery in the various processing rooms comes gradually to a halt. Oh dear, you probably shouldn't have done that! Better get out of there before someone comes along to see who just shut the entire operation down.
         </para>

         <para number='2' comment='Roomex'>
         There is a sudden loud blast of a klaxon - %s has yanked on the emergency stop lever. The machinery in the various processing rooms comes gradually to a halt. Oh dear, you had better scarper before you get the blame for shutting the entire operation down.
         </para>

         <para number='3' comment='Announce for various locs'>
         There is a sudden loud blast of a klaxon, and the machinery in the room comes gradually to a halt. Oh dear, somebody must have pulled the emergency stop lever again! After the loud noise made by the processors, the silence is quite shocking.
         </para>

         <para number='4' comment='Announcement for control room'>
         There is a sudden loud blast of a klaxon, and red lights start to flash on all the control panels, and the screens show that all the machinery has stopped, bringing production to a grinding halt.
         </para>

         <para number='5'>
         After a few moments, a harassed-looking engineer runs in and glares at and shakes its tentacles at you. "Some idiot pulled the emergency stop lever - again!" it growls. "It wasn't you, was it?" You hastily assure it of your innocence; it seems to believe you.
         </para>

         <para number='6'>
         It uses its multiple tentacles to flip switches, turn dials and pull levers until the flashing lights go off, and the machinery starts up again. With a final grumble at whatever irresponsible joker did it this time, the engineer leaves.
         </para>

         <para number='7' comment='Operation resumes...'>
         After a few moments, the machinery starts up again. Somebody must have over-riden the emergency stop!
         </para>

      </section>

      <section name='marsrat'>

         <para number='1' comment='Marsrat event - small park'>
         The weeble looks delighted to see the marsrat you are carrying. "What an interesting creature," it says, stroking the rodent with an appendage.
         </para>

      </section>

      <section name='poster'>

         <para number='1' comment='Read poster (loc 456) - 1'>
         Rule 1 states: safety goggles must be worn in this laboratory at all times.
         </para>

         <para number='2' comment='Poster - 2'>
         Rule 2 states: radiation counters must be affixed to clothing and should be checked on a daily basis.
         </para>

         <para number='3' comment='Poster - 3'>
         Rule 3 states: when entering processing facilities, hard hats are mandatory.
         </para>

         <para number='4' comment='Poster - 4'>
         Rule 4 states: protective clothing should be worn by all personnel dealing with hazardous materials.
         </para>

         <para number='5' comment='Poster - 5'>
         Rule 5 states: no running in the corridors.
         </para>

         <para number='6' comment='Poster - 6'>
         Rule 6 states: it is prohibited to enter the mining areas alone - you must be in a party of two or more.
         </para>

      </section>

      <section name='skis'>

         <para number='1' comment='Get skis - 1301 - already got'>
         You are already wearing some skis, so you have no need for any more. They would only get in the way.
         </para>

         <para number='2' comment='Create some skis'>
         You pick out a pair of skis and strap them onto your feet (or equivalent).
         </para>

         <para number='3' comment='Drop skis'>
         You remove the skis and drop them. A small cleaning droid skis up and retrieves them, glaring at you for your untidiness.
         </para>

         <para number='4' comment='Use skis'>
         You are already wearing the skis, so just go to the top of one of the slopes and push off.
         </para>

      </section>

      <section name='snowglobe'>

         <para number='1' comment='Shake/use snowglobe'>
         You give the snowglobe a good shake and then stare at it... snowflakes swirl around, and as they settle you can see a tiny model skier make its way from the top of the mountain, down the black run, to the bottom.
         </para>

         <para number='2' comment='Drop snowglobe'>
         You drop the snowglobe and it bounces on the ground - it's obviously made of something tough that won't break, which is just as well. However, before you can retrieve it, a cleaning droid scuttles up and removes it, grumbling about litterbugs.
         </para>

      </section>

      <section name='tdx'>

         <para number='1' comment='458 - get TDX - already got'>
         You are already carrying a packet of very dangerous, highly explosive material. It would be extremely foolish to take any more.
         </para>

         <para number='2' comment='Create TDX'>
         You pick up a packet of TDX. Be careful with it - it's very dangerous!
         </para>

         <para number='3' comment='roomex'>
         %s has taken a packet of TDX out of the box.
         </para>

         <para number='4' comment='Drop TDX'>
         Ignoring all the warnings about handling high explosives with care, you drop the packet of TDX. It hits the ground and explodes with a bright flash and a noisy bang. You have just enough time to regret your idiocy before your body is blown to bits and you die.
         </para>

         <para number='5' comment='roomex'>
         There is a bright flash and a noisy bang, and %s is blown to bits by a packet of highly explosive TDX. Luckily, the explosion is small and doesn't affect anyone else in the room.
         </para>

         <para number='6' comment='ex tdx'>
         The packet has a warning stencilled on it in big, red letters: WARNING - HIGH EXPLOSIVE. You need to handle this stuff carefully or something drastic will happen.
         </para>

         <para number='7' comment='In secure dome'>
         You carefully put the TDX back into the box, and gently step away, trying not to jostle it.
         </para>

         <para number='8' comment='roomex'>
         Very carefully, %s has put the TDX back into the box it came from.
         </para>

         <para number='9' comment='Elsewhere'>
         There is nowhere to replace the TDX here - you had better take it back to the place it came from.
         </para>

         <para number='10' comment='throw TDX'>
         You toss the explosive away and duck down. It detonates some way away from you, and you don't sustain any damage from your reckless behavior. Fortunately, nobody else gets hurt, although there's some property damage.
         </para>

         <para number='11'>
         A member of Nightwatch strolls up with a grim look on her face. She lectures you at length about the dangers of playing with high explosives, and fines you 100 groats.
         </para>

         <para number='12' comment='roomex'>
         With a flash and a bang, an explosive thrown by %s detonates. Fortunately, you are not hurt and neither is anyone else, although there is some property damage.
         </para>

         <para number='13'>
         A member of Nightwatch strolls up with a grim look on her face. She proceeds to lecture %s at length about the dangers of playing with high explosives, and issues a fine. Quite right too!
         </para>

         <para number='14' comment='Tick effects - option 1'>
         Something you are carrying goes **tick**.
         </para>

         <para number='15' comment='option 2'>
         Something you are carrying goes **tick... tick...**
         </para>

         <para number='16' comment='option 3'>
         Something you are carrying goes **tick... tick... tick...**
         </para>

         <para number='17' comment='option 4'>
         Something you are carrying starts to make a buzzing sound. The noise gets louder and then ceases abruptly.
         </para>

         <para number='18' comment='option 5'>
         Something you are carrying starts to make a rapid ticking noise. It goes on for a moment, then suddenly stops.
         </para>

         <para number='19' comment='Juggle tdx'>
         You toss the TDX into the air and catch it, then toss it again even higher and catch it with another hand, throw it underarm and then overarm, making more difficult catches each time. Such reckless behavior is not punished; you fail to set off the explosive, much to the relief of other people in the vicinity.
         </para>

         <para number='20' comment='roomex'>
         With shocking recklessness, %s juggles the TDX - tossing it into the air and catching it again, tossing it higher and catching it with another hand, throwing it underarm and then overarm, making more difficult catches each time. To everybody's relief, the explosive does not go off.
         </para>

      </section>

      <section name='weeble'>

         <para number='1' comment='Get weeble'>
         Attempting to pick up the weeble would be very discourteous! Do you usually try to lift other intelligent beings off the ground for no reason?
         </para>

         <para number='2' comment='Kiss weeble'>
         The weeble does not have a mouth, so there is no logical place to kiss it. Just brushing your lips against a random part of its body would probably startle it, and may be unhygienic.
         </para>

         <para number='3' comment='Hug weeble'>
         You put your arms around the little round alien and give it a light squeeze. It produces two arm-like protrusions and returns the hug, squeezing just a little too hard for comfort.
         </para>

         <para number='4' comment='Push weeble'>
         You give the weeble a shove - how rude! It wobbles but it doesn't fall down.
         </para>

         <para number='5' comment='Roomex'>
         Rudely, %s gives the weeble a shove! It wobbles but it doesn't fall down.
         </para>

         <para number='6' comment='Weeble conversation - hello'>
         The weeble extends an eyestalk, which examines you for a moment. Then a mouth slit opens allowing it to speak. "Felicitations of the current time period," it says formally. It then switches to a less overblown form of speech. "It would be pleasant to exchange conversation with you, if you would care to linger for a moment."
         </para>

         <para number='7' comment='Bye'>
         "Farewell, and the best of wishes to you as you go about your perambulations," says the weeble. It then pulls in all its appendages and returns to its resting state, a featureless round ball.
         </para>

         <para number='8' comment='Who'>
         The weeble gives a little giggle. "Oh, there would be no point whatsoever in me imparting my birth name to you. You wouldn't understand it. I have been told by others with whom I have shared converse that it sounds like somebody gargling. No, you can just call me Weeble. After all, I am the only one of my race in Sol, so there is no danger of confusing me with another."
         </para>

         <para number='9' comment='Weeble'>
         "Weebles come from the star system that you call Spica. It doesn't matter what we call it." It curves its mouth slit into something approximating a smile. "My home world is a warm, cozy place, and few of us ever choose to leave. I was considered something of a maverick in that when humans first visited our planet, I decided to hitch a ride with them and see something of the Galaxy."
         </para>

         <para number='10' comment='spica'>
         "My home world is the fourth planet in the system; the others are uninhabitable balls of rock or ice. Home was... warm; much warmer than Earth. Wetter, too; there was always moisture in the air. It's the one thing I find hard to tolerate now; the dryness of your atmosphere. It's why I enjoy sitting here next to the fountain.
         </para>

         <para number='11'>
         "We are born in deep caves, and when we mature to our equivalent of adolescence we emerge onto the planet's surface and range far and wide in search of food and experiences. Then after a few years, when our appetite for adventure is sated, we return to the caves to mate. Somehow, though, I never tired of seeing new things, which is why I chose to leave and see the Galaxy."
         </para>

         <para number='12' comment='job/profession'>
         "Many of the aliens on Titan prefer not to have any contact with humans - not surprising, really, considering some of the anti-alien riots and the other, more subtle, forms of harassment. But somebody has to deal with the outside world; we of the Sequestration cannot cut ourselves off completely. So that's my job - I am the Liaison."
         </para>

         <para number='13' comment='Titan'>
         "It's not much, but it's home," it says, screwing its mouth slit up into a grimace. "You probably know that most of the aliens stranded in Sol when the interstellar link system collapsed banded together for mutual support and safety, and took over an empty dome on Titan. Partly because it put us far, far away from the bigots on Earth with their unpleasant Sol First movement.
         </para>

         <para number='14'>
         "Also because we somehow felt that we wanted to be near the Interstellar Link, even if it wasn't working. It allowed us to feel a little closer to home." It gives a little shiver. "It is much colder here than at home, though."
         </para>

         <para number='15' comment='home'>
         The weeble gives a whistling sigh. "I did miss my homeworld, for a long time. I chose to leave, knowing I could return whenever I wished. Then, suddenly, I could no longer return. I was homesick, as were most of the refugees trapped in this star system where we were not wanted. Throughout the tedious centuries, I dreamt of my home and longed to return there." The weeble's voice sounds quite bleak as it talks.
         </para>

         <para number='16'>
         "Then, the moment we had all been waiting for: the link reopened. I could finally return to my home. And then I remember why I had left in the first place. It was boring! It seemed even more boring after I had seen the amazing sites of the Galaxy. The friends of my youth seemed so provincial; we had all matured and grown old, but our lives had moved in such different directions, we had nothing in common any more.
         </para>

         <para number='17'>
         "So I returned here, to the Sequestration, where many of the other aliens had chosen to remain. Some of them went to their home planets and discovered everything had changed in their absence, so that it no longer felt like home; plus, of course, many had been born here on Titan so to them, this was home."
         </para>

         <para number='18' comment='earth'>
         "There was a time, when I was younger, that I spent a lot of time on Earth. I had a post in the Galactic Administration - nothing important, just a junior attache to one of the alien contact officers - but I enjoyed being at the center of government." The weeble's mouth slot curls into a smile so broad it disappears around both sides of its little round body. "And I love your earth cuisine!"
         </para>

         <para number='19' comment='cuisine'>
         "You see," the weeble explains, "On my home world, our diet was very restricted. We ate foliage from one type of plant, and also consumed one type of... well, it's a kind of insect. Can you imagine my amazement when I discovered that humans had such an enormous variety of foodstuffs? Not only that, but the things you do to transform the basic ingredients... cooking! A process that seems magical, and that produces such wonderful things."
         </para>

         <para number='20'>
         It gives a pleasurable sigh, remembering some of its favorite meals. "Spices... what a wonderful sensation it is to feel the different flavors exploding onto the tastepads. We have nothing like that at home. Cheese... how astonishing that secretions from an animal can be formed into such an abundance of different varieties, mild and sharp, creamy and crumbly.
         </para>

         <para number='21'>
         "But best of all are your Earth puddings. Jam roly-poly was always a treat. Somehow, word got around that I was fond of it, and complete strangers would bring me portions of it. It was quite embarrassing; I felt obliged to pay them for their trouble."
         </para>

         <para number='22' comment='galactic admin'>
         The weeble gives a little quiver, which you guess is its version of a shrug. "All civilizations need some form of government, it seems. The GA isn't too bad compared to some of the others out in the Galaxy. They keep things ticking along, and don't interfere too much in the lives of ordinary people. Of course they are a huge, clumsy bureaucracy, but that's a good thing: it prevents them from doing anything terribly important."
         </para>

         <para number='23'>
         Its voice takes on a grimmer tone, and several appendages appear from its body and wave around agitatedly. "It was different when Ming was on the throne, of course. Those were dark days."
         </para>

         <para number='24' comment='ming'>
         "Working for the GA was very precarious when Ming was Emperor," explains the Weeble. "You never knew when he might take it into his head to demand something outrageous - and woe betide the official who couldn't produce what he desired with all speed. I will say something about him, though - he wasn't a bigot. He was equally vicious to all species; didn't discriminate at all.
         </para>

         <para number='25'>
         "Except for the Martians, of course. He especially hated them, with good reason."
         </para>

         <para number='26' comment='martians'>
         "It was during Ming's regime that the Martians' attempts to invade us were at their height. Surely you know that they made repeated efforts to tamper with time, using timewarps to travel to the period before humans discovered space travel, and wipe us out before we could spread throughout the Galaxy.
         </para>

         <para number='27'>
         "If it wasn't for the gallant work of a whole set of intrepid planet-owners, who one by one risked their fortunes and their lives to thwart the Martians' dastardly plans, the whole Galaxy would be a very different place now. Mars would belong to the Martians again."
         </para>

         <para number='28' comment='Mars'>
         "Mars without the Martians is a pleasant place to visit. I like it; I admire the independent spirit of the humans who have settled there. Unlike many, they really don't care about external trivialities such as species; they judge a being on what they say and what they do, not how many arms they have!
         </para>

         <para number='29'>
         "I'm quite friendly with Phil, the pianist who works for Diesel.
         </para>

         <para number='30' comment='Phil/pianist'>
         "He's a great pianist - well, his extra arms do help, don't they? Diesel is very lucky to have him - and he's also excellent company when he's not working." The weeble gives a fruity chuckle. "We share a taste for puns; the kind that make listeners groan and rush for some fresh air."
         </para>

         <para number='31' comment='pun'>
         "No, I am not going to repeat any now; you'd have to catch me and Phil together some time. That's if you have the stomach for it." It chuckles again.
         </para>

         <para number='32' comment='diesel'>
         "What can I say about the estimable Diesel that hasn't been said a thousand times? She and I have been friends for many years; when I was first brought to Sol by the human explorers who found Spica, she welcomed me to her bar, and when Sol First were being particularly unpleasant Chez Diesel provided a safe haven for the persecuted.
         </para>

         <para number='33'>
         "Plus, she serves a fantastic pizza. Adding moose to the topping - what a marvellous idea! The woman is a veritable genius!"
         </para>

         <para number='34' comment='chez diesel'>
         "A few centuries ago, the bar truly was the Social Center of the Solar System. Everybody, but everybody went there, and it was always crowded and humming. But then when the interregnum ended and the link opened up again, the exodus as new Founders emigrated to their own planet drew many of her customers away. For me, though, it'll always be the Social Center - the best bar in the whole Galaxy."
         </para>

         <para number='35' comment='alien'>
         "There were many aliens trapped in the Solar System when the constant catastrophe closed down the links. Some were in quite large groups; there were also small families, and the odd solitary individuals who were the only representatives of their species, such as myself. You would have thought such a diverse set of beings would have little in common, but we were forced to band together to protect against those idiotic bigots from Sol First."
         </para>

         <para number='36' comment='constant/catastrophe/interregnu'>
         "You can read all about those in the Encyclopedia Galactica at http://www.ibgames.net/fed2/galactica/index.html - they are far too complex for me to explain now."
         </para>

         <para number='37' comment='sequestration'>
         The weeble waves an eyestalk at you. "It's a lovely word, isn't it - it rolls around the oral cavity. Sequestration. Se-ques-tra-tion!" It giggles with delight. "I do love your human language, it's so rich and flavorsome.
         </para>

         <para number='38'>
         "Some of the humans called our dome on Titan the alien ghetto, but we resisted that name because it has an ugly history. We felt if we used that word, we would be encouraging the unpleasantness that had been visited upon various groupings of humans in the past."
         </para>

         <para number='39' comment='sol first'>
         It sighs and says, with a sorrowful note in its voice, "It is one of the uglier characteristics of humans that when forming into cohesive social groupings they need to exclude some people and look down upon them, in order to feel superior themselves. I have studied Earth history, you see. This contempt often seems to turn to hatred and violence and all manner of unpleasantness ensues.
         </para>

         <para number='40'>
         "Sol First is just the latest in a long, long line of organizations that campaign against whatever section of society they deem to be inferior. They are not as dangerous a threat as they would like to think they are, of course; oh, gangs do sometimes corner a lone alien and do it harm, but their attempts to whip up widespread hatred haven't really worked. Most humans may not like aliens, but they are too lazy to do anything about it.
         </para>

         <para number='41'>
         "Occasionally, some marauding gangs come here to Titan with the intent to 'kill all the alien scum' or something, but the exact location of the Sequestration is a well-kept secret, and they cannot find our dome in order to burn it down. They either stumble around on the surface for a while until they lose interest, or they come into the main domes here and try to cause trouble - at which point, the workers show them the error of their ways."
         </para>

         <para number='42' comment='Nomatch'>
         The weeble extends several eyestalks and examines from you different angles. "I am sorry my friend, I have nothing to say on that particular subject," it says.
         </para>

      </section>

   </category>

   <category name='ski'>

      <section name='black'>

         <para number='1' comment='Push off - 1299 - no skis'>
         You can't go down the slope without wearing skis, silly! Go visit the equipment hut.
         </para>

         <para number='2' comment='Not skied nursery slope yet'>
         The sensor can tell you have no skiing experience. A barrier is lowered to prevent you from going down the black run, and a sign lights up and flashes at you, telling you to try the nursery slope first.
         </para>

         <para number='3' comment='Player starts to ski'>
         You push off and slowly start to descend the mountain.
         </para>

         <para number='4' comment='Roomex'>
         With a big push, %s starts to slide down the slope...
         </para>

         <para number='5' comment='Black run - 2'>
         At first, it doesn't seem too difficult; you're moving fast, and the turns are tight, but the ice under your skis is smooth. It's nothing you can't handle, you think to yourself, feeling confident.
         </para>

         <para number='6' comment='Black run 3'>
         Around several turns you zoom, enjoying the thrill until suddenly, around a bend, the slope ends in a sheer drop. You sail off the end and fall through the air, but only for a few feet before landing on a lower part of the slope. That was scary, but you came through it alright.
         </para>

         <para number='7' comment='Black run 4'>
         After the next tight turn, it looks like the slope leads straight towards a ridge of ice jutting out from the mountain. You brace yourself for the impact, but at the last minute the slope turns at right-angles and you find yourself skiing in parallel to the spur.
         </para>

         <para number='8' comment='Finish - 1st time'>
         You're almost at the bottom now, and it looks like you have made it without injury. Phew! But just as you relax and look ahead to the finish, one of your skis hits a bump and swivels around to one side. It crosses over the other ski and gets tangled up hopelessly. As a result, you fall over and somersault a few times, tumbling down the last part of the slope to slither to a stop at the foot of the mountain.
         </para>

         <para number='9'>
         Miraculously, though, you don't seem to be hurt. Maybe if you try again you will do better next time.
         </para>

         <para number='10' comment='Announce - 1225'>
         You see somebody tumble down the last few feet of the slope and land in a heap - it looks like %s had a little accident.
         </para>

         <para number='11' comment='Announce - 1124'>
         Looking out of the window, you see somebody tumble down the last few feet of the slope and land in a heap - it looks like %s had a little accident.
         </para>

         <para number='12' comment='Finish - expert'>
         You're almost at the bottom now, and it looks like you have made it without injury. Phew! You concentrate very hard so that you don't lose it at the last moment, and swerve round the final bend to ski through the exit barrier and come to a halt at the foot of the mountain. As you catch your breath, a droid slithers across the ice and congratulates you, handing you a special souvenir to remind you of your triumph.
         </para>

         <para number='13' comment='Announce - 1225'>
         A skier slithers to a halt - %s has just successfully travelled down the black run. A droid congratulates the expert skier and hands over a souvenir.
         </para>

         <para number='14' comment='Announce - 1124'>
         Looking out of the window, you can see that %s has just successfully skied down the black run, and joined the ranks of the expert skiers.
         </para>

      </section>

      <section name='nursery'>

         <para number='1' comment='Push off - 1235 - no skis'>
         You can't go down the slope without wearing skis, silly! Go visit the equipment hut.
         </para>

         <para number='2' comment='Player starts to ski'>
         You push off and slowly start to slide down the slope...
         </para>

         <para number='3' comment='Roomex'>
         With a big push, %s starts to slide down the slope...
         </para>

         <para number='4' comment='Nursery slope - 2'>
         It's not too steep, and despite your lack of experience you find it easy to keep going in a straight line as you pick up speed. You reach the first turn and safely - if clumsily - change direction to leave the zig and descend the next zag.
         </para>

         <para number='5' comment='Nursery slope - 3'>
         You're moving quite fast now, and the feeling of the chill mountain air moving past you is quite exhilarating. The ice under your skis is completely smooth with no lumps and bumps, so there's no danger of you falling over unless you do something really dumb. You negotiate the second turn without incident.
         </para>

         <para number='6' comment='Nursery slope - end'>
         You're hurtling along now but despite your speed, you find the last few turns are a piece of cake. Feeling proud of the new skill you have learned, you ski through the exit barrier and come to a halt at the foot of the mountain. As you catch your breath, there's a flash, as a camera snaps a picture of you at this moment of triumph - and records the fact that you are no longer a beginner.
         </para>

         <para number='7' comment='Announce - 1225'>
         There is a flash as the camera snaps %s successfully skiing through the exit barrier, having negotiated the nursery slope.
         </para>

         <para number='8' comment='Announce - 1124'>
         Looking out of the window, you can see that %s has just successfully skied down the nursery slope.
         </para>

      </section>

   </category>

</para-list>

