<?xml version="1.0"?>

<para-list version='36'>

   <category name='food'>

      <section name='spaceman'>

         <para number='1' comment='Buy food - Urban Spaceman - 453'>
         You press the touchpad on the bar and a sign lights up: please deposit ten groats. You put the correct coins into the appropriate slot, and your chili-dog appears from a serving hatch. It's hot... and very spicy... it appears to be made of meat, of some sort, but best not to enquire too closely! The cheese is bright orange and has the consistency of rubber. The whole thing fills you up but leaves you feeling slightly queasy.
         </para>

         <para number='2' comment='Not enuff groats'>
         You press the touchpad on the bar and a sign lights up: please deposit ten groats. That's when you realize that you don't have ten groats - you are broke.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Slideways'>
         The rock walls prevent you from moving off the slideway in that direction.
         </para>

         <para number='2' comment='Park - loc 396, 397'>
         The rock walls of the park stop you from going in that direction.
         </para>

         <para number='3' comment='Mines'>
         The tunnel's rock walls bar your way in that direction.
         </para>

         <para number='4' comment='Spaceport'>
         The rock walls of the huge spaceport cavern stop you from going that way.
         </para>

         <para number='5' comment='Museum'>
         There are no museum exhibits in that direction.
         </para>

         <para number='6' comment='Bar - loc 453'>
         The urban spaceman gently stops you from walking into the wall.
         </para>

      </section>

   </category>

   <category name='newbod'>

      <section name='message'>

         <para number='1' comment='Player finds firestone'>
         As you enter the location you are drawn to a flickering smoky red gleam. It's a firestone, but it's already psychically imprinted with an image of the Magellan Society's crest. Obviously, it was left here for you to find. You prise it out of the wall, wrap it up to keep it safe and slip it into your pocket.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='adverts'>

         <para number='1' comment='Examine advert - loc 518'>
         The advert shows a selection of commercial messages from various organizations and companies on Venus.
         </para>

         <para number='2' comment='advert - 1'>
         A jolly chap raises a mug to the camera, and exhorts you to visit the Urban Spaceman bar, close to the spaceport, and drink in the company of authentic spacemen.
         </para>

         <para number='3' comment='advert - 2'>
         An announcement from the Venus power plant trumpets the fact that they will be bringing a new generator online soon, which will double their capacity.
         </para>

         <para number='4' comment='advert - 3'>
         A spokesman from the Venus Freedom Party rants on about the evil and corrupt Galactic Administration, which is strangling the freedom of Venusians... and on, and on. He closes by asking for donations to aid the cause.
         </para>

         <para number='5' comment='advert - 4'>
         The Venus Museum announces its new exhibit, entitled Myths and Legends. An earnest voice tells you it is both entertaining and educational, while the screen displays pictures of the some of the exhibits.
         </para>

         <para number='6' comment='advert - 5'>
         Cheesy saxophone music plays, and a silhouette of people dancing slowly and seductively appears on the screen. Lettering appears: "Dr Fogg's Marital Arts Emporium. You know what we offer." The picture fades to black, and the music is replaced by a man laughing the dirtiest laugh you have ever heard.
         </para>

         <para number='7' comment='adverts - 6'>
         An attractive woman in a slinky black dress holds out her arm, showing you a gold bracelet studded with Venusian opals. In a sultry voice, she says, "I had this delivered... by Armstrong Cuthbert."
         </para>

         <para number='8' comment='adverts - 7'>
         A smart executive in the latest cut-away pinstripe shorts brandishes a locked metal briefcase. "I had this delivered... by Armstrong Cuthbert," he says.
         </para>

         <para number='9' comment='adverts - 8'>
         A small furry alien holds a poster showing an old Earth baseball star. He speaks in his native language, which sounds like somebody gargling; the subtitle translates his speech as, "I had this delivered... by Armstrong Cuthbert."
         </para>

         <para number='10' comment='adverts - 9'>
         A gorgeous hunk of a man, dressed in not very much, holds a single white rose. He lifts it to his nose and inhales the scent deeply, his chest muscles rippling as he takes in the breath, then he looks out of the viewscreen and says, "I had this delivered... by Armstrong Cuthbert."
         </para>

         <para number='11' comment='adverts - 10'>
         A droid appears on the screen, with its head all battered and dented, hanging off its shoulders by a few wires. It removes the head and drops it, then picks up a new head and slots it in place. It shakes the new head backwards and forwards a few times, then says in a mechanical voice, "I had this delivered... by Armstrong Cuthbert."
         </para>

      </section>

      <section name='burbage'>

         <para number='1' comment='Burbage - variable unknown'>
         Burbage notices you and comes to the front of the stage. "Hamlet," says the droid. "I was born to play this role. There's no reason he has to be played by a human - robots can act just as well, and can show real emotion. Or at least we can fake it so you can't tell the difference." It jumps off the stage into the aisle. "You would like to hear me recite, I am sure."
         </para>

         <para number='2' comment='Burbage - variable is 1'>
         "Oh good," says the droid, regardless of what you actually said. He takes a heroic stance, fixes his sensors on you with a piercing gaze, and begins: "To be, or not to be--that is the question: Whether 'tis nobler in the mind to suffer The slings and arrows of outrageous fortune Or to take arms against a sea of troubles And by opposing end them."
         </para>

         <para number='3' comment='Burbage - variable is 2'>
         Ignoring your interruption, the droid actor continues: "To die, to sleep-- No more--and by a sleep to say we end The heartache, and the thousand natural shocks That flesh is heir to. 'Tis a consummation   Devoutly to be wished."
         </para>

         <para number='4' comment='Burbage - variable is 3'>
         And still it goes on: "To die, to sleep-- To sleep--perchance to dream: ay, there's the rub, For in that sleep of death what dreams may come When we have shuffled off this mortal coil, Must give us pause. There's the respect That makes calamity of so long life."
         </para>

         <para number='5' comment='Burbage - variable is 4'>
         It's really getting into the role now, oblivious to your comment, flecks of lub-oil flying out of its orifice as it continues with intensity: "For who would bear the whips and scorns of time, Th' oppressor's wrong, the proud man's contumely The pangs of despised love, the law's delay, The insolence of office, and the spurns That patient merit of th' unworthy takes, When he himself might his quietus make With a bare bodkin?"
         </para>

         <para number='6' comment='Burbage - variable is 5'>
         You may as well resign yourself to hearing the whole soliloquy because nothing is going to stop the droid now: "Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country, from whose bourn No traveller returns, puzzles the will, And makes us rather bear those ills we have Than fly to others that we know not of?"
         </para>

         <para number='7' comment='Burbage - variable is 6'>
         Never have you seen a droid so impassioned, as it launches itself into the final stanza of Hamlet's famous speech: "Thus conscience does make cowards of us all, And thus the native hue of resolution Is sicklied o'er with the pale cast of thought, And enterprise of great pitch and moment With this regard their currents turn awry And lose the name of action. -- Soft you now, The fair Ophelia! -- Nymph, in thy orisons Be all my sins remembered."
         </para>

         <para number='8' comment='Burbage - variable is 7'>
         "Well, I am sure you were impressed," says the thespian droid. "I've won awards for my Hamlet, you know. I wowed them on Mars, they lauded me on the Moon and cheered me to the rafters on Mercury. Even the little provincial planets, Titan and Castillo, heaped praises upon me. But will they let me play on Earth? No, they will not, because they are afraid that I will over-shadow their human actors," it says this with a sneer.
         </para>

         <para number='9'>
         "But talent will out, and one day they will treat me as I deserve." Its eyes gaze into the distance, as it ponders the applause that it clearly feels is its due.
         </para>

         <para number='10'>
         "Now, it was absolutely fascinating to hear all about you, but I must get on with rehearsals." The droid jumps back up onto the stage.
         </para>

         <para number='11' comment='Burbage has finished his speech'>
         Burbage ignores you and carries on rehearsing its lines in a monotonous mutter.
         </para>

      </section>

      <section name='castle'>

         <para number='1' comment='Bouncy castle - 1 - player'>
         Clambering onto the bouncy castle, you start jumping up and down. You bounce, bounce, bounce, then fall over in a very ungainly fashion, looking like a complete twit. You get off and hope nobody noticed your pratfall.
         </para>

         <para number='2' comment='Bouncy castle - 1 - roomex'>
         Clambering onto the bouncy castle, %s starts jumping up and down, with a bounce, bounce bounce... and then falls over in a very ungainly fashion, looking like a complete twit. What a pratfall!
         </para>

         <para number='3' comment='Bouncy castle - 2 - player'>
         Clambering onto the bouncy castle, you start jumping up and down. You bounce a few times, then decide to liven things up by bouncing sideways into the walls. After you almost knock over one of the children, a droid park-keeper very pointedly asks you to calm down a bit, so you get off again.
         </para>

         <para number='4' comment='Bouncy castle - 2 - roomex'>
         Clambering onto the bouncy castle, %s starts jumping up and down. After bouncing a few times, the bouncer decides to liven things up by bouncing sideways into the walls, but almost knocks over one of the children, who calls for a droid park-keeper!
         </para>

         <para number='5' comment='Bouncy castle - 3 - player'>
         Clambering onto the bouncy castle, you start jumping up and down. You bounce once, twice, three times, getting higher each time, until your head is going higher than the top of the castle walls. You get a lovely view over the rest of the park! After a few moments you start to feel quite light-headed from the exertion, so you decide to get off and rest.
         </para>

         <para number='6' comment='Bouncy castle - 3 - roomex'>
         Clambering onto the bouncy castle, %s starts jumping up and down... bouncing once, twice, three times, getting higher each time, going higher than the top of the castle walls. Must be a lovely view of the park from that high!
         </para>

         <para number='7' comment='Bouncy castle - 4 - player'>
         Clambering onto the bouncy castle, you start jumping up and down. You bounce around with wild abandon, not really paying attention to where you are bouncing, just enjoying yourself hugely - until you suddenly stumble and carom off one of the side walls, off the bouncy castle and towards the patch of grass, treading upon which is forbidden.
         </para>

         <para number='8'>
         For a moment, it looks as though you are going to land right in the middle of it, doing who knows what damage to the fragile stems, but a quick-thinking droid park-keeper calculates your trajectory and dives into your path, tackling you to the ground before you can squish any of the stalks. It helps you up and advises you to be more careful in the future.
         </para>

         <para number='9' comment='Bouncy castle - 4 - roomex'>
         Clambering onto the bouncy castle, %s starts jumping up and down. Bouncing around with wild abandon, the bouncer is not really paying attention, just enjoying the fun - until suddenly a mis-bounce results in a carom off one of the side walls, off the bouncy castle and towards the patch of grass, treading upon which is forbidden.
         </para>

         <para number='10'>
         For a moment, it looks as though %s is going to land right in the middle of it, doing who knows what damage to the fragile stems, but a quick-thinking droid park-keeper calculates the trajectory and dives into the bouncer's path; performing a heroic tackle, it saves the greenery from being squished.
         </para>

         <para number='11' comment='Bouncy castle - 5 - player'>
         Clambering onto the bouncy castle, you start jumping up and down. You bounce up and down several times and feel in complete control, so you decide to try some acrobatics. You scrunch up into a ball and bounce down then up again; stick your limbs out in front of you in a pike; bounce down into a sitting position, then swivel round and bounce facing the other way; and perform a mid-air somersault.
         </para>

         <para number='12'>
         It's all very impressive, and some of the children applaud as you complete the display with a massive bounce off the castle.
         </para>

         <para number='13' comment='Bouncy castle - 5 - roomex'>
         Clambering onto the bouncy castle, %s starts jumping up and down. Bouncing up and down several times, and appearing in complete control, the bouncer decides to try some acrobatics. There's the scrunch into a ball and bouncing down then up again; the sticking the limbs out in front in a pike; bouncing down into a sitting position, then swiveling round to bounce facing the other way; and even a mid-air somersault.
         </para>

         <para number='14'>
         It's all very impressive, and there is a ripple of applause from some of the children as %s completes the display with a massive bounce off the castle.
         </para>

         <para number='15' comment='Get bouncy castle'>
         Don't be silly - it would be far too heavy for you to move, even if it didn't have a crowd of children bouncing on it.
         </para>

         <para number='16' comment='pop/puncture/deflate'>
         What kind of a cruel being would ruin the fun of the little children that way? Well, obviously, you would - but fortunately, you are prevented from destroying the castle by a droid park-keeper, who restrains you until you promise to leave the bouncy castle alone.
         </para>

         <para number='17' comment='roomex'>
         If you have ever wondered what kind of a cruel being would try to ruin the fun of little children, then now you know - %s has just tried to destroy the bouncy castle. Fortunately, a droid park-keeper prevented this shocking act of vandalism, and restrained the miscreant, procuring a promise not to do it again.
         </para>

      </section>

      <section name='donut'>

         <para number='1' comment='Get donut - in loc 326 - 1'>
         You reach into the box and carefully extract a jelly donut. As you bite into it, the bright red jelly oozes out and smears all around your mouth.
         </para>

         <para number='2' comment='Get donut - in loc 326 - 2'>
         You reach into the box and carefully extract a chocolate donut. The delicious chocolatey goodness makes you moan with pleasure as you munch your way through it.
         </para>

         <para number='3' comment='Get donut - in loc 326 - 2'>
         You reach into the box and carefully extract a strawberry-frosted donut. The coating really does taste of real strawberries, even though it's probably been nowhere near a piece of fruit and is manufactured from all kinds of artificial flavorings.
         </para>

         <para number='4' comment='Get donut - in loc 326 - 4'>
         You reach into the box and carefully extract a cream-filled donut. It is impossible to eat tidily - the cream spurts out with some pressure, landing on the desk. Guiltily, you finish up the donut, then wipe up the spilt cream.
         </para>

         <para number='5' comment='Get donut - in loc 326 - 5'>
         You reach into the box and carefully extract a sugar-covered donut. Each bite you take from it produces a cloud of powdered sugar which fills the air like a miniature blizzard. A thin layer lands on the operator's face, making him twitch and snort in his sleep, but the strong air conditioning in the room blows it away before long.
         </para>

         <para number='6' comment='Get donut - in loc 326 - 6'>
         You reach into the box and carefully extract a green glowing donut. Odd - you didn't know donuts could be luminous. Biting into the donut you realize the green isn't because it is mint-flavored, or lime, or even pistachio - it's a radioactive donut! Oh dear! You hastily discard it, and hope it hasn't done you too much harm.
         </para>

         <para number='7' comment='Get donut - in loc 326 - 7'>
         You reach into the box and carefully extract a donut. Except that it's not a donut - for some reason, there is a piece of jam rolypoly in the box! Wonder how that got there? Oh well, it tastes almost as good as a donut.
         </para>

      </section>

      <section name='donutbox'>

         <para number='1' comment='Get box of donuts - in loc 326'>
         Taking the whole box of donuts would be terribly greedy - besides, your theft might wake up the sleeping operator!
         </para>

      </section>

      <section name='marsrat'>

         <para number='1' comment='Marsrat event - urban spaceman'>
         A bleary-eyed spacer hoists a tankard in your direction, and says, "Nice rat you got there pal."
         </para>

      </section>

      <section name='pegasus'>

         <para number='1' comment='Ride pegasus - loc 588'>
         You climb onto the back of this legendary beast, and dig your heels into his sides. "Gee up, horsey," you cry. Nothing happens, but then, you woudn't expect it to, because he's dead. Such a vicious, dangerous creature when he was alive, who would have thought he'd ever allow anyone on his back?
         </para>

         <para number='2' comment='roomex'>
         You hear a sudden cry of "Gee up, horsey!" Looking around, you discover that %s has climbed onto the back of the legendary beast and is riding him. Such a vicious, dangerous creature as the winged horse would never have allowed this when he was alive!
         </para>

      </section>

      <section name='priest'>

         <para number='1' comment='hello'>
         The priest acknowledges your greeting with a nod. "How can I help you, %s?"
         </para>

         <para number='2' comment='job/work (1)'>
         "I am the priest and councelor attached to this temple.", he explains. "We do not hold services as such, worship is by individual contemplation."
         </para>

         <para number='3' comment='job/work (2)'>
         "My job is to look after the shrine and to provide councel to the worshipers. I also," he smiles, "answer the questions of the curious who visit the shrine to find out more. However, we are not a proselyting organisation, so missionary activity is not called for."
         </para>

         <para number='4' comment='temple'>
         "The temple is, as near as we can tell, a replica of the inside of one of the Martian spaceships. We have explored the ruins extensively, and the design is based on frescos and blueprints found in the ruins."
         </para>

         <para number='5' comment='Cult (1)'>
         "Our Cult is based on the revelations of the prophet Gaelaan. We are a peaceful people, but unfortunately there are those of our foes who are far from peaceful, and on a number of occasions we have had to defend our members against outside violence.
         </para>

         <para number='6' comment='Cult (2)'>
         "You can read more about the Cult of Gaelaan in our Encyclopedia Galactica entry at http://www.ibgames.net/fed2/galactica/gaelaan.html"
         </para>

         <para number='7' comment='Gaelaan'>
         "The prophet Gaelaan was taken from us some years ago. We do not know exactly what happened, but we believe that he has gone before us."
         </para>

         <para number='8' comment='venus'>
         The priest looks thoughtful. "We have been lucky on Venus, a political alliance with the Venus Freedom Party has allowed us to openly establish the shrine. Sadly things are not so easy elsewhere. On Selena, for instance, the Cult is subject to repression, and worship is, by necessity, clandestine."
         </para>

         <para number='9' comment='bye'>
         The priest bows graciously and returns to his contemplation.
         </para>

         <para number='10' comment='nomatch'>
         The priest shakes his head regretfully. "I'm sorry, I can't help you with that.", he tells you.
         </para>

      </section>

      <section name='spittoon'>

         <para number='1' comment='Get/take spittoon - loc 453'>
         Don't be disgusting!
         </para>

         <para number='2' comment='Spit - player'>
         Even though you're not chewing any cud (it is a filthy habit!) you summon up some spittle, or mucus, or whatever the equivalent is for your species, and spit it into the spittoon. The clever little gadget uses suction to make it impossible to miss, which is a relief otherwise the floor would get very messy.
         </para>

         <para number='3' comment='Roomex'>
         Oh how disgusting - %s has just spat something in the vague direction of the spittoon. Luckily the clever little gadget uses suction to make it impossible to miss, which is a relief otherwise the floor would get very messy.
         </para>

      </section>

      <section name='zork'>

         <para number='1' comment='hello'>
         "Wotcha guv!" says the droid in an excruciating cockney accent. "Wot can I do you for?" It smirks, takes a swig of its coffee, and stares at you expectantly, ocular units swiveling to look at you from different angles.
         </para>

         <para number='2' comment='bye'>
         The droid waves an appendage in a casual manner. "'Ave-a-noice-day-guv," it says, running all the words together.
         </para>

         <para number='3' comment='nomatch'>
         "'Fraid I can't 'elp you with that one, guv," it says in an infuriatingly cheerful tone of voice.
         </para>

         <para number='4' comment='cockney'>
         "Manufactured within the sound of the Bow Bells!" the droid declares proudly. "All my assembly siblings have these accents. Blimey - some of 'em even became Pearly Droids!"
         </para>

         <para number='5' comment='pearly'>
         "Pearly Droids? They are an important piece of history. Blimey, what do they teach at schools these days? There's an entry about them in the Encyclopedia Galactica at http://www.ibgames.net/fed2/galactica/pearly.html." The droid zooms its ocular sensors slowly in and out, in the droid equivalent of shaking its head.
         </para>

         <para number='6' comment='job/work/profession [1]'>
         "I'm a dayta-input-droid," it says proudly, slurring the words together in a way that makes it difficult to understand. "The Company, Hermes Insurance, handles life insurance in this neck of the woods. I record the number of deaths for each punter."
         </para>

         <para number='7' comment='job/work/profession [2]'>
         Its ocular sensors give you a sly, sideways look. "Of course, for a suitable consideration, I might just be able to reduce the number of deaths for someone. Let's say a reduction in the number of deaths by five in return for a slithy tove?" You notice that the cockney accent has mysteriously vanished.
         </para>

         <para number='8' comment='insurance'>
         "Painfully expensive, isn't it guv?" It sounds very cheerful, but then it's not the droid's money. It lowers its voice, "For a small consideration - say a slithy tove - I could reduce the number of deaths on your record by five..." It raises an appendage. "For you I would do it for free, but the union won't let me. Honest guv, would I lie to you?"
         </para>

         <para number='9' comment='london [1]'>
         "Ah! Lundun!" The droid's ocular sensors mist over as it remembers its home. "Of course, fings-ain't-wot-they-use-ta-be." You rather wish it would stop running the words together - the accent is difficult enough to follow even when the words are separated.
         </para>

         <para number='10' comment='london [2]'>
         "I used to be a cab driver you know. Fings went downhill when they allowed those foreign robots from Slough in... it was all the fault of the govmint... I once had Ming in the back of my cab, before he was the big boss, of course... congestion charging... total nightmare... how can anyone be expected..." You find your concentration drifting as the droid's tirade washes over you.
         </para>

         <para number='11' comment='london [3]'>
         "...so after that I'd had enough, and I moved here and got this job working in life insurance." It stops, a bit like a run down clockwork toy. You jerk yourself back to reality and make some suitably sympathetic noises.
         </para>

         <para number='12' comment='venus'>
         "S'OK, if you like that sort of fing," it tells you. "The politics here is very weird, wot wiv the Lib-ray-shun Party and that funny Cult of Gaylin. I stay well clear and try to keep my olfactory sensors clean."
         </para>

         <para number='13' comment='beverage/coffee'>
         Somehow or other the droid manages to look furtive. "Coffee isn't illegal," it tells you defensively. "THEY" - you can hear the capitals in its voice - "want to ban it, but doing that would cause riots so they jus' put 'toxic substance' labels on the containers. I like to add some machine oil and a couple of drops of WD40 to keep the parts all moving in harmony."
         </para>

         <para number='14' comment='gaelaan/gaylin'>
         "That lot? Bunch o' loonies!"
         </para>

         <para number='15' comment='union/thwap'>
         The droid preens itself. "I," it informs you proudly, "am a fully paid up member of the union -  The Helpful Workers Alliance for Progress." Seeing that you look mystified it tells you that THWAP is a system-wide union for non-organics working in the data industry. "Of course," it adds, "I would like to be in the stevedore's union, but that's not possible..."
         </para>

         <para number='16' comment='stevedor'>
         "Everyone wants to be a stevedore," it tells you. "It's hard work, but well paid, and the, errrm, fringe benefits have to be seen to be believed. But you can't be a stevedore unless you are in their union. And you can't be in the union unless you are a stevedore. The jobs are heirlooms inherited by the children." The droid sighs deeply and lapses into a brooding silence.
         </para>

         <para number='17' comment='ming'>
         "Now there was someone who knew what he wanted!" exclaims the droid admiringly. "Did I tell you I once had him the back of my cab? Before he became emperor, of course. I remember it well - one of the mark IV assault robots he was using for security ate the cab fenders. But I have to say he was well spoken and paid for the damage - a real gent!"
         </para>

         <para number='18' comment='bribe command [start]'>
         Your proffered slithy tove certificate is accepted by the droid and rapidly vanishes from sight. "Wait here," says the droid. "I'll fix it while everyone is on their break." The droid oozes round the door and vanishes from sight for a few minutes.
         </para>

         <para number='19' comment='bribe command [finish]'>
         After what seems like a long time, but is, in reality, only a few minutes, the droid reappears. "Done," it tells you. "I knocked five deaths off your record. A-pleasure-to-do-business-wiv-a-toff-like-you." With that it ambles over to the group taking their break, and joins in the conversation.
         </para>

         <para number='20' comment='bribe [no slithy]'>
         "Sorry guv. The union would have me disassembled if it found out I'd fixed a record wivout bein' paid the going rate -- one slithy to shave five deaths off the record."
         </para>

         <para number='21' comment='try to enter loc 206'>
         You move towards the open door. "Oi! Waddja-think-you're-doin', guv". The zork857 droid bars your way with an extensor, "This is the private property of Hermes Insurance. Employees only!"
         </para>

      </section>

   </category>

   <category name='shuttle'>

      <section name='cargon'>

         <para number='1' comment='Arrival - on platform'>
         A canned voice announces, "The shuttle now arriving is for the Cargon Loop Line, calling at Nisrik, Harrington, Scargill and Hobbs End. Please allow disembarking passengers to get out before attempting to get in."
         </para>

         <para number='2' comment='Arrival - in shuttle'>
         An illuminated sign flickers into existence. "We are now arriving at Cargon City. Please make sure you have all your belongings with you." The doors slide open revealing the platform at Cargon City.
         </para>

      </section>

      <section name='general'>

         <para number='1' comment='departing general'>
         A sugar-coated female voice announces, "Please mind the closing doors, the shuttle is about to depart."
         </para>

         <para number='2' comment='departing - in shuttle'>
         The doors close and there is a slight feeling of pressure as the shuttle accelerates out of the station.
         </para>

         <para number='3' comment='departing - on platform'>
         The doors close, and with a --whoosh-- of displaced air the shuttle slides into the tunnel and disappears from sight.
         </para>

         <para number='4' comment='arrival description'>
         You can feel the overpressure as the shuttle rapidly decelerates into the station. As it halts the doors slide open and passengers rush out, elbowing those waiting to get in.
         </para>

      </section>

      <section name='harrington'>

         <para number='1' comment='Arrival - on platform'>
         A canned voice announces, "The shuttle now arriving is for the Cargon Loop Line, calling at Scargill, Hobbs End, Cargon City, and Nisrik. Please allow disembarking passengers to get out before attempting to get in."
         </para>

         <para number='2' comment='Arrival - in shuttle'>
         An illuminated sign flickers into existence. "We are now arriving at Harrington Mine. Please make sure you have all your belongings with you." The doors slide open revealing the platform at Harrington Mine.
         </para>

      </section>

      <section name='hobbsend'>

         <para number='1' comment='Arrival - on platform'>
         A canned voice announces, "The shuttle now arriving is for the Cargon Loop Line, calling at Cargon City, Nisrik, Harrington, and Scargill. Please allow disembarking passengers to get out before attempting to get in."
         </para>

         <para number='2' comment='Arrival - on shuttle'>
         An illuminated sign flickers into existence. "We are now arriving at Hobbs End Mine. Please make sure you have all your belongings with you." The doors slide open revealing the platform at Hobbs End Mine.
         </para>

      </section>

      <section name='nisrik'>

         <para number='1'>
         A canned voice announces, "The shuttle now arriving is for the Cargon Loop Line, calling at Harrington, Scargill, Hobbs End, and Cargon City. Please allow disembarking passengers to get out before attempting to get in."
         </para>

         <para number='2' comment='arrive - in shuttle'>
         An illuminated sign flickers into existence. "We are now arriving at Nisrik Mines. Please make sure you have all your belongings with you." The doors slide open revealing the platform at Nisrik Mine.
         </para>

      </section>

      <section name='scargill'>

         <para number='1' comment='Arrival - on platform'>
         A canned voice announces, "The shuttle now arriving is for the Cargon Loop Line, calling at Hobbs End, Cargon City, Nisrik, and Harrington. Please allow disembarking passengers to get out before attempting to get in."
         </para>

         <para number='2' comment='arrive -in shuttle'>
         An illuminated sign flickers into existence. "We are now arriving at Scargill Mines. Please make sure you have all your belongings with you." The doors slide open revealing the platform at Scargill Mine.
         </para>

      </section>

      <section name='wait'>

         <para number='1' comment='WAIT on shuttle stations'>
         You pull out a fresh pack of Yak 42s and remove one. Flicking the self-ignition patch you light the end and relax in the resulting aromatic haze. It doesn't make the shuttle arrive any sooner, but at least it passes the time.
         </para>

         <para number='2' comment='roomex'>
         To pass the time while waiting for the shuttle, %s has pulled out a fresh pack of Yak 42s and removed one, flicking the self-ignition patch to light the end. You get a pleasurable buzz from breathing in the resulting secondary aromatic haze.
         </para>

         <para number='3' comment='WAIT in the shuttle'>
         You pull out a fresh pack of Yak 42s and remove one. Flicking the self-ignition patch you light the end but before you can relax in the resulting aromatic haze, another passenger starts coughing and waving its tentacles fastidiously in front of its face, as if to fan away your noxious smoke. It points to the "No Smoking" sign with another appendage, so you sheepishly extinguish the offending cigarette.
         </para>

         <para number='4' comment='roomex'>
         Another passenger on the shuttle suddenly starts to cough and wave its tentacles fastidiously in front of its face. It appears to be trying to fan away the aromatic haze produced by %s's Yak 42. It points to the "No Smoking" sign with another appendage, and the offending smoker sheepishly extinguishes the cigarette.
         </para>

      </section>

   </category>

</para-list>

