<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='rome'>

      <section name='arena'>

         <para number='1' comment='arena stands and grounds'>
         The crowd boos your cowardly attempt to flee from battle.
         </para>

      </section>

      <section name='garden'>

         <para number='1' comment='shrine and garden'>
         This is a most scared place for the emperor, so please do not damage the flowers and statues by wandering of the path again.
         </para>

      </section>

      <section name='house'>

         <para number='1' comment='mansion'>
         The emperor would be most upset to learn that you tried to destroy his beautiful home.
         </para>

      </section>

      <section name='landingpad'>

         <para number='1' comment='landing pad'>
         The shuttles surrounding the landing area block travel in that direction.
         </para>

      </section>

      <section name='offices'>

         <para number='1' comment='office block'>
         The clerk appears from around the corner and curtly tells you that area is only for authorized visitors.
         </para>

      </section>

      <section name='palace'>

         <para number='1' comment='arena palace'>
         The emperor would be most upset to learn that you tried to destroy his beautiful home.
         </para>

      </section>

      <section name='towncenter'>

         <para number='1' comment='the town square'>
         A mean looking Roman soldier quickly walks up and blocks you from going in that direction.
         </para>

      </section>

   </category>

</para-list>

