<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Federal movement restriction regulation 104.234(d) states that you cannot go in that direction.
         </para>

         <para number='2'>
         The synthetic voice chimes and says, "Please do not rock the elevator, if it breaks down you will be responsible for repairing it and we doubt you have that large a bank account."
         </para>

         <para number='3'>
         You try to exit in that direction but the wall gets in your way.
         </para>

      </section>

   </category>

</para-list>

