<?xml version="1.0"?>

<para-list version='11' editor='standard'>

   <category name='objects'>

      <section name='animalballoon'>

         <para number='1' comment='Can t afford an animal balloon'>
         You don't have enough money to buy one of the animal balloons. You must be really hard up!
         </para>

         <para number='2' comment='create cat balloon - player'>
         The balloondroid carefully unties one of the cat balloons and hands it to you in exchange for your 4 groats.
         </para>

         <para number='3' comment='create cat balloon - roomex'>
         The balloondroid has just sold %s a cat balloon.
         </para>

         <para number='4' comment='create monkey balloon - player'>
         The balloondroid carefully unties one of the monkey balloons and hands it to you in exchange for your 4 groats.
         </para>

         <para number='5' comment='create monkey balloon - roomex'>
         The balloondroid has just sold %s a monkey balloon.
         </para>

         <para number='6' comment='create elephant balloon - playe'>
         The balloondroid carefully unties one of the elephant balloons and hands it to you in exchange for your 4 groats.
         </para>

         <para number='7' comment='create elephant balloon - roome'>
         The balloondroid has just sold %s an elephant balloon.
         </para>

         <para number='8' comment='create grizzle balloon - player'>
         The balloondroid carefully unties one of the grizzle balloons and hands it to you in exchange for your 4 groats.
         </para>

         <para number='9' comment='create grizzle balloon - roomex'>
         The balloondroid has just sold %s a grizzle balloon.
         </para>

         <para number='10' comment='create alien squid balloon - pl'>
         The balloondroid carefully unties one of the alien squid balloons and hands it to you in exchange for your 4 groats.
         </para>

         <para number='11' comment='create alien squid balloon - r'>
         The balloondroid has just sold %s an alien squid balloon.
         </para>

      </section>

      <section name='balloon'>

         <para number='1' comment='get balloon/round b/animal'>
         You cannot just take one of the balloons, you have to buy it!
         </para>

         <para number='2' comment='pop/burst balloon'>
         The balloon droid moves away slightly, stopping you from bursting any of its balloons. It gives you a dirty look at gestures towards the price list on its torso.
         </para>

         <para number='3' comment='buy balloon'>
         You need to specify what kind of balloon you want - a round one or an animal one?
         </para>

         <para number='4' comment='rub any created balloons - play'>
         You rub the balloon, making an irritating squeaking noise. The resulting static electricity makes your hair stand on end.
         </para>

         <para number='5' comment='roomex'>
         A sudden irritating squeaking noise assails your ears. You look around and see that %s's hair is standing on end - it must be the static electricity from rubbing a balloon.
         </para>

         <para number='6' comment='drop - player'>
         You let go of the string and the balloon floats up out of reach, then vanishes into the distance.
         </para>

         <para number='7' comment='roomex'>
         A balloon floats upwards, released by %s, then vanishes into the distance.
         </para>

         <para number='8' comment='pop/burst - player'>
         You deliberately pop the balloon. It bursts with an ear-splittingly loud BANG, leaving just a few scraps of foil and a piece of string, which you discard.
         </para>

         <para number='9' comment='roomex'>
         You hear an ear-splittingly loud BANG - %s has just burst a balloon.
         </para>

      </section>

      <section name='balloondroid'>

         <para number='1' comment='Description'>
         The small droid is festooned with balloons of all different shapes and sizes, so many that it can barely keep its metal feet from being lifted off the ground. A sign hung around its neck gives the price list:
         </para>

         <para number='2'>
         It says that simple round colored balloons cost 2 groats. Buy one with BUY ROUND BALLOON.
         </para>

         <para number='3'>
         Balloons in the shape of animals cost 4 groats. Buy one with BUY ANIMAL BALLOON.
         </para>

      </section>

      <section name='roundballoon'>

         <para number='1' comment='Can t afford a round balloon'>
         You don't have enough money to buy one of the round balloons. You are clearly in a very bad way financially!
         </para>

         <para number='2' comment='create red balloon - player'>
         The balloondroid carefully unties one of the red balloons and hands it to you in exchange for your 2 groats.
         </para>

         <para number='3' comment='create red balloon - roomex'>
         The balloondroid has just sold %s a red balloon.
         </para>

         <para number='4' comment='create blue balloon - player'>
         The balloondroid carefully unties one of the blue balloons and hands it to you in exchange for your 2 groats.
         </para>

         <para number='5' comment='create blue balloon - roomex'>
         The balloondroid has just sold %s a blue balloon.
         </para>

         <para number='6' comment='create green balloon - player'>
         The balloondroid carefully unties one of the green balloons and hands it to you in exchange for your 2 groats.
         </para>

         <para number='7' comment='create green balloon - roomex'>
         The balloondroid has just sold %s a green balloon.
         </para>

         <para number='8' comment='create yellow balloon - player'>
         The balloondroid carefully unties one of the yellow balloons and hands it to you in exchange for your 2 groats.
         </para>

         <para number='9' comment='create yellow balloon - roomex'>
         The balloondroid has just sold %s a yellow balloon.
         </para>

         <para number='10' comment='create rainbow balloon - player'>
         The balloondroid carefully unties one of the rainbow balloons and hands it to you in exchange for your 2 groats.
         </para>

         <para number='11' comment='create rainbow balloon - roomex'>
         The balloondroid has just sold %s a rainbow balloon.
         </para>

      </section>

   </category>

   <category name='planet'>

      <section name='new'>

         <para number='1'>
         Boom  Bang Crash   You look around to make sure no one saw that.
         </para>

         <para number='2'>
         The pleasent voice says" Please stay on the Pana for your safety"
         </para>

         <para number='3'>
         Does Occy know your here?
         </para>

         <para number='4'>
         It's Entertainment!
         </para>

      </section>

   </category>

</para-list>

