<?xml version="1.0"?>

<para-list version='13' editor='standard'>

   <category name='mobile'>

      <section name='minos'>

         <para number='1' comment='Response to hello'>
         Minos turns towards you and says, "Greetings mortal.  I am Minos, the Arbiter of the Damned.  It is I that review the lives of these pitiful souls that appear before me, and it is I that assign them to their appropriate place in Hell."  His tail whips about and then snaps in the air as his eyes gaze towards. you.  "Now  be off with you, there is a line, and we have to keep it moving."
         </para>

         <para number='2' comment='response to damned'>
         Minos' eyes blaze with fire, and sparks fly from the end of his beard as he looks at you and says, "The Damned?  Why they are those wretched souls who have not repented of their sins and are sent here for their eternal judgement."  Minos looks at you and says, "Why do you ask?  Have you done something that you need to repent?  I can review your life if you wish."
         </para>

         <para number='3' comment='response to inferno'>
         Minos looks upwards to the sky and bellows, "Inferno!  Even the name causes the soul to tremble.  This place was created as the final judgement of the transgressors.  No one, and nothing shall go unpunished.  So it has been decreed from Heaven itself."
         </para>

         <para number='4' comment='Response to hell'>
         Minos scowls and says, "Fool.  Hell.  Why that is this planet that you are standing on.  Inferno is Hell itself, home to the damned."
         </para>

         <para number='5' comment='response to review'>
         Minos smiles darkly and his tail whips the air.  He says, "I review the life of those that come before me.  I review their achievements, and failures.  I review their conduct and motives.  And based on how they have lived their life, I will assign them to the appropriate judgement.'  Minos peers at you intently and says, "Would you like me to review your life?"
         </para>

         <para number='6' comment='minos response to assign'>
         Minos has a wry smile as he says, "Each level of Hell has a specific punishment set forth for a particular sin.  The suffering that each soul will endure will vary with the suffering they have caused others during their mortal life."
         </para>

         <para number='7' comment='minos response to no'>
         Minos looks almost disappointed as mutters, "Very well then, but you'll be back.  They all come back."
         </para>

         <para number='8' comment='Minos response to yes'>
         Minos raises himself up and looks down on you.  He says, "Very well then," and places his heavy hand on your head and closes his eyes.  You feel a slight tingling and the memories of your entire life flash before your eyes.
         </para>

         <para number='9' comment='minos response to non match'>
         Minos looks down at you sharply and says, "What's that?  I can't hear you above the wailing of the damned.  Speak up!"
         </para>

         <para number='10' comment='message on 2nd circle'>
         Minos' tail coils around you two times, and his voice booms, "I have reviewed your life, and have found that you have been obsessed with lust.  Your fate is to be confined for eternity in the Second Circle of Hell!"  There is a flash of color, and cloud of smoke appears, and you feel the ground shift beneath your feet.  And everything goes black.
         </para>

         <para number='11' comment='minos message on 3rd circle'>
         Minos' tail wraps around you three times and he bellows, "I have reviewed your life, and you are guilty of gluttony.  To often you sat in the bars of Federation and munched on pizza.  You must now pay the price!"  There is a flash of light, a puff of smoke, and everything goes dark.
         </para>

         <para number='12' comment='minos move to 4th circle'>
         Minos' tail wraps around you four times and he bellow, "It is so clear!  You have thought selfishly of only yourself, and have never bought a round, nor given away a slithy!  Miser!  The Fourth Circle of Hell is your destiny!"  There is a flash of light, and a puff of smoke, and everything goes black.
         </para>

         <para number='13' comment='minos move to shore of styx'>
         Minos' tail wraps around you five times and he bellows, "It is clear to me!  You have been consumed by wrath.  To the River Styx is your fate!"  There is a flash of light, a puff of smoke, and everything goes dark.
         </para>

         <para number='14' comment='minos moves to 6th circle'>
         Minos' tail wraps around you six times, and he cries, "Heresy!  You dared to speak ill of Hazed!  Burn in your crypt for eternity!"  There is a brief flash of light, a puff of smoke, and everything goes dark.
         </para>

         <para number='15' comment='minos message to outer ring'>
         Minos wraps his tail around you seven times and he cries, "I see it all!  You have spent your life consumed by violence.  You have sent one too many emails to feedback asking for ship fighting!  It is the Outer Ring for you."  There is a brief flash of light, a puff of smoke, and everything goes black.
         </para>

         <para number='16' comment='minos sends to bolgia 1'>
         Minos wraps his tail around you eight times, and he cries, "Seducer!  You have misled others for too long!  It is the Malebolge for you!"  There is a brief flash of light, a puff of smoke, and everything turns black.
         </para>

         <para number='17' comment='minos sends player to caina'>
         Minos wraps his tail around you nine times and cries, "Traitor!  The Caina will be your fate!  You shall be frozen for eternity for your despicable sin!"  There is a brief flash of light, a puff of smoke, and everything goes black.
         </para>

         <para number='18' comment='Minos begins review'>
         You see a flash of light, feel a slight tingling, and it feels as though your entire life flashes before your eyes.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='keepout'>

         <para number='1' comment='Keep out of Dante s closet'>
         Dante's closet is a private area, and visitors are not allowed.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='Dante s Home'>
         Please leave Dante's home undisturbed, or you will be confined to one of the dark levels of Hell.
         </para>

         <para number='2' comment='Landing Pad'>
         The pyres crackle and hiss as you approach, and a booming voice says, "Thou Shalt Not Go This Direction."  I think that perhaps you should avoid eternal damnation and follow the marked path.
         </para>

         <para number='3' comment='Inferno Gate'>
         Your nose stikes the stone arch with a loud crunch.
         </para>

         <para number='4' comment='Shore of the River Acheron'>
         Beware, deviation from the marked trail represents a futile pursuit of the Banner of Selfish Interests.  You may be damned to spend the rest of time here if you are not careful.
         </para>

         <para number='5' comment='Caronte s Boat'>
         You struggle and nearly upset the boat, until Caronte strikes you with his oar.  Perhaps you should just get out of the boat.
         </para>

         <para number='6' comment='South Shore of Acheron'>
         The River Acheron is a foul, putrid body of filth.  Do you really want to go swimming here?
         </para>

         <para number='7' comment='Limbo'>
         You bump into Socrates who utters his famous quotation, "I drank what?" before he points you to the correct direction.
         </para>

         <para number='8' comment='Limbo Fields'>
         You wander and wander and see nothing in this direction, so you decide to turn back.
         </para>

         <para number='9' comment='Castelo Nobelo Door'>
         Your nose striking the door makes a most satisfying sound, but I don't think that you wish to spend eternity as a door knocker.
         </para>

         <para number='10' comment='Castle Entry Hall'>
         The hard stone walls feel cold to the touch as your face makes impact against the nearest wall.
         </para>

         <para number='11' comment='Exchange'>
         Your movement captures the attention of one of the demons and he brandishes his pitchfork menacingly.  After considering the fate of the hapless traders, perhaps you should decide to move carefully here.
         </para>

         <para number='12' comment='Dining Room'>
         You bump into the table and knock over several goblets of wine.
         </para>

         <para number='13' comment='Minos'>
         Minos glares at you and says, "Your frantic attempts at escape will avail you not of my judgement."
         </para>

         <para number='14' comment='Second Circle'>
         As you move about the wind tugs at you and threatens to capture you in it's swirling eddies.
         </para>

         <para number='15' comment='Third Circle'>
         You nearly fall into the pit, and Cerbero carefully watches you, deciding if perhaps you belong there.  I think you should be more careful with your movements.
         </para>

         <para number='16' comment='Fourth Circle'>
         You slip and are nearly squashed by a giant bag of coins.
         </para>

         <para number='17' comment='The River Styx'>
         The River Styx is most uninviting, and Phlegyas will not come to your aid if you fall in.
         </para>

         <para number='18' comment='Phlegyas  Skiff'>
         After seeing the fate of Filippo Argenti, you decide that it is best not to go swimming at the moment.
         </para>

         <para number='19' comment='Outside the City of Dis'>
         You turn and run smack into a horde of demons, who turn you back.
         </para>

         <para number='20' comment='sixth circle'>
         You slip and fall into an empty tomb.  Damn it's hot!  It's hotter than... Oh yeah, right... forgot where we were for a second.
         </para>

         <para number='21' comment='Minotaur'>
         You bump into the Minotaur, and he sees red.  This isn't Pamplona you know.
         </para>

         <para number='22' comment='Outer Ring'>
         I'm sure a dip in a river of boiling blood with a crowd of damned violent souls, while being shot at by Centaurs sounds rather refreshing at the moment, but perhaps you should just stay on the marked path for your own safety.
         </para>

         <para number='23' comment='Middle Ring'>
         A thorny, gnarled tree bars your path.
         </para>

         <para number='24' comment='Inner Ring'>
         The heat from the burning sand turns you back
         </para>

         <para number='25' comment='Back of Geryon'>
         The fall from this height would certainly kill you, and I don't think that this is where you want to die, much less spend eternity.  Perhaps you should hold on to Geryon until you are ready to get down.
         </para>

         <para number='26' comment='Bolgia 1'>
         Be careful, if you walk the wrong way, the demons will think you are misled, and start to beat you.
         </para>

         <para number='27' comment='Bolgia 2'>
         Oh gee... Human waste.  It's so inviting.  Are you sure you want to take a swim?
         </para>

         <para number='28' comment='Bolgia 3'>
         You slip and fall into a baptismal font.  Hurry, get out before your feet are set ablaze.
         </para>

         <para number='29' comment='Bolgia 4'>
         As you teeter on the edge of falling into the bolgia, you feel your neck begin to twist and turn.  Perhaps it would be wise to stay on the path here.
         </para>

         <para number='30' comment='Bolgia 5'>
         The Malebranche eye you carefully and debate whether or not to cast you into the pool of boiling pitch.
         </para>

         <para number='31' comment='Bolgia 6'>
         You trip over Caiaphas who lets out a bloodcurdling shriek.
         </para>

         <para number='32' comment='Bolgia 7'>
         You are set upon by snakes, and decide to turn back.
         </para>

         <para number='33' comment='Bolgia 8'>
         You burn yourself on the fire and move quickly back.
         </para>

         <para number='34' comment='Bolgia 9'>
         A sword wielding demon bars your path.
         </para>

         <para number='35' comment='Bolgia 10'>
         The smell of rotting flesh so repels you that you dry heave for a few minutes before deciding to try a different direction.
         </para>

         <para number='36' comment='Giants'>
         Anateus' large beefy hand comes down and stops you from moving in that direction.
         </para>

         <para number='37' comment='Frozen Lake'>
         You trip over a head, and fall face first on the frozen lake.
         </para>

         <para number='38' comment='Judecca'>
         You slip on the ice and fall on your arse as you try to fight the cold gusts of wind.
         </para>

         <para number='39' comment='Satan'>
         Satan's beating wings bar your path.
         </para>

         <para number='40' comment='Satan s back'>
         The gusts from Satan's beating wings prevent you from going that direction.
         </para>

         <para number='41' comment='Center of the Earth'>
         The rock walls of the cave block your path.
         </para>

      </section>

   </category>

</para-list>


