<?xml version="1.0"?>

<para-list version='10' editor='standard'>

   <category name='compass'>

      <section name='found'>

         <para number='195' comment='Exits w/compass'>
         The exit lies to the East.
         </para>

         <para number='196' comment='Exits w/compass'>
         The exit from the Hospital lies to the Southeast, and you can continue further into the hospital by going to the West.  The hospital nurse is here.
         </para>

         <para number='197' comment='Exits w/compass'>
         The exit back to the main part of the station is South.  A large man in overalls stands in front of you. A nametag identifies him as, "Al".
         </para>

         <para number='198' comment='Exits w/compass'>
         The exit back to the main part of the station is to the Southwest.
         </para>

         <para number='260' comment='Exits w/compass'>
         The heart of the station lies to the East.
         </para>

         <para number='261' comment='Exits w/compass'>
         The Docking bay is to your West, while the asteroid's Exchange lies to the Northeast.  A corridor goes to the rest of the station to the Southeast, and the Lounge lies to the Northwest.  A sign on the north doorway proudly states, "Big Al's Ship Emporium".
         </para>

         <para number='324' comment='Exits w/compass'>
         The exit back out to the hallway is South of you, while there is a back room to the East.
         </para>

         <para number='325' comment='Exits w/compass'>
         The exit back out to bar is to the West.
         </para>

         <para number='326' comment='Exits w/compass'>
         The corridor leads back to the main part of the station to the Northwest, and bends further inward to the Southwest.
         </para>

         <para number='387' comment='Exits w/compass'>
         The doorway out is to the East.
         </para>

         <para number='388' comment='Exits w/compass'>
         A corridor leads back out of this section to the East  To your North is Leucothea's Casino.  There is a jewelry shop to the West.  To the Southeast is Akumai's Multi-Polar Shop.  To the South is the entrance to Leucothea's mining operations.
         </para>

         <para number='389' comment='Exits w/compass'>
         A corridor leads off to what seems like a major concourse to the West, or back to the rest of the station to the Northeast.
         </para>

         <para number='452' comment='Exits w/compass'>
         The exit is to the North.
         </para>

         <para number='453' comment='Exits w/compass'>
         The exit is to the Northwest.
         </para>

      </section>

      <section name='notfound'>

         <para number='195' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but the exit lies in front of you - wherever that is.
         </para>

         <para number='196' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but the exit lies in front of you, and you can go further into the hospital by going behind and to your left.  The hospital nurse is here.
         </para>

         <para number='197' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but the exit lies behind you.  A large man in overalls stands in front of you. A nametag identifies him as, "Al".
         </para>

         <para number='198' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but the exit lies off to your left.
         </para>

         <para number='260' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but the doorway to the rest of the station lies ...straight ahead, whatever good that does you.
         </para>

         <para number='261' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but, you are facing a doorway that proudly states, "Big Al's Ship Emporium".  The Docking bay is to your left, while the asteroid's Exchange lies in front of you and to the left.  A corridor goes to the rest of the station behind you and to the right, and the Lounge lies in front of you and to the left.
         </para>

         <para number='324' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but the exit lies to your right, and there is a door leading to a back room behind you.
         </para>

         <para number='325' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but the exit to the bar is behind you.
         </para>

         <para number='326' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but the corridor leads back to the main part of the station to the right, and bends further inward ahead of you.
         </para>

         <para number='387' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which, but the doorway out is behind you.
         </para>

         <para number='388' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which. A corridor leads ahead, straight in front of you.  To your left is Leucothea's Casino.  There is a jewelry shop behind you.  In front of you and to the right is Akumai's Multi-Polar Shop.  To your right is the entrance to Leucothea's mining operations.
         </para>

         <para number='389' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which. A corridor leads off to what seems like a major concourse to your left, or back to the rest of the station in front of you and to the right.
         </para>

         <para number='452' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which. The exit is behind you.
         </para>

         <para number='453' comment='Exits w/ no compass'>
         Your compass spins wildly, you're not sure which way is which. You look at one of Akumai's compasses, which informs you that the exit is to the Northwest.
         </para>

      </section>

      <section name='warn'>

         <para number='1' comment='Warns player to get a compass'>
         The Welcome-Bot approaches you and says, "Greetings, %s!, I wish to inform you that Leucothea has a unique magnetic field, and most locations will cause your compass and teleportation devices to malfuction.  You may GET a compass calibrated to the unique magnetic field here, but due to budgetary constraints, you will have to return it at the end of the day.  If you wish a permanent replacement, they are available in Akumai's shop."
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message  - Leucothea'>
         Solid rock walls block you from moving that direction.
         </para>

         <para number='2' comment='No exit message  - Leucothea'>
         The foreman stops you and informs you that you're not allowed to go that way, not without a hardhat at least, and he's fresh out.
         </para>

      </section>

      <section name='rand'>

         <para number='1' comment='Given if the player is moved'>
         You suddenly lose all sense of direction and wander around aimlessly.  You finally get your bearings, and arive at
         </para>

      </section>

   </category>

   <category name='roulette'>

      <section name='russian'>

         <para number='1' comment='Player survives'>
         You look at the cylinder - one bullet is chambered.  You slap the cylinder into the gun and spin it rapidly.  Once the cylinder stops, you hold the gun to your head, and pull the trigger.    The gun clicks, and you win 100 groats! Lucky you!
         </para>

         <para number='2' comment='Player dies'>
         You look at the cylinder - one bullet is chambered.  You slap the cylinder into the gun and spin it rapidly.  Once the cylinder stops, you hold the gun to your head, and pull the trigger.    The gun fires, and you wake up in the hospital.
         </para>

      </section>

   </category>

</para-list>

