<?xml version="1.0"?>

<para-list version='10' editor='standard'>

   <category name='bedroom'>

      <section name='female'>

         <para number='1' comment='Message for Females in bed'>
         Liandri and Chandra look at you, unsurprised.  Liandri says, "Well, looks like we have another one, maybe this one will last longer..."  Liandri unleashes Chandra and they both walk over to you, and begin kissing you, ignoring your feeble protests, soon, one thing leads to another and you give in to your primal lust. After several hours, you manage to tire out both of the ravenous females and retrieve the key to the cuffs from Liandri.
         </para>

         <para number='2' comment='Message for Females in bed'>
         Liandri and Chandra look at you, unsurprised.  Liandri says, "Well, looks like we have another one, maybe this one will last longer..."  Liandri unleashes Chandra and they both walk over to you, and begin kissing you, ignoring your feeble protests, soon, one thing leads to another and you give in to your primal lust. After several hours, you are unable to continue due to sheer exhaustion.
         </para>

      </section>

      <section name='male'>

         <para number='1' comment='Message for Males in bed'>
         Liandri and Chandra look at you, unsurprised.  Liandri says, "Well, looks like we have another one, maybe this one will last longer..."  Liandri unleashes Chandra and they both walk over to you, and begin kissing you, laughing at your lustful groans. With continued encouragement, you give in to your primal lust and after several hours, you manage to tire out both of the ravenous females and retrieve the key to the cuffs from Liandri.
         </para>

         <para number='2' comment='Message for Males in bed'>
         Liandri and Chandra look at you, unsurprised.  Liandri says, "Well, looks like we have another one, maybe this one will last longer..."  Liandri unleashes Chandra and they both walk over to you, and begin kissing you, laughing at your lustful groans. With continued encouragement, you give in to your primal lust and after several hours, you are exhausted and unable to continue.
         </para>

      </section>

      <section name='neuter'>

         <para number='1' comment='Message for Neuters in bed'>
         Liandri and Chandra look at you, unsurprised.  Liandri says, "Well, looks like we have another one, pity it lacks the equipment to have any fun with."    Liandri unleashes Chandra and they both walk over to you, and begin setting apon you with the fury of a starving animal. Fortunately for you, they ended it quickly.
         </para>

      </section>

      <section name='null'>

         <para number='1' comment='Message for bed entrants'>
         Wondering what is to come, you strip down to your underwear (or equivalent) and gleefully slip on the handcuffs and lay back on the bed.    Wearing skin-tight black leather, Mistress Liandri has just arrived holding Chandra's Leash.  Looking subservient, Chandra has just arrived.
         </para>

      </section>

   </category>

   <category name='incinerator'>

      <section name='message'>

         <para number='1' comment='ID-10T message'>
         You gleefully open the door and hurl yourself face-first into the white-hot incinerator, instantly turning your every molecule into so much charcoal.    Perhaps this wasn't your best idea?
         </para>

      </section>

   </category>

   <category name='kaia'>

      <section name='club'>

         <para number='1' comment='Kaia s message to exiting Fs'>
         Kaia blocks your path out of the club and tells you that no one is allowed to leave until the 'fun' begins (whatever that means).  Perhaps there is another way out?
         </para>

         <para number='2' comment='Kaia s message to exiting Ms'>
         Kaia blocks your path out of the club and tells you that no one is allowed to leave until the 'fun' begins (whatever that means).  Kaia takes a quick look around and grabs you by the shoulders. She whispers in your ears that the 'fun' means that the members of her species will make you a midnight snack. If you want to escape this event, there is a back door in the North wall of the East room.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='clubrear'>

         <para number='1' comment='Informs player about the exit'>
         You find a loose grate on the north wall of the room and climb into it.  After a short distance, the floor drops at a sharp incline and you find yourself deposited outside the club in a featureless corridor.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='No exit message - Pharynx'>
         Unless you can phase through solid matter, you can't go that way.
         </para>

         <para number='2' comment='Dock Message'>
         A station worker informs you that that area is for station personnel only and instructs you to find a different route.
         </para>

         <para number='3' comment='Lvl 2 Hub'>
         Sorry, only station personnel are permitted on the lower level.
         </para>

         <para number='4' comment='Club message'>
         A burly bouncer grabs you before you run into a wall and points you back into the rest of the club.
         </para>

         <para number='5' comment='Club message'>
         Kaia grabs you before you run into a wall and points you back into the rest of the club.
         </para>

      </section>

   </category>

   <category name='sign'>

      <section name='dbay'>

         <para number='1' comment='Welcome/warning sign'>
         Welcome to Pharynx!  FAQ  Yes, there are death locations here, but they are much more obvious than Titan, and, per the rules of making them, there are none near any important locations (Hospital, Shipyard, Exchange). Both death locations should be impossible cause a DD, because both check that you are insured before allowing you to enter them.    That said, enjoy yourself, and have fun!  Pharynx is constantly changing, so check back!
         </para>

      </section>

      <section name='lvl3'>

         <para number='1' comment='Welcome/warning sign'>
         The sign reads:  Beings are warned to stay out of any unauthorized areas. Beings found in unauthorized areas are subject to being eaten.
         </para>

      </section>

   </category>

</para-list>

