<?xml version="1.0"?>

<para-list version='11' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for Vortex spac'>
         Sensors detect that there is nothing that direction and stop you from moving your ship into uncharted territory.
         </para>

         <para number='2' comment='No exit message for Vortex spac'>
         Moving your ship into the event horizon of a black hole is ill-advised.
         </para>

         <para number='3' comment='No exit message for Vortex spac'>
         The relay does not have a link in that direction, Captain.
         </para>

         <para number='4' comment='No exit message for Vortex spac'>
         Solid rock walls block you from moving that dirrection.
         </para>

         <para number='5' comment='No exit message for Vortex spac'>
         Rayler's thick hull prevents you from moving that dirrection.
         </para>

      </section>

   </category>

   <category name='relay'>

      <section name='sign'>

         <para number='1' comment='Lists available dirrections'>
         Northwest - Vortex System Relay       East - Pharynx Station      South - Leucothea
         </para>

      </section>

   </category>

</para-list>

