<?xml version="1.0"?>

<para-list version='8' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='noexit1'>
         You're afraid that if you drift off that way you may forever be lost in the Aegean Nebula!
         </para>

         <para number='2' comment='Atlantis LP NoExit Msg'>
         A villager grabs your hand, says something in an unknown language, and shakes his head. I guess he doesn't want you going that way!
         </para>

         <para number='3' comment='Town Center No-Exit'>
         You think to yourself that nothing can be gained by going thay way, so you think the better and stay where you're at.
         </para>

         <para number='4' comment='Cavern Entrance No-Exit'>
         The guards won't let you go that way...
         </para>

         <para number='5' comment='Drowning-NoExit'>
         You're helpless to travel in any direction but down...
         </para>

         <para number='6' comment='KelpWall-NoExit'>
         A thick wall of kelp prevents you from going that way.
         </para>

         <para number='7' comment='Generic-NoExit'>
         You cannot travel that way.
         </para>

         <para number='8' comment='Temple-NoExit'>
         The temple's structure won't let you go that way.
         </para>

         <para number='9' comment='Stadium-Closed'>
         The Stadium is closed, so you can't go that way.
         </para>

         <para number='10' comment='PalaceGuard-Noexit'>
         You're afraid that you might get tackled (or worse) by the Palace Guard if you go that way!
         </para>

         <para number='11' comment='Pirates-Noexit'>
         Iron Sam Rackham's pirates have knocked you out. All you can do is wake &lt;UP>.
         </para>

         <para number='12' comment='Rock-Noexit'>
         You feel nothing but solid rock in that direction.
         </para>

      </section>

   </category>

</para-list>


