<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No-Go'>
         You're about to go that way, then you think of the worst case scenario - accidentally opening up a door which blows up the entire station - so you decide to just stay where you are.
         </para>

         <para number='2' comment='Security'>
         The Security Droids prevent you from going in that direction - probably for your own good!
         </para>

      </section>

   </category>

</para-list>


