<?xml version="1.0"?>

<para-list version='14' editor='standard'>

   <category name='country'>

      <section name='trail'>

         <para number='1'>
         Please stay on marked path. You will damage the tender vegetation.
         </para>

         <para number='2'>
         Leaving the path is not advised. There are guards watching.
         </para>

      </section>

   </category>

   <category name='force'>

      <section name='field'>

         <para number='1' comment='bowling alley'>
         The force field stops you and pushs you back.
         </para>

      </section>

   </category>

   <category name='hedge'>

      <section name='door'>

         <para number='1'>
         The hedge is way too thick to get through here. You might check in another direction.
         </para>

      </section>

   </category>

   <category name='hospital'>

      <section name='exit'>

         <para number='1'>
         There are very sick people in there. Keep Out!
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='bowlingtowel'>

         <para number='1' comment='131-bowling towel- get towel'>
         You step over to the wall, release the fasteners, take the flag down and cram it into your back pocket.
         </para>

         <para number='2' comment='drop towel'>
         The towel hits the ground and before you can react, the Oldman comes along and says, "I'll Take that." He bends over and grabs the flag and is gone.
         </para>

         <para number='3' comment='1092-Bowling Towel- Jump ledge'>
         You wipe off your hands on the towel and throw it on the floor. The towel hits the ground and before you can react, the Oldman comes along and says, "I'll Take that." He bends over and grabs the towel and is gone. You think, 'Man, you cannot leave anything lying around here!".  Not to be held back in your quest, you step as far back as you can and run for the ledge. Jumping as high as you can you grab the lip of the ledge and swing your
         </para>

         <para number='4' comment='1092-bowling towel- no towel'>
         You try as hard as you can to get up onto the ledge but it is just to slippery to get a hand hold. If you just had something to wipe your hands on.
         </para>

      </section>

      <section name='diggingbar'>

         <para number='1' comment='324-DOWN-got Digging Bar'>
         Jamming the bar under one corner of the statue, you pry and it begins to move. Getting a new purchase on the bar and pushing hard, the statue moves out of the way and you can see into the hole. There is a ladder. There is also a very pungent smell coming from the hole. Holding your nose you climb down.
         </para>

         <para number='2' comment='694-get Digging Bar'>
         Stepping around the boxes, you grab the digging bar. It is heavier than it looked. You will have to carry it with 2 hands.
         </para>

         <para number='3' comment='drop Digging Bar'>
         The digging bar hits the ground and before you can react, the Oldman comes along and says, "I'll Take that." He bends over and grabs it and is gone.
         </para>

         <para number='4' comment='324-DOWN-no Digging Bar'>
         You try as hard as you can but the Statue will not move. If you just had something to use as a lever you could get it done.
         </para>

      </section>

      <section name='coin'>

         <para number='1' comment='Get coin - option 1'>
         You thrust your hand (or equivalent) into the cold water and rummage through the rubbish, finally seizing on a shiny little coin. It looks like it might be an ancient silver Imperial Groat! Trembling with excitement, you try to get a grip on the coin but it is stuck firmly to the floor of the conduit. You take your hand out of the cold water and thrust it into your pocket to warm up before you try again.
         </para>

         <para number='2' comment='Get coin - option 2'>
         You thrust your hand (or equivalent) into the cold water and rummage through the rubbish until you feel your fingers sinking into something squishy. You shudder at the disgusting sensation and a wave of weakness washes over you. You jerk your hand out, shaking it and rubbing it against your clothes to wipe away the slime before you try again.
         </para>

      </section>

      <section name='key'>

         <para number='1' comment='Get key - option 1'>
         You thrust your hand (or equivalent) into the cold water and rummage through the rubbish, finally seizing on an old key. It shines softly in the dim light of the sewer. You tuck the key safely into your pocket wondering what lock it might open.
         </para>

         <para number='2' comment='Get key - option 2'>
         You thrust your hand (or equivalent) into the cold water and rummage through the rubbish until you feel your fingers sinking into something squishy. You shudder at the disgusting sensation and a wave of weakness washes over you.  You jerk your hand out, shaking it and rubbing it against your clothes to wipe away the slime before you try again.
         </para>

         <para number='3' comment='Get key - option 3'>
         You thrust your hand (or equivalent) into the cold water and rummage through the rubbish, finally seizing on an old key. The key is rusty and the end is broken off; it's obviously useless and you throw it back into the water before trying again.
         </para>

         <para number='4' comment='Drop key'>
         The key hits the ground and before you can react, the Oldman comes along and says, "I've been looking for that." He bends over and grabs the key and is gone.
         </para>

         <para number='5' comment='329 - put key in lock - got key'>
         The key passes effortlessly through the force field and slides gently into the lock. You hear a faint click and whirring buzz as ancient circuits activate and when you turn the doorknob, the door swings open. The key seems to have fused to the lock so you abandon it and step into the dark room beyond.
         </para>

         <para number='6' comment='No key'>
         You search your pockets but can't find any keys to fit an ancient metal lock.
         </para>

      </section>

   </category>

   <category name='sewer'>

      <section name='pipe'>

         <para number='1'>
         Ouch, the side of the sewer pipe.
         </para>

      </section>

   </category>

   <category name='taxi'>

      <section name='exits'>

         <para number='1' comment='loc 193-194'>
         The Taxi door is locked.
         </para>

      </section>

   </category>

   <category name='tenpin'>

      <section name='landing'>

         <para number='1'>
         The People of Tenpin do not allow entry here.
         </para>

      </section>

   </category>

   <category name='town'>

      <section name='square'>

         <para number='1'>
         This door seems to be closed. Lets try going IN or maybe we should just move on.
         </para>

         <para number='2'>
         This door seems to be closed. Lets try going Out.
         </para>

      </section>

   </category>

</para-list>

