<?xml version="1.0"?>

<para-list version='8' editor='standard'>

   <category name='bandan'>

      <section name='elevator'>

         <para number='1' comment='Under Repairs'>
         As you enter the Elevator you hear a voice over the intercom, we are sorry to inform you that currently the Hawks nest is closed for renovations.  Please exit the Elevator to the North.
         </para>

      </section>

      <section name='noexit'>

         <para number='1' comment='Cliff Edge'>
         You really dont want to go that way, it is a long way down, remember you are on the top of a mountain, please stay on the road
         </para>

         <para number='2' comment='Space Port'>
         You are entering an unauthorized space, please turn around now. Violators will be prosecuted.
         </para>

         <para number='3' comment='Interior Locs'>
         Unless you have learned some new skills, I do not believe you can walk through walls.
         </para>

      </section>

      <section name='storm1'>

         <para number='1' comment='Storm Notice'>
         You hear a local announcement over the intercom, "Due to the severity of the storm over the city, travel outside of the Spaceport is forbidden until further notice."
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='cigar'>

         <para number='1' comment='Get/take cigar - loc 68'>
         As you reach for the cigar, the white-haired bandanian grabs it and moves it out of your reach. "Money up front please," he says, reminding you that the cigars cost 100 groats each.
         </para>

         <para number='2' comment='Buy cigar - pass'>
         The white-haired bandanian takes the 100 groats that you offer him, and in return gives you a fine cigar
         </para>

         <para number='3' comment='Buy cigar - fail'>
         You do not have enough groats to buy one of these expensive cigars.
         </para>

         <para number='4' comment='Shake/light cigar'>
         A flick of your hand and the end of the cigar starts to glow red as it ignites. You puff on it and can taste the deep, complex smoke as it fills your mouth and is drawn into your lungs. Don't worry, it's guaranteed non-cargenogenic!
         </para>

         <para number='5'>
         You continue puffing until the cigar is all but gone, and all you are left with is the butt (which you discard) and the memory of a truly satisfying experience.
         </para>

         <para number='6' comment='Drop cigar'>
         As the cigar hits the ground, it sparks briefly but then its safety features come into play and it goes out and disintegrates into a heap of fine dust, which disperses.
         </para>

      </section>

   </category>

</para-list>

