<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='nomove'>

      <section name='dannae'>

         <para number='1' comment='living room - loc 517- no exit'>
         A rather large guard blocks your path and says"The mistress of the house would not appreciate you going where your not invited."
         </para>

      </section>

      <section name='planet'>

         <para number='1' comment='Personal shuttle-loc 392- no ex'>
         a large planetary police tells you "we dont like law breakers around here, so please stop running into the walls"
         </para>

      </section>

      <section name='station '>

         <para number='1' comment='Spaceport-loc 200- no exit'>
         A Station Personal watchs up behind you and states"We perfer not to have the station opened into space"
         </para>

      </section>

   </category>

</para-list>

