<?xml version="1.0"?>

<para-list version='8' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message for Fishing space'>
         As you turn your ship you see an asteroid hurling towards you. Immediately you reverse your course. You realize the proximity-warning didn't work and you decide to have it checked asap.
         </para>

      </section>

   </category>

</para-list>

