<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='brick'>

         <para number='5'>
         Brick walls prevent you from going in that direction.
         </para>

      </section>

      <section name='confederate'>

         <para number='2' comment='General Lee'>
         General Lee has ordered that no one enter that area.
         </para>

      </section>

      <section name='dome'>

         <para number='7' comment='Shuttle Pad'>
         The plastic bubble of this dome will not allow movement in that direction.
         </para>

      </section>

      <section name='gravity'>

         <para number='3' comment='High Cupala'>
         Gravity might make a move in that direction an unhealthy choice.
         </para>

      </section>

      <section name='holodeck'>

         <para number='6'>
         As you bump into the soft pliable walls of the holo-deck, the projected image distorts. Realizing you cannot move in that direction, you step back and the image returns to its original form.
         </para>

      </section>

      <section name='lath'>

         <para number='4'>
         Lath and plaster prevents you from going in that direction.
         </para>

      </section>

      <section name='union'>

         <para number='1' comment='General Meade'>
         General Meade has ordered that no one enter that area.
         </para>

      </section>

   </category>

</para-list>

