<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='fanclub'>

         <para number='1' comment='2528 - fanclub member'>
         The guard notices your "Monodefuego Fan Club" button and ushers you around the corner to an expansive outdoor exchange!
         </para>

         <para number='2' comment='Not fanclub member'>
         The guard's eyes wander all over your body, either looking for something or checking you out. Or both. Whatever the reason, he's clearly unimpressed and doesn't move an inch. Glancing down at his orders, though, you see "Permit Entry to Fan Club Members only!
         </para>

      </section>

   </category>

   <category name='noexit'>

      <section name='back'>

         <para number='1' comment='noexit back areas generic'>
         If you wander off you might get hurt.
         </para>

         <para number='2' comment='noexit event horizon'>
         Seriously, messing around here and ending up falling into a virtual black hole... bad planning. Trust the voice in your head and comply with the laid out paths.
         </para>

         <para number='3' comment='noexit caves'>
         Unless you have a pick and a lot of time on your hands you can't tunnel that direction.
         </para>

         <para number='4' comment='noexit doctors room'>
         Too late, they've got you.
         </para>

         <para number='5' comment='noexit biological'>
         You try injecting yourself with stuff from that side of the room. It makes you feel funny, but not ha ha funny.
         </para>

         <para number='6' comment='noexit back room'>
         Ladies and Gentlemen, of the GED class of 1999, there is no exit in the champagne room. None. Unless you count up or out. Then yes, there are exits.
         </para>

         <para number='7' comment='noexit stairs'>
         Look, you're in a dark staircase, your choices for direction are limited.
         </para>

      </section>

      <section name='city'>

         <para number='1' comment='noexit lp'>
         Even though you try your best to crawl over the rock walls, you just can't scramble over. You do hear some voices talking about buttons from Narcissus, though.
         </para>

         <para number='2' comment='noexit city generic'>
         You're already confused as to how such a tiny link is holding so much stuff, it'd probably be better if you didn't try expanding it further by going in non-existant directions.
         </para>

         <para number='3' comment='noexit secure area 2399'>
         Doing that might get you pummeled. Is that what you want?
         </para>

         <para number='4' comment='noexit saloon'>
         You can't go that way... but there is a shady figure watching you bump into walls who beckons you IN to the back room...
         </para>

         <para number='5' comment='noexit city firemonkey lab'>
         You play with some stuff on that end of the room. It is entertaining, but your eyes continue to wander to the latch on the compression chamber, desperate to see what lies in it.
         </para>

      </section>

      <section name='secret'>

         <para number='1' comment='noexit compression chamber'>
         You set some stuff over there on fire. Yay!
         </para>

         <para number='2' comment='noexit secret room'>
         You strut about the area with a sense of pride and accomplishment, having found a secret room. You are, however, disappointed by the lack of stuff here.
         </para>

         <para number='3' comment='noexit biobar'>
         You walk to the windows and peer out, watching the beautiful space dance of ships flying through the interstellar link against a background of stars and the thin, virtually imperceptable beam of green light that penetrates each one from the nearby device.
         </para>

         <para number='4' comment='noexit really secret'>
         You flip through some pages of the cosmic conquest book, look out the windows at the stars, watch minions toil on the monitors, and generally enjoy yourself. But you don't leave, because there's no exit in that direction.
         </para>

         <para number='5' comment='noexit memories'>
         Lots of memories over that way, but no exit.
         </para>

         <para number='6' comment='noexit throne'>
         You watch the stars roll past as the link spins, smiling faintly as you see ships being unknowingly experimented on by this biological facility and you think to yourself... What a wonderful Link.
         </para>

         <para number='7' comment='noexit hospital extras'>
         I promise you, if you wander around the hospital they will perform more experiments on you. I also promise you that you don't want that.
         </para>

      </section>

      <section name='work'>

         <para number='1' comment='noexit work generic'>
         There's no work that way. That's what you're here for, isn't it? To work?
         </para>

         <para number='2' comment='noexit work genetics'>
         It seems your new powers do not enable you to walk through walls. Your nose hurts as you bump into the wall. Apparently nasal immunity is not included amongst your abilities either. Bummer.
         </para>

         <para number='3' comment='noexit foreman'>
         The foreman's enormous, hanging brown sits like a motionless cliff above his eyebrows as you walk directly into a wall.
         </para>

         <para number='4' comment='noexit weapons'>
         No guns for you.
         </para>

         <para number='5' comment='noexit plotting'>
         Why were you going that direction? You can't remember.
         </para>

         <para number='6' comment='noexit money'>
         Go... Make... Me... MONEY.
         </para>

      </section>

   </category>

</para-list>

