<?xml version="1.0"?>

<para-list version='12' editor='standard'>

   <category name='fanclub'>

      <section name='member'>

         <para number='1' comment='1889 - Give fanclub button'>
         A friendly human dressed as a firemonkey attaches a "Monodefuego Fan Club" button to your nano-chamelon suit. It must have some weird electronic property because no matter how many times you try to change and get it off, it's still there!
         </para>

         <para number='2' comment='Already got one'>
         A friendly human dressed as a firemonkey notices the button attached to your nano-chameleon suit and says, "What, didn't you get your orders? You're supposed to be hauling stuff to and from the Interstellar Link. The guard will let you through."
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='vip'>

         <para number='1' comment='Player turned back'>
         A polite but firm white-coated guide checks your credentials, and decides you are not important enough to be allowed into the VIP area.
         </para>

         <para number='2' comment='Player allowed in'>
         A polite guard in a white coat checks your credentials, and seeing that you are indeed a Very Important Person, he ushers you through the door.
         </para>

      </section>

   </category>

   <category name='noexit'>

      <section name='asylum'>

         <para number='1' comment='Generic Asylum Noexit'>
         All of the doors on that side of the room are locked. This is probably a good thing, considering the noises you hear coming from behind them.
         </para>

         <para number='2' comment='Special Noexit 1502'>
         The whitecoat has a very firm grip on you, and gently but insistently muscles you eastward.
         </para>

         <para number='3' comment='Observation Noexit 1630'>
         The large, staring eyes track your progress as you march across the room and straight into a wall. While they are distracted, one of the other inmates in the room dashes out the door to the east. Hey, that's a good idea!
         </para>

         <para number='4' comment='Padded Noexit 1694'>
         You run at the wall and crash into it. Suddenly it all makes sense as to why asylums have padded walls, it's for nutjobs like you!
         </para>

         <para number='5' comment='Infirmary Noexit 1758'>
         The whitecoats don't want you poking around the Infirmary. That's why you're being escorted east.
         </para>

         <para number='6' comment='Gates Noexit 1823'>
         These gates are enormous and very well protected. They resist all your efforts to go around, over, under or through.
         </para>

         <para number='7' comment='Operating Noexit 1634'>
         Sure, you're in the Asylum, but what are you, crazy?! Get outta there!
         </para>

         <para number='8' comment='Reception noexit 1446'>
         A whitecoat frowns and bars you from going in that direction.
         </para>

         <para number='9' comment='Throne noexit 1766'>
         Looking out the window in that direction you see thousands of people scurrying about. Using that spybeam will give you an insight into each of their little, little lives and gives you a sense of power over them.
         </para>

         <para number='10' comment='PO Lounge 1833'>
         Running around a nice restaurant like this is rude. A person of your means should know that.
         </para>

         <para number='11' comment='Monos Happy Place 1770 noexit'>
         Pull out the book "Walther's Law and Gospel" to get OUT.
         </para>

         <para number='12' comment='PO area Generic'>
         You're rich, not omnipresent. You still have to use conventional doorways and passages, one of which is not in the direction you just selected.
         </para>

         <para number='13' comment='Strange Shop 1316'>
         As you walk in that direction strange, angry faces appear on the walls and tables, watching you. They fade as you back away. Maybe if you're looking to leave the door to the east would be a promising option.
         </para>

         <para number='14' comment='Very Sticky Place 1706'>
         Just get out of the doggone pod and quit trying to be cute.
         </para>

         <para number='15' comment='Deep pit 1506'>
         Dude, there is a DOOR right there to your west. What more do you want, a map?
         </para>

         <para number='16' comment='Cold Storage 1824'>
         You peruse the body parts and organs in that part of the room, quickly checking yourself to make sure you don't need any of them. If you do, they're available for purchase. If you don't, head north.
         </para>

      </section>

      <section name='narcissus'>

         <para number='1' comment='generic noexit message'>
         Distracted by your environs you crash straight into a wall. Stepping back from it you notice a poster reading, "If you love Monodefuego, bash your head here!" What an odd coincidence... OR IS IT?
         </para>

         <para number='2' comment='reeducation center generic'>
         Sorry, there's no education to be had in that direction apart from a lesson in what it feels like to walk into a wall.
         </para>

         <para number='3' comment='Headquarters Generic'>
         Aren't there enough hallways to walk down already without you trying to punch out new ones?
         </para>

         <para number='4' comment='hypnotized noexit 2019'>
         You're floooooooating. Everybody flooooooats here.
         </para>

         <para number='5' comment='fanclub noexit'>
         All sorts of cool Monodefuego related paraphernalia is that direction, but no exit.
         </para>

         <para number='6' comment='detention center 2332'>
         I told you. No way out.
         </para>

         <para number='7' comment='political prisoners 2396'>
         You pat the head of a fat, balding man who believes himself to be a chick. Cute.
         </para>

         <para number='8' comment='non human rooms'>
         You draw a few glances from the various frightening creatures about the room, but other than that the only impression you make is with your head on the wall.
         </para>

         <para number='9' comment='thought reform 1951'>
         If you had independent will left over right now, you could do that. But you don't. So you can't.
         </para>

         <para number='10' comment='brutal subjugation 2015'>
         Do... as... you're... told.
         </para>

         <para number='11' comment='comfy room 2079'>
         You are only met by jeers and laughs in that direction. Go east to escape.
         </para>

         <para number='12' comment='merchandise areas generic'>
         There are all sorts of wonderful Monodefuego-related goodies to purchase on that wall!
         </para>

         <para number='13' comment='escaping a cell'>
         There's not enough room to maneuver down here. You'll just bonk your head if you try a bunch of creative stuff.
         </para>

         <para number='14' comment='credits 2975'>
         Alright, here's something extra: the other secret rooms on my planets are...  Monodefuego's Narcissus Throne Room  Monodefuego's Happy Place  and Monodefuego's Sanitaria Throne Room.  There are 76 rooms on Sanitaria and 49 on Narcissus.  Good Luck finding them all!
         </para>

         <para number='15' comment='throne room 2708'>
         You give some servants orders in that direction. They comply immediately. The feeling of power is intoxicating, you'd better keep it to a minimum or you'll be too drunk to leave and have to be... removed.
         </para>

         <para number='16' comment='courtroom 2268'>
         You're being dragged away. Just do what you're told.
         </para>

      </section>

      <section name='sanitaria'>

         <para number='1' comment='Sanitaria Generic'>
         People in the room look at you funny as you walk into a wall. If you keep doing that they're likely to throw you into the Asylum.
         </para>

         <para number='2' comment='Corpses noexit 1829'>
         Forget it, you're already halfway up. No escape now.
         </para>

         <para number='3' comment='Fountain noexit 1830'>
         Too late, you're already being hauled out of the fountain.
         </para>

         <para number='4' comment='Belfry Noexit 1702'>
         Going out that way would just mean a continued plunge to your death. If you're looking to go down, try using the rope. If you're looking to die, try the suicide command.
         </para>

         <para number='5' comment='Heap of Boxes noexit'>
         There's too many boxes that way. I promise you there's nothing cute about this room, just slide on down east.
         </para>

         <para number='6' comment='Back Alley noexit'>
         You browse through a third year med student's wares. He has some interesting potential selections, but he won't let you exit through his table. You'll need to head south to leave.
         </para>

         <para number='7' comment='Fines and Royalties noexit'>
         You get in that line and stand for hours. It doesn't move an inch and the noise/reek of this place is getting to you. If you want to skip out on your civil duty, you can always sneak to the north.
         </para>

         <para number='8' comment='Qrygg s Desk 1765 noexit'>
         Uhm... You're falling. Unless you learn very quickly how to fall in a particular direction, the only way you're heading is down, my friend.
         </para>

         <para number='9' comment='Grave 1703 noexit'>
         You dig frantically in that direction. It does you no good, of course, because open air is only above you, out of the tomb.
         </para>

         <para number='10' comment='Strapped to a Chair 1831 noexit'>
         You're strapped to a chair and can't go that way.
         </para>

         <para number='11' comment='Halo Noexit'>
         Doing that will certainly result in a very messy death. Granted, you're an inmate in the Asylum so maybe death doesn't bother you so much, but it's the messiness that you can't stand! Better look for a cleaner way to do yourself in.
         </para>

         <para number='12' comment='VR Machine 1705 noexit'>
         The only interesting thing in this blackness is to the north. Get this simulation going and head that way!
         </para>

      </section>

   </category>

</para-list>

