<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Your heavy clothing pulls you downward.  You are unable to move in any other direction.
         </para>

         <para number='2'>
         The drive-in is surounded by a forcefield, preventing you from moving in that direction.
         </para>

         <para number='3'>
         It's a good thing you're already in the hospital, because your nose starts bleeding when you insist on running into the wall.  A large male nurse makes you lie down until the bleeding stops, then reminds you that there is only one way out of the room.
         </para>

         <para number='4'>
         A large forcefield surrounds the landing area.  You bounce off, triggering the sound of Trill giggling over the loudspeaker.   Other visitors stop to stare at you, but the natives seem to be used to people bouncing off the forcefield.  Perhaps you should stay in the marked areas?
         </para>

         <para number='5'>
         Just because the walls are made of bamboo doesn't mean that they don't hurt when you run into them.  Perhaps you should look more carefully where you're walking.
         </para>

         <para number='6'>
         A red-haired, green-eyed Siryne gently directs you back to the path.  "We are trying to keep the planet as untouched as possible, you understand."
         </para>

         <para number='7'>
         You fall into the water with a splash, drawing several children to stare and point at you.  A good-natured fisherman nets you out of the ocean, leaving you dripping on the dock.  "Dock's gen'r'ly there f'r a reason.  If'n y'wanna go swimmin', should be 'bout findin' a swimmin' hole."  He returns to his line, leaving you to get to your feet on your own.
         </para>

         <para number='8'>
         The rails of the ship prevent you from moving that direction, although if you're determined to take a swim, you can always walk the plank.
         </para>

         <para number='9'>
         A waiter wheels around you, managing to set his tray down without spilling it.  The host lifts a tray of desserts out of the way, breathing a sigh of relief as you pass by without incident.  Baskets of bread are moved, water goblets are shifted, and plates are lifted.  Finally, a tourist who resembles an Earth mouse gets out of its chair before you sit down, hard.  Perhaps you should just go out the door to the east?
         </para>

         <para number='10'>
         You are suddenly hustled up onstage with a large group of very drunk tourists.  Before you can get off the stage, the song "YMCA" starts playing and you are dragged through the motions of every last chorus, right until the song ends.  Only then are you able to creep off the stage and back to the tables.  Perhaps you should stick to leaving by the exit to the west.
         </para>

         <para number='11'>
         If you have sampled too heavily of the liquors in the snack bar, perhaps you should lie down for a bit until you can figure out the right directions for the exits.  This, for example, is not one of them.
         </para>

         <para number='12'>
         You add to the blood ground deep into the wood of the hold as a gash in your temple from running into the wall bleeds freely.  The exit is up and out, if your head wound hasn't addled your senses too much to think clearly.
         </para>

         <para number='13'>
         The hold reverberates with the sound of your collision.  That'll leave a nasty bruise.  You might want to try another direction.
         </para>

         <para number='14'>
         Apparently armed with a deathwish, you try to walk toward the Scylla, but she's already caught all her prey.  There's only one direction you can go right now.  Try again?
         </para>

         <para number='15'>
         Was there really some part of the three directions choice that you didn't get or are you just testing?  Really.  Three directions. This is NOT one of them.
         </para>

         <para number='16'>
         If you really don't want to go where the ship is going, just jump in the ocean.  Otherwise, you're headed south.
         </para>

         <para number='17'>
         Get IN the boat. True, the rain is making it slippery and you're probably a bit deprived from lack of food and water, but anything other than getting in the boat would be suicide at this point.
         </para>

         <para number='18'>
         If you go that way, you'll drown.  Your best bet is to keep heading northwest.
         </para>

         <para number='19'>
         Weak from exhaustion and the heat, eyes still crusty... it's no wonder you can't see which way to go.  You stumble about a bit before deciding that this isn't the best course of action.
         </para>

         <para number='20'>
         The jungle tears at you, scoring deep scrapes when you try to push through it.  The only direction you can safely move is southwest.
         </para>

         <para number='21'>
         Jagged rocks and crashing waves prevent you from moving in that direction.
         </para>

         <para number='22'>
         You don't really want to fall off this tree, do you?  It's a long way to the ground.  Perhaps you could try staying where you're supposed to stay?
         </para>

      </section>

   </category>

</para-list>


