<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Your comm unit crackles with a message from the planet, "Mythos space is a restricted area.  Please remain near the link and planetary orbit or you will be exiled from the system."
         </para>

      </section>

   </category>

</para-list>


