<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='nomove'>

      <section name='all'>

         <para number='1'>
         You need to stay on the LP or use one of the appropriate paths, or else you will fall down the volcanic rocky mountain.
         </para>

         <para number='2'>
         The volcanic rock prevents you from going anywhere but back to the LP.
         </para>

         <para number='3'>
         The dense foliage of the Kona Coffee trees prevents you from going that direction.
         </para>

         <para number='4'>
         You are blocked from going that way by several caffienated workers, I wouldn't get in thier way if I were you.
         </para>

         <para number='5'>
         Are you serious? you may want to reconsider that move.
         </para>

         <para number='6'>
         You try to sneak out of the Embassy but are blocked by several crates of Coffee and Scotch.  You turn back afraid you'll break some expensive bottles.
         </para>

         <para number='7'>
         With the mystical features of Kingdom's planet being present, you may want to stay away from the walls. You wouldn't want to burst into flames now would you?
         </para>

      </section>

   </category>

</para-list>


