<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='nomove'>

      <section name='number'>

         <para number='1' comment='Inside message'>
         As you walk into the wall you feel very stupid...then a message booms over the loud speaker, "Get the hell off my planet you freakin' moron, we dont have room for your kind here!
         </para>

         <para number='2' comment='outside'>
         As you stepp of the beaten path, you hear Joe's thunderous voice, "Get back on the freakin' path!!! Gee, you act like you own the place!"
         </para>

      </section>

   </category>

</para-list>


