<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Space'>
         Warning chirps from the nav beacons alert you to uncharted space hazards, and you turn back
         </para>

         <para number='2' comment='Bridge'>
         You bump into the guard rails, and are lucky not to fall off the bridge
         </para>

         <para number='3' comment='Bank'>
         A bank security agent coldly tells you that area is off limits, and scans you for contraband
         </para>

         <para number='4' comment='Court of Justice'>
         The bailiff politely informs you that area is off limits, and prevents you from going further
         </para>

         <para number='5' comment='Merchant Court'>
         Throngs of exicited nanfab merchants shouting about their rights block your way in that direction
         </para>

         <para number='6' comment='Antechamber'>
         The house guard kindly admonishes you not to bump into the walls, and asks if you are feeling alright
         </para>

         <para number='7' comment='Elevator'>
         You throw your body uselessly against the glass, as it does not break
         </para>

         <para number='8' comment='Weapons Shop'>
         You dangerously jostle a rack of antimatter warheads before wisely deciding not to go in that direction
         </para>

         <para number='9' comment='Security'>
         A heavily armed security agents levels a plasma rifle at you and informs you that access is not permitted to outsiders
         </para>

         <para number='10' comment='Power Plant'>
         You nearly singe yourself on one of the force fields and decide not to go in that direction
         </para>

         <para number='11' comment='Shuttle Port'>
         A shuttle nearly lands on top of you, and you decide to stick to the marked paths
         </para>

         <para number='12' comment='Spaceport'>
         You jump back as a commod laden cart nearly crushes you
         </para>

         <para number='13' comment='Factory'>
         The force fields prevent access in that direction
         </para>

         <para number='14' comment='Metalworks'>
         Security droids prevent you from moving in that direction
         </para>

      </section>

   </category>

</para-list>

