<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='Moves'>

      <section name='Standard'>

         <para number='1'>
         You bang painfully into a bulkhead and stagger back, unable to move in that direction.
         </para>

         <para number='2'>
         A sailor grabs you by the scruff of the neck (or equivalent) and cheerfully yells "Careful mate, you don't want to fall off the ship!"
         </para>

      </section>

   </category>

</para-list>

