<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Illegal Move msg on planet'>
         Well trained Chicago Riot Police prevent your unauthorized access in that direction
         </para>

         <para number='2' comment='Illegal Moves on the El'>
         One can only get a limb cut off by trying to exit while the train is in motion!
         </para>

         <para number='3' comment='Illegal Elevator Moves'>
         Really!  An elevator can ONLY move up or down!  Sheesh!
         </para>

         <para number='4' comment='Illegal Moves Observation Deck'>
         No one will be jumping on our watch citizen!  Now move along!
         </para>

      </section>

   </category>

</para-list>

