<?xml version="1.0"?>

<para-list version='17' editor='standard'>

   <category name='earth'>

      <section name='msg'>

         <para number='1'>
         What do you think you're doing?
         </para>

      </section>

   </category>

   <category name='fire'>

      <section name='msg'>

         <para number='1'>
         Do you want to burn?
         </para>

      </section>

   </category>

   <category name='normal'>

      <section name='msg'>

         <para number='1'>
         Where do you think you're going?
         </para>

      </section>

   </category>

   <category name='party'>

      <section name='cake'>

         <para number='1' comment='Get/take/eat cake'>
         A waitdroid carves you off a chunky slice of cake and hands it to you on a doilly. The layers of light and airy sponge are sandwiched together with bright red jam and creamy butter icing, the whole thing covered in sugary frosting as white as an angel's feathers. It's yummy and you scoff it all down and lick the crumbs off the doilly, before disposing of it tidily in a responsible manner.
         </para>

      </section>

      <section name='milkshake'>

         <para number='1' comment='Get/take/drink milkshake - 1'>
         The waitdroid serves you a big glass full of thick, creamy milkshake. It's strawberry, bright pink in color with small chunks of real fruit in it. You drink it down, sucking every last drop through the straw, then give the glass back to the droid.
         </para>

         <para number='2' comment='2'>
         The waitdroid serves you a big glass full of thick, creamy milkshake. It's vanilla, pure white with a tangy, aromatic richness. You drink it down, sucking every last drop through the straw, then give the glass back to the droid.
         </para>

         <para number='3' comment='3'>
         The waitdroid serves you a big glass full of thick, creamy milkshake. It's chocolate, rich dark brown theobromine goodness, that fills the mouth with its slightly bitter richness. You drink it down, sucking every last drop through the straw, then give the glass back to the droid.
         </para>

         <para number='4' comment='4'>
         The waitdroid serves you a big glass full of thick, creamy milkshake. It's black in color, with a slightly greasy, pungent taste... it's luboils, intended for droids. Don't worry, it may taste off but it won't do you any harm. You drink it down, sucking every last drop through the straw, then give the glass back to the droid.
         </para>

      </section>

   </category>

   <category name='water'>

      <section name='msg'>

         <para number='1'>
         Do you want to drown?
         </para>

      </section>

   </category>

   <category name='wind'>

      <section name='msg'>

         <para number='1'>
         Do you want to fall?
         </para>

      </section>

   </category>

</para-list>

