<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='seasons'>

      <section name='entire'>

         <para number='1'>
         There is no exit message, please do not contact the planet owner, she doesn't really care, and was tired of writing up stuff at this point and just wanted her planet done. thank you
         </para>

      </section>

   </category>

</para-list>

