<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         As you venture off course, a wormhole begins to form in front of you.  With all your might you try to escape but end up venturing into the anomaly.  When you come thru half dazed you realize you are back at the entrance to the sector.  A scientific research vessel approaches asking you not to go where you do not belong!!
         </para>

      </section>

   </category>

</para-list>

