<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         As you move in that direction one of the droids begins speaking in a loud voice, "YOU MUST EXIT UP ONLY!!"  He physically assaults you and you determine that you should not resist!
         </para>

      </section>

      <section name='noexits'>

         <para number='1'>
         As you try to move in that direction you are blown into the air and begin screaming frantically.  An automated drone notices and uses his teleporter to bring you back to safety.  Please do not venture into non-public areas.
         </para>

      </section>

   </category>

</para-list>

