<?xml version="1.0"?>

<para-list version='8' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message'>
         The hair on your arms stand on their edge as you approach the electrified fence and the decision strikes you that perhaps you shouldn't go in this direction.
         </para>

         <para number='2' comment='No exit in tree'>
         You know the saying, "Knock on wood?"  Well, I don't think that applies to connecting your face to the solid wood interior of the oak tree... unless, that's just your thing.
         </para>

      </section>

   </category>

</para-list>
