<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Drunks messages'>
         The clear glazsteel prevents you from moving in that direction. Its a good thing too because otherwise you would wind up floating out into space!
         </para>

      </section>

   </category>

</para-list>


