<?xml version="1.0"?>

<para-list version='6' editor='standard'>

   <category name='food'>

      <section name='drink'>

         <para number='1' comment='Sell drink'>
         A scantily dressed waitress brings you the house drink, a strawberry Magarita with chips and salsa.
         </para>

         <para number='2' comment='Can t afford drink'>
         You don't have enough groats to buy yourself a Margarita.
         </para>

      </section>

      <section name='tacos'>

         <para number='1' comment='Buy food'>
         A scantily dressed waitress brings you a plate of fish tacos, rice, beans, salsa and an ice cold Corona beer.
         </para>

         <para number='2' comment='Can t afford tacos'>
         You are too poor to eat a plate of tacos here.
         </para>

      </section>

   </category>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Tour message'>
         You bump into the platter of sample food on display spilling the contents all over the floor. A moment later, the image is back in place as if never disturbed.
         </para>

         <para number='2' comment='main no exit message'>
         You just tripped over a tray of Fish Tacos, beans and rice being delivered to Andrew. Don't try to go that way again.
         </para>

         <para number='3' comment='woods locations'>
         As you head that direction you realize your chances of getting lost are higher if you wander off. You decide that sticking to the path is the best decision.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='keycard'>

         <para number='1' comment='Create keycard'>
         As you enter the code into the machine, it connects to the security center to verify your credentials. After a moment it spits a keycard card out still warm from the lamination process.
         </para>

         <para number='2' comment='Not PO'>
         I'm sorry I don't understand you. Can you put that a different way?
         </para>

         <para number='3' comment='Drop keycard'>
         As you drop the card, a securitybot grabs it and destroys it to make sure it doesn't fall into the wrong hands.
         </para>

         <para number='4' comment='Use keycard to enter 659'>
         You slide your card through the magnetic slot and the security gate opens, allowing you access to the private park.
         </para>

         <para number='5' comment='No card - so no entry'>
         You do not have access to this restricted area.
         </para>

         <para number='6' comment='Use keycard to enter 1051'>
         You slide your card through the magnetic slot and the security gate opens, allowing you access to the VIP lounge.
         </para>

      </section>

   </category>

</para-list>

