<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='Chernobyl'>

   </category>

   <category name='chernobyl'>

      <section name='movement'>

         <para number='1' comment='Warning'>
         You try to leave the safety of the dome, only to be stopped by a soldier who is in a radiation suit carrying an AK-47.
         </para>

      </section>

   </category>

</para-list>


