# Makefile for the fed2 Russia system

DEST=/var/opt/fed2/maps/russia

all:$(DEST)/chernobyl.loc $(DEST)/chernobyl.msg \
$(DEST)/garden.loc $(DEST)/garden.msg \
$(DEST)/marina.loc $(DEST)/marina.msg $(DEST)/marina.xev $(DEST)/marina.xob \
$(DEST)/space.loc $(DEST)/space.msg 

include ../data.mk
