<?xml version="1.0"?>

<para-list version='20' editor='standard'>

   <category name='marina'>

      <section name='planet'>

         <para number='2' comment='Dummies 2'>
         A soldier dressed in a uniform from the Cold War era stops you and and turns you around forcefully.
         </para>

      </section>

      <section name='space'>

         <para number='1' comment='Dummies'>
         What, can't you read? You can't go that way.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='doll'>

         <para number='1' comment='Get doll'>
         Ivan frowns at you and tells you that you can't just take one of the dolls - you will have to buy one.
         </para>

         <para number='2' comment='Buy doll - already got one'>
         Ivan frowns in distress, and says, "I am sorry my friend, but the authorities have restricted the sale of the Famous Figures of Federation dolls to just one per customer. So I cannot sell you another."
         </para>

         <para number='3' comment='Not enough groats'>
         I am sorry friend," says Ivan, "but I have to feed my family, so I can't just give the dolls away. Come back when you have 100 groats for me."
         </para>

         <para number='4' comment='Sell the player a doll'>
         Ivan grins happily and says, "But of course comrade, I would be more than happy to sell you one of my beautiful dolls." He takes one down from the shelf and hands it to you. In return, you pay the 100 groats.
         </para>

      </section>

      <section name='dolldiesel'>

         <para number='1' comment='Shake Diesel doll - full'>
         You shake the doll and hear a hollow rattle as something inside it moves about. Examining the doll, you find a seam between the top and bottom halves.
         </para>

         <para number='2' comment='Shake Diesel doll - empty'>
         You shake the Diesel doll but it doesn't make any sound.
         </para>

         <para number='3' comment='Open Diesel doll - full'>
         You twist the Diesel doll and the top pops off, revealing a smaller doll inside it! You remove the other doll, which is painted with Selena of the Spaceways' face, and close the Diesel doll again.
         </para>

         <para number='4' comment='Open Diesel doll - empty'>
         You open up the Diesel doll, but there is nothing inside it, so you close it again.
         </para>

         <para number='5' comment='Drop Diesel doll'>
         You drop the Diesel doll. It lands with a thump, and the wood smashes into several pieces. The face seems to look up at you reproachfully... an efficient cleaning droid clears up the mess and vanishes again.
         </para>

      </section>

      <section name='dollfogg'>

         <para number='1' comment='Shake Fogg doll - full'>
         You shake the doll and hear a hollow rattle as something inside it moves about. Examining the doll, you find a seam between the top and bottom halves.
         </para>

         <para number='2' comment='Shake Fogg doll - empty'>
         You shake the Fogg doll but it doesn't make any sound.
         </para>

         <para number='3' comment='Open Fogg doll - full'>
         You twist the Fogg doll and the top pops off, revealing a smaller doll inside it! You remove the other doll, which is painted with the face of Ming the Merciless, and close the Fogg doll again.
         </para>

         <para number='4' comment='Open Fogg doll - empty'>
         You open up the Fogg doll, but there is nothing inside it, so you close it again.
         </para>

         <para number='5' comment='Drop Fogg doll'>
         You drop the Fogg doll. It lands with a thump, and the wood smashes into several pieces. The face seems to look up at you reproachfully... an efficient cleaning droid clears up the mess and vanishes again.
         </para>

      </section>

      <section name='dollming'>

         <para number='1' comment='Shake Ming doll'>
         You shake the Ming doll but it doesn't make any sound.
         </para>

         <para number='2' comment='Open Ming doll'>
         You cannot open the Ming doll.
         </para>

         <para number='3' comment='Drop Ming doll'>
         You drop the Ming doll. It lands with a thump, and the wood smashes into several pieces. The face seems to look up at you reproachfully... an efficient cleaning droid clears up the mess and vanishes again.
         </para>

      </section>

      <section name='dollselena'>

         <para number='1' comment='Shake Selena doll - full'>
         You shake the doll and hear a hollow rattle as something inside it moves about. Examining the doll, you find a seam between the top and bottom halves.
         </para>

         <para number='2' comment='Shake Selena doll - empty'>
         You shake the Selena doll but it doesn't make any sound.
         </para>

         <para number='3' comment='Open Selena doll - full'>
         You twist the Selena doll and the top pops off, revealing a smaller doll inside it! You remove the other doll, which is painted with Fogg's leering face, and close the Selena doll again.
         </para>

         <para number='4' comment='Open Selena doll - empty'>
         You open up the Selena doll, but there is nothing inside it, so you close it again.
         </para>

         <para number='5' comment='Drop Selena doll'>
         You drop the Selena doll. It lands with a thump, and the wood smashes into several pieces. The face seems to look up at you reproachfully... an efficient cleaning droid clears up the mess and vanishes again.
         </para>

      </section>

      <section name='ivan'>

         <para number='1' comment='Match for Ivan'>
         Hi, and welcome to Marina's Gift Shop. My name is Ivan and I run this store for Djentsch.
         </para>

         <para number='2' comment='dmz'>
         He gets a look on his face as he starts remember his days on the DMZ in Europe and says, "You know, I remember being sent to the DMZ. Right across from where 3/11 ARC was setup in OP Romeo.
         </para>

         <para number='3' comment='No match'>
         Ivan just smiles at you, and carries on arranging his dolls.
         </para>

         <para number='4' comment='Marina'>
         Ivan asks, "Are you wanting to know about the planet, or the person?
         </para>

         <para number='5' comment='marina planet'>
         Ivan clears his throat and says, "The planet Marina is named after the young lady Djentsch meet while stationed in Korea. Because he wanted to learn as much about her as he could, he looked into the history of the country she is from. All locations here are named after real places in either Russia, or Korea."
         </para>

         <para number='6' comment='marina person'>
         With a twinkle in his eye, Ivan says, "Marina is the lady whom stole Djentsch's heart when he met her in Korea. She is from the small village of Khurba, Russia. A small little place that he hopes to visit one day. Marina and Djentsch were married on 28 Aug 2006."
         </para>

         <para number='7' comment='nesting dolls'>
         Ivan says, "The first Russian nesting doll (matryoshka) was born in 1890 in the workshop "Children's Education" situated in Abramtsevo estate new Moscow. Russian wooden dolls within smaller dolls were called matryoshka. In old Russian among peasants the name Matryona or Matriosha was a very popular female name. This name was associated with the image of a mother of a big peasant family who was very healthy and had a portly figure."
         </para>

         <para number='8' comment='vodka'>
         "So you want to know about Vodka do you?", asks Ivan. "Ok, in the old times Russian people didn't have any idea of getting drunk. Before the adoption of Christianity, alcoholic beverages were put on the table to celebrate thee holidays: the birth of a child, a military victory or the funeral. In acient Russia, vodka was highly appreciated and used as miracle-working medicine. Tzar Peter brought the Strict order in alcohol drinking."
         </para>

      </section>

      <section name='olga'>

         <para number='1' comment='hi'>
         Welcome to the Mustang Club, my name is Olga. Would you like to buy me a drink?
         </para>

         <para number='2' comment='no'>
         You hear Olga mumble, "Stuck up, cheap space travelers."
         </para>

         <para number='3' comment='yes'>
         Olga smiles and says, "Thank you darling", as she moves closer to you.
         </para>

         <para number='4' comment='no match'>
         Olga stands there with a look on her face suggesting that she didn't understand what you said.
         </para>

      </section>

   </category>

</para-list>


