<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Landing Pad'>
         The Landing Pad Safety Officer blows his whistle and motions for you to stay on the assigned areas.  "It's for your own safety Sir," he says.
         </para>

         <para number='2' comment='Exchange'>
         You trip and fall into the mud pit where you are set upon by the bounteous twins of Nardgoless Six (and this is only one wrestler we are talking about here).  After squeezing you into submission, you agree to stay on the marked areas only.
         </para>

         <para number='3' comment='Warehouse'>
         You run face first into a crate and create an indelible impression of your face that will be enjoyed by millions as the crate is shipped to its final destination.
         </para>

         <para number='4' comment='Bar'>
         The noise and clatter as you bounce off the wall and land head first in the spittoon gather the glares from all the customers as well as the Bartender.  "Hey, keep that up you lush, and you're 86'd for sure,"  says the Bartender.
         </para>

         <para number='5' comment='Aekonian Embassy'>
         Your pitiful displays are being recorded and will be broadcast on Aekonia's Funniest Home Videos.
         </para>

         <para number='6' comment='Carpathian Embassy'>
         As you bang your nose against the wall, a trickle of blood appears, and slowly drops to the floor.  The coffin in the center of the room quakes, and from within you hear a muffled moan.
         </para>

         <para number='7' comment='Office Building'>
         As you run into the wall, and create a small amount of damage, a security guard appoaches you and says, "Sir, if you continue this behavior, we will be required to collect a security deposit."
         </para>

         <para number='8' comment='Garden Path'>
         The thick bamboo and the rushing river make this kind of movement impossble.  Please stay on the garden path.
         </para>

         <para number='9' comment='Zardoz office'>
         Your pitiful attempts at movement have been observed by Zardoz and have given him a great source of amusement.
         </para>

         <para number='10' comment='Zardoz House'>
         Zardoz and Jezz are happy to have you visit, but would prefer it if you did not run into the walls of their home.
         </para>

         <para number='11' comment='Bamboo Veranda'>
         You teeter precariously over railing and nearly fall into the pool.
         </para>

         <para number='12' comment='Doncorleone Office'>
         Doncorleone makes you an offer you cannot refuse... Don't run into his walls, and you won't sleep with the fishes.
         </para>

         <para number='13' comment='Alcapone Office'>
         Alcapone points the scar on his face and says, "I got this from walking into walls.  Be more careful."
         </para>

         <para number='14' comment='Hospital'>
         A hard working nurse catches you and says, "If you continue to walk into the walls, I'll have to sedate you."
         </para>

         <para number='15' comment='Ookla Office'>
         Ookla gazes at your clumsiness with a disapproving scowl.
         </para>

         <para number='16' comment='Back Hallway'>
         You barely avoid knocking over a case of fine chianti.  Please be careful, we'd hate to lose some fine hooch due to someone's clumsiness.
         </para>

         <para number='17' comment='Restaurant'>
         You bounce off the walls and into a waiter carrying a tray of fresh steaming pasta putanesca.  The tray flies up in the air, and the bowl of pasta upends and lands on your head.  Somehow, noodles do not make a very good hair style.
         </para>

         <para number='18' comment='House of Doz Main Hall'>
         There are valuable paintings and artifacts here.  Please watch your step.
         </para>

         <para number='19' comment='Doz Members Lounge'>
         Invitation to the Members' Lounge is an honor, and normally isn't offered to clumsy oafs.  Please try to be careful.
         </para>

         <para number='20' comment='Zard and Jezz doorway'>
         If you'd like to go into the house, just go IN.  Walking into the doorway will only give you a bloody nose.
         </para>

         <para number='21' comment='Road'>
         The Ainokean Department of Public Works has gone to great pains to ensure that the lines are correctly painted on the streets.  Please honor their work by staying on the well marked roadway.
         </para>

         <para number='22' comment='House of Doz outside'>
         You have come all this way to see the famed House of Doz, and all you can do is walk into something?  For shame.  If you want to go in, go IN.
         </para>

         <para number='23' comment='Grotto'>
         Although the furniture that is disguised as rocks is soft, the real rocks are quite hard.  You may say ouch now.
         </para>

      </section>

   </category>

</para-list>


