<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Shuttle Bay'>
         The staff of Altwerkz have taken great pains to keep this shuttle bay clean and clear of clutter.  Please help them by not walking into things.
         </para>

         <para number='2' comment='Hallway'>
         Your nose creates a unique pattern on the wall that a cleaning droid will no doubt have to scrub off.
         </para>

         <para number='3' comment='Reception'>
         Altwerkz maintains strict rules regarding safety and integrity of the various containment fields.  Your clumsy movements are not inspiring confidence.  Please avoid walking into the walls.
         </para>

         <para number='4' comment='Exchange'>
         Your clumsy movements may draw attention away from the mud wrestling event, which will upset the entire Dozian Exchange system, and cause Galactic Economic collapse.  For the love of God, be careful!
         </para>

         <para number='5' comment='Grav Tube'>
         The Grav Tube does not move in that direction.
         </para>

         <para number='6' comment='Strip Down'>
         Your unclothed naked body will make an interesting mark on the wall.
         </para>

         <para number='7' comment='Dressing'>
         You should put some clothes on and follow the prescribed path rather than dancing around in the nude.
         </para>

         <para number='8' comment='Shower'>
         Your insane movements cause you to slip on a bar of disinfectant soap and careen into the nearest wall.
         </para>

         <para number='9' comment='UV area'>
         This is an UV treatment room, not a tanning booth.  Please follow the marked paths.
         </para>

         <para number='10' comment='Office'>
         Mr. Face meets Mr. Wall with a resounding THUD.
         </para>

         <para number='11' comment='Chem Lab'>
         Beakers of toxic chemicals shake from the force of your nose's impact against the wall.  Probably not a good idea to risk breaking something here.
         </para>

         <para number='12' comment='Computer Room'>
         Warning - The Federation 2 Server is in this room.  If you break something, you could cause a crash.  Be careful!
         </para>

         <para number='13' comment='hallways'>
         You can't go that direction.
         </para>

         <para number='14' comment='Alt Vats'>
         Zardoz is displeased with the movements of his latest alt creation.  Please stay on the marked path or he may decide to scrap his efforts and begin anew.
         </para>

         <para number='15' comment='Physics Lab'>
         Hmmm... radioactive... fusion reactor... Do you think it is a good place to be so clumsy?
         </para>

         <para number='16' comment='Bio Lab'>
         You crash into an animal cage, and tiny claws reach out and tear at your clothing.
         </para>

         <para number='17' comment='Canteen'>
         You knock over a cheap plastic table.
         </para>

         <para number='18' comment='Security'>
         A Security Droid looks at you and debates whether he should arrest you, or just kill you here.  Perhaps you should leave by the marked path before the debate ends.
         </para>

      </section>

   </category>

</para-list>


