<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='LP'>
         The Landing Bay is a dangerous place, filled with dangling cables and strewn with debris.  You had best be careful and follow the marked exits.
         </para>

         <para number='2' comment='Observation Deck'>
         You hit your head on some scafolding and decide that the marked paths are the only safe way to venture.
         </para>

         <para number='3' comment='Life Support'>
         A technician looks up from his monitor and scolds you about the sensitive equipment in the room.  You decide that maybe you should leave via the marked exits.
         </para>

         <para number='4' comment='Canteen'>
         You trip over a discarded pizza box and fall into a cot occupied by a sleeping worker.  He looks at you and informs you that he (1) is not into that sort of thing, and (2) is too tired anyway.  Maybe you should leave.
         </para>

         <para number='5' comment='Corridor/Misc'>
         After walking face first into the wall, you decide that perhaps following the marked paths is the safest course after all.
         </para>

         <para number='6' comment='Exchange'>
         You knock over a remote terminal and a repairman scolds you for your clumsiness.  Perhaps you should leave and stick to the marked paths.  They are there for your safety.
         </para>

         <para number='7' comment='Security'>
         A Security Guard stands up and reminds you that you are violating Station Rule 10(B)4(a) which prohibits Klutzy behavior.  Perhaps you should leave using the marked pathways.
         </para>

         <para number='8' comment='Grav Tube'>
         The tight confines of the Grav Tube allow for little movement other than the marked pathways.
         </para>

         <para number='9' comment='Shuttle Bay'>
         You walk into a stacked pile of boxes that teeter dangerously and signal the need to follow the marked pathways for your safety.
         </para>

         <para number='10' comment='Zardroid Station'>
         An electrician grabs you by the arm and points at the live, and very hot, high voltage electrical contacts.  He reminds you that the marked paths are there for your safety.
         </para>

         <para number='11' comment='Zardoz Office'>
         Your comm unit signals a message from Station Security that informs you that mucking about in Zardoz's office is not a very good idea.
         </para>

         <para number='12' comment='Observation Lounge'>
         A Repair Team member admonishes you to have some respect for this area, and to follow the marked pathways which were placed for your safety.
         </para>

      </section>

   </category>

</para-list>


