<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Space Station - no exit msg'>
         A large piece of the space station has broken away and blocks your path
         </para>

         <para number='2' comment='Empty Space no exit msg'>
         Your nav computer cannot get a fix on your position relative to this uncharted area, and you decide to turn back.
         </para>

         <para number='3' comment='Deos no exit message'>
         Debris and radiation are severe in this area, and its doubtful that your shields can withstand it, so you turn back.
         </para>

         <para number='4' comment='Ainokea no exit message'>
         Ainokea Planetary Defense has informed you that they have a lock-on.  Your threat displays are lighting up like the Vegas Strip.  You decide it would be prudent to stick to the established flight path.
         </para>

         <para number='5' comment='Altwerz no exit message'>
         A bio planet is a terrible thing to crash into.  Lord knows how many microbes, diseases, and other pathogens may be released.  I think you should stick to the established flight path.
         </para>

      </section>

   </category>

</para-list>


