#!/usr/bin/python

import time
now = time.time()
utc = time.gmtime(now)
today = "%d%02d%02d" % utc[0:3]
src = "/var/opt/fed2/log/"
dest = "/backup/logs/"

import os
import sys
import shutil


if os.access(dest + "fed2.log." + today,os.F_OK):
	sys.exit()
else:
	shutil.rmtree("/backup/fed2",1);
	shutil.copytree("/var/opt/fed2","/backup/fed2");

	file_names = ["fed2.log", "err.log", "usage.log"]
	for x in file_names:
		shutil.move(src + x,dest + x + "." + today)

	shutil.copy("/var/opt/fed2/data/avatars.dat","/backup/avatars/avatars.dat." + today);
	shutil.copy("/var/opt/fed2/data/companies.dat","/backup/data/companies.dat." + today);

	shutil.rmtree("/backup/maps",1);
	shutil.copytree("/var/opt/fed2/maps","/backup/maps");
