<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         Several very large, very frightening ogres pick up up by your puny arms (or similiar appendage) and set you back onto the allowed course.  Perhaps you should refrain from meandering into unauthorized areas?  They do not looked too pleased with your last deviation.
         </para>

      </section>

   </category>

</para-list>

