<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         A fleet of large, very clunky, but very powerful ships decends upon your position.  You com squawks, "Please stay within the marked transport corridors or face imminent destruction.".  You decide to heed the warning and veer back into the marked corridor.
         </para>

      </section>

   </category>

</para-list>

