<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='noexit'>

      <section name='landing'>

         <para number='1' comment='Noexit for LP and surroundings'>
         You are absolutely certain you would get lost if you tried wandering out into the forest. However, if you truly have an adventurous spirit, you can go OUT to do some exploring.
         </para>

         <para number='2'>
         You walk and walk and walk, but it seems as though you are staying in the exact same location.
         </para>

      </section>

   </category>

</para-list>

