<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='DC - loc 330 - no exit'>
         As you manuver your spaceship into that direction two F-22 Raptors appear on either side of you.  Your comm unit crackles with a message from the F-22 on your right, "United States Air Force to unidentified flying object: This is restricted air space please turn back to your original course heading and speed we will be forced to take action. You have ten seconds." Your comm unit falls silent and you decide to turn around immediately.
         </para>

      </section>

   </category>

</para-list>

