<?xml version="1.0"?>

<para-list version='8' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Cyclide space'>
         You are not allowed to fly through the storage piles, and there's nothing else of interest in this system, so all you can do is dock your shuttle with the Thorus Station, or jump elsewhere.
         </para>

      </section>

   </category>

</para-list>

