<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Wotsamatta you'>
         Ey!  Wotsamatta You?  The way out is on da map.  Capice?
         </para>

         <para number='2' comment='Riverbed'>
         The river rocks slide and shift and you wind up back where you started.
         </para>

         <para number='3' comment='Sign'>
         You walk face first into the sign.  Perhaps now you will read it, and then you won't have these embarrassing accidents.
         </para>

         <para number='4' comment='roadway'>
         After falling into a culvert, and tripping over some thorny bushes, you decide that it would be best to stay on the road.
         </para>

         <para number='5' comment='vineyard'>
         The rows of grapes prevent you from moving this direction.
         </para>

         <para number='6' comment='wine crusher'>
         You fall face first into the Wine Crusher.  As you see the large foot of a villager bear down on your head, you decide to exit and move only in the marked directions.
         </para>

         <para number='7' comment='Winery'>
         After walking face first into a wine cask, you are threatened with no more samples.  Perhaps you should stay on the marked areas of the map.
         </para>

         <para number='8' comment='Olive Grove'>
         You trip and fall and get caught in one of the nets.  Perhaps it would be better if you stayed on the marked areas of the map.
         </para>

         <para number='9' comment='Olive Press'>
         Your foot becomes lodged in the Olive Press, and as the press begins to crush your little tootsies, you extracate yourself and decide to stay on the marked paths.
         </para>

         <para number='10' comment='Bottling Plant'>
         A bottling plant is no place for such foolishness.  Please stay on the marked paths.
         </para>

         <para number='11' comment='Luca s Office'>
         Luca Brasi fixes you with a baleful stare.  Perhaps you should leave before you incur his wrath.
         </para>

         <para number='12' comment='fountain'>
         You fall into the fountain.  As you emerge, soaked, and to the delight of the passing school children, you decide to stay on the marked paths.
         </para>

         <para number='13' comment='Exchange'>
         You trip over a trading terminal and your wild flailings inadvertently creates a crash in the demand for olives.  Perhaps you should be more careful with both your movements.
         </para>

         <para number='14' comment='City Hall'>
         A clerk balefully glances in your direction and makes a mental note.  I think that any business you wish to conduct here will now require substantial bribes.
         </para>

         <para number='15' comment='cafe'>
         You trip over a table and nearly knock over a waiter before you slide face first into a steaming platter of pasta.  Perhaps you should move along the marked areas only.
         </para>

         <para number='16' comment='avenue'>
         You bump into a passerby, and fall onto your face.  Please be more careful.
         </para>

         <para number='17' comment='plaza'>
         The yawning cliff, and it's dizzying heights, suggest a more cautious approach to movements.
         </para>

         <para number='18' comment='cathedral'>
         You trip and fall into an incense burner lighting your clothes on fire.  As you extinguish the blaze with a handy bowl of holy water, you decide to be more careful about your movements.
         </para>

         <para number='19' comment='Doncorleone s villa'>
         Doncorleone informs you that if you break anything here, he will make you an offer you cannot refuse for it's repair.  I suggest you stay on the marked paths.
         </para>

      </section>

   </category>

</para-list>


