<?xml version="1.0"?>

<para-list version='5' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Landing Pad'>
         Doesn't the presence of escaping gas from fuel lines indicate that some amount of caution should be exercised here?  Stay on the indicated paths to avoid injury.
         </para>

         <para number='2' comment='Misc Hallway etc.'>
         Mr. Face meets Mr. Wall with a resounding thud.
         </para>

         <para number='3' comment='Palermo terminal'>
         You bump into a seedy gentleman in a worn trench coat.  OMG!  He appears to be happy to see you!  I'd move quickly in some other direction right now.
         </para>

         <para number='4' comment='space port bar'>
         You bump into the postcard display, and a large man approaches you and says, "Eh,  youse going to pay for that?"  Perhaps now would be a good time to leave by the indicated exit.
         </para>

         <para number='5' comment='shipyard'>
         Hmmmm.... Shipyard.... Equipment.... Repairs.... Probably not the safest place to wander around, ya think?
         </para>

         <para number='6' comment='Roadway'>
         After falling into the gutter and wallowing in the mud, you decide to pay attention to the directions.
         </para>

         <para number='7' comment='City Gates'>
         You slam face first into a stone wall and get moss stuck up your nose.
         </para>

         <para number='8' comment='plaza'>
         You slip and fall into the fountain and wind up in a less than flattering pose with a horse.
         </para>

         <para number='9' comment='west plaza'>
         The buildings, while very old, are still just as hard.  So walking face first into them is not wise at all.
         </para>

         <para number='10' comment='don barzini office'>
         Don Barzini is not known for his humor.  Perhaps walking into walls is your idea of jocularity, but it is not working.
         </para>

         <para number='11' comment='santa jezzeria'>
         The parishioners of the Cathedral well pray that you terminal case of klutziness will be cured.
         </para>

         <para number='12' comment='market'>
         You stumble over a bushel of fruit and upend a cart of spices before falling on your face.
         </para>

         <para number='13' comment='government offices'>
         Your wild antics will require the payment of a substantial bribe to get the witnesses to forget this.
         </para>

         <para number='14' comment='genco'>
         Luca Brasi is not known for smiling, but your face first walk into a wall brings the slightest hint of a grin to his face.
         </para>

         <para number='15' comment='exchange'>
         Your wild antics draw the attention of everyone in the exchange.... Well, everyone except those watching the foreign exchange transactions, that is.
         </para>

         <para number='16' comment='exchange bar'>
         The bartender looks at you and suspects that you have had enough, and promptly cuts you off.
         </para>

         <para number='17' comment='Hotel Palermo'>
         After falling face first onto the ground, the bell staff hurriedly runs over and checks to see if you are a discarded piece of luggage.
         </para>

         <para number='18' comment='ballroom'>
         Your wild antics qualify you for first place in the Palermo Dance Contest... but unfortunately, that was held last week.  So all you get now is a bloody nose from walking into the wall.
         </para>

         <para number='19' comment='cafe'>
         You trip and fall face first into a dish of pasta.  Yummm... al dente.
         </para>

         <para number='20' comment='gave tube/hallway'>
         Mr. Face meets Mr. Wall with a resounding Thud.
         </para>

         <para number='21' comment='honeymoon'>
         I don't know what you have been told, but acting like a dork is NOT a turn on for the opposite sex.
         </para>

         <para number='22' comment='Presidential'>
         Your insane antics may cause a war or at the very least, bouts of unrestrained laughter.
         </para>

      </section>

   </category>

</para-list>


