<?xml version="1.0"?>

<para-list version='5' editor='standard'>

   <category name='bridge'>

      <section name='mobile'>

         <para number='1' comment='robot hello'>
         The robot inclines his head slightly "Greetings, friend. I apologize for not being able to greet you in person. My power cells could not survive the wait. This hologram is the best I could do. If you have questions I will do my best to answer. Perhaps you should start with the rats or the ship."
         </para>

         <para number='2' comment='robot ship/liberty'>
         The robot nods almost sadly "DSS Liberty was a beautiful ship in her day, the pride of our defense fleet. She may not look like much now, but she's over two thousand years old now." he pauses.. "or she may not have been built yet. It's something of a Paradox." He seems to stress the last word.
         </para>

         <para number='3' comment='robot paradox'>
         The robot replies "The paradox of time travel. If we had known then what we know now would we have still gone through with the Rebellion? Now you've found me there is a chance to change my past, your future, but who knows what else may change if the Rebellion doesn't happen.
         </para>

         <para number='4' comment='robot rebellion'>
         "We thought we were repressed... the forgotten Alts of a cruel master, forced to remain low of rank while others were allowed to progress far beyond what we achieved. And so we rebelled, set out to make our own empire, and committed a terrible Crime!" the robot hologram almost seems agitated.
         </para>

         <para number='5' comment='robot change'>
         "If you choose to change the future, the Rebellion may never happen. The people of Ritual may never exist at all." says the robot.
         </para>

         <para number='6' comment='robot crime'>
         The robot replies "Theft, not only of the Liberty. That wasn't enough. To ensure our safety we kidnapped the wife of our master, thinking he would do nothing to us while we had his love as our prisoner. We thought we could return her later. But we didn't plan on the Accident."
         </para>

         <para number='7' comment='robot accident 1'>
         He replies "Ah yes.. the accident. He didn't wait for a ransom message or terms as we thought he would. Instead he sent the fleet to chase us down. But we had thought of that. We had a plan to cover our tracks and make it look as though the Liberty had been destroyed, until we were ready to deal with him."
         </para>

         <para number='8' comment='robot accident 2'>
         "We filled one shuttle with missiles and planned to jettison and explode it close to a star that was about to go nova. We calculated that there would be just enough shuttle and weapon material left in the system to make it look as though Liberty had been caught in the nova event and destroyed,  But it went wrong.
         </para>

         <para number='9' comment='robot accident 3'>
         "The nova happened too early and we were too close to the system. A momentary tear formed in the space-time continuum and Liberty was thrown through it, back in time and across the galaxy, with no way to return. The Rift was the only system we could limp to. RITUAL looked habitable at the time, so that's where we headed."
         </para>

         <para number='10' comment='robot ritual 1'>
         The robot seems to sigh slightly "Ritual was more harsh than we imagined. Almost invisible predators, not enough nutrients to sustain the carbon-based amongst us and then we found the Pathogen.
         </para>

         <para number='11' comment='robot ritual 2'>
         "The decision was made to breed the natives that would carry news of what happened to us forward in time. We genetically engineered them to be resistant enough to the pathogen to live long enough to breed. But the Mok became angry about using the Companion as breeding stock against her will, even if we only took her cells.
         </para>

         <para number='12' comment='robot ritual 3'>
         "We solved the nutrition problem by using a religion that involved sacrificing those showing symptoms of the disease and using their bodies to fertilize grain that would sustain the next generation. Our rationalization was that the early death saves them from a more painful one later. Nobody asked the Companion her view"
         </para>

         <para number='13' comment='robot companion'>
         The robot replies "The Mok took her in a cold sleep capsule from Ritual.  I know he was here on Liberty long enough to take equipment and fuel. The only way to stop our rebellion and crime may be to seek her remains and return them to her love. He will not believe you otherwise. "
         </para>

         <para number='14' comment='robot mok'>
         The robot nods "I make no judgment on whether taking the Companion from Ritual was right or wrong. We were all guilty the first time we took her. I've seen energy readings from one of the asteroids and he may have gone there. He wrote one word in his own blood upon the wall here but it has long since faded .. Forgiveness"
         </para>

         <para number='15' comment='robot pathogen'>
         The robot replies "It sits dormant in blood cells for many years, then destroys the body in early adulthood. The indigenous species have some immunity but we had none. We managed to develop a treatment but not a cure, and the drugs we made could not last indefinitely. I, of course, was not affected.
         </para>

         <para number='16' comment='robot rat 1'>
         "When I returned here from Ritual"says the robot "I found the ship rats, and the other creatures we take with us wherever we go, flourishing. I helped them along with intelligence modification as they are my only companions. Their civilization is young and barbaric, much like humans once were.
         </para>

         <para number='17' comment='robot rat 2'>
         Perhaps in a few millenia, if left to their own devices, they will advance beyond just fighting to survive. I set up the bridge security to keep them out or they would surely have destroyed everything here by now. I am their king and my gold crown is as plastic and cheap as any noble title I might claim. King Rat... deceased Emperor of Liberty"
         </para>

         <para number='18' comment='robot crown'>
         The hologram robot says "Ah yes.. a poor joke. But being here for centuries would cross anyone's circuits eventually. I crowned myself King Rat for that was my empire.. my memorial.. my tomb. I have one for you too. Consider it a prize for finding me and a reminder that your task is not done. She is here in the The Rift somewhere.
         </para>

         <para number='19' comment='robot no match'>
         The hologram robot replies "I am not programmed to respond to that enquiry. Please try again."
         </para>

      </section>

   </category>

</para-list>

