<?xml version="1.0"?>

<para-list version='12' editor='standard'>

   <category name='mob'>

      <section name='comp'>

         <para number='1' comment='comp reply hello'>
         The Companion Squints at you then says sharply, "Hello?  Hello?  Don't give me Hello.  You're late! How many freaking centuries does a girl have to wait around here anyway?" She seems to calm down somewhat before she adds, " So now that you're here, I suppose you want to know WHO I am." She looks at you expectantly.
         </para>

         <para number='2' comment='comp response who'>
         "Ha! It's not so much who I am that matters, you know." she replies. "It's more of who I will be in the past and who I was in the future." The companion chuckles. "I am The Jezz.. or at least she might be me, I'm not too sure anymore. I was Jezz, wife and companion of Zardoz, First Lady of the House of Doz. But that was before and after.. now is now. If you like I will tell you what happened on RITUAL.
         </para>

         <para number='3' comment='comp response Ritual 1'>
         The Companion nods "Yes well... I don't remember much about the kidnapping. But I know I ended up far from my beloved Zardoz not only in distance but far back in time. There may be records on Liberty that can tell you more about that. Now the boys, Zodbot and Ookla and three others from Zard's staff regretted the whole rebellion thing. But they couldn't go back. So we were stuck two thousand years before our time."
         </para>

         <para number='4' comment='comp reponse ritual 2'>
         The Companion takes a deep breath "The pathogen that infects everything on Ritual also infected all of us eventually. The rebels created a race of people using my DNA and theirs in order to let Zardoz know what happened to them and me.. a sort of biological message in a test tube, if you like." She pauses.. "But they assumed the virus was affecting me the same way it was them.  It wasn't."
         </para>

         <para number='5' comment='comp resp. ritual 3'>
         "When Ookla realized, he brought me here. Used everything he could scrounge from Liberty to build Penance.  You see, the pathogen that killed others did something different to me. It extended my life far beyond what is reasonable." she snorts "Jezzian DNA.. who knew? They thought their genetic tinkering was doing the job for the people they engineered, but in truth it was having some of my genes that made them resistant."
         </para>

         <para number='6' comment='comp resp ritual 4'>
         The companion looks measuringly at you "So here's the problem. Zardoz must not know. My children on Ritual are thriving and I'm not going to have someone messing up that timeline and making them non-existent! But at the same time, I want to live my life with him and not be kidnapped and trapped in this forsaken chunk of rock for damned near two thousand years. So what's the solution, I hear you ask..."
         </para>

         <para number='7' comment='comp resp solution'>
         The companion chuckles "Good question! it's this. I..er.. Jezz. must make a clone, one with all the memories and experiences of the original. The clone must not know she's a clone. Jezz will just have to bear the knowledge of what is to come and when the rebellion happens either the original or the clone will be kidnapped. Zardoz will still have his Jezz. My children on Ritual will still exist. Now I have a task for you.
         </para>

         <para number='8' comment='comp resp task'>
         She smiles "You must take a letter to Jezz's office on Ritual. The letter will explain everything.  You must tell Nobody! I believe soon I will die and half the problem will be solved. I want to remain here in peace and not become some freak of nature to be studied and dissected. I would give anything to see Zardoz again, but I must not. Say you agree to to my terms and I will give you the letter. You will be rewarded."
         </para>

         <para number='9' comment='comp resp zardoz'>
         The companion sighs sadly and a tear trickles down her cheek, "My Zardoz.. my one true love. For two thousand years I have waited and now, should he see me, he would run screaming from me."
         </para>

         <para number='10' comment='comp resp no match'>
         The Companion frowns "Look.. I could croak any second. I don't have time to talk about trivialities! You wat me to remember everything that happened over the last two thousand years?"
         </para>

      </section>

      <section name='gord'>

         <para number='1' comment='gord response hello'>
         The huge security droid regards you for a moment "You are not authorized for entry to Gamma Rock.  Return to Alpha Rock immediately."
         </para>

         <para number='2' comment='gord response nomatch'>
         Gord says in a monotone voice, "I have no interest in conversation with you. Return to Alpha Rock immediately"
         </para>

      </section>

      <section name='joey'>

         <para number='1' comment='joey response hello'>
         Joey sets down the glass he was wiping "Bon giorno.. ana welcome to Joey's Rock Bottom.  I am Joey Brasi, da owner.  You want somet'ing? I fix it for ya" He pours a glass of red wine and sets it in front of you as if you'd ordered it. Deciding not to argue, you quickly pay for the drink.
         </para>

         <para number='2' comment='joey response wine/drink'>
         "only da best! The wine of Sicilia. My cousin, Luca, he make sure I get deliveries on time" Joey smiles affably but there is a hint of coldness in his eyes.
         </para>

         <para number='3' comment='joey response luca'>
         Joey grins broadly "Luca's da best cousin.  He's a man of few words, eh, but plenty action.  He makesa things go away for la famiglia. I makesa things go away for Universal Salvage."
         </para>

         <para number='4' comment='joey response rift'>
         Joey taps the side of his nose and leans forward "I aint seen nothin of the Rift 'cept what any mook can see through the view port, ya know whadda mean? Universal Salvage runs dis rock. I runs Rock Bottom and does a few favors for dem Salvage bosses.  Dey keeps me happy.. I donna tell Luca. I keeps dem happy.. dey lets me run da Rock Bottom without no interference."
         </para>

         <para number='5' comment='joey response liberty'>
         Joey grimmances "yeah I heard tell of some old wreck in orbit 'round Ritual.  They says dere's some sorta secret on da bridge that mean sommat here.  But wadda they know eh?  'Roid workers aint never been the smartest bunch of mooks."
         </para>

         <para number='6' comment='joey response jezz'>
         "Ah, la bella Jezzeria!" Joey's face lights up "She gets em Salvage bosses scurryin' like Liberty rats. The lady's got class. Ain't no figuring why she married that Zardoz when she coulda had me"
         </para>

         <para number='7' comment='joey response zardoz'>
         "He comes in here wantin' ta use a VE of dat pollen brain, Tracey" Joey rolls his eyes, "So I says.. why ya wanting ta virtual wiv dat bimbo when you gots the Jezz?  An' he says.. I gots me some herbicide.. so I says.. you hurts the Jezz an I gots you some suicide out da open airlock... dat mook."
         </para>

         <para number='8' comment='joey response universal/salvage'>
         Joey nods "You wanna work on Penance you gotta go to Universal Salvage." He gives you a measuring look "ok .. go over to the salvage offices an tell em Joey sent ya. I know they needs people since the accident last week" he smiles slyly as he says the word "accident".
         </para>

         <para number='9' comment='joey response accident'>
         Joey grins a toothy grin "coupla wiseguys stuck their noses in where they don't belong. Ended up stickin em out an airlock and sniffin deep space.  Accidents happen, eh?"
         </para>

         <para number='10' comment='joey response penance'>
         Joey replies "Eh.. a rock's a rock only dis place is three of em. Da Salvage guys, dey got their own game runnin' out on the other rocks. People got secrets?..  I like dat. Always work for a guy like me when peoples got secrets."
         </para>

         <para number='11' comment='joey response bye'>
         Joey calls after you "yeah yeah, get outta here.. don't forget what I told ya to say, eh."
         </para>

         <para number='12' comment='joey response nomatch'>
         Joey narrows his eyes at you "wad are ya? some kinda wiseguy?"
         </para>

      </section>

      <section name='tammy'>

         <para number='1' comment='tammy match hello'>
         Tammy smiles her brightest smile and says "Welcome to Universal Salvage. We are equal opportunity employers and the friendliest company in The Rift.  How may I help you today?"
         </para>

         <para number='2' comment='tammy match work/job'>
         Tammy looks you over carefully "In order to work for Universal Salvage you will need a local reference. Please state the name of your personal reference here on Penance". She waits with fingers poised over her keyboard for you to give her a name.
         </para>

         <para number='3' comment='tammy match joey'>
         Tammy brightens "Ah.. of course!  Well now let me see... " She taps away at her keyboard and scans the monitor "I do have a vacancy in the maintenance section." Tammy thrusts a form in your direction. "To accept the post please READ FORM."
         </para>

         <para number='4' comment='tammy match penance'>
         "Oh it's not as bad as it sounds." Tammy smiles "We have some benefits that visitors don't get to see." She leans forward and lowers her voice "You know this place was already here when we arrived.  The company just enlarged the facilities. Nobody actually knows who was here before or who joined the three asteroids that make up Penance."
         </para>

         <para number='5' comment='tammy match pay/wage'>
         Tammy pulls up your records on her computer "well now, %s, you'll have to start at a pay rate that is comensurate with your skills.  I'm afraid in your case that would be Galactic minimum wage."
         </para>

         <para number='6' comment='tammy match benefits'>
         Tammy smiles, "We have quite a few facilities here, and believe it or not, we have a lovely park in the middle of Beta Rock"
         </para>

         <para number='7' comment='tammy nomatch'>
         Tammy gets a fixed smile "I'm sorry.  Please come back when you are looking for work and have a local reference.  Have a nice day"
         </para>

      </section>

      <section name='type'>

         <para number='1' comment='keyboard response password'>
         There is a soft chime which presumably means the password you typed has been accepted.
         </para>

         <para number='2' comment='no match type password'>
         A harsh beep appears to signify that the password was incorrect.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='form'>

         <para number='1' comment='read form messages loc 398'>
         -Terms of Employment- Employment with Universal Salvage is solely at the discretion of the company.  Any injury or loss sustained by the employee during employment is the responsibility of the employee and Universal Salvage shall be held blameless in all circumstances. DO NOT reveal any information regarding Penance or Universal Salvage to ANY other person.
         </para>

         <para number='2' comment='form message 2'>
         Failure to abide by the above rules will result in termination of employment and probably termination of life as well. All items on Penance are deemed the property of Universal Salvage and may be confiscated if you leave the asteroid. Universal Salvage does not pay for holidays.  If you leave Penance you will cease to be an employee but may reapply upon your return. If you agree to these terms, SIGN FORM
         </para>

      </section>

   </category>

</para-list>


