<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='ritual'>

      <section name='station'>

         <para number='1' comment='launch pad 260 no exit'>
         Clean up and repair costs for anything you damage when you land after that brief but interesting fall will be deducted from your personal account.
         </para>

         <para number='2' comment='centerpoint'>
         A maintenance worker rushes towards you and tells you politely to keep your great big clod-hopping boots out of the flower beds!
         </para>

         <para number='3' comment='exchange'>
         An over zealous sales person notices your indecision and takes the opportunity to spray you with the latest perfume on offer... Eau de Propellant Sludge..  for the real space hauler in everyone.  Other shoppers back away from you as you try to wipe the stinging scent from your eyes.
         </para>

         <para number='4' comment='theatre'>
         Tickets!  Tickets please!  Sorry.. no admittance without a ticket.
         </para>

         <para number='5' comment='restuarant'>
         There are some rumors that the natives here are cannibals but there is really no need to throw yourself into the luau cooking fires!
         </para>

         <para number='6' comment='security'>
         The guard looks up and snarls "Don't make me find a reason to arrest you."
         </para>

         <para number='7' comment='admin recep'>
         Please refrain from leaving marks on the nice clean walls.
         </para>

         <para number='8' comment='medical'>
         Any delicate medical equipment that you manage to break while stumbling around will be deducted automatically from your personal account.
         </para>

         <para number='9' comment='office'>
         Yes the walls are indeed quite solid.
         </para>

         <para number='10' comment='fire'>
         Banging your head on the brickwork does little to dull the pain you are in.
         </para>

         <para number='11' comment='shipyard'>
         The more you look as though you don't know what you're doing, the bigger the saleman's grin becomes.
         </para>

         <para number='12' comment='tunnels'>
         Gravel rash is so attractive when added to that nice big bruise on your forehead.
         </para>

         <para number='13' comment='shelf'>
         Teetering on the edge of the shelf you notice dark shadows in the water below you.  Chances of surviving a fall here are slim to none.
         </para>

         <para number='14' comment='flitter'>
         The confines of the Flitter make that sort of activity difficult.. especially at your age!
         </para>

         <para number='15' comment='wildside'>
         The chances of running into something that considers you to be edible rise substantially if you leave the path.
         </para>

         <para number='16' comment='by the village'>
         It would be extremely unwise to venture further at this time, particularly since you aren't supposed to be here in the first place.  Perhaps the governor will find a way for people to visit the village without becoming dinner soon.
         </para>

         <para number='17' comment='cave'>
         After thourough testing you discover that the rock on this island is just as hard as the rock on the other one.
         </para>

      </section>

   </category>

</para-list>



