<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='space'>

      <section name='space'>

         <para number='1' comment='space message'>
         Straying from the narrow space lanes is likely to cause an encounter between your ship and any number of large asteroids. Remedial piloting classes are available on Ritual at a grossly inflated price.
         </para>

      </section>

   </category>

</para-list>



