<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='error message for space locs'>
         The link is in geosynchronous orbit around the planet, so there is no need for you to head out into the rest of the system.
         </para>

      </section>

   </category>

</para-list>


