<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='error message for planet moves'>
         You bump your head before you realize you can't go that way.
         </para>

         <para number='2' comment='errro planet moves'>
         You stumble and almst falls befor you realize you can't go that way.
         </para>

      </section>

   </category>

</para-list>


