<?xml version="1.0"?>

<para-list version='10' editor='standard'>

   <category name='nomove'>

      <section name='general'>

         <para number='1' comment='no move message'>
         That direction just doesn't appear to be in the cards at the moment.
         </para>

      </section>

   </category>

   <category name='reading'>

      <section name='cards'>

         <para number='1' comment='message on choosing a card'>
         You hesitantly reach towards the cards that are spread out on the table.  After a moment one card just seems to be the right one to choose. Zenia turns it over and allows you to study the picture.
         </para>

         <para number='2' comment='the fool card'>
         You have chosen The Fool. The fool strides out on his journey with his belongings in a handkerchief on a stick over his shoulder.  The sun shines brightly upon him and his little dog yaps by his ankle.  They both step over the cliff without a second thought.  He is the jester, the seeker, and has complete trust that the universe will save him from harm.
         </para>

         <para number='3' comment='the fool interp'>
         Zenia nods at your card choice. She leans forward and whispers "There is opportunity just around the corner but in order to take advantage of it you must let go of your fear of the unknown.  Trust in the Higher Power that watches over you and take a chance. The future is full of promise if you are willing to take the leap. Commit yourself to your course fully."
         </para>

         <para number='4' comment='the fool rev'>
         You have chosen The Fool but find yourself holding the card upside-down. The fool strides out on his journey with his belongings in a handkerchief on a stick over his shoulder.  The sun shines brightly upon him and his little dog yaps by his ankle.  They both step over the cliff without a second thought.  He is the jester, the seeker, and has complete trust that the universe will save him from harm.
         </para>

         <para number='5' comment='the fool rev interp'>
         Zenia nods at your card choice and whispers "Avoid reckless and careless action. Now is not the time to take rash leaps into the unknown.  You must put careful thought into the path ahead if you are to achieve success"
         </para>

         <para number='6' comment='magician'>
         You have chosen The Magician. The Magician studies the tools upon the table in front of him, the cup of emotion, the sword of intellect, the rod of action and spirit and the pentacle of the physical world. He holds aloft a wand and becomes the lightning rod between the spiritual and the practical. He links the heavens to the ground.  He is the word, the will, the wisdom.
         </para>

         <para number='7' comment='magician interp'>
         Zenia nods at your card choice and whispers "You are ready to show everyone how creative you are.  It is a time to turn thoughts into action and draw upon both your intellect and your intuition to make a new start.  You have the mental capacity and the sensitivity to make the decision that is required and conjure up those new ideas into a practical reality.  Use the talents you've been given."
         </para>

         <para number='8' comment='magician rev'>
         You have chosen the Magician but the card is upside-down. The Magician studies the tools upon the table in front of him, the cup of emotion, the sword of intellect, the rod of action and spirit and the pentacle of wealth and the physical.  He holds aloft the wand and becomes the lightning rod between the spiritual and the practical. He links the heavens to the ground.  He is the word, the will, the wisdom.
         </para>

         <para number='9' comment='magician rev interp'>
         Zenia nods at your card choice and whispers " Before success can come to you, more self awareness is required.  You must make more effort to understand the talents you have before they can serve you best. Use the delay wisely."
         </para>

         <para number='10' comment='high priestess'>
         You have chosen the High Priestess.  She sits between the black pillar of Boaz and the white pillar of Jachin with the veil of the Temple of Solomon behind her, hiding most of what lies beyond. Her crown is the waxing, full and waning moon.  The new moon is at her feet.  She holds the Tora, the secret law, upon her lap and upon her chest is a cross.
         </para>

         <para number='11' comment='high priestess interp'>
         Zenia nods and whispers "Plumb the depths of your subconscious and what you find there might be beyond the power of words. Let your intuition guide you.  You must search for the answer inside yourself and not in the outside world.  Meditate upon what lies within and success and contentment will come to you."
         </para>

         <para number='12' comment='high priestess rev'>
         You have chosen the High Priestess but the card is upside-down. She sits between the black pillar of Boaz and the white pillar of Jachin with the veil of the Temple of Solomon behind her, hiding most of what lies beyond. Her crown is the waxing, full and waning moon.  The new moon is at her feet.  She holds the Tora, the secret law, upon her lap and upon her chest is a cross.
         </para>

         <para number='13' comment='high priestess rev interp'>
         Zenia nods and whispers "You cannot see the entire picture at this time and you must wait for things to become more clear.  Though success will likely come to you later, there is a danger that your purpose will become lost as you contemplate the mysteries of life and forget practical action."
         </para>

         <para number='14' comment='empress'>
         You have chosen The Empress. The Empress sits upon a cushioned throne, a sceptre in her hand and a crown of stars upon her head. The river of life flows from the lush forest behind her and the field of corn before her is ready for harvest. She is maternal power, fruitfulness and abundance personified. The Empress has a deep understanding of the duality of creation, the joy of birth and the mourning of separation.
         </para>

         <para number='15' comment='the empress interp'>
         Zenia nods and whispers "The time is ripe for your creative powers to bear fruit. Through practical application you can realize your creative potential.  You may gain even more than you imagined.  There may be emotional fulfillment in a happy and secure realtionship."
         </para>

         <para number='16' comment='empress rev'>
         You have chosen The Empress but the card is upside-down. The Empress sits upon a cushioned throne, a sceptre in her hand and a crown of stars upon her head. The river of life flows from the lush forest behind her and the field of corn before her is ready for harvest. She is maternal power, fruitfulness and abundance personified. The Empress is secure in her femininity and has a deep understanding of the duality of creation.
         </para>

         <para number='17' comment='empress rev interp'>
         Zenia nods at your card choice and whispers "Success may be delayed.  Be sure to allow others to realize their own potential and give them room to grow. Beware of laziness, excess and waste."
         </para>

         <para number='18' comment='emperor'>
         You have chosen The Emperor, a dignified figure on a throne of stone.  The sceptre and orb he holds are symbols of his authority.  He is dynamic and extrovert with the ability to take control.  He is rational and serious, ambitious and powerful. His throne is surrounded by desert and the river of life has slowed to a trickle behind him.  He organizes his thoughts in a solid, concrete way and has little time for fanciful pursuits.
         </para>

         <para number='19' comment='emperor interp'>
         Zenia nods and whispers "You must use your intellect and reasoning powers to organize the situation. Through hard work and having the courage of your convictions you can attain your goals.  You must be in control of the course of your life. The Emperor may also signify an authority figure in your life.  He is a hard taskmaster."
         </para>

         <para number='20' comment='emperor rev'>
         You have chosen the Emperor but the card is upside-down. The Emperor is a dignified figure on a throne of stone.  The sceptre and orb he holds are symbols of his authority.  He is dynamic and extrovert with the ability to take control.  He is rational and serious, ambitious and powerful. His throne is surrounded by desert and the river of life has slowed to a trickle behind him.
         </para>

         <para number='21' comment='emperor rev interp'>
         Zenia nods and whispers "Whether this card represents you or someone else is for you to decide. The Emperor reversed is egocentric and childish with a need to dominate others.  His obsession with power and stature is unhealthy. Success could well be delayed as the competition he brings is ruthless."
         </para>

         <para number='22' comment='hierophant'>
         The Heirophant sits between the pillars of Severity and Mercy, handing down time honored tradition and established teachings to his students. He recommends hard work and study in all spiritual matters.  He offers guidance and holds the keys to understanding of the spiritual being.  His message is one of greater peace of mind through conformity.
         </para>

         <para number='23' comment='hierophant interp'>
         Zenia nods and whispers "If you act selfishly you may gain stature but there will be little actual reward.  What you do now should benefit others.  It is time to be in contact with your spiritual self.  You might embark on a course of study that will benefit you in ways other than the material. Remember that there is value in traditional ways"
         </para>

         <para number='24' comment='hirophant rev'>
         You have chosen the Hierophant but the card is upside-down. The Heirophant sits between the pillars of Severity and Mercy, handing down time honored tradition and established teachings to his students. He recommends hard work and study in all spiritual matters.  He offers guidance and holds the keys to understanding of the spiritual being.  His message is one of greater peace of mind through conformity.
         </para>

         <para number='25' comment='hierophant rev interp'>
         Zenia nods and whispers " Success will be delayed and you must have the courage of your convictions to see the project through to the end. Do not become so enmired in tradition that you forget the value of innovative thinking."
         </para>

         <para number='26' comment='lovers'>
         You have chosen The Lovers. In the bright light of the sun, a winged angel watches over a man and a woman.  They are naked before the angel.  Behind the man is a fiery tree of passion and behind the woman is the tree of life where the serpent waits to whisper his message. The man looks towards the woman while she in turn looks to the angel, perhaps for guidance.
         </para>

         <para number='27' comment='lovers interp'>
         Zenia nods and whispers "This is a card of choices.  This decision will have a lasting impact. Such decisions are not always about love but may be about the choice between emotion and intellect, heart and mind. Learn to accept yourself for who you are and accept others for who they are and you will make the right choice and find contentment. You must be honest with yourself now because in any choice something will be left behind."
         </para>

         <para number='28' comment='lovers rev'>
         You have chosen The Lovers but the card is upside-down. In the bright light of the sun, a winged angel watches over a man and a woman.  They are naked before the angel.  You see the scene Upside-down. Behind the man is a fiery tree of passion and behind the woman is the tree of life where the serpent waits to whisper his message. The man looks towards the woman while she in turn looks to the angel, perhaps for guidance.
         </para>

         <para number='29' comment='lovers rev interp'>
         Zenia nods and whispers "You may be indecisive now. Quarrels are indicated and someone may be interfering with your ability to make a choice.  You must choose your path very carefully now.  Are you really sure it is what you want?"
         </para>

         <para number='30' comment='chariot'>
         You have chosen The Chariot. A chariot drawn by two sphinxes, one black and one white, charges past driven by a conquering hero.  He has struggled against the odds and through his sustained effort he has won wealth and prosperity. The sphinxes seem to pull in opposite directions, spiritual and intellectual, but the hero drives the middle ground.  He uses the conflict to drive a creative force.
         </para>

         <para number='31' comment='chariot interp'>
         Zenia nods and whispers "You have the energy to overcome the obstacles and suceed.  To the victor go the spoils.  Remember that you must balance your needs and provide a place for both the intellectual and spiritual sides of you."
         </para>

         <para number='32' comment='chariot reversed'>
         You have chosen the Chariot but the card is upside-down. A chariot drawn by two sphinxes, one black and one white, charges past driven by a a conquering hero.  He has struggled against the odds and through his sustained effort he has won wealth and prosperity. The sphinxes seem to pull in opposite directions, spiritual and intellectual, but the hero drives the middle ground.  He uses the conflict to drive a creative force.
         </para>

         <para number='33' comment='chariot rev interp'>
         Zenia nods and whispers "Control your passion and ambition or you may ruin your plans.  If you charge ahead thoughtlessly you may hurt others in the process."
         </para>

         <para number='34' comment='justice'>
         You have chosen Justice who sits upon her throne holding the scale in one hand and a sword in the other. Justice is not blind, but actively seeks truth.  While her face is grave, her demeanor is majestic. She sits between twin pillars, weighing good and evil carefully.  She represents the law and the ability to condemn or save. She warns not to judge on appearance, for the true measure of a person often lies much deeper.
         </para>

         <para number='35' comment='justice interp'>
         Zenia nods and whispers "You may be given good advice by a powerful or educated person. Consider the advice and think carefully before acting. You may be involved in a legal matter.  Even if you do not like the outcome, it will be just."
         </para>

         <para number='36' comment='justice rev'>
         You have chosen Justice, but upside down. She sits upon her throne holding the scale in one hand and a sword in the other. Justice is not blind, but actively seeks truth.  Her face is grave, her demeanor is majestic. She sits between twin pillars, weighing good and evil carefully.  She represents the law and the ability to condemn or save. She warns not to judge on appearance, for the true measure of a person often lies much deeper.
         </para>

         <para number='37' comment='justice rev interp'>
         Zenia nods and whispers "You may have a hard time adjusting to changes. Beware of indecision, judging too harshly and bigotry.  Mercy may be the tool through which you may yet achieve success."
         </para>

         <para number='38' comment='hermit'>
         You have chosen the Hermit. He travels slowly but steadfast on his course.  From his lantern shines the light of divine spirit and self knowledge.  He lets nothing deflect him from his purpose but knows that wisdom comes from patience, time and the search for inner truth. He offers wise council as he crosses your path, advising against excesses, reminding you that through truly knowing yourself you may yet learn to understand others.
         </para>

         <para number='39' comment='hermit interp'>
         Zenia nods and whispers "Life puts you to the test but you come through.  There is an opportunity for you learn about parts of your psyche that were previously hidden.  Through leaving something behind you become aware that you are self-sufficient."
         </para>

         <para number='40' comment='hermit rev'>
         You have chosen the Hermit but the card is upside-down. He travels slow but steadfast on his course.  From his lantern shines the light of divine spirit and self knowledge.  He lets nothing deflect him from his purpose but knows that wisdom comes from patience, time and the search for inner truth. He reminds you that through truly knowing yourself you may yet learn to understand others.
         </para>

         <para number='41' comment='hermit rev interp'>
         Zenia nods and whispers "Do not close your mind to other possibilities.  If you become too much of a perfectionist or too cautious you can stall any forward movement.  However you should plan your next move carefully."
         </para>

         <para number='42' comment='wheel fortune'>
         You have chosen the Wheel of Fortune. Winged creatures on clouds surround the great wheel as it spins in the sky. Osiris, the god of death and resurrection, sits atop the wheel as a serpent is crushed beneath it. Anubis rises signaling the triumph of good over evil. The wheel turns just as our fortunes rise and fall upon it's rim. Our lives may not be predetermined by fate, and yet we do not have total control.
         </para>

         <para number='43' comment='wheel fortune interp'>
         Zenia nods and whispers "All things are transient. Yet we do have control over how we face the challenges presented to us. The wheel does not absolve us of our responsibility, no matter what fate brings to us. The turning wheel brings new opportunities and change. It is the end of one cycle and the beginning of another which brings good fortune with it."
         </para>

         <para number='44' comment='wheel forune rev'>
         You have chosen the Wheel of Fortune. It is upside-down. Winged creatures on clouds surround the great wheel as it spins in the sky. Osiris, the god of death and resurrection, sits atop the wheel as a serpent is crushed beneath it. Anubis rises signaling the triumph of good over evil. The wheel turns just as our fortunes rise and fall upon it's rim. Our lives may not be predetermined by fate, and yet we do not have total control.
         </para>

         <para number='45' comment='wheel rev interp'>
         Zenia nods and whispers "All things are transient. Yet we do have control over how we face the challenges presented to us. The wheel does not absolve us of our responsibility, no matter what fate brings to us. Fate throws something unexpected your way. You will have to change your plans to accommodate the new circumstances."
         </para>

         <para number='46' comment='strength'>
         You have chosen Strength. In the midst of a meadow, a beautiful girl with long flowing hair sits astride a fearsome lion. It is by strength of will and mastery of her own emotions that the girl controls the lion.  With her bare hands she closes the lion's mouth. With a white robe and red roses in her hair, she tells you that passion and spirit must work together to tame the savage beast.
         </para>

         <para number='47' comment='stength interp'>
         Zenia nods and whispers "You are fortunate to choose strength as she influences everything around her with a positive energy. A wonderful opportunity to change approaches. There is triumph ahead if you use positive thoughts and energy to combat the more negative aspects of life."
         </para>

         <para number='48' comment='hanged man'>
         You have chosen The Hanged Man, who is suspended by one ankle from a beam the balances on a tree-trunk. Surprisingly, his face appears serene and his body relaxed with his hands behind his back. A bright halo around his head shows that his trust lies in something other than the physical world and that being in this position where he has no control may have been his own choice. He has made a willing sacrifice.
         </para>

         <para number='49' comment='hanged man interp'>
         Zenia whispers softly "Perhaps the inverted position gives him a new perspective on life. You feel as though you are in stasis for the time being. You must spend the time gaining a new perspective on the situation before you can move forward. Set aside your ego and make a sacrifice so that eventually you can move forward in peace."
         </para>

         <para number='50' comment='hanged man rev'>
         Your choice is The hanged man who is suspended by one ankle from a beam the balances on a tree-trunk. But it is reversed. Surprisingly, his face appears serene and his body relaxed with his hands behind his back. A bright halo around his head shows that his trust lies in something other than the physical world and that being in this position where he has no control may have been his own choice. He has made a willing sacrifice.
         </para>

         <para number='51' comment='hanged man rev interp'>
         Zenia whispers to you "Your sacrifice is in vain. Take responsibilty and move forward.  It's time to get on with your own life."
         </para>

         <para number='52' comment='death'>
         You have chosen Death. Death rides in upon a white horse.  The King attempts to bar his way and is trampled underfoot. The Bishop tries to bargain but will also be pushed aside.  The maiden turns her head, refusing to acknowledge the change.  Only the child looks death in the face and waits to see what will happen. In the distance, the sun rises between two towers, shedding warm light on a new day.
         </para>

         <para number='53' comment='death interp'>
         Zenia smiles softly and whispers " Do not panic.  The death card does not herald physical death. Sweeping change is coming. The old must perish in order to make room for the new. Mourn what is lost in the inevitable change and greet what comes now with acceptance. You must let go of the past in order to embrace the new opportunities that are coming your way."
         </para>

         <para number='54' comment='death rev'>
         You have chosen Death. The card is reversed. Death rides in upon a white horse.  The King attempts to bar his way and is trampled underfoot. The Bishop tries to bargain but will also be pushed aside.  The maiden turns her head, refusing to acknowledge the end.  Only the child looks death in the face and waits to see what will happen. In the distance, the sun rises between two towers, shedding warm light on a new day.
         </para>

         <para number='55' comment='death rev interp'>
         Zenia leans forward and whispers "The old must perish in order to make room for the new. Stop dreaming and wishing for what has outlived its usefulness. Renewal requires positive action.  You are in danger of stagnation if you fear change so much that you cannot move forward."
         </para>

         <para number='56' comment='temperance'>
         You have chosen Temperance. An angelic figure stands at the edge of a pool, one foot dipped in the water and the other on dry land forming a bridge between the spiritual and the mundane. The angel pours water from one cup to another without spilling any. A path leads off towards a distant dawn. There is a strong feeling of harmony here and though the path may be long it leads towards a bright future.
         </para>

         <para number='57' comment='temperance interp'>
         Zenia smiles and whispers "Patience is required to reach your long term goals.  Look at the big picture and use a calm, measured response to the situation. Diplomacy, calm communication and moderation will serve you best."
         </para>

         <para number='58' comment='temperance rev'>
         You have chosen Temperance. The card is upside-down. An angelic figure stands at the edge of a pool, one foot dipped in the water and the other on dry land forming a bridge between the spiritual and the mundane. The angel pours water from one cup to another without spilling any. A path leads off towards a distant dawn. There is a strong feeling of harmony here and though the path may be long it leads towards a bright future.
         </para>

         <para number='59' comment='temperance rev interp'>
         Zenia nods and whispers "There may be clashing interests and emotional instability around you. Beware of rash or ill-advised action but do not vacillate about a decision. There is the danger that you will over-react emotionally if you do not exercise caution."
         </para>

         <para number='60' comment='the devil'>
         You have chosen The Devil. The Devil sits on a stone plinth, a man and a woman chained beneath him. Their chains sit loosely around their necks and they could removed them if only they could see past the illusion of imprisonment. Light and dark, good and bad, reside in everyone.
         </para>

         <para number='61' comment='devil enterp'>
         Zenia whispers "Don't point at others instead of dealing with your own demons. Only by investigating the dark recesses of your own psyche can you break the chain and come to a new understanding. You may feel trapped by circumstances beyond your control and seek to blame others. You must face up to your own darker side in order to free yourself. Be wary of self indulgence and greed. Change may be coming."
         </para>

         <para number='62' comment='devil rev'>
         You have chosen The Devil but the card is upside-down. The Devil sits on a stone plinth, a man and a woman chained beneath him. Their chains sit loosely around their necks and they could removed them if only they could see past the illusion of imprisonment. Light and dark, good and bad, reside in everyone.
         </para>

         <para number='63' comment='dev rev interp'>
         Zenia smiles and whispers "The time has come to rid yourself of the chains. Because you have ackowledged both the light and dark within your own psyche, the illusion slips away and you are free.  The reward for your courage and self-honesty is happiness and success."
         </para>

         <para number='64' comment='tower'>
         You have chosen The Tower. Lightning strikes the great tower, smashing the battlements as fire breaks out within.  The occupants fall screaming from the heights as the tower is about to collapse.  The flash of lightning illuminates the cracks and faults in the concepts upon which they have built their lives. Such sudden realization, that all one is comfortable with has become restrictive, is painful and shocking.
         </para>

         <para number='65' comment='tower interp'>
         An entire belief system may have to change now. But this catastrophic event is a blessing in disguise.  It is time to clear away the old and embark upon a more fullfilling adventure. Great change is coming.  It may be painful at first but will eventually bring greater happiness and healing.
         </para>

         <para number='66' comment='star'>
         You have chosen The Star. A maiden kneels by a pool beneath a starry sky, one foot resting on the water.  She pours refreshing water from one pitcher onto the ground and from another into the pool, nurturing both the spiritual and the physical world. Behind her a bird, the symbol of love, sits singing in a tree. The Star is faith, hope and love combined.  She is naked to represent that nothing is hidden.
         </para>

         <para number='67' comment='star interp'>
         Zenia smiles and whispers "Happiness and reciprocated friendship or love await.  Through a positive attitude you can overcome any difficulties before you. The Star is a card of healing.  Believe in your own potential and you may be inspired to realise your dreams."
         </para>

         <para number='68' comment='star rev'>
         You have chosen the Star but the card is upside down. A fair maiden kneels by a pool beneath a starry sky, one foot resting on the water.  She pours refreshing water from one pitcher onto the ground and from another into the pool, nurturing both the spiritual and the physical world. Behind her a bird, the symbol of love, sits singing in a tree.
         </para>

         <para number='69' comment='star rev interp'>
         Zenia whispers "Do not allow others to steal your self confidence or put you down. Positive thought and attitude is required.  Hope springs eternal."
         </para>

         <para number='70' comment='sun'>
         You have chosen The Sun. The brilliant Sun shines down upon a happy child who is riding a horse through a beautiful garden. Sunflowers bloom and all shadow is dispelled by the bright rays. Nothing negative can enter the garden while the Sun shines so brightly.  It brings with it a clarity of vision and a confidence that the future holds good things.
         </para>

         <para number='71' comment='sun interp'>
         Zeria smiles and whispers "You can think clearly now and you have the energy to achieve your goals. There may be a happy reunion approaching."
         </para>

         <para number='72' comment='moon'>
         You have chosen The Moon. A crab crawls from a pool to dry land as wild dogs bay at the full moon. A winding path leads off through the dark towards two towers in the distance. The scene evokes a feeling on unease and strikes at something buried in your subconscious mind.
         </para>

         <para number='73' comment='moon interp'>
         Zera whispers "You cannot see the path clearly but you must trust now in your intuition. Step forward onto the path even though you have fears. Listen to your dreams. They can show you how to succeed in a creative project."
         </para>

         <para number='74' comment='judgement'>
         You have chosen Judgement. A winged angel blows a trumpet, summoning the dead to rise from their graves and be accountable for all they have done with their lives.
         </para>

         <para number='75' comment='judgement interp'>
         Zenia whispers to you "Review what you have done and accept the rewards. Your achievements will be recognized and happiness follows."
         </para>

         <para number='76' comment='judgement rev'>
         You have chosen Judgement but the card is reversed. Angel blows a trumpet and summons the dead to rise from their graves and accept responsibility for how they have lived their lives"
         </para>

         <para number='77' comment='judgement rev interp'>
         Zenia whispers "Lessons must be learned but if you learn them well then you open the door for happiness to come into your life. The choices you make in your life are your own responsibility and you shall reap as you have sown."
         </para>

         <para number='78' comment='world'>
         You have chosen The World.  A maiden dances across the sky, surrounded by a laurel wreath.  At the corners of the card are a lion, an eagle, an angel and a bull.  They are the poles, the sunrise and the sunset. Everything is in harmony and complete.
         </para>

         <para number='79' comment='world interp'>
         Zenia smiles and whispers "The world can be a successful conclusion or the deginning of a dream come true.  You have the freedom now to start afresh on another path.  Victory is yours."
         </para>

      </section>

      <section name='zenia'>

         <para number='1' comment='zenia hello'>
         Zenia smiles, "Greetings, %s. I am Zenia and I have been expecting you, of course. I will do my best to answer your questions about Tarot.
         </para>

         <para number='2' comment='zenia chat Tarot'>
         Zenia replies "Tarot is an ancient way of developing our intuitive skills.  It's origins are shrouded in mystery. It may not give definitive answers to your questions. But it may help you understand the forces that are at work in your life. I could tell you more about the deck."
         </para>

         <para number='3' comment='zenia chat deck'>
         Zenia says "The Tarot deck is made up of  78 cards... 22 Major Arcana and 56 Minor Arcana. The Minor Arcana cards are divided into four suits, Cups, Swords, Wands and Pentacles. As the planet name suggests, I have the MAJOR Arcana here. If you would like to know what the major arcana have to say to you today, simply  Choose Card "
         </para>

         <para number='4' comment='zenia chat major'>
         Zenia replies "Major Arcana cards are powerful images that represent you, a person close to you or a situation or turning point in your life. When you CHOOSE a CARD, you must decide which of those your card represents."
         </para>

         <para number='5' comment='zenia chat minor'>
         Zenia says "The Minor Arcana are the ancestors of the playing cards that people use today.  There are 4 suits. Cups are hearts, Swords are spades, Wands are clubs and Pentacles are diamonds. Each suit leans towards a different aspect of your psyche."
         </para>

         <para number='6' comment='zenia chat reading/card'>
         Zenia replies "Before you are the 22 Major Arcana cards. Think about the situation upon which you want advice, then CHOOSE CARD.  I will turn the card over and tell you what it means."
         </para>

         <para number='7' comment='zenia chat bye'>
         Zenia smiles "Farewell, %s.  Remember that the cards do not absolve you of your responsibility for the choices you make. Your fate.. for the most part.. lies in your own hands."
         </para>

         <para number='8' comment='zenia chat cups'>
         Zenia smiles "Ah cups are the cards of love, emotion, relationships and feelings."
         </para>

         <para number='9' comment='zenia chat swords'>
         Zenia says "Swords are cards of the intellect and controlled actions governed by the mind"
         </para>

         <para number='10' comment='zenia chat wands'>
         Zenia replies "Wands are cards of action, energy, initiative and growth"
         </para>

         <para number='11' comment='zenia chat pentacles'>
         Zenia nods "Pentacles are earthy cards.  They speak of status, wealth and physical health"
         </para>

         <para number='12' comment='zenia chat who'>
         Zenia smiles "Some call me Mystic Zenia because of my skill with reading the tarot cards. You have but to choose a card and I will tell you it's meaning."
         </para>

         <para number='13' comment='zenia chat zzeria'>
         "Ah, our illustrious planet owner... Do you know her?" Zenia chuckles. "You know I did tell her not to set her hopes on a relationship with Zardoz, but somehow I think Jezz's words to her about it carried more weight. Perhaps the cards will hold better news for you. Just Choose one and see."
         </para>

         <para number='14' comment='zenia chat fortune / future'>
         Zenia replies "The cards may help you understand aspects of your life but your future depends upon the way you respond to what fate throws at you. A person's future is rarely set in stone. CHOOSE CARD and we will see what message the tarot holds for you today."
         </para>

         <para number='15' comment='zenia chat nomatch'>
         Zenia frowns "I'm afraid the answer to that question is hidden in the mists of time"
         </para>

      </section>

   </category>

</para-list>

