<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='pub wall bashing'>
         Sit down and have another Slobber and Tonic until you figure out how to get out of here
         </para>

         <para number='2' comment='ATB'>
         You are not yet worthy of passing that way.
         </para>

         <para number='3'>
         You bend over and pets some off the cutest Basset Babies around.
         </para>

         <para number='4'>
         Better have the Doc take a look at the bump you got from running into the wall just now.
         </para>

         <para number='5' comment='exchange'>
         What? Hard to find the door with your hands full of goodies?
         </para>

         <para number='6' comment='Dawg s booth'>
         .....and don't let it happen again!
         </para>

         <para number='7' comment='abandoned building'>
         Nothing of interest here so move along.
         </para>

         <para number='8' comment='memorial walk'>
         Whoa there Hoss.  Let's not be hasty.
         </para>

      </section>

   </category>

</para-list>

