<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='noexit'>

      <section name='carlos'>

         <para number='1' comment='No-exit first level'>
         You're lucky the gunmetal gray bulkhead is here, because if it weren't, you'd be in the cold vacuum of space or somewhere equally unpleasant.
         </para>

         <para number='2' comment='No-exit Second level'>
         The transparent material used is kept exceptionally clean because you bump right into it! Though an understandable mistake, it does not stop onlookers from sniggering at you.
         </para>

         <para number='3' comment='No-exit for Control Room'>
         You fall over the railing and start plunging down into the space of the dome. Luckily, a perceptive tech steers his chair under you, and brings you back to the catwalk.
         </para>

      </section>

      <section name='indoor'>

         <para number='1' comment='No-exit in buildings'>
         Your mind must have been wandering because as you look up, you're about to smack into a stucco'd wall.
         </para>

         <para number='2' comment='No-exit for my residence'>
         Careful, now! You almost put a big hole in the screen there.
         </para>

         <para number='3' comment='No-exit 2nd level Facilities'>
         Certainly you weren't trying to exit this way, but merely trying to get a better look at this lovely architecture. We commend you!
         </para>

      </section>

      <section name='leon'>

         <para number='1' comment='No-exit brick path'>
         As you set foot off the interlocking path, a burly ex-marine all in black steps in front of you. "It's in your best interest to stay on the road," she says.
         </para>

         <para number='2' comment='No-exit jungle'>
         Not even a machete would be enough to blaze that trail, my friend. You'd need some serious industrial equipment.
         </para>

         <para number='3' comment='No-exit Registry'>
         A small floating droid, about the size of a seagull, floats down and tsks at you. It encourages you to try a different route. With gravitics.
         </para>

         <para number='4' comment='No-exit town square'>
         Oh come on! I've provided you with almost all of the possible exits, but you just have to try and go this way. Go back there and try it again!
         </para>

      </section>

   </category>

</para-list>

