<?xml version="1.0"?>

<para-list version='8' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         There is nothing but the inky blackness of space in that direction.
         </para>

         <para number='2'>
         An armed, black-and-gold clad functionary blocks your path and dissuades you from wandering off.
         </para>

         <para number='3'>
         The dense jungle foliage is impassable in that direction.
         </para>

         <para number='4'>
         The rocky, uneven ground is impassable in that direction.
         </para>

         <para number='5'>
         The terrain does not permit you to move in that direction.
         </para>

         <para number='6'>
         The heat from the magma is simply too intense in that direction.
         </para>

         <para number='7'>
         You cannot move in that direction.
         </para>

      </section>

   </category>

   <category name='objects'>

      <section name='horse'>

         <para number='1' comment='Pet horse - player'>
         You reach up and gently stroke the horse's nose.  It snorts softly in response and nuzzles your hand gently, clearly enjoying your touch.
         </para>

         <para number='2' comment='Pet horse - roomex'>
         %s reaches up and softly strokes the horse's nose.
         </para>

         <para number='3' comment='Feed horse - player'>
         You reach into your pocket and pull out an apple, offering it up to the horse.  It leans down and slowly begins munching, its lips delicately tickling your palm until it has eaten up the entire apple.
         </para>

         <para number='4' comment='Feed horse - roomex'>
         %s offers up an apple to the horse, which slowly munches away until it is entirely gone.
         </para>

         <para number='5' comment='Groom horse - player'>
         You notice a stiff-bristled brush nearby, pick it up, and begin to brush the horse down, starting at the neck and slowly working your way to his rear, then switching sides and repeating.  The horse stands calmly and allows you to brush him down, occasionally neighing softly.
         </para>

         <para number='6' comment='Groom horse - roomex'>
         %s reaches down, picks up a brush lying in the sand and begins brushing down the horse from neck to rear, focusing first on one side, then the other.
         </para>

         <para number='7' comment='Ride horse - player'>
         The horse leans down and allows you to climb up, bareback.  Once you are settled it rises up, whinnies and suddenly takes off like a shot down the beach.  You cling to its heaving neck as it tears down the beach.  Its hooves thunder through the surf, kicking up salt water and wet sand as the sea air whips through your hair.
         </para>

         <para number='8'>
         After an exhilarating sprint down the beach, the horse turns and slowly trots back, allowing you to dismount where you started.
         </para>

         <para number='9' comment='Ride horse - roomex'>
         %s gingerly climbs upon the back of the horse, which whinnies loudly and suddenly takes off down the beach, taking the rider for a wild ride through the surf.
         </para>

         <para number='10'>
         The horse then returns and allows %s to dismount.
         </para>

         <para number='11' comment='examine horse'>
         A lofty, elegantly-formed Appaloosa mare, with a roan coat, spotted hindquarters and odd dark vertical stripes on its hooves.  It is without saddle or other marking except for a single sash around its neck, emblazoned with the name "Angel."
         </para>

      </section>

      <section name='keypad'>

         <para number='1' comment='Press/push/use keypad - 1066'>
         To enter a code into the keypad you 'TYPE codenumber'. Warning: entering the wrong code will result in considerable discomfort.
         </para>

         <para number='2' comment='Correct code is entered'>
         You punch the code into the keypad and the steel door slides open long enough for you to slip through, before it quickly shuts behind you.
         </para>

         <para number='3' comment='Roomex'>
         %s presses a few buttons on the keypad, and the steel door slides open...
         </para>

         <para number='4'>
         It remains open just long enough for %s to step through, before quickly shutting again.
         </para>

         <para number='5' comment='Wrong code'>
         As you punch the code into the keypad, it buzzes loudly and zaps you with a painful electric shock!
         </para>

         <para number='6' comment='Roomex'>
         %s presses a few buttons on the keypad and receives a nasty electric shock in return!
         </para>

      </section>

   </category>

   <category name='snake'>

      <section name='examine'>

         <para number='1' comment='ex snake - in habitat'>
         You peer into the large habitat and see a huge snake. It is a shimmering pearl white with emerald green eyes. It is curled lazily on a stone under a warm heat lamp. A cute little sign that looks like two boards nailed to a fence post sitting to one side of the stone reads: "Emerald's Pad".
         </para>

         <para number='2' comment='roomex'>
         %s peers into the habitat intently studying the creature within.
         </para>

         <para number='3' comment='Snake is held by player'>
         You turn your head to look the snake in the eye. Her tongue darts out, flicking you on the nose. Did that snake just grin?
         </para>

         <para number='4' comment='roomex - male'>
         %s turns his head to look the snake in the eye. His head snaps back and his eyes widen as the snake flicks him on the nose. Did that snake just grin?
         </para>

         <para number='5' comment='roomex - female'>
         %s turns her head to look the snake in the eye. Her head snaps back and her eyes widen as the snake flicks her on the nose. Did that snake just grin?
         </para>

         <para number='6' comment='roomex - neuter'>
         %s turns its head to look the snake in the eye. Its head snaps back and its eyes widen as the snake flicks it on the nose. Did that snake just grin?
         </para>

         <para number='7' comment='Snake is held by someone else'>
         The shimmering white snake rests comfortably entwined around the body of her current admirer. Her long tongue darts in and out of her mouth, tasting the air.
         </para>

         <para number='8' comment='roomex'>
         %s peers at the snake as she enjoys the warmth from the body of her current admirer.
         </para>

      </section>

      <section name='exit'>

         <para number='1' comment='Enter 2327 - turn back'>
         You can tell by Emerald's struggles and evil glare that she wouldn't appreciate being carried around the planet. You should probably replace her in her habitat.
         </para>

      </section>

      <section name='feed'>

         <para number='1' comment='Feed snake - in habitat'>
         You pull a brass lever beside the glass releasing a small white mouse that somehow looks vaguely familiar into the habitat. As you peer in, the snake quickly strikes at the mouse and coils itself tightly around it until it becomes lost from sight. After a few moments of squeezing the snake uncoils itself and begins to slowly swallow the limp rodent.
         </para>

         <para number='2' comment='roomex'>
         As you look on with a mixture of fascination and repulsion, %s pulls a brass lever beside the glass releasing a small white mouse that somehow looks vaguely familiar into the habitat. As you peer in, the snake quickly strikes at the mouse and coils itself tightly around it until it becomes lost from sight. After a few moments of squeezing the snake uncoils itself and begins to slowly swallow the limp rodent.
         </para>

         <para number='3' comment='Being held by anyone'>
         You pull a brass lever beside the glass releasing a small white mouse that somehow looks vaguely familiar into the habitat. The mouse wanders around the empty habitat for a while, eventually disappearing under a branch.
         </para>

         <para number='4' comment='roomex'>
         %s pulls a brass lever beside the glass releasing a small white mouse that somehow looks vaguely familiar into the habitat. The mouse wanders around the empty habitat for a while, eventually disappearing under a branch.
         </para>

      </section>

      <section name='hold'>

         <para number='1' comment='Hold snake - in habitat'>
         You reach into the habitat with both hands and pick up the large snake. She coils around your body for warmth before resting her head on your shoulder.
         </para>

         <para number='2' comment='roomex - male'>
         %s reaches into the habitat with both hands and picks up the large snake. She coils around his body for warmth.
         </para>

         <para number='3' comment='roomex - female'>
         %s reaches into the habitat with both hands and picks up the large snake. She coils around her body for warmth.
         </para>

         <para number='4' comment='roomex - neuter'>
         %s reaches into the habitat with both hands and picks up the large snake. She coils around its body for warmth.
         </para>

         <para number='5' comment='Snake is held by someone else'>
         You can tell by Emerald's evil stare that it would be unwise to try to remove her from the arms of her current admirer.
         </para>

         <para number='6' comment='roomex - male'>
         %s tries to take the snake from the arms of her current admirer, but after an evil stare from the snake, he thinks better of it and waits his turn.
         </para>

         <para number='7' comment='roomex - female'>
         %s tries to take the snake from the arms of her current admirer, but after an evil stare from the snake, she thinks better of it and waits her turn.
         </para>

         <para number='8' comment='roomex - neuter'>
         %s tries to take the snake from the arms of her current admirer, but after an evil stare from the snake, it thinks better of it and waits its turn.
         </para>

         <para number='9' comment='Snake is held by player'>
         You hold Emerald tighter causing her eyes to nearly pop out of her head. Her evil stare suggests she doesn't like that.
         </para>

         <para number='10' comment='roomex'>
         %s holds Emerald tighter causing her eyes to nearly pop out of her head. Her evil stare suggests she doesn't like that.
         </para>

      </section>

      <section name='pet'>

         <para number='1' comment='Pet snake - in habitat'>
         You reach into the habitat and stroke Emerald's head, who seems to enjoy it. You may be able to hold Emerald, if you so choose.
         </para>

         <para number='2' comment='roomex'>
         %s reaches into the habitat and strokes the snake's head, who seems to enjoy it.
         </para>

         <para number='3' comment='Player is holding snake'>
         You stroke the top of Emerald's head tentatively. Her forked tongue slithers from her mouth and flicks across your cheek.
         </para>

         <para number='4' comment='roomex'>
         %s strokes the snake's head tentatively.
         </para>

         <para number='5' comment='Some else is holding snake'>
         As Emerald enjoys the attention of her current admirer, you reach over and rub the top of her head. She gazes in your direction, her eyes gleaming.
         </para>

         <para number='6' comment='roomex'>
         As Emerald enjoys the attention of her current admirer, %s reaches over and rubs the top of her head. She gazes back, her eyes gleaming.
         </para>

      </section>

      <section name='replace'>

         <para number='1' comment='Replace snake - Player holding'>
         You reach into the habitat with both hands and place Emerald back into her home. She crawls back onto her heated stone and curls up leisurely.
         </para>

         <para number='2' comment='roomex'>
         %s reaches into the habitat with both hands and places the large snake back inside her home. She crawls back onto her heated stone and curls up leisurely.
         </para>

         <para number='3' comment='Not holding - male'>
         You reach into the habitat with both hands to place Emerald back into her home. You quickly realize you aren't holding her. As you hope that no one has noticed you suddenly hear sirens wail and klaxons blare. Then a loud voice announces: "%s just tried to put the snake back into her habitat, but he wasn't holding her to begin with!"
         </para>

         <para number='4' comment='roomex'>
         %s reaches into the habitat with both hands to place the large snake back inside her home. Sirens wail and klaxons blare.
         </para>

         <para number='5'>
         A loud voice announces: "%s just tried to put the snake back into her habitat, but he wasn't holding her to begin with!"
         </para>

         <para number='6' comment='female'>
         You reach into the habitat with both hands to place Emerald back into her home. You quickly realize you aren't holding her. As you hope that no one has noticed you suddenly hear sirens wail and klaxons blare. Then a loud voice announces: "%s just tried to put the snake back into her habitat, but she wasn't holding her to begin with!"
         </para>

         <para number='7' comment='roomex'>
         %s reaches into the habitat with both hands to place the large snake back inside her home. Sirens wail and klaxons blare.
         </para>

         <para number='8'>
         A loud voice announces: "%s just tried to put the snake back into her habitat, but she wasn't holding her to begin with!"
         </para>

         <para number='9' comment='neuter'>
         You reach into the habitat with both hands to place Emerald back into her home. You quickly realize you aren't holding her. As you hope that no one has noticed you suddenly hear sirens wail and klaxons blare. Then a loud voice announces: "%s just tried to put the snake back into her habitat, but it wasn't holding her to begin with!"
         </para>

         <para number='10' comment='roomex'>
         %s reaches into the habitat with both hands to place the large snake back inside her home. Sirens wail and klaxons blare
         </para>

         <para number='11'>
         A loud voice announces: "%s just tried to put the snake back into her habitat, but it wasn't holding her to begin with!"
         </para>

      </section>

   </category>

</para-list>


