<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         As you attempt to move in that direction, you almost hit a Zidon debris field.  You are quickly escorted back to the main pathways by Zidonian Security.  You receive a signal from your comm unit, "Please refrain from straying from main space lanes."
         </para>

      </section>

   </category>

</para-list>

