<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1'>
         You cannot exit outside the shield protected area!!!  A droid walks over to you and bonks you on the head.  He mentions, "What are you trying to do, kill us ALL!!?!?!?"  You decide to not try that again.
         </para>

         <para number='2'>
         Weren't you just told only Zidonians can enter here!!!  You are tazzed and dragged back out to the main corridor, DO NOT TRY THIS AGAIN!!!
         </para>

         <para number='3'>
         A forcefield blocks you from moving that direction, you are electrocuted attempting this direction.  You fall down and lose consciousness.  You awaken 15 minutes later to find no one around.
         </para>

         <para number='4'>
         You can't even attempt that!!!  What are you trying to plan to take some of the planets treasury!!  A hefty Zidonian begins beating you up to the point of death.  Just before you lose consciousness, he says, "Don't ever try that again, or you won't be alive next time once I'm finished with you!!.   You awake an hour later to find everyone gone and decide not to attempt that again...
         </para>

      </section>

   </category>

</para-list>

