<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - space default'>
         Pacifica Control reports that you can not deviate from established space lanes.
         </para>

         <para number='2' comment='No exit message - arena default'>
         Your Navigation Computer prevents you from moving into unstable space.
         </para>

      </section>

   </category>

</para-list>