<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='planet'>

      <section name='artwork'>

         <para number='7' comment='for museums and artwork areas'>
         Hey!! Watch yourself, you almost knoced over a priceless artifact there bub.  You may not have any nice things in your ship, but please be mindful of the nice things others have acquired.  Now, move along!
         </para>

      </section>

      <section name='bargrill'>

         <para number='6' comment='bar and grill'>
         Whoa! you don't want trouble with the big hairy, burly, furry, bouncer do you?  You better stand up straight and behave!
         </para>

      </section>

      <section name='entrance'>

         <para number='8' comment='entrance to the grandstands'>
         Confusing isn't it.  Take a deep breath.  I know there's lots of people, but don't worry, no one is going to steal your seat.
         </para>

      </section>

      <section name='exchange'>

         <para number='5' comment='this is for the exchange'>
         I'm sorry, you must be so distraught over your latest blunder in the market that you forgot where the door is.  Please, open your eyes, look around, and get a clue!
         </para>

      </section>

      <section name='general'>

         <para number='1' comment='general message'>
         Whoa, there watch your step.  You never know when a mechanic needs to race by with a spare part, wouldn't want to get your head bashed in.
         </para>

      </section>

      <section name='medical'>

         <para number='3' comment='for the hospital'>
         Attention doctors!  A patient is trying to escape.  Their wounds are not healed and they need immediate medical attention.  Please use any force necessary to restrain the crazed individual.  Are they talking about you?
         </para>

      </section>

      <section name='newships'>

         <para number='2' comment='This is for the shipyard area'>
         Look, if you want a new ship or need repairs you've come to the right place, just don't wreck the joint!
         </para>

      </section>

      <section name='path'>

         <para number='4' comment='message for path locations'>
         Please, don't wander off the paths.  The paths are here for your protection.  And no littering!
         </para>

      </section>

      <section name='seats'>

         <para number='9' comment='this is for grandstand sections'>
         Hey!! Sit down!!! People are trying to watch a race here!  Man, some people have no common sense.  Either get out or sit down and enjoy the view.  But remember you're not a door, no matter how transparent your species is.
         </para>

      </section>

   </category>

</para-list>


