<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='linkpad'>

      <section name='link'>

         <para number='1' comment='this is for the link'>
         Look, you only have 2 options.  Leave the system, or continue north.  Don't let your ship block traffic, keep it moving.
         </para>

      </section>

      <section name='pad'>

         <para number='3' comment='pad leading to pits'>
         No, no, no!  Either land that boat of yours or move it onto the pits.  But be warned if you move it onto the pits you have to go the whole route.
         </para>

      </section>

      <section name='racetrack'>

         <para number='2' comment='this is for the racetrack'>
         You only have three options.  Go to the race, go to the link, or go to the pad.  Don't block traffic, we have a lot of people to process here.
         </para>

      </section>

   </category>

   <category name='track'>

      <section name='grandstands'>

         <para number='1' comment='this is for the turns'>
         You don't want to go that way!  You'll run into the stands and kill lots of people!  Keep it on the course buster.
         </para>

      </section>

      <section name='straights'>

         <para number='3' comment='This is for the straights'>
         Did you doze off?!  You can't go that way.  You'll go off course and ruin your ship!  Get focused and keep your eyes on the prize!
         </para>

      </section>

      <section name='turns'>

         <para number='2' comment='for turns with no grandstands'>
         Watch it there, buddy.  Keep it on the course, follow through with the turn.  No fair trying to take shortcuts!
         </para>

      </section>

   </category>

</para-list>


