<?xml version="1.0"?>

<para-list version='5' editor='standard'>

   <category name='city'>

      <section name='noexit'>

         <para number='1' comment='no exit for city'>
         A trojan guard examines your papers, you are not aloud in this area he says, and  turns you back
         </para>

      </section>

   </category>

   <category name='olympus'>

      <section name='noexit'>

         <para number='3' comment='On Mount Olympus'>
         You are forbidden in this area, you turn back so as not to anger the gods.
         </para>

      </section>

   </category>

   <category name='road'>

      <section name='noexit'>

         <para number='2' comment='Outside the City'>
         Please follow chosen paths, for your own safety.
         </para>

      </section>

   </category>

</para-list>

