<?xml version="1.0"?>

<para-list version='3' editor='standard'>

   <category name='message'>

      <section name='noexit'>

         <para number='1'>
         A kind farmer guides you back on the path.
         </para>

         <para number='2'>
         A kind Edinboro villager catches you before you fall over and points you back to the path.
         </para>

         <para number='3'>
         A passing Student sees your confusion and helps you by pointing out the proper way to go.
         </para>

         <para number='4'>
         You bounce off the wall and into a drunken student... OMG, the drunken student looks just like a younger Meteu.
         </para>

         <para number='5'>
         Your movements are being recorded for rebroadcast on Aekonia's Funniest Videos.
         </para>

         <para number='6'>
         Zardoz and Sephy hope you didn't hurt yourself, but would appreciate it if you were more careful in their house.
         </para>

         <para number='7'>
         Careful, you don't want to go for a swim do you?
         </para>

         <para number='8'>
         Careful, you nearly knocked over a waitdroid carrying a hot pizza.
         </para>

         <para number='9'>
         Careful, choose the wrong way, and you may end up in the lake.
         </para>

         <para number='10'>
         Management requests that you be careful.  You may be charged for any damages to the walls and carpets.
         </para>

         <para number='11'>
         Zardoz observes your klutzy moves, and is amused.
         </para>

         <para number='12'>
         A harried trader catches you and prevents you from falling over.
         </para>

         <para number='13'>
         You try to sneak out of the bar but are blocked by several crates of Coffee and Scotch.  You turn back afraid you'll break some expensive bottles.
         </para>

         <para number='14'>
         Meteu would like you to be more careful in his room.
         </para>

         <para number='15'>
         Count Nosferatu's promise to refrain from dining on his guests would certainly be rescinded if you insist on knocking on the walls.
         </para>

      </section>

   </category>

</para-list>

