<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Illegal Space moves message'>
         Access in that direction is not allowed.  Fighter pilots guide you back on course.  Failure to heed their warnings could get you shot down.  Quickly!
         </para>

      </section>

   </category>

</para-list>

