<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Starfleet-All Locations-noexit'>
         As you move off in an unauthorized direction, Voyager locks it's phasers on you...I think they're trying to coerce you into resuming standard approach or departure pattern
         </para>

      </section>

   </category>

</para-list>

