<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Standard No Exit'>
         A very large Moke places a very large hand on your shoulder, and says, "No can.... Kapu."
         </para>

         <para number='2' comment='LZ No Exit'>
         After nearly being flattened by a landing shuttle, and impaled by a speeding forklift, you decide that it is safer to stay on the map.
         </para>

         <para number='3' comment='Professor No Exit'>
         The professor looks at you and says, "What part of OUT do you not understand?"
         </para>

         <para number='4' comment='Groundskeeper no exit'>
         The Groundskeeper looks at you and says, "What part of OUT do you not understand?"
         </para>

         <para number='5' comment='Restaurant/Bar no exit'>
         You bump off a wall and into a waitdroid that spills hot soup all over your clothes.
         </para>

         <para number='6' comment='face No exit'>
         Mr. Face meets Mr. Wall with a resounding thud.
         </para>

         <para number='7' comment='garden no exit'>
         The garden is circled by hedges and the only openings are on the marked trails.
         </para>

         <para number='8' comment='Zardoz Office'>
         Zardoz watches your pathetic attempts at navigation and laughs.
         </para>

         <para number='9' comment='Zodraz secretary'>
         You walk into a wall and Zodraz's secretary observes your plight and giggles.
         </para>

      </section>

   </category>

</para-list>


