<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Shuttle'>
         There is only one way out of your shuttle, and it is not that way.  Be careful, the penalties for Flying while under the influence are severe.  So you want to at least appear sober, as you move about.
         </para>

         <para number='2' comment='Tube C'>
         Warning... breaching a boarding tunnel on an asteroid with no atmosphere is not a good idea... unless you can hold your breath for a very long time.
         </para>

         <para number='3' comment='Reception'>
         Although there are a myriad of choices for movement, that is not one of them.
         </para>

         <para number='4' comment='Empty Shuttle'>
         It is probably not wise to add vandalism to the list of charges along with Grand Theft Shuttle.  It might be wise to leave through a valid exit... like a door.
         </para>

         <para number='5' comment='Security Station'>
         A security droid glances up and intones in a metallic voice, "You are violating Rule 142(A)(1)(c)(iii) --- Prohibiting Dorkish behavior.  Cease and Desist or I'll place you under arrest."  Maybe it's a good idea to leave by a valid exit... like a door.
         </para>

         <para number='6' comment='cafeteria'>
         Tables fly and chairs skid across the floor as you bounce off the wall and land with an embarassing thud upon your butt.  Perhaps you should use the door.
         </para>

         <para number='7' comment='exchange'>
         Mr. Face meets Mr. Wall with a resounding Thud.
         </para>

         <para number='8' comment='Airlock'>
         Hmmm... Airlock... to keep out dangerous bacteria and viruses.... What do you say?  Not a good idea to breach the field... ehhhh?
         </para>

         <para number='9' comment='Grav Tube'>
         Mr. Face meets Mr. Wall with a resounding Thud.
         </para>

         <para number='10' comment='Lab Reception'>
         Clipboard go flying as you ricochet off the wall into a technician.  Perhaps you should stick with the map and not try to make your own exit.
         </para>

         <para number='11' comment='Directors Office'>
         The Director's Office is under constant surveillance by security.  Right now, a Security Droid just burst four gaskets, and fried its humor chip as it laughed at your pathetic attempts to navigate a simple map.
         </para>

         <para number='12' comment='Bio Lab'>
         The caged monkeys squeal with delight as they watch you bang into the wall.  Unless you want to claim to be their uncle (and who'd want to be related to Monodefuego anyway), I suggest you follow the marked paths.
         </para>

         <para number='13' comment='Chem Lab'>
         Glass crashes and shatters on the ground.  A technician shouts, "Please be more careful!"  I think you should leave right away by the marked exit.
         </para>

         <para number='14' comment='Nuclear Lab'>
         Even our dimwitted President, who can't pronounce the word, knows that you don't go bouncing off things where atoms are being split.  Be careful, or you'll turn this planet into a pile of radioactive dust.
         </para>

         <para number='15' comment='Droid Repair'>
         PaulTeutulSrbot glares at you and threatens you with his size 12 metal foot.  That sounds scary.  I think you should leave by the marked exit.
         </para>

         <para number='16' comment='Droid Storage'>
         The droids fall into each other and continue on as if a domino chain had been started.  It might be a good idea to leave now before security arrives.  But this time, leave by the marked exit to the south so you don't make a bad situation worse.
         </para>

         <para number='17' comment='Bio Weapons'>
         The Security Droids eye you warily.  Given the fact that they are armed, it might be a good idea to leave... now... while you are still integrated, and breathing.
         </para>

      </section>

   </category>

</para-list>


