<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='Landing Pad'>
         You trip over a fuel line and bounce off your shuttle and fall flat on your face much to the amusement of the ground crew.  They point out the various exits and explain that they are well marked and recommend that you not take short cuts.
         </para>

         <para number='2' comment='Noom Buggy'>
         Exiting a speeding vehicle is never a good idea.  Perhaps you should wait until it comes to a complete stop before exiting.
         </para>

         <para number='3' comment='Shower'>
         Your foot lands on an errant piece of soap and you take off on a slippery slide across the smooth tiled surface.  Even in a low grav environment, the impact of your face against the wall is painful.
         </para>

         <para number='4' comment='Mess Hall'>
         You bump into a crew member and trip over a chair.  Luckily for you, a large tray of creamed spinach cushions your face from impact against a table, and you injure only your pride.
         </para>

         <para number='5' comment='Kitchen'>
         A cook grabs you by the shoulder and informs you that a busy kitchen is no place for such antics.
         </para>

         <para number='6' comment='Buggy Dome'>
         The cramped confines of the Buggy Dome are no place for such errant movements.
         </para>

         <para number='7' comment='Flight Control'>
         The entire Flight Control Staff watch your bungled attempts to move and break out in uproarious laughter.
         </para>

         <para number='8' comment='Zard House'>
         Zard and Sephy kindly request that you treat their house with respect, and not put marks on the walls.
         </para>

         <para number='9' comment='Agri Dome'>
         You trip over a hose and land face first in a steaming pile of compost.  You don't want to know where it came from.
         </para>

         <para number='10' comment='Rec Room'>
         You trip and start to fall.  As you frantically try to regain your balance, your flailing arms and panic stricken expressions provide the crew members with some needed entertainment.
         </para>

         <para number='11' comment='Dorm Room'>
         Your face slams into a locker with a resounding crash, waking several dozin crew mambers.  It might be  good idea to leave now before they get out of bed.
         </para>

         <para number='12' comment='Maintenance'>
         Movement in this room is quite restricted due to the number of tools and parts strewn about.
         </para>

         <para number='13' comment='Hanger Bay'>
         A crew member notices your plight and cautions you on the danger in this area.
         </para>

         <para number='14' comment='Bar'>
         The bartender eyes you coldy and decides that you have had enough to drink.
         </para>

         <para number='15' comment='Exchange'>
         You trip over a terminal and fall flat on your face.
         </para>

         <para number='16' comment='Thundarr Office'>
         The hard rock walls of the cave do wonders for your complexion, as your face impacts solidly against them.
         </para>

         <para number='17' comment='Zod Office'>
         Hidden cameras record your antics and will be broadcast on Aekonia's Funniest Home Videos.
         </para>

         <para number='18' comment='Hallways'>
         The narrow hallways confine your movements, and in the low grav environment you bounce from wall to wall.
         </para>

         <para number='19' comment='Offices'>
         Station Security advises you to please refrain from marking the walls and ceiling with hand and face prints.
         </para>

         <para number='20' comment='employee store'>
         You knock over some especially high priced items, and the store manager reminds you of the "Pottery Barn Rule."  Perhaps you should leave before you get a huge bill for the items you have broken.
         </para>

      </section>

   </category>

</para-list>


