<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='lolo'>
         You receive a tight beam message from Planet Space Command, "Eh Lolo!!.... No can!!!"
         </para>

         <para number='2' comment='portagee'>
         You receive a tight beam transmission from Planet Space Command, "Eh bra, you one Portagee pilot right?  Stay on the freaking flight path Brah!"
         </para>

      </section>

   </category>

</para-list>


