<?xml version="1.0"?>

<para-list version='11' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='noexit for inferno area'>
         As you try to walk off, you notice a sign saying 'Do NOT go that way for it trap your soul in the Inferno for all eternity!'
         </para>

         <para number='2' comment='noexit for LP area'>
         Walking straight into a cement wall, you finally realize there was a wall there along, now turn around and try again!
         </para>

         <para number='3' comment='noexit for Space locations'>
         Are you trying to fly into a black hole? If you're not careful you will eventually hit that black hole, and that isn't good.
         </para>

         <para number='4' comment='Monodefuego room exit'>
         You run straight into a burnt wall and realize you have gone the wrong way when you hear laughter coming from behind you.
         </para>

         <para number='5' comment='ferreri bar'>
         As you try to leave the room, you run straight into the oaken paneling of the wall and fall right on your butt.
         </para>

         <para number='6' comment='gravel road'>
         As you try to leave the road, you realize you've gone the wrong way and slip face first down into the gravel. OUCH!
         </para>

         <para number='7' comment='ferreri bed'>
         As you try to leave the bed, you walk right into a bedpost and fall backwards into the lap of the person beside you.
         </para>

         <para number='8' comment='Darkangels Office'>
         As you try to exit, you bump into a device known only as stocks which then snap shut, lock, and trap you in a bent over position until the DarkAngel comes and releases you.
         </para>

         <para number='9' comment='Iron Maiden'>
         As you head in the wrong direction, the doors of the Iron Maiden slowly shut, trapping you inside waiting for DarkAngel to come let you out.
         </para>

         <para number='10' comment='Jessecka House'>
         As you try to leave the room, you bump into a brick wall throwing you back on the ground, butt first. You rub your butt thinking, "Ouch!, That hurt!"
         </para>

         <para number='11' comment='Black Hole'>
         As you try to exit, the pull of the black hole sucks your ship deep into it, allowing only one exit route.
         </para>

         <para number='12' comment='Hot tub'>
         Heading in that direction while in the Boiling Pit of Despair is a bad idea. As you try to move, you trip over everyone else in the pit, spilling your drink all over everyone, and angering the droid, who picks you up and slams you back down in your seat.
         </para>

      </section>

   </category>

</para-list>

