<?xml version="1.0"?>

<para-list version='1' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='space locations'>
         Are you trying to fly into a black hole? If you're not careful you will eventually hit that black hole, and that isn't good.
         </para>

         <para number='2'>
         As you try to exit, the pull of the black hole sucks your ship deep into it, allowing only one exit route.
         </para>

      </section>

   </category>

</para-list>

