<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='noexit'>

      <section name='inside'>

         <para number='1' comment='regular inside'>
         You smack into an obvious wall and decide to check the directions.
         </para>

         <para number='2' comment='grav-tube'>
         There is no button to make the grav-tube move that direction.
         </para>

         <para number='3' comment='gaming area'>
         A gaming console slams into your gut and you stumble backwards to catch your breath.
         </para>

         <para number='4' comment='plaza'>
         Tripping over the attendant seems like a mean thing to do.
         </para>

      </section>

      <section name='outside'>

         <para number='1' comment='regular outside'>
         Stepping on the grass is illegal.  All law infractions are punishable by death.  Scurry back now.
         </para>

         <para number='2' comment='park'>
         Hitting an invisible wall, you are pushed back into the scenery.
         </para>

         <para number='3' comment='fountain'>
         Attempting to circle the fountain seems pointless.
         </para>

         <para number='4' comment='platform'>
         There seems to be no reason to plummet to a grisly death.  You step backwards.  Quickly.
         </para>

      </section>

   </category>

</para-list>

