<?xml version="1.0"?>

<para-list version='12' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Larg'>
         You run smack dab into a concrete wall. Ouch!
         </para>

         <para number='2' comment='No exit message - Larg'>
         You run smack dab into a concrete wall. Instead of hurting yourself, though, you chipped off a piece of the wall. A small stream of water starts leaking onto the floor!
         </para>

         <para number='3' comment='No exit message - Larg'>
         The prefabricated walls of the medical facility prevent you from moving in that direction.
         </para>

         <para number='4' comment='No exit message - Larg'>
         You run smack dab into the elevator's wall. The service Mokona snickers at your misfortune!
         </para>

         <para number='5' comment='No exit message - Larg'>
         You run smack into the glass window of a Mokona's office. The receptionist rushes over to help you up!
         </para>

         <para number='6' comment='No exit message - Larg'>
         As you try to run into the wilderness, a friendly Mokona blocks your path! "Ohayo! The forest is dangerous if you don't know where you're going!"
         </para>

         <para number='7' comment='No exit message - Larg'>
         Before you can swim farther out into the ocean, you think you see something ahead... is that a shark fin?! You decide to head back to shallower waters where it's safer.
         </para>

         <para number='8' comment='No exit message - Larg'>
         You push against the walls with all your might to no avail... you just aren't strong enough to punch a hole through the reinforced concrete behind the sheetrock.
         </para>

      </section>

   </category>

</para-list>


