<?xml version="1.0"?>

<para-list version='12' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1' comment='No exit message - Modoki space'>
         A warning message is transmitted to your ship as you begin to leave the sector. "Travel outside of the Larg/Soel Binary System is not permitted at this time. Please turn about. Thank you!" =)
         </para>

      </section>

   </category>

</para-list>


