<?xml version="1.0"?>

<para-list version='2' editor='standard'>

   <category name='moves'>

      <section name='noexit'>

         <para number='1999' comment='no exit 1999'>
         An invisible force field keeps you from making an unhappy mistake!
         </para>

         <para number='2000' comment='no exit 2000'>
         An invisible force field keeps you from making an unhappy mistake!
         </para>

         <para number='2001' comment='no exit 2001'>
         An invisible force field keeps you from making an unhappy mistake!
         </para>

         <para number='2002' comment='no exit 2002'>
         An invisible force field keeps you from making an unhappy mistake!
         </para>

         <para number='2064' comment='no exit 2064'>
         An invisible force field keeps you from making an unhappy mistake!
         </para>

         <para number='2065' comment='no exit 2065'>
         As you try to go back, you are steered toward the exits by a polite droid.
         </para>

         <para number='2130' comment='no exit 2130'>
         As you try to go back, you are reminded to proceed forward by a flashing "One Way" sign.
         </para>

         <para number='2131' comment='no exit 2131'>
         As you try to go back, you are reminded to proceed forward by a flashing "One Way" sign.
         </para>

         <para number='2193' comment='no exit 2193'>
         As you try to go back, you are reminded to proceed forward by a flashing "One Way" sign.
         </para>

         <para number='2196' comment='no exit 2196'>
         As you try to go back, you are reminded to proceed forward by a flashing "One Way" sign.
         </para>

         <para number='2258' comment='no exit 2258'>
         As you try to go back, you are reminded to proceed forward by a flashing "One Way" sign.
         </para>

         <para number='2259' comment='no exit 2259'>
         As you try to go back, you are reminded to proceed forward by a flashing "One Way" sign.
         </para>

      </section>

   </category>

</para-list>

