<?xml version="1.0"?>

<para-list version='9' editor='standard'>

   <category name='noexit'>

      <section name='diningroom'>

         <para number='1'>
         You trip over a loose carpet and fall headfirst onto a dining table set up for the next meal. The waiters and waitress rush over to pick up and count all the silverware. Obviously they think your actions were a diversion to pilfer some of the country club's fine dining utensils. Perhaps you should dress better.
         </para>

      </section>

      <section name='exchange'>

         <para number='1'>
         As you attempt to move, the crowd of traders twists and turns you around as they rush to and from the trading consoles that you end up back where you started.
         </para>

         <para number='2'>
         Your stumble and bump into the other patrons who turn and give you stern looks. Phil looks at you and asks "Hey there, have you had a little too much celebrating? Here, have some coffee and take a seat while you sober up a bit"
         </para>

      </section>

      <section name='hallway'>

         <para number='1'>
         You admire the fine wooden paneling of the wall you just walked into. Rubbing your sore nose you plan to pay better attention to where you are going.
         </para>

      </section>

      <section name='hospital'>

         <para number='1'>
         Fortunately your avatar is smarter than you are and refuses to run into a wall, lie down on the floor or attempt to climb the walls to get on the ceiling. Doing crazy things like that in a hospital might get you an all expenses paid 30-day stay in the mental ward.
         </para>

         <para number='2'>
         You walk around the cafeteria with your tray of food looking for a place to sit down and eat.
         </para>

         <para number='3'>
         You are feeling very disoriented by the cloning fluids as you stumble around and bump into chairs, walls and the hospital gurney table.
         </para>

      </section>

      <section name='kitchen'>

         <para number='1'>
         You stumble and bang your head on several hanging pots and pans creating a ruckus that causes the kitchen staff to look your way. You apologize for disturbing their routine as you grab the hanging pots and pans to stop their swinging.
         </para>

      </section>

      <section name='lounge'>

         <para number='1'>
         You trip on one of the chair legs and stumble toward a window. You reach out and grab one of the drapes to steady yourself. You look up to see the members in the room are all looking your way. You smile, wave and say "I'm okay." But it is apparent that the members were more worried about the furnishings than your well being.
         </para>

         <para number='2'>
         You stumble and bump into patrons who are standing at the bar. You make your apologies to the group who you bumped into and take a seat near the end of the bar.
         </para>

         <para number='3'>
         You are scanning the room when you bump into a gentleman who is looking out the window. You turn to excuse yourself and find yourself staring into the eyes of a most disagreeable person. He says in a gruff voice "Are you a member of the club? I think not!" He turns to beckon a waiter to call security, but you quickly mumble off an apology and move away.
         </para>

         <para number='4'>
         You turn to move and find yourself in a crowd of members who have moved into the alcove to look at the trophy case. Better be careful! You don't want to break the glass display case, it looks expensive.
         </para>

         <para number='5'>
         A crowd of members is in your way. You should look for another way out.
         </para>

      </section>

      <section name='manager'>

         <para number='1'>
         You stumble around the Manager's Office and nearly tip over one of the potted plants. Perhaps you should beat a hasty retreat through the doorway to the north before Mr. McLeod returns.
         </para>

      </section>

      <section name='pathways'>

         <para number='1'>
         The ground crew are a surly lot and would be offended if they saw you walking on their well-manicured landscaping. You do not want to offend them or you may find yourself swimming in the pond along next to the first tee.
         </para>

         <para number='2'>
         You aimlessly wander around the landing pad until an Armstrong Cuthbert agent directs you to look at the directional kiosk on the landing pad.
         </para>

      </section>

      <section name='patio'>

         <para number='1'>
         You trip and stumble but catch yourself by flailing your arms around and moving your feet fast. The members seated at the tables stop and clap for your performance as they thought you were performing for their amusement. You smile, bow and wave to their acknowledgement.
         </para>

      </section>

      <section name='porch'>

         <para number='1'>
         The wooden railing keeps you from falling off the porch and breaking your neck.
         </para>

      </section>

      <section name='proshop'>

         <para number='1'>
         You bump into a rack of clothing and almost knock it over. The pro shop assistant rushes over to inquire if you need any help. You politely decline and say you are only looking. She reminds you to please be careful and points to a notice near the door that reads "You break it, you buy it. Mgmt."
         </para>

      </section>

      <section name='starter'>

         <para number='1'>
         You stumble around looking for the exit when John looks up and asks in a sarcastic voice "Say there, what's a five letter word for someone who wears a pointed paper hat?" You look at him with a unknowing stare. He points to the doorway to the north and says "Exactly" and goes back to his crossword puzzle.
         </para>

      </section>

   </category>

</para-list>


