<?xml version="1.0"?>

<para-list version='4' editor='standard'>

   <category name='noexit'>

      <section name='debris'>

         <para number='1'>
         The ship's short-range sensors indicate that the debris field is too concentrated in that direction. You would never make it through in one piece.
         </para>

      </section>

      <section name='general'>

         <para number='1'>
         Your attempt to override the navigational computer fails and the ship continues on its way to the designated coordinates.
         </para>

         <para number='2'>
         Your spaceship attempts to veer off course. You spring upright in your chair and flip the navigational calibration sensor to the ON position. Your navigational computer picks up the automatic coordinate signal coming from the beacon and readjusts its course to the planned flight path.
         </para>

      </section>

      <section name='planet'>

         <para number='1' comment='Hazard'>
         You board your shuttle and head for the planet. The planetary craft sensor detection system issues an automatic warning to you. "Your shuttle craft is not authorized for underwater travel. The Planetary Authorities will not be responsible for your death. Cloning facilities will not be made available for unauthorized vessels." You think twice about attempting a landing and return to your spaceship.
         </para>

         <para number='2' comment='Bunker'>
         You jump into your shuttle and head down to the surface of the asteroid. Before you reach the landing pad, you are intercepted by two USGA &amp; RA attack fighters. Your comm unit crackles to life "Unidentified shuttle craft, this is Wolf Leader, you are attempting to land at a quarantined facility. Please turn back now or be interned for the duration of the outbreak." You heed their warning and return to your vessel.
         </para>

         <para number='3' comment='Fringe'>
         You jump into your shuttle and head down to the moon's outpost. Your comm beeps as it receives a tightbeam message. "Attention approaching vessel, this is Reno McKnight, leader of the Fringe Element. You should not attempt to land at the Fairway System outpost. It is a trap!" The communication abruptly ends. You think twice about landing and decide to head back to your vessel.
         </para>

         <para number='4' comment='Green'>
         You turn to engage the engines and spill your coffee on the control console. While attempting to clean up the mess you accidentally turn back on the navigational computer which returns you to orbit around the planet Green.
         </para>

      </section>

   </category>

</para-list>


